### ISSUE TITLE
Disable Automatic Login (T4322)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#10]
<div dir="rtl"><b>Gibran&nbsp;Ortega</b>&nbsp;(<em>&#35;gibranlp</em>),&nbsp;2017-08-18&nbsp;19:09:14&nbsp;UTC</div><br/>

I've been using Solus for a while now, and at first, i liked the idea to be logged in automatically now i tried to revert the automatic login but it doesn't work, 

I went to Settings >> Users and reverted the change,

Is this normal or an issue.

Solus Rocks BTW

**Comment by davidjharder** [comment]
Was able to toggle automatic login on and off, with subsequent restarts behaving as expected, on both Plasma and Budgie.
Also, this is old as dirt. Closing
