### ISSUE TITLE
GLib-GIO-CRITICAL spam regarding GFileInfo created without standard::icon

### ISSUE THREAD

**Issue by GZGavinZhao** [getsolus/packages#1005]
### Summary

When running certain applications (in my case, `nvim-qt`), I get a barrage of Glib-GIO-CRITICAL warnings from the command-line that repeats the following two lines:

(nvim-qt:47528): GLib-GIO-CRITICAL **: 01:28:52.536: GFileInfo created without standard::icon
(nvim-qt:47528): GLib-GIO-CRITICAL **: 01:28:52.536: file ../gio/gfileinfo.c: line 1766 (g_file_info_get_icon): should not be reached

### Steps to reproduce

Run `nvim-qt`. You should immediately see the messages.

### Expected result

No warning messages should be outputted.

### Actual result

These two lines keep repeating:
```
(nvim-qt:47528): GLib-GIO-CRITICAL **: 01:28:52.536: GFileInfo created without standard::icon

(nvim-qt:47528): GLib-GIO-CRITICAL **: 01:28:52.536: file ../gio/gfileinfo.c: line 1766 (g_file_info_get_icon): should not be reached
```

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

Budgie

### System details

OS: Solus x86_64 
Kernel: 6.6.6-266.current 
Packages: 2148 (eopkg), 1 (nix-user), 23 (flatpak) 
Shell: fish 3.6.4 
Resolution: 1920x1080 
DE: Budgie 10.8.2 
WM: Mutter(Budgie) 
Theme: Materia-dark [GTK2/3] 
Icons: Papirus-Dark [GTK2/3] 
Terminal: gnome-terminal 
CPU: AMD Ryzen 7 5800H with Radeon Graphics (16) @ 3.201GHz 
GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series 
GPU: AMD ATI Radeon RX 6600/6600 XT/6600M 
Memory: 4227MiB / 13837MiB 

### Other comments

[This](https://gitlab.gnome.org/GNOME/glib/-/issues/2945) seems to be the relevant glib bug report, but I'm not sure which package should be fixed/updated/patched.

**Comment by TraceyC77** [comment]
I cannot reproduce this in Plasma (unstable), but I can on Budgie (unstable)
