### ISSUE TITLE
.NET 8.0 SDK (as well as 6)

### ISSUE THREAD

**Issue by bradyjam** [getsolus/packages#1007]
### Homepage

https://dotnet.microsoft.com/en-us/download

### Why should this be included in the repository?

Especially given how Solus' PATHs work, it was quite a pain to try and get dotnet working. Mono is not equivalent to dotnet and is behind in functionality.

I'd imagine maintenance would be fairly easy, as

> Updates are released on the Microsoft "Patch Tuesday" (second Tuesday of each month), however there is no guarantee that there will be a .NET release on any given Patch Tuesday.

### Are we allowed to redistribute it?

MIT

### What kind of user will use this package, and how many users do you think will use this package?

Desktop software and video game developers. Godot requires dotnet. I can't say how many users will use this package, but C# has been gaining popularity.

### Link to source archive file

https://download.visualstudio.microsoft.com/download/pr/5226a5fa-8c0b-474f-b79a-8984ad7c5beb/3113ccbf789c9fd29972835f0f334b7a/dotnet-sdk-8.0.100-linux-x64.tar.gz

**Comment by ReillyBrogan** [comment]
Note that .net has been attempted in the past and is fairly fiddly to build and maintain. This hopefully has improved since then. Best of luck to anyone who attempts this.

**Comment by ReillyBrogan** [comment]
> as well as 6

Please note that I'm only approving the addition of .NET 8 for now. We usually only have runtimes like this in the repo for repo applications that need them, users who need to develop with a specific version are recommended to use tooling to download the specific version they need (like pyenv for Python, sdkman for Java etc).

**Comment by nelsontkq** [comment]
I've been looking into this and have [an open issue on dotnet/source-build](https://github.com/dotnet/source-build/issues/3810). I'll update here when I get .NET 8 building successfully on solus.
