### ISSUE TITLE
Installing 4.5 Xfce Fails

### ISSUE THREAD

**Issue by WetGeek** [getsolus/packages#1016]
### Summary

The partition manager in the installer was so easy to use, compared to GEdit or KDE Partition Manager that I don't know why I had trouble with it when I created the Plasma VM - just unfamiliarity and a rush to get something done, I guess.  I went slower this time, and had no problems creating what I needed, including a swap space big enough for hibernating the finished VM.
![image](https://github.com/getsolus/packages/assets/6805994/15f12f45-1ebf-4b6f-bcfc-57e8242f46a7)

Everything seemed to go well until the end of the installation, where I encountered this issue.
![image](https://github.com/getsolus/packages/assets/6805994/fc629c6c-0a4e-4442-8177-be170e76a59d)

I'm not sure what it means to "paste the log to the web," or where on the web it will end up, but I suspect it will be somewhere I can access it.  The web is a pretty big place.  I'll try that now, and see if I can include it here.

Sweet!  The install log was pasted to termbin, and a link copied to the clipboard.  Unfortunately, it must have been the clipboard for the "live" session, but when I tried to paste it into Firefox in that session, nothing came out.  But the address listed on the error message gave me access to the message:
![image](https://github.com/getsolus/packages/assets/6805994/43739ea2-7db0-43bc-98c7-e782acb28306)

It's a little puzzling why there seemed to be so much content in the original error message, and so little in the install log that was saved, but perhaps that identifies a related error.  I suspect that log is rather useless.

### Steps to reproduce

1.  Create a VBox VM using the 4.5 Xfce .iso, and 4 GB of RAM.  I created it with a size 32 GB.
2. The initial "live" session won't be large enough to accommodate the installer, so use the Display setting to enlarge it.
3. Select the option to manually create partitions.  The Summary above shows what I crreated.
4. Continue until the installer starts.  It's at the end of the installation that the error message is presented.

### Expected result

I expected the installation to succeed, whereupon I'd close the installer, exit from the live session, and use the VM manager to remove the .iISO file from the VM's virtual CD drive.  Then I would be able to launch the VM and begin configuring it.

### Actual result

The error message listed in the Summary above was displayed, ending the installation before it completed.

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Xfce

### System details

I'm unable to provide system details, because I was unable to install and run the system.

**Comment by WetGeek** [comment]
I see that the image links I copied from the message I started to create in the forum didn't transfer well to this venue.  The first one was an image of the Calamares partition manager having created a virtual disk drive with a boot partition of 1.0 GiB, a swap partition of 6.0 GiB, and a root partition of 25.0 GiB.  I had created the file with a length of 32 GB.

The second image was the error message that ended the installation.  Next time I'll know better.

**Comment by WetGeek** [comment]
I suspecte that it might be a problem with the way the .VDI was created with the Calaamares partition manager, so I attempted the installation one more time, creating a new partition table with GParted and then creating the same partitions I'd created before.  This time the installation went to completion without a problem.
![image](https://github.com/getsolus/packages/assets/6805994/58bc2384-f8cd-4c9d-83d2-a065e5876061)

**Comment by EbonJaeger** [comment]
Fixed by a0b1050ad31eb272964644336ca36a3bf3a41a68, just haven't made new ISOs yet.
