### ISSUE TITLE
In Solus 4.5 Xfce Running Applications Do Not Appear in Task Manager

### ISSUE THREAD

**Issue by WetGeek** [getsolus/packages#1019]
### Summary

In other DEs, running applications show up in the task manager, and can be pinned there easily.  In this Xfce, that doesn't happen.

![image](https://github.com/getsolus/packages/assets/6805994/93fb9521-5a01-4d65-bf0d-130a6ad344a4)

Consequently users would need to locare all of those applications in the menu, and perhaps pin them from there.  The option there is Add to Panel, not the task manager, and when that's selected, the icon is added to the far right end, relative to the user.  

![image](https://github.com/getsolus/packages/assets/6805994/455284c4-5d15-434f-adb6-f68999420985)

This could be much improved.

### Steps to reproduce

In an Xfce VM with a workstation switcher in the bottom panel, notice that the applications running in the various workspaces do not show up in the task manager, and there is no easy way to pin them there.

### Expected result

As in other DEs, I expected to find an easy way to pin the application icons to the task manager.  

### Actual result

As is, the task manager is pretty much useless.

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Xfce

### System details

![image](https://github.com/getsolus/packages/assets/6805994/d5fb122e-f56f-4dfb-8de7-c884fe489f62)

**Comment by WetGeek** [comment]
I tried moving that icon from the far right of the bottom panel to what looks like the task manager, and indeed I was able to move it to there.  I realize now that it's not really a task manager, but just the bottom panel.  The playing card that's now here is the icon that I moved from the far right end.

![image](https://github.com/getsolus/packages/assets/6805994/4876ce13-2aa1-45e0-a3ec-499695602792)

**Comment by WetGeek** [comment]
The dock idea apparently isn't feasible as the system now exists.  I found and installed three docks that I found with a search of the repo: latte-dock, mate-dock-applet, and plank.

Latte installed without a problem, and showed up in the Accessories menu.  I clicked on it there, and nothing appeared to happen.  I could not get it to appear in the UI.

Because the panel in Xfce resembles the panel in mate, I installed the mate dock, but it didn't show up anywhere in the menu, that I could find.  And it makes sense that it could only show up in the list of applets that can be installed in the mate panel.  

The plank installed, and when I ran it from the menu, it atually appeared.  It initialized itself to contain icons for all of the applications that are running in the various workspaces, plus some duplicates.  But it clobbered the Xfce bottom panel.  Literally.  It removed and replaced that panel, 

Actually, this might be the best option of all, if the Xfce dock can't be used.  I'll continue working with it to see whether there's a way to access the other elements of the bottom panel, and if so, the plank is the option I would prefer.  It preserves the multiple workspaces, and clicking on the icons in the plank works as expected.
![image](https://github.com/getsolus/packages/assets/6805994/1ce84524-d989-4786-8e66-1aa78a82e8f9)

**Comment by WetGeek** [comment]
To update after much has happened:  There is no task list, but the functionality can be provided by a Plank .  And a plank, with the proper configuration, can contain permenent icons, and it can be set to oaunch opon logon through the autostart settings.

**Comment by TraceyC77** [comment]
Unfortunately, the xfce-panel has no ability to right click running applications to pin them, per one of the XFCE devs in [this closed bug](https://bugzilla.xfce.org/show_bug.cgi?id=11774)

Thanks for checking out those docks. We can consider possibly adding one of those to our default XFCE install.

**Comment by ermo** [comment]
> I should also note that I could find no way to move the bottom panel to the top of the screen, and thus removing the conflict between the plank and the panel.

You select the properties for the panel, unlock the panel you want to move, then drag it using e.g. the leftmost handle:

![xfce-dragging-bottom-panel-via-its-left-handle-after-unlocking-it](https://github.com/getsolus/packages/assets/118045/2dc26d1e-6cfa-4253-9254-961b9ea2ae09)

**Comment by WetGeek** [comment]
After learning that what appeared to be an icon-only task list was, instead, just a collection of application launchers that are not otherwise connected to the system or the menu, and after installing and configuring a Plank as a dock, I've now provided the functionality I need.  Closing this now as not planned, as the problem is simply missing functionality in Xfce compared with other Solus DEs, not something that's not working correctly.
