### ISSUE TITLE
Firefox: The interface language is not saved (T10124)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#102]
<div dir="rtl"><b>Maksym&nbsp;Bilak</b>&nbsp;(<em>&#35;bmivzkrp</em>),&nbsp;2022-01-18&nbsp;16:11:06&nbsp;UTC</div><br/>

Dear Solus team.
I noticed the following problem: after updating Firefox (from 94 to 95, and from 95 to 96), the Firefox interface language switches to English, despite the fact that I set up the Ukrainian interface language. That is, after each update of Firefox, I have to choose the Ukrainian language again.
Could anyone look at this?

**Comment by davidjharder** [comment]
We have new reports of this on the forums, see
https://discuss.getsol.us/d/9689-firefox-dont-keep-language-setting-after-update
https://discuss.getsol.us/d/9808-sync-update-for-week-39-2023/20

**Comment by davidjharder** [comment]
Doing some reading, it seems to me, we should set
`pref("intl.locale.requested",               "");` 
in `files/prefs.js` which will cause firefox to use whatever `$LANG` is, as we did before
 https://phab.getsol.us/R755:f0213db88ee66c3b09f6777e81c7c08888ee01f0

With this pref not set, firefox will use the default firefox locale (presumably en-us)
see https://firefox-source-docs.mozilla.org/intl/locale.html#requested-locales

A quick survey of other distros:
Fedora https://src.fedoraproject.org/rpms/firefox/blob/rawhide/f/firefox-redhat-default-prefs.js
Arch https://gitlab.archlinux.org/archlinux/packaging/packages/firefox/-/blob/main/PKGBUILD?ref_type=heads#L202

We can troubleshoot this by asking users to scroll to the bottom of `about:support` and report their localization settings:

**Comment by ReillyBrogan** [comment]
Resolved by 8c962e504d047ceea6567d500fbdff5e996da742
