### ISSUE TITLE
In an Xfce 4.5 VM, Vivaldi Blanks its Start Page Bookmarks

### ISSUE THREAD

**Issue by WetGeek** [getsolus/packages#1024]
### Summary

This happens at odd, but frequent times, and ends up looking like this:

![image](https://github.com/getsolus/packages/assets/6805994/c15f540c-9395-4933-966e-6f3a023eca98)

The only clue I can offer is that the Coinbase bookmark which is the only one that's unaffected by this issue is the only one that wasn't created by doing a Vivaldi sync.  I had created that bookmark by typing "coinbase.com" into the address bar, and then creating the bookmark in the usual way from its UI.  If I shut down Vivaldi and restart it, this doesn't change.  

And a possible second clue is that the number of bookmarks is correct, and their descriptive names are present and correct.  Normally I can click the _page reload_ button in the address bar to have the bookmarks all refresh their images, but doing that in this case has no effect.

I have not seen this happen with any other instance of Vivaldi on hardware, or virtual.  Vivaldi is my default browser on all devices, and I'm usually using it for a large part of each day.  That said, I have 3 other VMs that are based on Solus 4.5, with other DEs.  It's only on the Xfce VM that this has happened so far, leading me to believe that it's probably an Xfce issue, and not a Vivaldi issue.

If I click on the upper left-hand corner of a bookmark, it will load and display the correct image.  However, it's tedious to do that for 50+ bookmarks, and it doesn't prevent this from happening again at unexpected times.

### Steps to reproduce

It may be difficult to get to root cause on this one.  I can't provide a list of steps that will reliably cause it to happen, but here's what seems to be relevant for me.

I've created a VBox VM that 's based on Solus 4.5 RC1, and as part of testing that VM I installed my usual applications.  That includes Vivaldi.  Since I use Vivaldi on a number of devices here, I typically sync any new Vivaldi installation so that its Start Page displays bookmarks for the various sites I need to access.  That's what the image in the Summary above shows. 

### Expected result

The bookmarks usually display a small image related to the page they represent.  

### Actual result

The bookmarks don't display any image at all.  They just display the names assigned to them, repsenting the pages they connect with.

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

Xfce

### System details

There is no such item in the Xfce application menu.  This is from neofetch.
![image](https://github.com/getsolus/packages/assets/6805994/3f9cbf50-edaa-4291-8655-79d6832dc472)

**Comment by EbonJaeger** [comment]
That's a known upstream issue with Vivaldi. I'm not sure if it was fixed in the latest release or not, but either way, nothing we can do about it. It's very annoying, so hopefully it's either fixed or will be fixed soon.
