### ISSUE TITLE
Update Mullvad to 2023.6

### ISSUE THREAD

**Issue by JanAlbertD** [getsolus/packages#1027]
### Name

Mullvad

### Version

2023.6

### Link to the release notes or announcement.

https://github.com/mullvad/mullvadvpn-app/releases/tag/2023.6

### Other comments

Current package in the repository is 2023.4.
In October Mullvad released 2023.5.

**Comment by algent-al** [comment]
@tarkah can you look at this please.

**Comment by tarkah** [comment]
> @tarkah can you look at this please.

On it :+1:
