### ISSUE TITLE
handbrake: update to 1.7.1

### ISSUE THREAD

**Issue by luzpaz** [getsolus/packages#1029]
### Name

handbrake

### Version

1.7.1

### Link to the release notes or announcement.

https://github.com/HandBrake/HandBrake/releases/tag/1.7.1

**Comment by rav101** [comment]
Just to +1 this, version 1.7.0 bumped up SVT-AV1 version from 1.4.1 up 1.7 which has some very sizable improvements to speed for the same quality encode.

**Comment by aleksvor** [comment]
Updated in https://github.com/getsolus/packages/commit/40c30bd57021ebf58be25a677bcf4b2c3e51037b
