### ISSUE TITLE
IBus preference not showing up in menu (T10104)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#103]
<div dir="rtl"><b>Gavin&nbsp;Zhao</b>&nbsp;(<em>&#35;GZGavinZhao</em>),&nbsp;2022-01-12&nbsp;20:15:42&nbsp;UTC</div><br/>

IBus installs a desktop file for the `ibus-setup` GUI to easily modify its settings (see [here](https://dev.getsol.us/source/ibus/browse/tag%253A%2520ibus-1.5.22-19/pspec_x86_64.xml;a5fac4c556286d53e1aafd8fb9cf81b61b265896$43)). This is very useful because you either have to use the command-line or dig through the system settings to find what you want. However, it doesn't appear in the application menu. I can't really take a screenshot of it because the menu disappears if I click my mouse. However, if you have `ibus` installed, typing `IBus Preferences` should show you an application, but there's nothing there.

After some fiddling around, I found that [this line](https://github.com/ibus/ibus/blob/f5757ada54edaa7d2e3ea948d340cdf48064e30c/setup/ibus-setup.desktop#L11) is causing the issue. Is it okay to remove this line?

**Comment by ermo** [comment]
@GZGavinZhao Can you still reproduce this? If not, please close. ^^'

**Comment by TraceyC77** [comment]
Closing since there's been no update. If this is still a problem, feel free to reopen this.
