### ISSUE TITLE
Plasma screen brightness level with keyboard ignored in power management screen brightness (T7146)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#104]
<div dir="rtl"><b>Padraig&nbsp;Mac</b>&nbsp;(<em>&#35;padraig</em>),&nbsp;2018-11-02&nbsp;11:28:00&nbsp;UTC</div><br/>

I have two issues with power management on Plasma, both of which I have now tested on two laptops (note I have not tested this with other distributions but I don't remember seeing it with KDE Neon when I last used that over a year ago). I couldn't find these reported elsewhere.

The first (which is quite minor) can hopefully be seen in the screenshot attached, when I change the brightness using the brightness keys the popup in the middle of the screen shows the brightness level, this is ignored in the power management widget on the bottom right. If I click on that after it is set at a different value which is wrong. However, if I change the display birghtness with the power manager that will be the correct value for the centre popup next time I use the keys. So it appear to be one way. {F4034198}

Secondly, when I moust over the power management icon it gives the time remaining on battery, this time does not change from when I first check it. I started today at 41% battery with 1:14 remaining, now I'm on 18% battery still with 1:14 remaining. This is a different value to what is reported in `upower -d`, at 25% that reported 2.1 hours as time to empty, now at 18% it's giving 1.4 hours. I'm not sure where the widget calculates it from but it doesn't change on either of my laptops.

**Comment by davidjharder** [comment]
Old, closing
