### ISSUE TITLE
Solus 4.5 RC2 Xfce Desktop Icon for Calamares is Old

### ISSUE THREAD

**Issue by WetGeek** [getsolus/packages#1043]
### Summary

I created an entirely new VBox VM for Solus 4.5 Xfce based on the RC2 .ISO file, and started it.  Since I intended to see whether partitioning the disk would be improved from the last version, the first task I attempted was to start the installer.  Using the desktop icon on the UI didn't launch that installer.  It did nothing, and hovering the mouse over the icon displayed a tool tip indicating that it was the 12/12 version, not from 12/17.

I instead started the installer from the System menu, and that worked normally.  I'm about to begin the installation now.  

### Steps to reproduce

Create a new VBox VM with 4 GB of RAM and 4 CPU cores.  Assign its CD ROM the .ISO file for Solus Xfce RC2, and start the new VM.  When the UI appears, click on the Install icon on the desktop.

### Expected result

I expected that the Calamares installer would be launched, so I could install Solus onto the new VM.

### Actual result

Absolutely nothing happened, and the Tool Tip indicated that the installer icon is not current, but is from RC1 instead.  

### Environment

- [ ] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Xfce

### System details

Since I was unable to install the system, I can't answer this.

### Other comments

Starting the installer from the System menu works fine.  Only the desktop icon failed.

**Comment by TraceyC77** [comment]
@WetGeek , I just tested this in a smoketest ISO (built from internal up to date sources) and the installer on the desktop is up to date. Might I ask you to test this again when we release the next RC ISO? You'll get an email when they're available. Thanks!

**Comment by TraceyC77** [comment]
Closing, as I see the Calamares installer icon on the desktop, and it works as expected.
