### ISSUE TITLE
Desktop Flicker with Vesa Adaptive Sync Enabled (T9163)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#105]
<div dir="rtl"><b>Danny</b>&nbsp;(<em>&#35;WannaBeOCer</em>),&nbsp;2020-07-06&nbsp;20:21:57&nbsp;UTC</div><br/>

I noticed VRR works on the desktop which enables "Low Framerate Compensation" due to the low frame rate causing the desktop to flicker. On Windows the screen just locks itself at the selected refresh rate until games are launched. This occurs on both AMD and Nvidia cards using Vesa Adaptive Sync with monitors that support Low Framerate Compensation.

I noticed this happens on Budgie, Gnome and Plasma along on Solus. I did notice this issue on other distributions but also a few distributions with the expected behavior of the desktop just staying at the selected refresh rate. KDE Neon, Fedora 32 and openSUSE Tumbleweed are the distros I've noticed with the expected behavior using KDE Plasma and Gnome.

**Comment by ReillyBrogan** [comment]
Is this still an issue?

**Comment by ermo** [comment]
@WannaBeOCer Is this still an issue?
