### ISSUE TITLE
GUI locked up when attempting to wake from sleep - intermittent

### ISSUE THREAD

**Issue by TraceyC77** [getsolus/packages#1054]
### Summary

After putting my laptop to sleep, an attempt to wake it up resulted in it displaying an error and a blinking cursor on a black background. I could access the TTY, but not get back to the GUI (trying made the system appear to hang).

### Steps to reproduce

1. Put the system to sleep (I used a keyboard shortcut) and close the lid
2. Open the lid and press a key on the keyboard to wake the system

### Expected result

The system wakes and presents a lock screen

### Actual result

An error with blinking cursor on a black background. The system was unresponsive. I had to press the power button to do a hard boot. The battery was at 3% (seen after I rebooted)

The boot is in the attached logs near the end as:

```
Power key pressed short.
```

The logs start with the suspend event and end there.

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

Plasma

### System details

Operating System: Solus 4.5
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.112.0
Qt Version: 5.15.11
Kernel Version: 6.6.7-267.current (64-bit)
Graphics Platform: X11
Processors: 16 × 11th Gen Intel® Core™ i7-11800H @ 2.30GHz
Memory: 62.5 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2
Manufacturer: Dell Inc.
Product Name: XPS 17 9710

### Other comments
- This can happen whether or not any peripherals are connected to the laptop
- The contents of the error on screen are pretty consistent

```
~ ❯❯❯ ll /usr/bin/nvidia-sleep.sh
-rwxr-xr-x 1 root root 900 Dec 15 12:21 /usr/bin/nvidia-sleep.sh*
```

Error:

![20231218_laptop_rip](https://github.com/getsolus/packages/assets/10402612/e52a3a21-8354-4f31-ab7f-2cf492c7c8ca)

Logs:
[system_wake_log_2023-12-18.txt](https://github.com/getsolus/packages/files/13710556/system_wake_log_2023-12-18.txt)

Further troubleshooting:
After getting this error with a USB drive and Yubikey connected, I removed the USB drive. Then was able to suspend and wake as normal. But after removing the Yubikey while the system was awake, suspending and waking, I got the same type of error.

With no peripherals connected:
* Booted the laptop
* Connected to the dock
* Put system to sleep, attempted to wake
Got the black screen with error as described.

Was also able to reproduce with no peripherals connected at the time the system was put to sleep.

**Comment by TraceyC77** [comment]
After a bit more testing, I found this only occurs if a USB drive I use for backups is connected at wake.
If it is not connected the system wakes normally.
This only started happening in the last week or so, shortly before I filed the issue. The system woke with this drive connected successfully before.

**Comment by TraceyC77** [comment]
Intermittent, but it happened again today.

**Comment by TraceyC77** [comment]
This happened again a few times between yesterday and today with nothing plugged into the laptop when it went to sleep. peripherals connected or not seems to be not the cause

**Comment by ReillyBrogan** [comment]
What happens if you delete the `NVreg_PreserveVideoMemoryAllocations=1` option from your kernel command line?

**Comment by TraceyC77** [comment]
I've removed that option from the kernel boot parameters. I'll continue testing and let you know the outcome.

**Comment by TraceyC77** [comment]
Without that kernel parameter, I still had the same problem this morning when trying to wake the system from sleep.

```bash
~ ❯❯❯ cat /proc/cmdline
initrd=\EFI\com.solus-project\initrd-com.solus-project.current.6.6.11-270 root=PARTUUID=a7a26d35-2150-7f48-9225-78b81a6f62ea quiet splash systemd.show_status=false rw nvidia-drm.modeset=1 nvidia.NVreg_TemporaryFilePath=/var/tmp
```

mtp:/XQ-BC62/disk/DCIM/PHOTOGRAPHY_PRO/20240112_102319.JPG

**Comment by ReillyBrogan** [comment]
Per another report on Phoronix (of all places) this appears to be a KDE-specific issue. I know you are likely loathe to do this, but could you try GNOME and see if the same issue is present?

**Comment by TraceyC77** [comment]
I have Budgie installed alongside Plasma, I'll try to reproduce with Budgie.

**Comment by TraceyC77** [comment]
Notable that there is always this:
efi_pstore writing error -5

That service is disabled (which wasn't done by me), going to re-enable to see if I can catch logs next time

```bash
❯ systemctl status systemd-pstore
○ systemd-pstore.service - Platform Persistent Storage Archival
     Loaded: loaded (/usr/lib/systemd/system/systemd-pstore.service; disabled; preset: enab>
    Drop-In: /usr/lib64/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: inactive (dead)
       Docs: man:systemd-pstore(8)
```

The last logs in the relevant directory are from Mar 14

```bash
❯ sudo ls -la /sys/fs/pstore |tail -5
-r--r--r--  1 root root 1556 Mar 14 11:46 dmesg-efi_pstore-171043481215001
-r--r--r--  1 root root 1630 Mar 14 11:46 dmesg-efi_pstore-171043481216001
-r--r--r--  1 root root 1577 Mar 14 11:46 dmesg-efi_pstore-171043481217001
-r--r--r--  1 root root 1652 Mar 14 11:46 dmesg-efi_pstore-171043481218001
-r--r--r--  1 root root 1643 Mar 14 11:46 dmesg-efi_pstore-171043481219001
```

**Comment by TraceyC77** [comment]
This is still happening regularly. Unassigning from myself, since I can't fix it sadly.

**Comment by TraceyC77** [comment]
Related, from the nVidia developer forums [a screenshot of a similar RIP error](https://forums.developer.nvidia.com/t/series-550-freezes-laptop/284772/164)
From [Series 550 freezes laptop](https://forums.developer.nvidia.com/t/series-550-freezes-laptop/284772)

That screenshot is from someone with 555.42.02 and kernel 6.9.1.arch1-1

Another person said that for  them "535.171.04, kernel 6.8.7 + Xorg is most stable combination so far."

Based on comments, there were possibly changes with systemd services added in 550
Given these problems, would it be possible for us to package the 535 driver again?

**Comment by TraceyC77** [comment]
This is resolved. Currently I've got the 560-35-03 nvidia drivers installed.
