### ISSUE TITLE
scribus 1.5.8 won't launch (T10173)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#106]
<div dir="rtl"><b>brent&nbsp;webster</b>&nbsp;(<em>&#35;brent</em>),&nbsp;2022-02-25&nbsp;17:42:03&nbsp;UTC</div><br/>

Expected: install Scribus from repo, launch app, use scribus
Current: will not launch. install, reboot, launch, abort, uninstall, reboot, install, repeat

```
$ scribus
pathForIcon: Unable to load icon /usr/share/scribus/icons/1_5_1/lab.png: File not found
pathForIcon: Unable to load icon /usr/share/scribus/icons/1_5_1/spot.png: File not found
pathForIcon: Unable to load icon /usr/share/scribus/icons/1_5_1/register.png: File not found
qt.gui.icc: Unsupported ICC profile class 70727472
QPngHandler: Failed to parse ICC profile
QPainter::begin: Paint device returned engine == 0, type: 2
Scribus Crash
-------------
Scribus crashes due to Signal #11
QWidget::repaint: Recursive repaint detected
QPainter::begin: Paint device returned engine == 0, type: 2
Segmentation fault (core dumped)
```
Can gladly run debug commands or anything else you suggest. Thank you,

**Comment by davidjharder** [comment]
Old, original reporter is not using solus-packaged scribus.
https://discuss.getsol.us/d/8072-scribus-problems/6
