### ISSUE TITLE
Add Java as dependency of LibreOffice Base (T7172)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#107]
<div dir="rtl"><b>Yurizal&nbsp;Susanto</b>&nbsp;(<em>&#35;yursan9</em>),&nbsp;2018-11-07&nbsp;02:50:13&nbsp;UTC</div><br/>

I don't know how many people use LibreOffice Base. But ootb, you need to install JRE after installing LibreOffice Base.

{F4047235}

**Comment by davidjharder** [comment]
Old as dirt. Closing
