### ISSUE TITLE
Insecure lock-screen with multi-monitor setup (T2952)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#108]
<div dir="rtl"><b>Leum&nbsp;Dunn</b>&nbsp;(<em>&#35;HL_Benton</em>),&nbsp;2017-03-20&nbsp;13:47:16&nbsp;UTC</div><br/>

I have Solus installed onto a HP Elitebook 850 and a second screen which is a Samsung 4k monitor over displaylink.
If I lock my screen and walk away, both laptop and secondary monitors go blank.
When I return and move my mouse or use my keyboard to wake the machine, both screens will flicker as the lock-screen is rendered. During this rendering process, the content of my desktop will be displayed for a second or two before the unlock screen is drawn. 
This means that a malicious actor could simply walk up to my machine, wake the screen and record or photograph anything I'm working on and walk away again. 
There are no logs or errors generated that I'm aware of to indicate to me a failed or incomplete logon attempt.
I had planned to use power saving settings to stop the screen from ever blanking, but whilst these stop the machine hibernating, they don't appear to affect the lockscreen from blanking the screen.
I am patched up to date as of 20.03.2017 and have a video of the issue (but don't know where to send it).
This is the first time I've ever submitted a bug to any project so please let me know if you require additional detail.
Thanks, HL.

**Comment by TraceyC77** [comment]
If this is still an issue with Budgie, it should have an issue opened on their tracker
Closing as stale
