### ISSUE TITLE
DNS Leak with NetworkManager-openvpn connections. (T5436)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#11]
<div dir="rtl"><b>Eric&nbsp;S.</b>&nbsp;(<em>&#35;eric-salo</em>),&nbsp;2018-01-02&nbsp;00:57:28&nbsp;UTC</div><br/>

This was raised as [a package request in March](https://dev.solus-project.com/T2931), and I think it is time it gets solved on the development end, or at very least publish the fix on the blog and make people aware of the issue.

By default, NetworkManager's DNS settings are preferred over OpenVPN's when NetworkManager-openvpn is used to make the connection. This causes your ISP's location to be leaked and detectable, information that could be used against protestors, activists, and people living under oppressive third world regimes. People use VPN's for privacy, and NetworkManager-openvpn... without providing the packages necessary to fix it, provides nothing but a false sense of security to people who need actual security.

https://github.com/masterkorp/openvpn-update-resolv-conf  
Here is another workaround for this issue using systemd-resolved: https://github.com/jonathanio/update-systemd-resolved

**Comment by ermo** [comment]
@silkeh Can you reproduce this?

**Comment by ReillyBrogan** [comment]
This is probably resolved after the switch to systemd-resolved.
