### ISSUE TITLE
Error: CUPS waiting for job to be completed" even though printing works fine (T5972)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#111]
<div dir="rtl"><b>Mario</b>&nbsp;(<em>&#35;Speedhoven</em>),&nbsp;2018-03-03&nbsp;09:42:49&nbsp;UTC</div><br/>

Hello,

Every time I print something, this notification appear:

"Error: CUPS waiting for job to be completed"

However, it still prints with no issues and after a few seconds I get the notification that the file was correctly printed.

I'm using Solus Budgie (freshly installed and updated) and my printer is a HP OfficeJet 6950 connected via Wi-Fi.

**Comment by davidjharder** [comment]
Nobody likes printers anyway
