### ISSUE TITLE
CoreCtrl profiles don't work (T10177)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#114]
<div dir="rtl"><b>Jonata&nbsp;de&nbsp;Paula</b>&nbsp;(<em>&#35;Khrona</em>),&nbsp;2022-02-27&nbsp;01:27:22&nbsp;UTC</div><br/>

I don't know if this is an issue with Solus or CoreCtrl, but currently CoreCtrl can't activate anything but the Global Profile.

I need to set my GPU to max clock to get better performance on Elden Ring, and doing it manually every time I open the game is a hassle. CoreCtrl supports this with multiple profiles. So far I tried by inputting 'eldenring.exe', 'wineserver' and even tested with 'firefox', 'Firefox' and 'Steam', 'steam', None work, and I couldn't find much about it online too.

**Comment by ermo** [comment]
I have just successfully created and activated/de-activated/activated a manual profile. Closing as completed.
