### ISSUE TITLE
Problems with LTS kernel

### ISSUE THREAD

**Issue by malfisya** [getsolus/packages#1144]
### Summary

I just booted to LTS kernel after a long time to test droidcam and I found a few problems. Here is the list :
1. **Audio device not working**. Both on Wayland and X11. This is a PC tower with speaker plugged in to rear 3.5 mm jack.
2. **Flatpak apps is not visible in app menu**. This only happens in Wayland but not in X11. Flatpak apps are still available/installed by checking with `flatpak list` and can be launched with `flatpak run`.

None of this behaviour present last time I booted to LTS kernel which is around November (Also to test droidcam). Also all of this behaviour is not present in linux-current.

### Steps to reproduce

1. Install `linux-lts`
2. Boot to `com.solus-project.lts.5.15.144-226`
3. Login to Wayland session

### Expected result

None of the problems present

### Actual result

Audio not working, flatpak apps not showing

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

GNOME

### System details

**Hardware Information:**
- **Memory:**                                      16,0 GiB
- **Processor:**                                   Intel® Core™ i5-3570K × 4
- **Graphics:**                                    AMD Radeon™ RX 550 / 550 Series
- **Disk Capacity:**                               752,2 GB

**Software Information:**
- **Firmware Version:**                            4.6.5
- **OS Name:**                                     Solus 4.5 Resilience
- **OS Type:**                                     64-bit
- **GNOME Version:**                               45.2
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.6.8-268.current

### Other comments

[journalctl.txt](https://github.com/getsolus/packages/files/13792675/journalctl.txt)

**Comment by ReillyBrogan** [comment]
Hi @malfisya. The current plan with the LTS kernel is to replace it in February with 6.6. Given that I'm not going to spend time fixing things in a kernel that will be replaced soon anyway I'm going to go ahead and close this. Please feel free to re-open if these issues still happen in the -current kernel, as that will essentially become the new LTS kernel build.
