### ISSUE TITLE
Switch (back) to i3lock-color fork (T8187)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#115]
<div dir="rtl"><b>Evan&nbsp;Wegley</b>&nbsp;(<em>&#35;tomocafe</em>),&nbsp;2019-07-29&nbsp;19:18:38&nbsp;UTC</div><br/>

A while back the `i3lock` repo was switched to the [i3lock-color](https://github.com/PandorasFox/i3lock-color) fork but quickly reverted back to the standard version due to stability issues with the fork. (See our i3lock repo for the history on this.)

I've been using the i3lock-color fork for a few months, locally built on my Solus machine. 

Can we consider moving (again) to this fork? I can do the work if needed.

**Comment by TraceyC77** [comment]
At this time the [main fork](https://github.com/i3/i3lock) is being actively maintained. Last update was 3 mo ago.
The latest release is [2.15](https://github.com/i3/i3lock/releases/tag/2.15) from March of this year

The [fork](https://github.com/Raymo111/i3lock-color) has a latest release from July 2023
The latest update was 10 months ago to the README.md

At this point, the main repo is more up to date. We should update the package to 2.15 from there. I've submitted [an update request](https://github.com/getsolus/packages/issues/4239)
