### ISSUE TITLE
Xfce: Laptop won't hibernate when  lid is closed.

### ISSUE THREAD

**Issue by WetGeek** [getsolus/packages#1161]
### Summary

Several times I've closed the lid on my laptop while the action for that was set to hibernate but that has never worked for me.  

### Steps to reproduce

1.  On a laptop loaded with Xfce, choose the action to hibbernate when the lid is closed.
2.  When the computer won't be needed for a while, close its lid.
3.  Later, reopen the laptop lid.

### Expected result

I expected the previous session to be continued, just as it was before I closed the lid.

### Actual result

The screen was visible, but it was because the screen had never been shut off.  
![image](https://github.com/getsolus/packages/assets/6805994/16f2f667-bc48-4397-92be-8663da85cc3b)

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Xfce

### System details

![image](https://github.com/getsolus/packages/assets/6805994/84c60425-3078-4101-837b-b7ef4c6a205d)

**Comment by TraceyC77** [comment]
@WetGeek , what ISO were you using? RC5?

**Comment by WetGeek** [comment]
Yes, it was RC 5.  Note that I just edited this as you were looking at it.  To be sure, why not take another look.  
At first, I was confusing it with another problem I'd seen a while ago.  It actually has to do with not hibernating.
