### ISSUE TITLE
Update dnscrypt-proxy to 2.1.1 (T10222)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#118]
<div dir="rtl"><b>Marshall</b>&nbsp;(<em>&#35;Marshallishere</em>),&nbsp;2022-04-03&nbsp;18:20:38&nbsp;UTC</div><br/>

Since the repo version there were a lot of bugfixes and new features.

Link to the source code: https://github.com/DNSCrypt/dnscrypt-proxy/archive/refs/tags/2.1.1.tar.gz

**Comment by androidnisse** [comment]
The newest version is in the repo now, so this is resolved.

**Comment by algent-al** [comment]
Thanks for the heads up @androidnisse
