### ISSUE TITLE
Inclusion of the poly cmd tool to manage projects using the polylith architecture

### ISSUE THREAD

**Issue by olymk2** [getsolus/packages#1195]
### Homepage

https://github.com/polyfy/polylith

### Why should this be included in the repository?

Developer tool to help developing lego like reusable components for complex projects. 

### Are we allowed to redistribute it?

Eclipse Public License - v 1.0

### What kind of user will use this package, and how many users do you think will use this package?

Developers

### Link to source archive file

https://github.com/polyfy/polylith/archive/refs/tags/v0.2.18.tar.gz

**Comment by olymk2** [comment]
If accepted I will create a pull request for inclusion.

**Comment by ReillyBrogan** [comment]
So this is a build system like Gradle or Maven? But Clojure-specific?

**Comment by olymk2** [comment]
kind of its more for management it creates boiler plate code run tests against only changes code, enforces and checks that the layout is correct etc

You still use maven / clojars separately via your deps.edn files.

Basically it structures you projects into component bases and projects the tool lets you run commands like this

poly create component name:validation
poly create project name:backend-api

those create the folder structure and basic files for you you can then run commands like this

poly info
poly test

It can then tell you which projects are using your components, and can check dependencies so if you have 3 projects and 2 use a component and run poly test it will only run the test suit for the 2 projects that use the shared component.

hope the simple example above helps explain what the tool does.
