### ISSUE TITLE
Solus Budgie Desktop Login does not work with latest update

### ISSUE THREAD

**Issue by ChriA3** [getsolus/packages#1203]
### Summary

Hello Solus team. I am only a simple user of your great software and hope this is the right place to post this: I have a problem with some part of the software which became updated around December 23rd 2023... but I am not sure which part it is. The problem is, that I can not login to my Solus Account after the update. Can you please help me finding out the real problem and solve it? Thank you very much!

### Steps to reproduce

1. Using Solus Budgie Installation from December 23rd -> everything works fine (see system details below)
2. Upgrade latest available Upgrades (in my case 41 updates) works fine
3. System after upgrade works fine
4. Turn off the computer or restart
5. Turn on computer works fine until Login Screen
6. Entering Login Name and Enter -> shows Login Screen again (same for all logins on the screen) = FAILURE
7. Login with CTRL ALT F2 works fine
8. Downgrade updates with "sudo eopkg history -t xxx" resolves the problem

### Expected result

At Step 6 -> Login should work
Step 7-8 should not be necessary

### Actual result

At Step 6 -> Entering Password works but with Enter or Button -> turning back to Login Page
Step 7-8 necessary to be able to normally login to system and use it

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Budgie

### System details

![Snapshot_2024-01-06_18-22-00](https://github.com/getsolus/packages/assets/155837688/fc1edbeb-be45-4f5a-85b6-0c4522381143)

-> This is the latest working system...

**Comment by joebonrichie** [comment]
Hi, thanks for the bug report and sorry for the trouble. Can you list the packages downgraded as part of the `eopkg history` here? That'll help narrow it down.

Additionally, after an unsuccessful login from the GUI can you post output of `sudo journalctl -b | tail -n 200` after switching to TTY and logging in there.

**Comment by ChriA3** [comment]
Hi, Thank you very much for the answer. I send you both infos as files attached... Hope you can use it!
[eopkg.txt](https://github.com/getsolus/packages/files/13850782/eopkg.txt)
[journalctl200.txt](https://github.com/getsolus/packages/files/13850788/journalctl200.txt)

**Comment by ReillyBrogan** [comment]
Alright, unfortunately it doesn't look like that journal log captured everything. Can you re-do those steps but give us the output of `sudo journalctl -b > journal.log` (there should be a created `journal.log` file wherever you ran that command, you can upload that to hastebin or something). I did notice one issue in your logs that I went ahead and fixed, but I doubt it was the cause of your issue. 

Also, could you give us the output of `tree /etc/pam.d` (install the `tree` package if you get a command not found message).

**Comment by ChriA3** [comment]
With the latest updates the problem became worse, now I cannot go back in eopkg history any more with failure: "Deposit item qca not found"... now I do not have normal access to my pc and I have no idea how to send you the files I generated.... 

I can make pictures from the screen, but not sure if that helps? ;-) 
![IMG_20240108_113858](https://github.com/getsolus/packages/assets/155837688/790938b2-2adb-4b71-b00b-4a8ad9c64f77)

**Comment by ReillyBrogan** [comment]
Are you able to hop on the Solus Matrix from your phone by any chance? We can probably help you more interactively there. Also, is there anything in `/etc/pam.d`? It's okay if that folder doesn't exist. I notice that you shared the `tree` for `/usr/share/defaults/etc/pam.d` which is not what we need.

**Comment by ReillyBrogan** [comment]
If you have a flash drive you can copy the journal logs to it and then upload them from another computer.

**Comment by ChriA3** [comment]
Hi, thank you so much for your patience! And for the hint with the usb drive, that worked... 
I tried hastebin for the journal.log: https://hastebin.de/viserokixu
And yes, you are right, /etc/pam.d does not exists, I just searched for pam.d and found the other one... 

If it is necessary we can try this with "Solus Matrix" by phone... however I need more infos, I do not exactly know, what you mean and how it works, very sorry about that...

**Comment by ReillyBrogan** [comment]
Please update again and see if you still have the issue upon reboot. You should see dbus-broker as the only package being updated.

**Comment by ChriA3** [comment]
Hi, I upgraded dbus-broker and everything works fine now. Thank you very much for your effort and help!! Have a wonderful day!
