### ISSUE TITLE
Laptop speakers snd_hda_intel current kernel issue. (T9570)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#121]
<div dir="rtl"><b>David</b>&nbsp;(<em>&#35;dms</em>),&nbsp;2021-02-10&nbsp;19:29:19&nbsp;UTC</div><br/>

**No sound from laptop speakers with latest kernel 5.10.12-171.current**

Latest fully updated Solus with current kernel there is no sound via laptop speakers but if I plug in headphones the sound works fine via headphones only, unplug them and no sound again.

If I boot the last live Solus linux usb the sound works fine via laptop speakers. Also if I boot with the LTS kernel, sound works fine. A quick google searching the last 4 weeks only shows other distros have been having this issue with snd_hda_intel and current kernel.

lspci -nnk | grep -A2 Audio
00:1b.0 Audio device [0403]: Intel Corporation 7 Series/C216 Chipset Family High Definition Audio Controller [8086:1e20] (rev 04)
Subsystem: ASUSTeK Computer Inc. 7 Series/C216 Chipset Family High Definition Audio Controller [1043:14c7]
Kernel driver in use: snd_hda_intel
00:1c.0 PCI bridge [0604]: Intel Corporation 7 Series/C216 Chipset Family PCI Express Root Port 1 [8086:1e10] (rev c4)

sudo dmesg | grep snd
[ 6.308028] snd_hda_intel 0000:00:1b.0: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[ 6.350354] snd_hda_codec_via hdaudioC0D0: autoconfig for VT1802: line_outs=1 (0x24/0x0/0x0/0x0/0x0) type:speaker
[ 6.350359] snd_hda_codec_via hdaudioC0D0: speaker_outs=0 (0x0/0x0/0x0/0x0/0x0)
[ 6.350361] snd_hda_codec_via hdaudioC0D0: hp_outs=1 (0x25/0x0/0x0/0x0/0x0)
[ 6.350363] snd_hda_codec_via hdaudioC0D0: mono: mono_out=0x0
[ 6.350364] snd_hda_codec_via hdaudioC0D0: inputs:
[ 6.350367] snd_hda_codec_via hdaudioC0D0: Mic=0x29

inxi -SMA
System: Host: asus-i5 Kernel: 5.10.12-171.current x86_64 bits: 64 Desktop: Budgie 10.5.2 Distro: Solus 4.2
Machine: Type: Laptop System: ASUSTeK product: X75VD v: 1.0 serial: <superuser required>
Mobo: ASUSTeK model: X75VD v: 1.0 serial: <superuser required> BIOS: American Megatrends v: X75VD.409
date: 12/26/2012
Audio: Device-1: Intel 7 Series/C216 Family High Definition Audio driver: snd_hda_intel
Sound Server: ALSA v: k5.10.12-171.current

aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: PCH [HDA Intel PCH], device 0: VT1802 Analog [VT1802 Analog]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 2: VT1802 Alt Analog [VT1802 Alt Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

**Comment by davidjharder** [comment]
Old, no new info. Closing
