### ISSUE TITLE
Update insomnia to 2022.2.1 (T10238)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#122]
<div dir="rtl"><b>Marc&nbsp;Sommerau</b>&nbsp;(<em>&#35;seagle</em>),&nbsp;2022-04-21&nbsp;13:19:45&nbsp;UTC</div><br/>

Insomnia has gotten new releases in March with fixes and improvements. Please consider updating the package to the latest stable version 2022.2.1

Changelog:
- https://insomnia.rest/changelog#2022.1.0
- https://insomnia.rest/changelog#2022.1.1
- https://insomnia.rest/changelog#2022.2.0
- https://insomnia.rest/changelog#2022.2.1

**Comment by androidnisse** [comment]
Just tried to add the homepage to package.yml and it did not build so still broken.
