### ISSUE TITLE
Calamares - Partitions screen is not big enough to show contents

### ISSUE THREAD

**Issue by TraceyC77** [getsolus/packages#1239]
### Summary

After selecting an install option on the Partitions screen, the window is too small to show the content, which is cut off

### Steps to reproduce

1. Boot up a system / VM with the latest installer
2. Go through the steps until you get to Partitions
3. Select the option "Install alongside", "Replace a Partition" or "Erase Disk"

### Expected result

I can see all content in the window (it may need to auto-adjust, or the window is set to the biggest screen for all screens)

### Actual result

The bottom pane gets one line bigger, pushing upward.
The content at the bottom of the top pane is too big to fit and is cut off, obscuring the choice I made. There is a scrollbar. 

In the case of "Erase Disk", this obscures the swap / filesystem drop down options. You need to scroll down to see them or enlarge the window.

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Xfce

### System details

XFCE Calamares installer shipped with 4.5

### Other comments

Seen with the XFCE spin, I believe I saw it in other spins as well
Workaround: You can enlarge the window with the mouse, or use the scrollbar in the top pane.

**Comment by joebonrichie** [comment]
https://github.com/getsolus/packages/blob/main/packages/c/calamares/files/install/branding/solus/branding.desc#L41

**Comment by TraceyC77** [comment]
I see in that file we specified on line 32

```
windowExpanding:    noexpand
```
