### ISSUE TITLE
Selecting "Format..." in USB drive context menu in Files does nothing.  (T10272)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#125]
<div dir="rtl"><b>goldie</b>&nbsp;(<em>&#35;goldencut</em>),&nbsp;2022-05-26&nbsp;09:24:43&nbsp;UTC</div><br/>

When I insert FAT32 USB stick and open Files, then right-click on that drive and select "Format..." nothing happens - the menu stays open and no other apps or windows pop up. I assume this isn't intended behavior.

**Comment by davidjharder** [comment]
Budgie uses Nemo now. Also no new info. Closing
