### ISSUE TITLE
cmus audio player hangs on pipewire

### ISSUE THREAD

**Issue by ListeningGarden** [getsolus/packages#1254]
### Summary

cmus 2.10.0 will hang playback when switching albums after being idle and paused for a certain period of time (5-10+ minutes, does not seem consistent and will sometimes do it without the idle time at all) and will fail to quit gracefully if exited while the audio is paused. the player does reactivate after 15-30 seconds and will terminate eventually after quitting, but this is a fairly significant degradation of performance

cmus/cmus#1268 fixes the issue (which is related to pipewire, which is now the default audio server on solus), but an official release of the player has not been made since july of 2022, so the version we have in the repos is faulty

### Steps to reproduce

1.) load cmus music player from solus repositories
2.) load a library with multiple albums
3.) play a song from one album
4.) pause the track, and leave the player idle for 10 or so minutes
5.) attempt to switch to another album 

and

1.) load cmus music player from solus repositories
2.) load library
3.) play a song, then pause it
4.) quit cmus while song is paused

### Expected result

cmus should switch immediately to the new album and track without any delay

and

cmus should exit gracefully to a functional terminal prompt without delay

### Actual result

cmus will hang playback and sometimes the entire application itself for 15-30 seconds before it switches the track properly

and

cmus will terminate but the terminal remains inactive for 15-30 seconds before the system reports its successful shutdown and the terminal prompt allows input again

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Budgie

### System details

ASUS TUF GAMING X570-PRO _WI-FI_
32.0 GiB RAM
AMD Ryzen™ 5 5600X × 12
NVIDIA GeForce RTX™ 3070

budgie version: 10.8.2
os name: Solus 4.5 Resilience
os type: 64-bit
windowing system: X11
kernel version: Linux 6.6.9-269.current

**Comment by malfisya** [comment]
Hey sorry about the problem! I am the the guy that updated this package not realizing there is annoying bug. I patch cmus in this [link](https://send.internxt.com/download/fbadd36d-981b-4618-987d-7fc672029dde?code=f8e0b452f4b17d0cfda043f2dfed24ccf366c7f1bf29676d64204688101d2ca7). From the folder you downloaded into you can run :
```sh
sudo eopkg it cmus-2.10.0-20-1-x86_64.eopkg
```
Let me know if the bugs fixed for you. After this i will make PR for this patch. Cheers!

**Comment by ListeningGarden** [comment]
ran tests over the afternoon/evening with the build you provided, and can confirm that the fix does restore intended functionality with no observed drawbacks caused. should be all cleared for sync into stable, thank you for the quick patch!

**Comment by malfisya** [comment]
Nice, lets wait until Friday sync. I hope this can be merged to unstable soon.
