### ISSUE TITLE
Unknown Horizons porting to Godot, we should deprecate

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#126]
<div dir="rtl"><b>Thomas&nbsp;Staudinger</b>&nbsp;(<em>&#35;Staudey</em>),&nbsp;2021-09-07&nbsp;01:30:26&nbsp;UTC</div><br/>

The game Unknown Horizons (from the repo) fails to launch with the following error:

```
Traceback (most recent call last):
  File "/usr/bin/unknown-horizons", line 381, in <module>
    main()
  File "/usr/bin/unknown-horizons", line 122, in main
    ret = horizons.main.start(options)
  File "/usr/lib/python3.9/site-packages/horizons/main.py", line 113, in start
    horizons.globals.fife = Fife()
  File "/usr/lib/python3.9/site-packages/horizons/engine/engine.py", line 46, in __init__
    self._setting = Settings(PATHS.USER_CONFIG_FILE, PATHS.SETTINGS_TEMPLATE_FILE)
  File "/usr/lib/python3.9/site-packages/horizons/engine/settings.py", line 39, in __init__
    self._settings_serializer.load(settings_file)
  File "/usr/lib/python3.9/site-packages/fife/extensions/serializers/simplexml.py", line 132, in load
    self._validateTree()
  File "/usr/lib/python3.9/site-packages/fife/extensions/serializers/simplexml.py", line 386, in _validateTree
    for c in self._root_element.getchildren():
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'
```

After a bit of research it seems we should add the following patch to `fifengine`, to restore compatibility with Python >= 3.9 and fix this error:
https://github.com/fifengine/fifengine/commit/78c07b9ac4df03329bcaf052557b9c9450b18d3a

There is also a Python 3.9 fix commit for Unknown Horizons itself, which might be worth including while we're at it:
https://github.com/unknown-horizons/unknown-horizons/commit/7f6f613826aef9810999c1599c8354e8a78fbdb4

(and maybe this to fix a warning: https://github.com/unknown-horizons/unknown-horizons/commit/05267e0d7f1223ddd0517f4f02c4d8444668f559)

Adding &#35;DataDrake because she is the maintainer.

**Comment by davidjharder** [comment]
From the project GH page: 

> [Unknown-Horizons based on Fifengine is no longer in development. We are porting it to Godot Engine.](https://github.com/unknown-horizons/unknown-horizons#unknown-horizons-based-on-fifengine-is-no-longer-in-development-we-are-porting-it-to-godot-engine)

We should probably deprecate this.

**Comment by malfisya** [comment]
It runs though right now, i just played it in reference to this commit https://github.com/getsolus/packages/pull/598/commits/f4f5434750b183b5559ca9550fb7e852d97b2453
