### ISSUE TITLE
Kernel amdgpu NULL pointer dereference

### ISSUE THREAD

**Issue by GZGavinZhao** [getsolus/packages#1266]
As reported in https://gitlab.freedesktop.org/drm/amd/-/issues/2991, to prevent ROCm 6.0 from crashing, kernel commit [`96c211f1f9ef82183493f4ceed4e347b52849149`](https://github.com/torvalds/linux/commit/96c211f1f9ef82183493f4ceed4e347b52849149) should be reverted. I'm not sure why this doesn't causes ROCm 5.5 to crash, but I can confirm that without reverting this commit Blender with ROCm 6.0 crashes with the same reported error message, and after the revert Blender works again.

**Comment by GZGavinZhao** [comment]
This is not an urgent patch, because even with this patch there are remaining issues (e.g. sporadic GPU memory access fault) that nobody has been able to reliably reproduce and fix, so if there are issues with higher priority feel free to leave this patch till the next kernel update. The purpose of this revert is just to make Blender at least partially work with ROCm 6. Without this revert, Blender just doesn't work at all with ROCm 6.

**Comment by ReillyBrogan** [comment]
Revert doesn't apply cleanly, I'll look at it again later
