### ISSUE TITLE
Package request: loupe (default GNOME image viewer as of GNOME 45)

### ISSUE THREAD

**Issue by sebo505** [getsolus/packages#1272]
### Homepage

https://gitlab.gnome.org/GNOME/loupe

### Why should this be included in the repository?

As of GNOME 45, GNOME introduced loupe as the default GNOME image viewer app. It uses GTK4 and is written in rust.
While there is nothing wrong in particular with Eye of GNOME (eog) and we should keep it around, I think as a matter of coherence Solus should provide loupe in the repo, and, subsequently, ship it as the default image viewer for GNOME.

### Are we allowed to redistribute it?

GPL3 licence

### What kind of user will use this package, and how many users do you think will use this package?

Everyone using GNOME would use it, if adopted as default image viewer

### Link to source archive file

https://gitlab.gnome.org/GNOME/loupe/-/archive/main/loupe-main.tar.gz

**Comment by malfisya** [comment]
I already have local recipe working. I will submit a PR if this is approved. Cheers!

**Comment by sebo505** [comment]
Well, that went quick. Thank you.
