### ISSUE TITLE
Discord crash when minimize in task bar (gnome)

### ISSUE THREAD

**Issue by camini** [getsolus/packages#1278]
### Summary

My discord has crashed many time when i minimize it to task bar in Gnome.

### Steps to reproduce

Open Discord on gnome
close it, so it only appear in appindicator.
try to open it from the appindicator
Discrod crash.

### Expected result

don't crash

### Actual result

It crash many time

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

GNOME

### System details

*

**Comment by joebonrichie** [comment]
I can produce this in the gnome Wayland session but not the x11 one. Seems to be some sort of problem with the appindicator extension.

**Comment by joebonrichie** [comment]
Upstream issue: https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/445

**Comment by camini** [comment]
don't have this issue on my gentoo/gnome45.2 wayland and appindicator.

**Comment by joebonrichie** [comment]
It's because with run discord under wayland if supported rather than xwayland with:

`/usr/share/discord/Discord --enable-features=WaylandWindowDecorations --ozone-platform-hint=auto`

if you just run `discord` from the terminal normally the issue goes away?

**Comment by camini** [comment]
yes , no crash when i just rundiscord with the terminal

**Comment by joebonrichie** [comment]
@ReillyBrogan is there any issue with reverting to xwayland for discord on plasma wayland?

**Comment by ReillyBrogan** [comment]
After the next sync you can set the `DISCORD_NO_WAYLAND` environmental variable and it will launch in xwayland.

**Comment by Neo-29** [comment]
> After the next sync you can set the `DISCORD_NO_WAYLAND` environmental variable and it will launch in xwayland.

How to do so?
