### ISSUE TITLE
Wrong keyboard layout at KDE login screen (T10298)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#128]
<div dir="rtl"><b>Marko</b>&nbsp;(<em>&#35;playforvoices</em>),&nbsp;2022-06-25&nbsp;08:08:49&nbsp;UTC</div><br/>

Hi dev team,

I use the German version of Solus with KDE. At the first startup, the login screen will use the English keyboard layout instead of the German one. If I'm successfully logged in, and I just lock my screen, then the German layout works if I unlock again. 

Is this an issue or have I something not set properly?

**Comment by davidjharder** [comment]
Closing this in favor of #88
