### ISSUE TITLE
Plasma 6 packaging megathread

### ISSUE THREAD

**Issue by Justinzobel** [getsolus/packages#1286]
### KDE Frameworks deps

- [x] accounts-qt6 (temp fork: https://gitlab.com/nicolasfella/libaccounts-qt/-/tree/qt6) (see kf6-purpose)
- [x] Appstream 1.x + qt bindings (https://github.com/getsolus/packages/pull/1281)
  - [x] Rebuild Frameworksintegration
- [x] qca-qt6
- [x] Catdoc for kfilemetadata (optional, enables microsoft office document parsing)
- [x] Fix kf6-purpose w/ kaccounts-integration
- [ ] (optional) XZing for barcode scanning (kf6-prison)

### Plasma deps
- [x] Phonon 4.12 and phonon-vlc + qt5/qt6
- [x] libqaccessibilityclient v0.6
- [x] kirigami-addons 0.11.75 qt6
- [x] signond, signon-plugin-oauth2, signon-ui
- [x] xdg-utils needed [a change](https://gitlab.freedesktop.org/xdg/xdg-utils/-/merge_requests/67) to support KDE_SESSION_VERSION=6. A [new release](https://gitlab.freedesktop.org/xdg/xdg-utils/-/issues/223) is needed
- [x] packagekit Qt6
- [x] kde-inotify-survey
### Gear deps
- [x] ktextaddons v1.5.3 + qt6 bindings
- [x] libquotient - Update and switch to qt6 build (neochat is the only consumer so we don't need to keep around qt5 bindings)
- [x] libkcddb needs a Qt 5 version for k3b and a Qt 6 version for kio-audiocd.
- [x] WAY MORE https://community.kde.org/KDE_Gear/24.02_Release_notes

### Other packages that should be updated
- [ ] kstars - Outdated
- [ ] kdocker - outdated
- [x] gcompris

### Add to plasma-branding
- [x] xwaylandvideobridge

### Can be removed (probably)
- [x] phonon-gstreamer
- [ ] kuserfeedback (non-KF6 version)

**Comment by ReillyBrogan** [comment]
Currently broken for me:
- drkonqi service is crashing on start
- Taking a screenshot doesn't show the preview in the notification

**Comment by Justinzobel** [comment]
> Icons in the screen that shows up when you hit "logoff/shutdown/restart" aren't showing up

Check you have breeze-qt6 and plasma-integration installed

> Taking a screenshot doesn't show the preview in the notification

Check you have ffmpegthumbs maybe?

**Comment by HarveyDevel** [comment]
```
File conflicts:
/usr/share/applications/kde-mimeapps.list from plasma-desktop-branding package.
```

**Comment by Justinzobel** [comment]
Closing as this is now in unstable.
