### ISSUE TITLE
Screen flickering stopped in X11, but still present with Wayland

### ISSUE THREAD

**Issue by WetGeek** [getsolus/packages#1291]
### Summary

As discussed in the Solus forum recently, https://discuss.getsol.us/u/BuzzPCSOS, there is a small file that can be used to eliminate the flickering many of us have noticed when the mouse pointer is near the bottom of our screens.  Sadly, this fix doesn't seem to affect a Wayland session.  Since Wayland is now becoming very popular, and will eventually replace X11, it would be great if a way were found to apply that fix to Wayland sessions as well.

### Steps to reproduce

I notice it mostly when I'm using Vivaldi, but that's probably because I use Vivaldi most of the time.  So I'm not sure that Vivaldi has anything to do with it.  I just rebooted to an X11 session and the issue is conspicuous by its absence.  I can move the mouse cursor all over the lower screen area with no sign of the flickering I notice with Wayland.

### Expected result

Screen image will be stable, even when the mouse pointer is near the bottom of the screen.

### Actual result

There's a very obvious flashing, or "stuttering," visual effect when the mouse pointer first enters an area near the bottom of the screen.

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Plasma

### System details

![image](https://github.com/getsolus/packages/assets/6805994/58292485-12ff-4397-8d5b-f6720e3c3fea)

**Comment by Justinzobel** [comment]
Any chance you can try this on the Plasma 6 testing repo to see if it still occurs?

**Comment by WetGeek** [comment]
I'd be happy to help, but I've not accessed the Plasma 6 repo yet.  What's the incantation to change to it?  It's bedtime here in about 5 minutes, but I can get on it first thing in the morning.  And I can leave my workstation on Plasma 6 in case any further testing would  be helpful - I'm not currently using it for anything else.

**Comment by Justinzobel** [comment]
I'd suggest jumping in the #solus-packaging:matrix.org Matrix channel as it requires using the unstable repository which fluctuates a bit and updates to that repository are announced there so you know when it's safe to update.

**Comment by Justinzobel** [comment]
I'd suggest jumping in the #solus-packaging:matrix.org Matrix channel as it requires using the unstable repository which fluctuates a bit and updates to that repository are announced there so you know when it's safe to update.

**Comment by WetGeek** [comment]
My workstation was already using unstable, so I checked to be sure it wasn't blocked, and did an update.  100 packages upgraded on this machine.  Since I'd gotten used to ignoring the defect and just moving the mouse a bit to clear it up, I wanted to use the workstation for a while and purposely use the mouse in areas that were likely to expose the problem, if it still exists.

I read some email on Thunderbird, checked for forum messages with Vivaldi, and used an upgraded Handbrake to rip a John Wick DVD to the Videos share on my NAS, then added a comment to the issue I'd reported about k3b not working.  The new Handbrake makes a great replacement for k3b, in my opinion.

So I've been testing this issue for more than 1/2 hour, and found no "stuttering" at all when the mouse is at or near the bottom of the screen.  Since nothing unusual has occurred, I'm going to change my daily laptop to unstable now, and update it.  I want to test this on the machine where I most often needed to deal with the issue.  I'll return here and let you know how that worked out, and if it's the same as on this workstation, I'll close this bug report.

Thanks to everyone who's helped to make Plasma 6 a reality!

**Comment by WetGeek** [comment]
I'm logged in from my daily-driver laptop now, and have changed to unstable and done an update.  I've been using it for a variety of typical tasks for about an hour, and have seen no evidence of the issue I reported here, so I'm going to call this one "fixed."
