### ISSUE TITLE
[Do Not Starve Together] Mouse doesn't work (T5789)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#13]
<div dir="rtl"><b>Kim&nbsp;Kröger</b>&nbsp;(<em>&#35;Blodoffer</em>),&nbsp;2018-02-10&nbsp;13:01:19&nbsp;UTC</div><br/>

Somehow this is a Solus specific issue: http://steamcommunity.com/app/322330/discussions/0/1620599015907038390/ No such complaints on other distros.

**Comment by davidjharder** [comment]
Very old, closing.
