### ISSUE TITLE
XFCE does not respond to keyboard shortcuts set in Window Manager which use the Super key

### ISSUE THREAD

**Issue by TraceyC77** [getsolus/packages#1302]
### Summary

Shortcuts set in Window Manager do not trigger the action they are set for if the Super key is part of the shortcut

### Steps to reproduce

1. Open Window Manager
2. Changed a few shortcuts, Tile window to right / left / bottom / top. The keyboard combo was recognized, since it was accepted, in all cases. All new shortcuts had the Super key

![xfce_window_shortcuts_2024-01-14](https://github.com/getsolus/packages/assets/10402612/be974e9c-c7d6-4fa2-97db-84464e9073ed)

### Expected result

When pressing the keyboard shortcut (ex: Super+Up) the action is triggered (ex: Tile window to the top)

### Actual result

The application menu expands as if only the Super key was pressed

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Xfce

### System details

```bash
$ inxi -b
System:
  Host: tracey-flex-solus-xfce Kernel: 6.6.9-269.current arch: x86_64 bits: 64
    Desktop: Xfce v: 4.18.1 Distro: Solus 4.5 resilience
Machine:
  Type: Laptop System: LENOVO product: 81SS v: Lenovo IdeaPad FLEX-14API
    serial: <superuser required>
  Mobo: LENOVO model: LNVNB161216 v: SDK0J40709 WIN
    serial: <superuser required> UEFI: LENOVO v: AGCN29WW(V1.12)
    date: 02/21/2022
Battery:
  ID-1: BAT1 charge: 40.0 Wh (99.0%) condition: 40.4/45.0 Wh (89.8%)
CPU:
  Info: quad core AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx [MT MCP]
    speed (MHz): avg: 1384 min/max: 1400/2300
Graphics:
  Device-1: AMD Picasso/Raven 2 [Radeon Vega Series / Radeon Mobile Series]
    driver: amdgpu v: kernel
  Device-2: Chicony Integrated Camera driver: uvcvideo type: USB
  Display: x11 server: X.Org v: 21.1.10 with: Xwayland v: 23.2.3 driver: X:
    loaded: amdgpu unloaded: fbdev,modesetting,radeon,vesa dri: radeonsi
    gpu: amdgpu resolution: 1: 3440x1440~50Hz 2: 1920x1080~60Hz
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 23.3.3 renderer: AMD
    Radeon Vega 10 Graphics (radeonsi raven LLVM 16.0.6 DRM 3.54
    6.6.9-269.current)
Network:
  Device-1: Realtek RTL8822BE 802.11a/b/g/n/ac WiFi adapter driver: rtw_8822be
Drives:
  Local Storage: total: 536.57 GiB used: 88.11 GiB (16.4%)
Info:
  Processes: 259 Uptime: 3h 15m Memory: total: 20 GiB note: est.
  available: 17.51 GiB used: 1.87 GiB (10.7%) Shell: Bash inxi: 3.3.31
```

### Other comments

I noticed other default shortcuts also don't work if they use the Super key. 
Ex: Super+Tab - Switch window for same application

**Comment by TraceyC77** [comment]
Ermo is testing this

**Comment by ermo** [comment]
Can confirm.

I suspect that this might actually be an upstream issue?

**Comment by EbonJaeger** [comment]
@ermo could you retest this, please? I just set the shortcut to lock the screen to `Super` + `L`, and to my surprise, it worked. I'm running the 4.20pre1 now, so I don't know if something changed upstream, or what.

![image](https://github.com/user-attachments/assets/7ed0d496-c2f6-4239-a749-cd349ab6c0da)

**Comment by ermo** [comment]
Application shortcuts (under the Keyboard thing in system settings) using the _Super_ key work fine in 4.18.x

But any shortcuts set in the Window Manager do not work for me in 4.18.

I tested with _Super+Tab_ in both multiple Firefox windows and multiple Thunar windows -- neither reacted to _Super+Tab_...

**Comment by EbonJaeger** [comment]
It looks to be [this issue](https://gitlab.xfce.org/xfce/xfwm4/-/issues/773), sadly. See the comment by Tamaranch.
