### ISSUE TITLE
Enable `nmtui` in gnome network manager

### ISSUE THREAD

**Issue by davidjharder** [getsolus/packages#1330]
Consider enabling Gnome Network Manager's TUI:

https://github.com/getsolus/packages/blob/main/packages/n/network-manager/package.yml#L78

Uses: Tiling WMs like sway and i3

**Comment by ReillyBrogan** [comment]
I'll do this when I update network-manager next.

**Comment by davidjharder** [comment]
Heads up, It's not as simple as setting that one line to `true`, I think because nmtui requires `libnewt` and we don't have an emul32 build of `libnewt`. That's as far as I got

**Comment by Justinzobel** [comment]
This is handy for emergency situations where the desktop hasn't loaded yet and won't load, and you need network access to fix it, e.g. eopkg history revert. Yes, nmcli works, but it requires knowledge of the syntax. Nmtui is much simpler to use, and requires zero knowledge on how to use it, as it's a TUI and very straight forward.

**Comment by ReillyBrogan** [comment]
80fe11aaa545f5464f034e39dfdcffab97cc73de

**Comment by Justinzobel** [comment]
Thanks!
