### ISSUE TITLE
trayer-srg system tray

### ISSUE THREAD

**Issue by yusi1** [getsolus/packages#1338]
### Homepage

https://github.com/sargon/trayer-srg

### Why should this be included in the repository?

There is not any standalone system tray software packaged yet.

### Are we allowed to redistribute it?

GPL 2.0

### What kind of user will use this package, and how many users do you think will use this package?

Mostly people who use a desktop environment / window manager that does not include a system tray. I do not think much people will use it since most desktop environments have system trays.

### Link to source archive file

https://github.com/sargon/trayer-srg/archive/refs/tags/trayer-1.1.8.tar.gz

**Comment by EbonJaeger** [comment]
This project doesn't appear to have been touched in years, and the last release was back in 2018. On top of that, it's using GTK *2*. I really don't think this should be included in the repository.

**Comment by yusi1** [comment]
> This project doesn't appear to have been touched in years, and the last release was back in 2018. On top of that, it's using GTK _2_. I really don't think this should be included in the repository.
> 
> If there are any more modern alternatives, those can be evaluated.

Yeah it is quite old, I understand, thank you. Issue can be closed.

**Comment by davidjharder** [comment]
Closed, project is stale
