### ISSUE TITLE
Mailspring broken (T10275)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#134]
<div dir="rtl"><b>Felipe&nbsp;Aldrete</b>&nbsp;(<em>&#35;raenk</em>),&nbsp;2022-06-01&nbsp;16:06:37&nbsp;UTC</div><br/>

Version mailspring-1.10.3-41-1-x86_64.eopkg won't open. Had to downgrade to previous version.

**Comment by Justinzobel** [comment]
Gets past the intro screen for me on current version. @ReillyBrogan can you confirm?

**Comment by ermo** [comment]
> Gets past the intro screen for me on current version. @ReillyBrogan can you confirm?

I can. Closing.
