### ISSUE TITLE
Update ROCm stack to 6.x

### ISSUE THREAD

**Issue by ermo** [getsolus/packages#1345]

**Comment by malfisya** [comment]
Is this technically done by this [PR](https://github.com/getsolus/packages/pull/2019) ?

**Comment by GZGavinZhao** [comment]
@malfisya Yeah, will close, after all packages in the stack is pushed.

**Comment by GZGavinZhao** [comment]
Every ROCm package is pushed, preliminary testing is good (Blender _finally_ doesn't crash), closing as complete.
