### ISSUE TITLE
Update grub to 2.12

### ISSUE THREAD

**Issue by ermo** [getsolus/packages#1348]
Requires careful testing with cbm.

**Comment by ermo** [comment]
@silkeh Is it realistic to get this working in time for 4.6?

**Comment by silkeh** [comment]
@ermo: yes, see #2439 :sweat_smile:

**Comment by ermo** [comment]
> @silkeh Is it realistic to get this working in time for 4.6?
> @ermo: yes, see #2439 😅

Does this imply that this will likely land soon after the next sync?

**Comment by ermo** [comment]
> Yes, although it probably needs testing by someone with a stack of BIOS notebooks before landing

@sheepman4267 ... Do you happen to know a special someone "with a stack of BIOS notebooks"?
