### ISSUE TITLE
tomlplusplus

### ISSUE THREAD

**Issue by yusi1** [getsolus/packages#1354]
### Homepage

https://github.com/marzer/tomlplusplus

### Why should this be included in the repository?

This is a library needed to package the Hyprland tiling window manager.

### Are we allowed to redistribute it?

MIT

### What kind of user will use this package, and how many users do you think will use this package?

People that need it as a dependency to be able to install Hyprland.

### Link to source archive file

https://github.com/marzer/tomlplusplus/archive/refs/tags/v3.4.0.tar.gz

**Comment by ReillyBrogan** [comment]
@yusi1 I take it that you're interested in packaging Hyprland on Solus? That will require that someone steps up to be the **dedicated** maintainer of it. It also requires that you be active on our Matrix, might I have your username there?

**Comment by ReillyBrogan** [comment]
Note that it is correct to create a packaging request for _hyprland_ as all dependencies of an accepted package are implicitly accepted and do not need individual requests.

**Comment by yusi1** [comment]
> @yusi1 I take it that you're interested in packaging Hyprland on Solus? That will require that someone steps up to be the **dedicated** maintainer of it. It also requires that you be active on our Matrix, might I have your username there?

Yes, my username on Matrix is Yusef Aslam.

**Comment by yusi1** [comment]
> Note that it is correct to create a packaging request for _hyprland_ as all dependencies of an accepted package are implicitly accepted and do not need individual requests.

Ohk I understand. Will do that

**Comment by yusi1** [comment]
I have created a package for Hyprland but I cannot test it as it needs this dependency, I will create a packaging request tomorrow.

**Comment by yusi1** [comment]
Closing because of Matrix discussion
