### ISSUE TITLE
[RFC] Needs New Maintainer: The wxwidgets version of WoeUSB is deprecated (T9505)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#136]
<div dir="rtl"><b>Jake</b>&nbsp;(<em>&#35;stalebrim</em>),&nbsp;2021-01-05&nbsp;22:09:25&nbsp;UTC</div><br/>

It seems the wxwidgets version of WoeUSB is deprecated, and the woeusb program itself is moved to https://github.com/WoeUSB/WoeUSB

A gui written in Python for it can be found here https://github.com/WoeUSB/WoeUSB-ng

**Comment by malfisya** [comment]
Isn't this already adressed with this [commit](https://github.com/getsolus/packages/commit/d70be3ed9f3e2fbe4c5e1787ce4cdff8d580e7bb) ?

**Comment by joebonrichie** [comment]
d70be3ed9f3e2fbe4c5e1787ce4cdff8d580e7bb
