### ISSUE TITLE
LbreakoutHD

### ISSUE THREAD

**Issue by malfisya** [getsolus/packages#1409]
### Homepage

https://lgames.sourceforge.io/LBreakoutHD/

### Why should this be included in the repository?

This is an HD remake of Lbreakout2 that is available in repo . Lbreakout2 is unmaintained and last release is 2015. Although this is overall an improvement compared to Lbreakout2, LbreakoutHD lacks network play. Still, it is probably better to replace Lbreakout2 with LbreakoutHD. I already have working recipe ready to submit. Cheers!

### Are we allowed to redistribute it?

GPL-3.0 license

### What kind of user will use this package, and how many users do you think will use this package?

Casual gamer.

### Link to source archive file

https://sourceforge.net/projects/lgames/files/lbreakouthd/lbreakouthd-1.1.6.tar.gz

**Comment by codewizard1975** [comment]
Checking it out now.  If all goes well, will be in unstable later today.

**Comment by malfisya** [comment]
Has this been approved? Why are you already making PR? I wrote that i already have recipe ready locally.

**Comment by codewizard1975** [comment]
Ive closed the PR.  You can submit a PR for this.

**Comment by yusi1** [comment]
This game is great I remember playing it on other distros.

**Comment by malfisya** [comment]
@codewizard1975 hey no problem. Before submitting a PR for package request, make sure it is already been approved. There will be tag "approved" with green color.  This one has not. Not every package request will be accepted. Cheers!
