### ISSUE TITLE
fwupd - can't download metadata

### ISSUE THREAD

**Issue by Justinzobel** [getsolus/packages#1413]
### Summary

```
sudo fwupdmgr get-updates
WARNING: This package has not been validated, it may not work properly.
Firmware metadata has not been updated for 30 days and may not be up to date.
Update now? (Requires internet connection) [y|N]: y
Updating lvfs
Downloading…             [  -                                    ]fish: Job 1, 'sudo fwupdmgr get-updates' terminated by signal SIGSEGV (Address boundary error)
```

### Steps to reproduce

See above

### Expected result

Metadata updated

### Actual result

Failure

### Environment

- [ ] Is system up to date?

### Repo

Unstable

### Desktop Environment

Plasma

### System details

```
System:
  Host: lenovo-laptop Kernel: 6.6.12-271.current arch: x86_64 bits: 64
    Desktop: KDE Plasma v: 5.92.0 Distro: Solus 4.5 resilience
Machine:
  Type: Laptop System: LENOVO product: 20Y1001SAU v: ThinkPad P14s Gen 1
    serial: <superuser required>
  Mobo: LENOVO model: 20Y1001SAU v: SDK0J40697 WIN
    serial: <superuser required> UEFI: LENOVO v: R1BET75W(1.44 )
    date: 06/13/2023
Battery:
  ID-1: BAT0 charge: 32.7 Wh (75.3%) condition: 43.4/50.5 Wh (85.9%)
    volts: 12.0 min: 11.6
CPU:
  Info: 8-core AMD Ryzen 7 PRO 4750U with Radeon Graphics [MT MCP]
    speed (MHz): avg: 1411 min/max: 1400/1700
Graphics:
  Device-1: AMD Renoir [Radeon RX Vega 6 ] driver: amdgpu v: kernel
  Device-2: Chicony Integrated Camera driver: uvcvideo type: USB
  Display: wayland server: X.org v: 1.21.1.11 with: Xwayland v: 23.2.4
    compositor: kwin_wayland driver: N/A resolution: 1536x864
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 23.3.3 renderer: AMD
    Radeon Graphics (radeonsi renoir LLVM 16.0.6 DRM 3.54 6.6.12-271.current)
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet
    driver: r8169
  Device-2: Intel Wi-Fi 6 AX200 driver: iwlwifi
  Device-3: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet
    driver: r8169
Drives:
  Local Storage: total: 476.94 GiB used: 123.73 GiB (25.9%)
Info:
  Processes: 405 Uptime: 1h 5m Memory: total: 28 GiB note: est.
  available: 29.11 GiB used: 7.13 GiB (24.5%) Shell: fish inxi: 3.3.31
```

### Other comments

Likely also crashing Discover now that it's in the repo.

When the fwupd backend is enabled, it crashes on startup.

**Comment by rav101** [comment]
ravi@RaviFW13
                                           -------------
                                           OS: Solus resilience 4.5 x86_64
                                           Host: Laptop 13 (AMD Ryzen 7040Series) (A7)
                                           Kernel: 6.6.11-270.current
                                           Uptime: 56 mins
                                           Packages: 859 (eopkg), 8 (flatpak)
                                           Shell: bash 5.1.16
                                           Display (eDP-1): 1803x1202 @ 60Hz
                                           DE: Gnome 45.3
                                           WM: Mutter (Wayland)
                                           WM Theme: Everforest-Dark-BL
                                           Theme: Everforest-Dark-BL [GTK2/3/4]
                                           Icons: Everforest-Dark [GTK2/3/4]
                                           Font: Noto Sans (9pt) [GTK2/3/4]
                                           Cursor: breeze (24px)
                                           Terminal: GNOME Terminal 3.48.0
                                           Terminal Font: Hack (10pt)
                                           CPU: AMD Ryzen 7 7840U w/ Radeon  780M Graphics (16) @ 5.13 GHz
                                           GPU: AMD Phoenix1
                                           Memory: 2.02 GiB / 58.56 GiB (3%)
                                           Swap: 0 B / 8.00 GiB (0%)
                                           Disk (/): 31.57 GiB / 3.42 TiB (1%) - ext4
                                           Local IP (wlp1s0): 
                                           Battery: 91% [Charging]
                                           Locale: en_GB.utf8

ravi@RaviFW13 ~ $ fwupdmgr get-updates
WARNING: This package has not been validated, it may not work properly.
Firmware metadata has not been updated for 30 days and may not be up to date.
Update now? (Requires internet connection) [y|N]: y
Updating lvfs
Downloading…             [     \                                 ]Segmentation fault (core dumped)
ravi@RaviFW13 ~ $`

This is the error I get on fwupd. Slightly different to yours.

**Comment by Justinzobel** [comment]
> Btw,
> 
> May not fix the issue but there is an update:
> 
> https://github.com/fwupd/fwupd/releases/tag/1.9.12
> 
> https://github.com/fwupd/fwupd/archive/refs/tags/1.9.12.tar.gz

It did solve the issue, thanks! Are you on unstable @rav101 if so please test and feel free to close this if it works for you too.

**Comment by rav101** [comment]
> > Btw,
> > May not fix the issue but there is an update:
> > https://github.com/fwupd/fwupd/releases/tag/1.9.12
> > https://github.com/fwupd/fwupd/archive/refs/tags/1.9.12.tar.gz
> 
> It did solve the issue, thanks! Are you on unstable @rav101 if so please test and feel free to close this if it works for you too.

Confirmed working on my end but this is your bug so I don't think I can close it on my end?
