### ISSUE TITLE
xpadneo

### ISSUE THREAD

**Issue by yusi1** [getsolus/packages#1419]
### Homepage

https://github.com/atar-axis/xpadneo

### Why should this be included in the repository?

I see that Solus already has the `xone` driver that supports Xbox One controllers in wired mode, the `xpadneo` driver supports Xbox One controllers in bluetooth and wired mode.

Other advantages are here: https://github.com/atar-axis/xpadneo#advantages-of-this-driver

### Are we allowed to redistribute it?

GPL-3.0

### What kind of user will use this package, and how many users do you think will use this package?

Mostly gamers that use Xbox One controllers in bluetooth mode.

### Link to source archive file

https://github.com/atar-axis/xpadneo/archive/refs/tags/v0.9.5.tar.gz

**Comment by infinitymdm** [comment]
Is this actually needed?

I need to go back and test again, but iirc Xbox one controllers already work via Bluetooth and wired connections without xpadneo installed. I'll try to test sometime this week and verify that's actually the case.

**Comment by HarveyDevel** [comment]
That was my understanding. I have a Xbox Series X/S Controller and it connects fine via bluetooth. So I assumed the Xbox One variant would too.

**Comment by yusi1** [comment]
> Is this actually needed?
> 
> I need to go back and test again, but iirc Xbox one controllers already work via Bluetooth and wired connections without xpadneo installed. I'll try to test sometime this week and verify that's actually the case.

Oh? Maybe something is wrong with my bluetooth or something, nvm then in that case

**Comment by yusi1** [comment]
Xbox controllers DO work over bluetooth without this driver, can also play games. My mistake.

**Comment by yusi1** [comment]
> That was my understanding. I have a Xbox Series X/S Controller and it connects fine via bluetooth. So I assumed the Xbox One variant would too.

I have the same controller but it wouldn't connect the first few times for some reason, it does now though

**Comment by HarveyDevel** [comment]
Sweet.

In that case I am going to close this request for now. If anyone has further justification for its inclusion feel free to reopen for consideration.
