### ISSUE TITLE
nextpnr-ice40 (T10426)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#143]
<div dir="rtl"><b>Marcus&nbsp;Mellor</b>&nbsp;(<em>&#35;infinitymdm</em>),&nbsp;2022-11-06&nbsp;04:13:10&nbsp;UTC</div><br/>

  - Name of the software: nextpnr (for ice40 architectures)
  - Project Homepage: https://github.com/YosysHQ/nextpnr 
  - Justification for inclusion: nextpnr is a vendor-neutral, timing-driven FPGA place-and-route tool. It can be set up for a variety of architectures. Here, I've set it up for iCE40 as that's the hardware I have on hand to test against. This is a pretty specific tool that honestly not a lot of folks will use. 
  - Open source: Yes, licensed under ISC
  - Link to release tarball: https://github.com/YosysHQ/nextpnr/archive/refs/tags/nextpnr-0.4.tar.gz

**Comment by silkeh** [comment]
@infinitymdm: accepted. You're still welcome to maintain it if you're up for it!

**Comment by infinitymdm** [comment]
Awesome! I'll take care of it this afternoon if I have some time.

**Comment by infinitymdm** [comment]
So nextpnr supports a variety of FPGA architectures. I see two options for handling this:

a) Splitting it into arch-specific subpackages (in which case the nextpnr package would only produce nextpnr-ice40 for now, but I'll set it up so other architectures can be added later)
b) Building a single package with support for all architectures. This would mean packaging Project Trellis, Project Oxide, and Project Apicula in addition to Project Icestorm.

Unless someone objects I'm going to work option a. If other FPGA architectures are added in the future, nextpnr can be configured to generate the appropriate subpackages for those architectures.
