### ISSUE TITLE
Update openjdk to 21

### ISSUE THREAD

**Issue by Bambus89** [getsolus/packages#1433]
### Name

openjdk

### Version

21

### Link to the release notes or announcement.

https://openjdk.org/projects/jdk/21/

### Reason for updating

JDK 21 will be a long-term support (LTS) release from most vendors.

**Comment by Bambus89** [comment]
Found out that I can install openjdk as portable directory. Packaging it would be great nonetheless

**Comment by ReillyBrogan** [comment]
> Found out that I can install openjdk as portable directory. Packaging it would be great nonetheless

Yeah, it's on our list. Maintaining JDK builds is a PITA so adding a new one isn't quite yet high on our priority list considering how easy it is to run a portable build.

**Comment by palto42** [comment]
I wanted to update the very outdated pdfsam package, but it depends on openjdk 21.
So I hope that this will be picked up soon.
