### ISSUE TITLE
unknown-horizons doesn't launch

### ISSUE THREAD

**Issue by malfisya** [getsolus/packages#1442]
### Summary

After installing `unknown-horizons` from repo, it failed to start.

### Steps to reproduce

Install `unknown-horizons` , then run it.

### Expected result

The game launches.

### Actual result

The game doesn't launch with this error : 
```
Traceback (most recent call last):
  File "/usr/bin/unknown-horizons", line 381, in <module>
    main()
  File "/usr/bin/unknown-horizons", line 122, in main
    ret = horizons.main.start(options)
  File "/usr/lib/python3.10/site-packages/horizons/main.py", line 149, in start
    generate_atlases()
  File "/usr/lib/python3.10/site-packages/horizons/util/atlasloading.py", line 58, in generate_atlases
    res_logo = logo.resize((116, 99), Image.ANTIALIAS)
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/horizons/engine/generate_atlases.py", line 430, in <module>
    AtlasGenerator.clear_everything()
  File "/usr/lib/python3.10/site-packages/horizons/engine/generate_atlases.py", line 406, in clear_everything
    os.unlink(path)
PermissionError: [Errno 13] Permission denied: 'content/atlas.sql'

```

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

GNOME

### System details

System:
  Host: dev-solus Kernel: 6.6.12-271.current arch: x86_64 bits: 64
    Desktop: GNOME v: 45.3 Distro: Solus 4.5 resilience
Machine:
  Type: Desktop Mobo: Wibtek model: H77-M v: V1.3 serial: <superuser required>
    BIOS: American Megatrends v: 4.6.5 date: 09/03/2012
CPU:
  Info: quad core Intel Core i5-3570K [MCP] speed (MHz): avg: 1879
    min/max: 1600/3800
Graphics:
  Device-1: AMD Lexa PRO [Radeon 540/540X/550/550X / RX 540X/550/550X]
    driver: amdgpu v: kernel
  Device-2: Jieli USB PHY 2.0 driver: snd-usb-audio,uvcvideo type: USB
  Display: wayland server: X.Org v: 23.2.4 with: Xwayland v: 23.2.4
    compositors: 1: gnome-shell 2: Mutter v: 45.3 driver: X: loaded: amdgpu
    unloaded: fbdev,modesetting,radeon,vesa dri: radeonsi gpu: amdgpu
    resolution: 1366x768~60Hz
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 23.3.4 renderer: AMD
    Radeon RX 550 / 550 Series (radeonsi polaris12 LLVM 16.0.6 DRM 3.54
    6.6.12-271.current)
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet
    driver: r8169
  Device-2: Realtek RTL8192EE PCIe Wireless Network Adapter
    driver: rtl8192ee
  Device-3: Realtek RTL8188EUS 802.11n Wireless Network Adapter
    driver: rtl8xxxu type: USB
Drives:
  Local Storage: total: 700.51 GiB used: 343.12 GiB (49.0%)
Info:
  Processes: 280 Uptime: 55m Memory: total: 16 GiB available: 15.6 GiB
  used: 4.08 GiB (26.2%) Shell: fish inxi: 3.3.31

### Other comments

I thougt it was because i updated `allegro` without rebuilding `fifechan` but I already tried that.  I rebuild `fifechan` then rebuild `fifengine`, then rebuild `unknown-horizons`, still the same error. Nuke it? :smile:

**Comment by EbonJaeger** [comment]
That file is shipped with the `unknown-horizons` package. Not sure why it wouldn't suddenly have permission to access it...

**Comment by HarveyDevel** [comment]
Appears to launch fine for me.

**Comment by malfisya** [comment]
Just tried in VM. Yeah it runs. Why did it not run here? weird.
