### ISSUE TITLE
Holotz Castle game (T10448)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#145]
<div dir="rtl"><b>Rafal&nbsp;Mintus</b>&nbsp;(<em>&#35;raf092</em>),&nbsp;2022-12-04&nbsp;08:16:31&nbsp;UTC</div><br/>

Hello, it's great platformer, that Solus repositories missing. 
Here's some packages for other distributions: https://pkgs.org/download/holotz-castle
And here's how it looks like: https://www.youtube.com/watch?v=GrxwUWnYXJU

**Comment by davidjharder** [comment]
Closing this. Can't find a good tarball link.
The typical source (see here for example https://github.com/rpmsphere/spec/blob/e2ab8db6c20a74f3944e96417c124804c2792bb9/h/holotz-castle.spe) now has a domain squatter page
