### ISSUE TITLE
picard: update to 2.11

### ISSUE THREAD

**Issue by luzpaz** [getsolus/packages#1451]
### Name

picard

### Version

2.11

### Link to the release notes or announcement.

https://github.com/metabrainz/picard/releases/tag/release-2.11

### Reason for updating

Changelog: https://raw.githubusercontent.com/metabrainz/picard/master/NEWS.md

**Comment by infinitymdm** [comment]
I'll try to get around to this sometime in the next week. Things have been a bit busy IRL for me
