### ISSUE TITLE
stunnel: update to 5.71

### ISSUE THREAD

**Issue by luzpaz** [getsolus/packages#1466]
### Name

stunnel

### Version

5.71

### Link to the release notes or announcement.

https://www.stunnel.org/NEWS.html

### Reason for updating

Backlog of bugfixes and features

<details> 

<summary> Changelog since 5.56</summary>

         

Version 5.71, 2023.09.19, urgency: MEDIUM

    Security bugfixes
        OpenSSL DLLs updated to version 3.1.3.
    Bugfixes
        Fixed the console output of tstunnel.exe.
    Features sponsored by SAE IT-systems
        OCSP stapling is requested and verified in the client mode.
        Using "verifyChain" automatically enables OCSP stapling in the client mode.
        OCSP stapling is always available in the server mode.
        An inconclusive OCSP verification breaks TLS negotiation. This can be disabled with "OCSPrequire = no".
        Added the "TIMEOUTocsp" option to control the maximum time allowed for connecting an OCSP responder.
    Features
        Added support for Red Hat OpenSSL 3.x patches.

Version 5.70, 2023.07.12, urgency: HIGH

    Security bugfixes
        OpenSSL DLLs updated to version 3.0.9.
        OpenSSL FIPS Provider updated to version 3.0.8.
    Bugfixes
        Fixed TLS socket EOF handling with OpenSSL 3.x. This bug caused major interoperability issues between stunnel built with OpenSSL 3.x and Microsoft's Schannel Security Support Provider (SSP).
        Fixed reading certificate chains from PKCS#12 files.
    Features
        Added configurable delay for the "retry" option.

Version 5.69, 2023.03.04, urgency: MEDIUM

    New features
        Improved logging performance with the "output" option.
        Improved file read performance on the WIN32 platform.
        DH and kDHEPSK ciphersuites removed from FIPS defaults.
        Set the LimitNOFILE ulimit in stunnel.service to allow for up to 10,000 concurrent clients.
    Bugfixes
        Fixed the "CApath" option on the WIN32 platform by applying https://github.com/openssl/openssl/pull/20312.
        Fixed stunnel.spec used for building rpm packages.
        Fixed tests on some OSes and architectures by merging Debian 07-tests-errmsg.patch (thx to Peter Pentchev).

Version 5.68, 2023.02.07, urgency: HIGH

    Security bugfixes
        OpenSSL DLLs updated to version 3.0.8.
    New features
        Added the new 'CAengine' service-level option to load a trusted CA certificate from an engine.
        Added requesting client certificates in server mode with 'CApath' besides 'CAfile'.
        Improved file read performance.
        Improved logging performance.
    Bugfixes
        Fixed EWOULDBLOCK errors in protocol negotiation.
        Fixed handling TLS errors in protocol negotiation.
        Prevented following fatal TLS alerts with TCP resets.
        Improved OpenSSL initialization on WIN32.
        Improved testing suite stability.

Version 5.67, 2022.11.01, urgency: HIGH

    Security bugfixes
        OpenSSL DLLs updated to version 3.0.7.
    New features
        Provided a logging callback to custom engines.
    Bugfixes
        Fixed "make cert" with OpenSSL older than 3.0.
        Fixed the code and the documentation to use conscious language for SNI servers (thx to Clemens Lang).

Version 5.66, 2022.09.11, urgency: MEDIUM

    New features
        OpenSSL 3.0 FIPS Provider support for Windows.
    Bugfixes
        Fixed building on machines without pkg-config.
        Added the missing "environ" declaration for BSD-based operating systems.
        Fixed the passphrase dialog with OpenSSL 3.0.

Version 5.65, 2022.07.17, urgency: HIGH

    Security bugfixes
        OpenSSL DLLs updated to version 3.0.5.
    Bugfixes
        Fixed handling globally enabled FIPS.
        Fixed openssl.cnf processing in WIN32 GUI.
        Fixed a number of compiler warnings.
        Fixed tests on older versions of OpenSSL.

Version 5.64, 2022.05.06, urgency: MEDIUM

    Security bugfixes
        OpenSSL DLLs updated to version 3.0.3.
    New features
        Updated the pkcs11 engine for Windows.
    Bugfixes
        Removed the SERVICE_INTERACTIVE_PROCESS flag in "stunnel -install".

Version 5.63, 2022.03.15, urgency: HIGH

    Security bugfixes
        OpenSSL DLLs updated to version 3.0.2.
    New features
        Updated stunnel.spec to support bash completion.
    Bugfixes
        Fixed a PRNG initialization crash (thx to Gleydson Soares).

Version 5.62, 2022.01.17, urgency: MEDIUM

    New features
        Added a bash completion script.
    Bugfixes
        Fixed a transfer() loop bug.

Version 5.61, 2021.12.22, urgency: LOW

    New features sponsored by the University of Maryland
        Added new "protocol = capwin" and "protocol = capwinctrl" configuration file options.
    New features for the Windows platform
        Added client mode allowing authenticated users to view logs, reconfigure and terminate running stunnel services.
        Added support for multiple GUI and service instances distinguised by the location of stunnel.conf.
        Improved log window scrolling.
        Added a new 'Pause auto-scroll' GUI checkbox.
        Double click on the icon tray replaced with single click.
        OpenSSL DLLs updated to version 3.0.1.
    Other new features
        Rewritten the testing framework in python (thx to Peter Pentchev for inspiration and initial framework).
        Added support for missing SSL_set_options() values.
        Updated stunnel.spec to support RHEL8.
    Bugfixes
        Fixed OpenSSL 3.0 build.
        Fixed reloading configuration with "systemctl reload stunnel.service".
        Fixed incorrect messages logged for OpenSSL errors.
        Fixed printing IPv6 socket option defaults on FreeBSD.

Version 5.60, 2021.08.16, urgency: LOW

    New features
        New 'sessionResume' service-level option to allow or disallow session resumption
        Added support for the new SSL_set_options() values.
        Download fresh ca-certs.pem for each new release.
    Bugfixes
        Fixed 'redirect' with 'protocol'. This combination is not supported by 'smtp', 'pop3' and 'imap' protocols.
        Enforced minimum WIN32 log window size.
        Fixed support for password-protected private keys with OpenSSL 3.0 (thx to Dmitry Belyavskiy).

Version 5.59, 2021.04.05, urgency: HIGH

    Security bugfixes
        OpenSSL DLLs updated to version 1.1.1k.
    New features
        Client-side "protocol = ldap" support (thx to Bart Dopheide and Seth Grover).
    Bugfixes
        The test suite fixed not to require external connectivity.
        Fixed paths in generated manuals (thx to Tatsuki Makino).
        Fixed configuration reload when compression is used.
        Fixed compilation with early releases of OpenSSL 1.1.1.

Version 5.58, 2021.02.20, urgency: HIGH

    Security bugfixes
        The "redirect" option was fixed to properly handle unauthenticated requests (thx to Martin Stein).
        Fixed a double free with OpenSSL older than 1.1.0 (thx to Petr Strukov).
        OpenSSL DLLs updated to version 1.1.1j.
    New features
        New 'protocolHeader' service-level option to insert custom 'connect' protocol negotiation headers. This feature can be used to impersonate other software (e.g. web browsers).
        'protocolHost' can also be used to control the client SMTP protocol negotiation HELO/EHLO value.
        Initial FIPS 3.0 support.
    Bugfixes
        X.509v3 extensions required by modern versions of OpenSSL are added to generated self-signed test certificates.
        Fixed a tiny memory leak in configuration file reload error handling (thx to Richard Könning).
        Merged Debian 05-typos.patch (thx to Peter Pentchev).
        Merged with minor changes Debian 06-hup-separate.patch (thx to Peter Pentchev).
        Merged Debian 07-imap-capabilities.patch (thx to Ansgar).
        Merged Debian 08-addrconfig-workaround.patch (thx to Peter Pentchev).
        Fixed tests on the WSL2 platform.
        NSIS installer updated to version 3.06 to fix a multiuser installation bug on some platforms, including 64-bit XP.
        Fixed engine initialization (thx to Petr Strukov).
        FIPS TLS feature is reported when a provider or container is available, and not when FIPS control API is available.

Version 5.57, 2020.10.11, urgency: HIGH

    Security bugfixes
        The "redirect" option was fixed to properly handle "verifyChain = yes" (thx to Rob Hoes).
        OpenSSL DLLs updated to version 1.1.1h.
    New features
        New securityLevel configuration file option.
        FIPS support for RHEL-based distributions.
        Support for modern PostgreSQL clients (thx to Bram Geron).
        Windows tooltip texts updated to mention "stunnel".
        TLS 1.3 configuration updated for better compatibility.
    Bugfixes
        Fixed a transfer() loop bug.
        Fixed memory leaks on configuration reloading errors.
        DH/ECDH initialization restored for client sections.
        Delay startup with systemd until network is online.
        bin\libssp-0.dll removed when uninstalling.
        A number of testing framework fixes and improvements.

</details>

**Comment by davidjharder** [comment]
Resolved by https://github.com/getsolus/packages/commit/9d2568c5b374e3344ba08a99566947807928ec3c
