### ISSUE TITLE
fastfetch (T10462)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#147]
<div dir="rtl"><b>Arnaud&nbsp;Mez</b>&nbsp;(<em>&#35;theunclemez</em>),&nbsp;2022-12-26&nbsp;12:03:29&nbsp;UTC</div><br/>

  - Name: fastfetch
  - Homepage: https://github.com/LinusDierheimer/fastfetch
  - Why should it be added to the repository? :  Actually, fastfetch is a much better alternative to both neofetch and screenfetch; Fastfetch is a neofetch-like tool for fetching system information and displaying them in a pretty way. It is written in pure c, with performance and customizability in mind.
  - This is opensource? :  Yes [MIT License]
  - Link to latest tarball: https://github.com/LinusDierheimer/fastfetch/releases/download/1.7.5/fastfetch-1.7.5-Linux.tar.gz
  - Who will use: Pretty sure users will be interrested into this neofetch-like tool for its performances and maybe drop other fetch tools.

Attached here, a screeshot of fastfetch output on my Solus laptop
{F10637904}

**Comment by algent-al** [comment]
In my opinion fastfetch is ore accurate  and faster than neofetch:
![fastfetch](https://github.com/getsolus/packages/assets/46356616/f99a7824-808f-45d7-b6b0-4396f5e4743f)

**Comment by rav101** [comment]
My duplicate was closed just just to add my vote to this.

I know we have neofetch I see three distinct benefits:

1) Active: Neofetch was last updated in August 2020 so isn't being maintained and could / should be considered abandoned. Fastfetch is actively being maintained with the latest release just 2 days ago.
2) Information: Fastfetch is providing additional information compared to Neofetch and new releases are continually improving this.
3) Speed: It's the least important on this list but Fastfetch is faster than Neofetch by some margin. On new hardware this doesn't make as much of a difference but on older hardware this could become more noticeable.

**Comment by algent-al** [comment]
@theunclemez ^
