### ISSUE TITLE
GNOME: prevent nautilus being replaced by non-file-browsers like decibels, vs code as default app to open directories

### ISSUE THREAD

**Issue by sebo505** [getsolus/packages#1470]
### Summary

If you install for instance decibels (flatpak) or vs code, these apps kind of hi-jack default file browser setting and get set as default app for opening directories.
You can check this with `xdg-mime query default inode/directory`

If you then for instance try to access a directory via GNOME Places(extension) in panel, decibels or vs code get launched instead of nautilus and then fail to open the directory, of course.
Same thing I have observed in past when additionally installing nemo on GNOME. In this case, nemo kind of was set as default file browser and was run instead of nautilus when accessing folders via GNOME Places or when opening downloads folder via Firefox, if I remember right.

This seems to be because we do not properly set nautilus as default file browser.

Since you can only set default apps for Web, E-Mail, Calendar, Music, Video, and Images in GNOME settings, the only thing you can do as end-user to get back to nautilus as default file browser is uninstalling decibels, respectively vs code, nemo.

Or you run `xdg-mime default org.gnome.Nautilus.desktop inode/directory`

I encountered this after installing decibels.
Decibels was suddenly set as default file browser.
After uninstalling decibels, nautilus was set as default file browser again.
If you then reinstalled decibels, decibels was set again and so forth.

However, after running `xdg-mime default org.gnome.Nautilus.desktop inode/directory` nautilus was set as default file browser with decibels installed. And remained default file browser even after uninstalling and reinstalling decibels.

I had opened an issue for this on the decibels [tracker](https://github.com/vixalien/decibels/issues/58#issuecomment-1913614929). Decibels devs claim this is not a decibels issue and referred me to this [entry](https://wiki.archlinux.org/title/File_manager_functionality#Directories_are_not_opened_in_the_file_manager) of Arch wiki.

Seems plausible to me, since this issue does not occur on Fedora.
We have further a similar [issue](https://discuss.getsol.us/d/9955-why-does-vs-code-open-when-i-click-places-xd/17) for vs code in our forum.
This is the vs code related [issue](https://github.com/getsolus/packages/issues/1031) on our tracker.
This okular [issue](https://github.com/getsolus/packages/issues/94) on our tracker might also be related.

Further interesting read on that matter is this [explanation](https://discourse.gnome.org/t/why-doesnt-default-applications-have-file-manager/14167) for this behaviour by the GNOME devs on GNOME discourse.

In conclusion, I believe we can do something about it, since other distros like Fedora, Ubuntu seem to do.

### Steps to reproduce

install decibels (flatpak)
access any folder via GNOME Places or run `xdg-mime query default inode/directory`

### Expected result

nautilus should remain standard file browser

### Actual result

nautilus does not remain standard file browser

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

GNOME

### System details

Hardware Information:

    Hardware-Modell: Hewlett-Packard HP EliteBook 6930p
    Speicher: 8,0 GiB
    Prozessor: Intel® Core™2 Duo T9550 × 2
    Grafik: AMD RV620
    Festplattenkapazität: 250,1 GB

Software Information:

    Firmware-Version: 68PCD Ver. F.16
    Name des Betriebssystems: Solus 4.5 Resilience
    Betriebssystem-Build: (null)
    Betriebssystem-Typ: 64-bit
    GNOME-Version: 45.3
    Fenstermanager: X11
    Kernel-Version: Linux 6.6.12-271.current

**Comment by sebo505** [comment]
Just want to share another recent [example](https://discuss.getsol.us/d/10390-caja-file-manager) from the forum where someone was wondering why caja opens when clicking on Trash in Budgie.

**Comment by ReillyBrogan** [comment]
Should be resolved with my recent overhaul of mimeapps.list handling, at least for KDE, GNOME, and Budgie. Someone will need to create a mimetypes file for the other DEs like XFCE and MATE, but that's outside of the scope of this.
