### ISSUE TITLE
Add link for searching issues on issue landing page

### ISSUE THREAD

**Issue by TraceyC77** [getsolus/packages#1485]
https://github.com/getsolus/packages/issues/new/choose

Add link to search the tracker, with verbiage to search for an issue before creating a new one.
As the issues list gets bigger, it's more unwieldy for the Solus Team to find if there are duplicate issues. This will help trim down the duplicates.

https://github.com/getsolus/packages/issues
https://github.com/getsolus/packages/issues?q=is%3Aissue+is%3Aopen+label%3ABug
https://github.com/getsolus/packages/labels/Package%20Request
https://github.com/getsolus/packages/labels/Package%20Update%20Request

**Comment by TraceyC77** [comment]
Related - https://github.com/getsolus/packages/pull/1486

**Comment by ermo** [comment]
@davidjharder Maybe you can think of a good solution here?

**Comment by malfisya** [comment]
Can we consider this solved now that every issue template have that checklist and link to related tags?

**Comment by TraceyC77** [comment]
> Can we consider this solved now that every issue template have that checklist and link to related tags?

Good point, I think we can.
