### ISSUE TITLE
darktable crashes with "Illegal Instruction (core dumped)" error

### ISSUE THREAD

**Issue by jaybratcher** [getsolus/packages#1497]
### Summary

Darktable 4.4.2 crashes on launch:

[jayb@machina ~]$ darktable
Illegal instruction (core dumped)

journalctl reports:
Feb 02 18:06:09 machina systemd[1]: Started Process Core Dump (PID 4619/UID 0).
Feb 02 18:06:09 machina systemd-coredump[4620]: [🡕] Process 4614 (darktable) of user 1000 dumped core.
                                                
                                                Stack trace of thread 4614:
                                                #0  0x00007ff25c091d01 n/a (libdarktable.so + 0x91d01)
                                                #1  0x00007ff25c091f5a n/a (libdarktable.so + 0x91f5a)
                                                #2  0x00007ff25c094ff3 dt_colorspaces_init (libdarktable.so + 0x94ff3)
                                                #3  0x00007ff25c0a4f75 dt_init (libdarktable.so + 0xa4f75)
                                                #4  0x000055bbe5cf5057 n/a (darktable + 0x1057)
                                                #5  0x00007ff25be2b28e n/a (libc.so.6 + 0x2828e)
                                                #6  0x00007ff25be2b349 __libc_start_main (libc.so.6 + 0x28349)
                                                #7  0x000055bbe5cf50a5 n/a (darktable + 0x10a5)
                                                
                                                Stack trace of thread 4615:
                                                #0  0x00007ff25bf2537d syscall (libc.so.6 + 0x12237d)
                                                #1  0x00007ff25bd1d49c g_cond_wait (libglib-2.0.so.0 + 0xb849c)
                                                #2  0x00007ff25bc876bc n/a (libglib-2.0.so.0 + 0x226bc)
                                                #3  0x00007ff25bcee637 n/a (libglib-2.0.so.0 + 0x89637)
                                                #4  0x00007ff25bcedfb8 n/a (libglib-2.0.so.0 + 0x88fb8)
                                                #5  0x00007ff25be9a10a n/a (libc.so.6 + 0x9710a)
                                                #6  0x00007ff25bf27a8c n/a (libc.so.6 + 0x124a8c)
                                                
                                                Stack trace of thread 4616:
                                                #0  0x00007ff25bf1a8bf __poll (libc.so.6 + 0x1178bf)
                                                #1  0x00007ff25bcbee57 n/a (libglib-2.0.so.0 + 0x59e57)
                                                #2  0x00007ff25bcbf571 g_main_context_iteration (libglib-2.0.so.0 + 0x5a571)
                                                #3  0x00007ff25bcbf5c2 n/a (libglib-2.0.so.0 + 0x5a5c2)
                                                #4  0x00007ff25bcedfb8 n/a (libglib-2.0.so.0 + 0x88fb8)
                                                #5  0x00007ff25be9a10a n/a (libc.so.6 + 0x9710a)
                                                #6  0x00007ff25bf27a8c n/a (libc.so.6 + 0x124a8c)
                                                
                                                Stack trace of thread 4617:
                                                #0  0x00007ff25bf2537d syscall (libc.so.6 + 0x12237d)
                                                #1  0x00007ff25bd1d67f g_cond_wait_until (libglib-2.0.so.0 + 0xb867f)
                                                #2  0x00007ff25bc87685 n/a (libglib-2.0.so.0 + 0x22685)
                                                #3  0x00007ff25bcee9cb n/a (libglib-2.0.so.0 + 0x899cb)
                                                #4  0x00007ff25bcedfb8 n/a (libglib-2.0.so.0 + 0x88fb8)
                                                #5  0x00007ff25be9a10a n/a (libc.so.6 + 0x9710a)
                                                #6  0x00007ff25bf27a8c n/a (libc.so.6 + 0x124a8c)
                                                
                                                Stack trace of thread 4618:
                                                #0  0x00007ff25bf1a8bf __poll (libc.so.6 + 0x1178bf)
                                                #1  0x00007ff25bcbee57 n/a (libglib-2.0.so.0 + 0x59e57)
                                                #2  0x00007ff25bcbf857 g_main_loop_run (libglib-2.0.so.0 + 0x5a857)
                                                #3  0x00007ff25b19e730 n/a (libgio-2.0.so.0 + 0x121730)
                                                #4  0x00007ff25bcedfb8 n/a (libglib-2.0.so.0 + 0x88fb8)
                                                #5  0x00007ff25be9a10a n/a (libc.so.6 + 0x9710a)
                                                #6  0x00007ff25bf27a8c n/a (libc.so.6 + 0x124a8c)
                                                ELF object binary architecture: AMD x86-64
Feb 02 18:06:09 machina systemd[1]: systemd-coredump@1-4619-0.service: Deactivated successfully.

### Steps to reproduce

Simply trying to launch darktable immediately fails

### Expected result

darktable should launch.

### Actual result

darktable crashes.

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Xfce

### System details

System:
  Host: machina Kernel: 6.6.12-271.current arch: x86_64 bits: 64 Desktop: Xfce
    v: 4.18.1 Distro: Solus 4.5 resilience
Machine:
  Type: Desktop Mobo: Gigabyte model: X570 GAMING X
    serial: <superuser required> UEFI: American Megatrends LLC. v: F38f
    date: 09/20/2023
CPU:
  Info: 6-core AMD Ryzen 5 5600X [MT MCP] speed (MHz): avg: 2807
    min/max: 2200/4650
Graphics:
  Device-1: AMD Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT]
    driver: amdgpu v: kernel
  Display: x11 server: X.Org v: 21.1.11 with: Xwayland v: 23.2.4 driver: X:
    loaded: amdgpu unloaded: fbdev,modesetting,radeon,vesa dri: radeonsi
    gpu: amdgpu resolution: 2560x1440~60Hz
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 23.3.4 renderer: AMD
    Radeon RX 6700 XT (radeonsi navi22 LLVM 16.0.6 DRM 3.54
    6.6.12-271.current)
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet
    driver: r8169
Drives:
  Local Storage: total: 6.7 TiB used: 1.03 TiB (15.4%)
Info:
  Processes: 320 Uptime: 2h 23m Memory: total: 32 GiB available: 31.27 GiB
  used: 2.8 GiB (8.9%) Shell: Bash inxi: 3.3.31

### Other comments

One user in Solus support forums confirmed the same issue.

**Comment by malfisya** [comment]
Can you please try [this](https://send.internxt.com/download/842e5a4f-3bd7-4fe0-921a-c7ae2036b958?code=81772606bf359952cac94b31a5a4a0df0d8a5cbdfc9a57111383b5c78d614677)? From the folder you downloaded into, run :
```sh
sudo eopkg it darktable-4.6.0-74-1-x86_64.eopkg
```
Then please report back here if it works. Cheers!

**Comment by jaybratcher** [comment]
Wow, that was quick!  I just pulled it down, but:

[jayb@machina Downloads]$ sudo eopkg it darktable-4.6.0-74-1-x86_64.eopkg 
System error. Program terminated.
External dependencies not satisfied: colord release >= 23
[jayb@machina Downloads]$ eopkg info colord
Installed package:
Name                : colord, version: 1.4.6, release: 22
Summary             : Color Daemon
Description         : colord is a system service that makes it easy to manage, install and generate color profiles to accurately color manage input and output devices.
Licenses            : GPL-2.0-or-later
Component           : desktop.core
Dependencies        : systemd liblcms2 glibc polkit sqlite3 libgusb libgudev glib2 
Distribution        : Solus, Dist. Release: 1
Architecture        : x86_64, Installed Size: 4.26 MB
Reverse Dependencies: libgtk-4 libgtk-3 colord-32bit libcolord-gtk darktable 

Package found in Solus repository:
Name                : colord, version: 1.4.6, release: 22
Summary             : Color Daemon
Description         : colord is a system service that makes it easy to manage, install and generate color profiles to accurately color manage input and output devices.
Licenses            : GPL-2.0-or-later
Component           : desktop.core
Dependencies        : systemd liblcms2 glibc polkit sqlite3 libgusb libgudev glib2 
Distribution        : Solus, Dist. Release: 1
Architecture        : x86_64, Installed Size: 4.26 MB, Package Size: 618.00 KB
Reverse Dependencies: gnome-control-center darktable simple-scan colord-dbginfo gnome-settings-daemon budgie-control-center libcolord-gtk colord-devel libgtk-3 gnome-color-manager gthumb magpie xiccd libgtk-4 colord-32bit mutter

I am on stable repo, FWIW...

**Comment by malfisya** [comment]
ah I built in against unstable. You could try switch to unstable, test this, do `eopkg hs` to rollback, then switch back to stable. Or the easiest, wait until this get merged to stable. Sorry!

**Comment by ReillyBrogan** [comment]
ORRRRRRRR you could just do an update on your system since I literally synced 5 minutes ago. Then you should be able to install the package without a dependency issue.

**Comment by jaybratcher** [comment]
Alright, y'all made me stop playing Genshin for this, lol!  Updating now...

Also - thank you for the attention to this - I did not see this as a critical issue, but your attention to this issue is to be commended.  It makes me feel like Solus was the right choice.  Thank you, both, and I will report back in a bit!

**Comment by jaybratcher** [comment]
So, mixed news here...

First up, the good - it now launches, and I can select images to import.

The bad news is that it says the raw format is unsupported, which I know to not be true based on past experience.  My camera is a Sony A7R (Sony ILCE-7R, which shows supported on the Darktable website).  That said, I cannot actually take images from lighttable to darkroom in the app.  Not sure what to make of it, but I will dig around for error messages and logs, and report back here.  It could well be a Darktable issue...

**Comment by jaybratcher** [comment]
Actually...  It just started working for some reason.  Still going to dig through the logs, but at this point, I would say this has resolved the initial problem.  Again, thank you both!

**Comment by jaybratcher** [comment]
Looking at journalctl, I see a lot of this:

Feb 02 21:45:55 machina colord[5331]: CdMain: failed to load mapping database: Can't open database: unable to open database file
Feb 02 21:45:55 machina systemd[1]: colord.service: Main process exited, code=exited, status=1/FAILURE
Feb 02 21:45:55 machina systemd[1]: colord.service: Failed with result 'exit-code'.
Feb 02 21:45:55 machina systemd[1]: Failed to start Manage, Install and Generate Color Profiles.
Feb 02 21:45:55 machina systemd[1]: Starting Manage, Install and Generate Color Profiles...
Feb 02 21:45:55 machina colord[5336]: CdMain: failed to load mapping database: Can't open database: unable to open database file
Feb 02 21:45:55 machina systemd[1]: colord.service: Main process exited, code=exited, status=1/FAILURE
Feb 02 21:45:55 machina systemd[1]: colord.service: Failed with result 'exit-code'.
Feb 02 21:45:55 machina systemd[1]: Failed to start Manage, Install and Generate Color Profiles.
Feb 02 21:45:56 machina systemd[1]: Starting Manage, Install and Generate Color Profiles...


And:

oot@machina /var/log # systemctl status colord
× colord.service - Manage, Install and Generate Color Profiles
     Loaded: loaded (/usr/lib/systemd/system/colord.service; static)
    Drop-In: /usr/lib64/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: failed (Result: exit-code) since Fri 2024-02-02 21:45:59 CST; 8min ago
    Process: 5352 ExecStart=/usr/lib64/colord/colord (code=exited, status=1/FAILURE)
   Main PID: 5352 (code=exited, status=1/FAILURE)
        CPU: 24ms

Feb 02 21:45:59 machina systemd[1]: Starting Manage, Install and Generate Color Profiles...
Feb 02 21:45:59 machina colord[5352]: CdMain: failed to load mapping database: Can't open database: unable to open database file
Feb 02 21:45:59 machina systemd[1]: colord.service: Main process exited, code=exited, status=1/FAILURE
Feb 02 21:45:59 machina systemd[1]: colord.service: Failed with result 'exit-code'.
Feb 02 21:45:59 machina systemd[1]: Failed to start Manage, Install and Generate Color Profiles.

Perhaps there is some configuration I need to look into, since the version changed...

**Comment by palto42** [comment]
Just tested `darktable-4.6.0-74-1-x86_64.eopkg` on latest stable and seems to work :)

**Comment by jaybratcher** [comment]
Darktable seems to be working for me as well.  The issue I see now is with colord, complaining about a missing database.  I researched a little, and it seems I may need to create it myself - however, the colormgr command is also failing.  Unfortunately, my day job beckons this morning, so it may be a bit before I can dig into my colord issue.

**Comment by malfisya** [comment]
It is still crashing when installed from repo, but works fine if built locally. Please reopen

**Comment by palto42** [comment]
I confirm that with the latest updates darktable crashes again. The temp fix provided above doesn't work anymore as it is missing some libraries which have been upgraded to a new version:
`error while loading shared libraries: libicui18n.so.73`

**Comment by malfisya** [comment]
Just updated on unstable, it is still crashing on startup. This is the (not looking useful) debug run:
```
$ darktable -d all 
darktable 4.6.0
Copyright (C) 2012-2023 Johannes Hanika and other contributors.

Compile options:
  Bit depth              -> 64 bit
  Debug                  -> DISABLED
  SSE2 optimizations     -> ENABLED
  OpenMP                 -> ENABLED
  OpenCL                 -> ENABLED
  Lua                    -> DISABLED
  Colord                 -> ENABLED
  gPhoto2                -> ENABLED
  GMIC                   -> ENABLED  - Compressed LUTs are supported
  GraphicsMagick         -> ENABLED
  ImageMagick            -> DISABLED
  libavif                -> ENABLED
  libheif                -> ENABLED
  libjxl                 -> ENABLED
  OpenJPEG               -> ENABLED
  OpenEXR                -> ENABLED
  WebP                   -> ENABLED

See https://www.darktable.org/resources/ for detailed documentation.
See https://github.com/darktable-org/darktable/issues/new/choose to report bugs.

     0.0002 application_directory: /usr/bin
     0.0002 darktable.datadir: /usr/share/darktable
     0.0002 darktable.plugindir: /usr/lib64/darktable
     0.0003 darktable.localedir: /usr/share/locale
     0.0003 darktable.configdir: /home/alfisya/.config/darktable
     0.0003 darktable.cachedir: /home/alfisya/.cache/darktable
     0.0003 darktable.sharedir: /usr/share
     0.0003 darktable.tmpdir: /tmp
     0.0003 [memory] at startup
     0.0004 [memory] max address space (vmpeak):      155324 kB
            [memory] cur address space (vmsize):      155324 kB
            [memory] max used memory   (vmhwm ):       27648 kB
            [memory] cur used memory   (vmrss ):       27648 kB
     0.0004 new_xdg_data_dirs: /usr/share:/home/alfisya/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop/
fish: Job 1, 'darktable -d all' terminated by signal SIGILL (Illegal instruction)

```
But locally built is always fine. Maybe there should be build flag added like `-j1` to ninja. Maybe pararel build is the problem. I am just throwing idea to the wall.

**Comment by malfisya** [comment]
I think @HarveyDevel already figured out the solution in this [commit](https://github.com/getsolus/packages/commit/3e12b4295851f3325da4d4f43ff1cd4e093d65eb). It works for me so far on unstable. Anybody inclined to test it please switch to unstable (join our matrix channel if you do so), or it will be available next sync. Cheers!

**Comment by HarveyDevel** [comment]
Fix seems good. Cherry-picked to stable. Re-open if issues persist.
