### ISSUE TITLE
Exaile music player (T8317)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#152]
<div dir="rtl"><b>Daltro&nbsp;Campanher</b>&nbsp;(<em>&#35;mrdaltro</em>),&nbsp;2019-09-06&nbsp;04:06:56&nbsp;UTC</div><br/>

  - Name: Exaile
  - Homepage: https://www.exaile.org/
  - The reason for this request: absolutely none of the available music players in Solus repository, currently, have all of these features: working lyrics fetching, song rating system, simple to use playlist mode (Guayadeque can't actually afford it). I can only think in Clementine running via Snap or Flatpak, but... Flatpak version is broken (can't play ALAC/M4A files) and both Flatpak or Snapd versions run with poor performance given that both run in sandbox, of course. Furthermore, when you run a music player under a sandbox, you get two gstreamer samplering your song, what means and results in... lower sound quality. If someone care about sound quality as I care, will obviously notice it. Strawberry? Good Clementine port, without rating system and smart playlist feature don't accept the same filters as the latest Clementine version or even Exaile. In addition, both Clementine and Strawberry are Qt aplications running in a GTK-based DE, so... Ya, Exaile would be a thing. For who?
  - Anyone who cares about good sound library management, music critics, audiophiles (who can't accept a gstreamer inside a gstreamer, if want good library management and lyrics and well-done UI and a stable software);
  - Yes. Exaile is open-source and source is available at https://github.com/exaile/exaile/releases/download/4.0.0/exaile-4.0.0.tar.gz.
  - As https://github.com/exaile/exaile/blob/master/COPYING attests, Exaile is free software under GNU GPLv2 license.

**Comment by davidjharder** [comment]
Old, closing
