### ISSUE TITLE
Spontaneous Log Offs (T9592)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#153]
<div dir="rtl"><b>Jacob</b>&nbsp;(<em>&#35;jm-brennan</em>),&nbsp;2021-02-22&nbsp;15:36:47&nbsp;UTC</div><br/>

I have for at least two weekly update cycles been experiencing an issue where I will suddenly just be logged off while using my laptop, which closes all my applications and is generally quite frustrating. I suppose I don't for sure know that it is a log off that is happening, the screen will suddenly go black for a couple seconds, and then I will be presented with the login screen (not the lock screen), and upon logging in all applications will have been closed which does mirror the exact behavior when I log off manually. I have fully updated my system every week when the new package updates get pushed. I would estimate that it has happened in total about 5 times in the last two or maybe three weeks, sorry that I am not able to remember exactly when it started happening. The last two times it happened was within 10 minutes of waking from suspend, not sure if that is significant, I can't see any other pattern in when it is happening based on what applications are running or anything. I can provide whatever logs may be helpful to see, but I am not familiar enough with Solus to know exactly what would be necessary to see. Also unclear if this is the correct place to post this and am happy to copy the discussion elsewhere.

System Information:
Dell G5 5590 Laptop
i7-9750H CPU
GeForce GTX 1650 Mobile / Max-Q using the latest NVIDIA drivers, including the 32 bit drivers
uname -a output: 5.10.15-172.current #1 SMP PREEMPT Fri Feb 12 16:35:57 UTC 2021 x86_64 GNU/Linux

**Comment by TraceyC77** [comment]
@palto42 is this still an issue? It has been a long time since there was an update to this task, and there have been many updates since this issue was opened, particularly the kernels.

**Comment by palto42** [comment]
@TraceyC77 thanks for following up on this issue, I can confirm that it disappeared at some point and no such issue anymore for quiet a while now. So from my point of view it can be closed.
