### ISSUE TITLE
Update mame to 0.262

### ISSUE THREAD

**Issue by malfisya** [getsolus/packages#1533]
### Name

mame

### Version

0.262

### Link to the release notes or announcement.

https://www.mamedev.org/?p=533

### Reason for updating

The one in repo is close to two years old and 14 version old. The update doesn't build with the current recipe. I put it here so anyone (or myself) remember to update it. Desktop file, app icons, and appstream metainfo can be taken from flathub mainfest. Cheers!

**Comment by malfisya** [comment]
@livingsilver94 If you  don't mind, can you please update this? Or at least make it build, right now it doesn't. My google-fu is just not enough to make it build. Cheers! (Found you in MAINTAINERS.md)

**Comment by livingsilver94** [comment]
Please use this patch after the new lua version landed: https://github.com/mamedev/mame/commit/e7969d76da6c6d17457f614f3e46abe17f3281e1.patch

I tested it locally and it works.

**Comment by livingsilver94** [comment]
Also, gold doesn't support the `-z` flag we're now passing among our standard LDFLAGS. As Joey stated, remove that flag with `export LDFLAGS="${LDFLAGS/-Wl,-z,pack-relative-relocs/}"`

**Comment by TraceyC77** [comment]
This is being updated as part of getsolus/packages/pull/1783
