### ISSUE TITLE
Laptop Frozen after Suspend (T8699)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#154]
<div dir="rtl"><b>Joe</b>&nbsp;(<em>&#35;JoeOnSolus4.1</em>),&nbsp;2020-02-08&nbsp;00:48:20&nbsp;UTC</div><br/>

Yesterday I installed Solus 4.1, and its up to date. Today I clicked on suspend and after a few minutes when I hit the power button the screen background comes on but no functionality on 
the keyboard or mouse. The system is completely frozen, I can't even open terminals with Ctrl + Alt + F... . I have tried this twice and same results. I have to do a hard-reset to start system again. I'm using a Hp Elitebook 6930p with 4Gb Ram.

**Comment by TraceyC77** [comment]
Closing since original reporter said the issue had been resolved many kernels ago in 2020
