### ISSUE TITLE
pcsx2 doesn't launch

### ISSUE THREAD

**Issue by malfisya** [getsolus/packages#1542]
### Summary

Right now pcsx2 doesn't launch and spits out error when run from terminal.

### Steps to reproduce

Install `pcsx2` and run it

### Expected result

It launches properly

### Actual result

it doesn't launch with this error :
`/usr/share/pcsx2/bin/pcsx2-qt: symbol lookup error: /usr/share/pcsx2/bin/pcsx2-qt: undefined symbol: _ZN20QFutureInterfaceBase15setContinuationESt8functionIFvRKS_EEP27QFutureInterfaceBasePrivate, version Qt_6_PRIVATE_API`

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

GNOME

### System details

System:
  Host: dev-solus Kernel: 6.6.15-272.current arch: x86_64 bits: 64
    Desktop: GNOME v: 45.3 Distro: Solus 4.5 resilience
Machine:
  Type: Desktop Mobo: Wibtek model: H77-M v: V1.3 serial: <superuser required>
    BIOS: American Megatrends v: 4.6.5 date: 09/03/2012
CPU:
  Info: quad core Intel Core i5-3570K [MCP] speed (MHz): avg: 1597
    min/max: 1600/3800
Graphics:
  Device-1: AMD Lexa PRO [Radeon 540/540X/550/550X / RX 540X/550/550X]
    driver: amdgpu v: kernel
  Device-2: Jieli USB PHY 2.0 driver: snd-usb-audio,uvcvideo type: USB
  Display: wayland server: X.Org v: 23.2.4 with: Xwayland v: 23.2.4
    compositors: 1: gnome-shell 2: Mutter v: 45.3 driver: X: loaded: amdgpu
    unloaded: fbdev,modesetting,radeon,vesa dri: radeonsi gpu: amdgpu
    resolution: 1366x768~60Hz
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 23.3.5 renderer: AMD
    Radeon RX 550 / 550 Series (radeonsi polaris12 LLVM 16.0.6 DRM 3.54
    6.6.15-272.current)
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet
    driver: r8169
  Device-2: Realtek RTL8192EE PCIe Wireless Network Adapter
    driver: rtl8192ee
  Device-3: Realtek RTL8188EUS 802.11n Wireless Network Adapter
    driver: rtl8xxxu type: USB
Drives:
  Local Storage: total: 700.51 GiB used: 385.23 GiB (55.0%)
Info:
  Processes: 281 Uptime: 2h 32m Memory: total: 16 GiB available: 15.6 GiB
  used: 4.27 GiB (27.4%) Shell: fish inxi: 3.3.31

### Other comments

I already rebuild it in this [PR](https://github.com/getsolus/packages/pull/1541), now it launches the first time setup. Following the steps except I don't have a bios file, until the end I click "finish" and it just segfault. Every time i open it again, it starts on first time setup again. [`.eopkg` file](https://send.internxt.com/download/c46fcff2-dd60-4914-834b-7d810a32b429?code=6ee8603cff90173cd557120c4ac090834e55b846e7ee428d7737aa4f02a732f9) for anyone want to test my build.

**Comment by ReillyBrogan** [comment]
This means it uses private qt headers and will need to be rebuilt on every qt6 update. You can submit a pr rebuilding it along with your changes but please also add a commit adding it to the rebuilds list in qt6-base
