### ISSUE TITLE
modem-manager: update to 1.22.0

### ISSUE THREAD

**Issue by luzpaz** [getsolus/packages#1558]
### Name

modem-manager

### Version

1.22.0

### Link to the release notes or announcement.

https://lists.freedesktop.org/archives/modemmanager-devel/2023-October/009783.html

### Reason for updating

[NEWS](https://gitlab.freedesktop.org/mobile-broadband/ModemManager/-/blob/main/NEWS) file for details.

**Comment by androidnisse** [comment]
@luzpaz I have built this update now, can you test it?

**Comment by luzpaz** [comment]
Can't test atm
