### ISSUE TITLE
Waypipe

### ISSUE THREAD

**Issue by joebonrichie** [getsolus/packages#1560]
### Homepage

https://gitlab.freedesktop.org/mstoeckl/waypipe

### Why should this be included in the repository?

Application forwarding with wayland e.g. like ssh -X

### Are we allowed to redistribute it?

MIT, Expat

### What kind of user will use this package, and how many users do you think will use this package?

ssh users

### Link to source archive file

https://gitlab.freedesktop.org/mstoeckl/waypipe/-/archive/v0.8.6/waypipe-v0.8.6.tar.gz

**Comment by androidnisse** [comment]
I have built this now @davidjharder but I can't test this as I'm not using Wayland. Are you able to test this?

**Comment by davidjharder** [comment]
@androidnisse Sure, I can try this
