### ISSUE TITLE
Heroic Games Launcher

### ISSUE THREAD

**Issue by SlowNicoFish** [getsolus/packages#1567]
### Homepage

https://heroicgameslauncher.com/

### Why should this be included in the repository?

Heroic is a great alternative to Epic games

### Are we allowed to redistribute it?

GPL-3.0-only

### What kind of user will use this package, and how many users do you think will use this package?

People who game on Solus

### Link to source archive file

https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/download/v2.12.0/heroic-2.12.0.tar.xz

**Comment by HarveyDevel** [comment]
It is already in the repository as `heroic-games-launcher`
