### ISSUE TITLE
openra: update to 20231010

### ISSUE THREAD

**Issue by luzpaz** [getsolus/packages#1599]
### Name

openra

### Version

20231010

### Link to the release notes or announcement.

https://github.com/OpenRA/OpenRA/releases/tag/release-20231010

### Reason for updating

https://github.com/OpenRA/OpenRA/wiki/Changelog  
http://www.openra.net/news/

**Comment by davidjharder** [comment]
Hey @nelsontkq any interest in tackling this? It's a mono/dotnet project. A simple update fails for reasons I don't understand.

**Comment by nelsontkq** [comment]
> Hey @nelsontkq any interest in tackling this? It's a mono/dotnet project. A simple update fails for reasons I don't understand.

Sure thing
