### ISSUE TITLE
Steam Big Picture Mode does not startup on correct (primary) monitor  (T1354)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#16]
<div dir="rtl"><b>Nathan&nbsp;Caldwell</b>&nbsp;(<em>&#35;saintdev</em>),&nbsp;2016-10-29&nbsp;03:13:14&nbsp;UTC</div><br/>

I have two monitors and when I start Steam Big Picture Mode, it starts on the secondary monitor. Games (tested with Rocket League) startup on the correct, primary, monitor. If I start Big Picture Mode windowed, it defaults to starting on the primary monitor. I'm using the binary nvidia driver. With other distros (Arch and Gentoo) Big Picture Mode starts on the primary monitor.

**Comment by davidjharder** [comment]
Old as dirt. Closing
