### ISSUE TITLE
systemd: Don't hide fsck messages during silent boot

### ISSUE THREAD

**Issue by joebonrichie** [getsolus/packages#1602]
### Summary

fsck can take a while, to the user it can appear the system is hang during boot.

### Steps to reproduce

boot whilst an fsck is scheduled

### Expected result

fsck progress bar to appear

### Actual result

nothing appears

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

GNOME

### System details

Battery:
  ID-1: BAT0 charge: 13.2 Wh (29.1%) condition: 45.3/51.2 Wh (88.4%)
    volts: 7.5 min: 7.7
ninya@yoga-c13 ~ $ inxi -b
System:
  Host: yoga-c13 Kernel: 6.6.16-274.current arch: x86_64 bits: 64
    Desktop: KDE Plasma v: 5.27.10 Distro: Solus 4.5 resilience
Machine:
  Type: Laptop System: Google product: Morphius v: rev6
    serial: <superuser required>
  Mobo: Google model: Morphius v: rev6 serial: <superuser required>
    UEFI: coreboot v: MrChromebox-4.22.0-6-g135ae7306d6 date: 01/08/2024
Battery:
  ID-1: BAT0 charge: 13.2 Wh (29.1%) condition: 45.3/51.2 Wh (88.4%)
    volts: 7.5 min: 7.7
CPU:
  Info: quad core AMD Ryzen 5 3500C with Radeon Vega Mobile Gfx [MT MCP]
    speed (MHz): avg: 1399 min/max: 1400/2100
Graphics:
  Device-1: AMD Picasso/Raven 2 [Radeon Vega Series / Radeon Mobile Series]
    driver: amdgpu v: kernel
  Device-2: Syntek Integrated Camera driver: uvcvideo type: USB
  Display: wayland server: X.org v: 1.21.1.11 with: Xwayland v: 23.2.4
    compositor: kwin_wayland driver: X:
    loaded: amdgpu,fbdev,modesetting,radeon,vesa gpu: amdgpu
    resolution: 1536x864
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 23.3.5 renderer: AMD
    Radeon Vega 8 Graphics (radeonsi raven LLVM 16.0.6 DRM 3.54
    6.6.16-274.current)
Network:
  Device-1: Realtek RTL8822CE 802.11ac PCIe Wireless Network Adapter
    driver: rtw_8822ce
Drives:
  Local Storage: total: 119.24 GiB used: 31.27 GiB (26.2%)
Info:
  Processes: 289 Uptime: 1d 1h 10m Memory: total: 8 GiB available: 7.69 GiB
  used: 5.39 GiB (70.1%) Shell: Bash inxi: 3.3.31

**Comment by ReillyBrogan** [comment]
I have absolutely no idea how to enable this.

**Comment by joebonrichie** [comment]
i think systemd.show_status = 0 hides it

**Comment by joebonrichie** [comment]
https://github.com/systemd/systemd/blob/v255/src/fsck/fsck.c#L115
