### ISSUE TITLE
iso won't boot with intel 12th gen laptop (T10396)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#162]
<div dir="rtl"><b>Eric&nbsp;Hecker</b>&nbsp;(<em>&#35;E_Hex</em>),&nbsp;2022-09-21&nbsp;21:07:06&nbsp;UTC</div><br/>

solus budgie 4.3 iso won't boot on framework intel 12 gen laptop I get error:

tpm tpm0: [Firmware Bug]: TPM interrupt not working, polling instead
thunderbolt 0-0: reading DROM failed
thunderbolt 0-0: reading DROM failed

I also tried plasma I got more errors still didn't work
from what i found online its most likely due to the age of the live boot file causing an incompatibility with intel 12th gen

**Comment by davidjharder** [comment]
Gonna call this fixed, due to new ISO
