### ISSUE TITLE
Update Request: Power Profiles Daemon

### ISSUE THREAD

**Issue by rav101** [getsolus/packages#1625]
### Name

Power Profiles Daemon

### Version

0.20

### Link to the release notes or announcement.

https://gitlab.freedesktop.org/upower/power-profiles-daemon/-/releases

### Reason for updating

This release adds support for:

Multiple power-profiles-daemon drivers to load simultaneously.  This notably
allows both CPU based control with amd-pstate or intel-pstate as well as
ACPI platform profile based control.

amdgpu panel power savings which uses dedicated hardware in systems with
integrated Radeon graphics to decrease panel power consumption when the
system is on battery.

This release also enables the test suite by default, so distribution vendors
should update packaging accordingly.

**Comment by Staudey** [comment]
So you're really into test suites, huh? 😉
