### ISSUE TITLE
Libreoffice cannot find java

### ISSUE THREAD

**Issue by elusian** [getsolus/packages#1626]
### Summary

Libreoffice needs a working JVM for a few of its features. Currently, in Solus, it is unable to find it, despite having both openjdk 11 and 17 installed.

In the options, there is also a way to point it to a specific openjdk installation, but even when pointed to `/usr/lib64/openjdk-{11,17}` (I also tried the bin folder inside) it seems to be unable to recognize it.
Setting `$JAVA_HOME` or adding `$JAVA_HOME/bin` to the `$PATH` has no effect.

Reading the libreoffice sources or using `strace` I think the issue lies in the `libjvm.so` search paths:
1. libreoffice searches for libjvm.so at
    - `$SELECTED_FOLDER/lib/amd64/client/libjvm.so`
    - `$SELECTED_FOLDER/lib/amd64/server/libjvm.so`
    - `$SELECTED_FOLDER/lib/amd64/classic/libjvm.so`
    - `$SELECTED_FOLDER/lib/amd64/jrockit/libjvm.so`
    - `$SELECTED_FOLDER/lib/server/libjvm.so`
the latter being the correct path in distros like Ubuntu or Arch
2. openjdk in Solus contains `$JAVA_HOME/lib/client/libjvm.so`, which is a different variant (feature set?).

Since I don't think libreoffice actually needs the server variant (after all, among the searched paths there is a client variant), I see a few possible solutions:
- ask libreoffice to add the correct search path
- patch libreoffice in Solus to add the correct search path
- build the openjdk server variant as other distros do, likely increasing the build time
- lie and link the client variant to the server path

### Steps to reproduce

1. install libreoffice and openjdk (either version)
2. in libreoffice, open the Options (from the Tool menu) and go to Advanced. No JRE will be found
3. Click the button to manually add a runtime, select the openjdk folder

### Expected result

Ideally the JVM is found automatically, but at least adding it manually should work

### Actual result

The folder you selected does not contain a Java Runtime Environment

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Budgie

### System details

```
System:
  Host: elusian Kernel: 6.6.16-273.current arch: x86_64 bits: 64
    Desktop: Budgie v: 10.9.1 Distro: Solus 4.5 resilience
Machine:
  Type: Portable System: Dell product: Inspiron 7559 v: 1.1.8
    serial: <superuser required>
  Mobo: Dell model: 0H0CC0 v: A00 serial: <superuser required> UEFI: Dell
    v: 1.1.8 date: 04/17/2016
Battery:
  ID-1: BAT0 charge: 65.5 Wh (100.0%) condition: 65.5/74.0 Wh (88.5%)
CPU:
  Info: quad core Intel Core i7-6700HQ [MT MCP] speed (MHz): avg: 900
    min/max: 800/3500
Graphics:
  Device-1: Intel HD Graphics 530 driver: i915 v: kernel
  Device-2: NVIDIA GM107M [GeForce GTX 960M] driver: nvidia v: 535.154.05
  Device-3: Sunplus Innovation Integrated_Webcam_HD driver: uvcvideo
    type: USB
  Display: x11 server: X.Org v: 21.1.11 with: Xwayland v: 23.2.4 driver: X:
    loaded: modesetting,nvidia dri: iris gpu: i915 resolution: 1920x1080
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: nvidia mesa v: 535.154.05
    renderer: NVIDIA GeForce GTX 960M/PCIe/SSE2
Network:
  Device-1: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet
    driver: r8169
  Device-2: Intel Wireless 3165 driver: iwlwifi
Drives:
  Local Storage: total: 1.14 TiB used: 765.74 GiB (65.8%)
Info:
  Processes: 347 Uptime: 2h 5m Memory: total: 16 GiB available: 15.5 GiB
  used: 7.35 GiB (47.4%) Shell: fish inxi: 3.3.31
  ```

### Other comments

I am not sure whether this should be considered a Solus issue or a Libreoffice issue, I am mostly asking for feedback.

**Comment by elusian** [comment]
Thank you! I can test this over the weekend if I can get a link to the unstable package

**Comment by ReillyBrogan** [comment]
`https://cdn.getsol.us/repo/unstable/libr/libreoffice/` - Filter by `24.2.0.3-175`

**Comment by ReillyBrogan** [comment]
Note that it's not finished building yet, should be up within 30-60

**Comment by elusian** [comment]
I need to apply the stable updates first anyway, and I'm not doing that before tomorrow

**Comment by elusian** [comment]
I can confirm that java is now detected (both versions). Thanks!
