### ISSUE TITLE
Steam icon(s) doesn't appear on "Icon Task List".

### ISSUE THREAD

**Issue by SethStormR** [getsolus/packages#1627]
### Summary

Greetings,

Steam icon doesn't appear on the Icon Task List in the panel when launched in Budgie.

### Steps to reproduce

1. Add "Icon Task List" addon to a panel in Budgie Desktop Settings.
2. Start Steam up.

### Expected result

To see Steam icon in the Icon Task List.

### Actual result

It doesn't show.

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Budgie

### System details

System:
  Host: universe Kernel: 6.6.16-273.current arch: x86_64 bits: 64
    Desktop: Budgie v: 10.9.1 Distro: Solus 4.5 resilience
Machine:
  Type: Desktop Mobo: ASUSTeK model: PRIME X370-A v: Rev X.0x
    serial: <superuser required> UEFI: American Megatrends v: 5222
    date: 10/15/2019
CPU:
  Info: 8-core AMD Ryzen 7 1700X [MT MCP] speed (MHz): avg: 2553
    min/max: 2200/3400
Graphics:
  Device-1: NVIDIA GP104 [GeForce GTX 1070] driver: nvidia v: 535.154.05
  Display: x11 server: X.Org v: 21.1.11 with: Xwayland v: 23.2.4 driver:
    gpu: nvidia,nvidia-nvswitch resolution: 1920x1080~60Hz
  API: OpenGL v: 4.6.0 vendor: nvidia v: 535.154.05 renderer: NVIDIA
    GeForce GTX 1070/PCIe/SSE2
Network:
  Device-1: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet
    driver: r8169
  Device-2: Intel Wi-Fi 6 AX200 driver: iwlwifi
Drives:
  Local Storage: total: 938.72 GiB used: 169.52 GiB (18.1%)
Info:
  Processes: 405 Uptime: 1h 47m Memory: total: 32 GiB available: 31.29 GiB
  used: 3.33 GiB (10.6%) Shell: Zsh inxi: 3.3.31

**Comment by infinitymdm** [comment]
Steam shows up in the icon task list for me.

- Where did you install Steam from (Flatpak or eopkg)?
- Are you using the Unstable repo? (post the output of `eopkg lr` if you're unsure)

**Comment by SethStormR** [comment]
I installed it from eopkg.

```
eopkg lr                                                                
Solus [active]
   https://cdn.getsol.us/repo/shannon/eopkg-index.xml.xz
```

I don't know if it's makes a different. I have the panel in the left side of the screen.

![Snapshot_2024-02-16_06-26-07](https://github.com/getsolus/packages/assets/60283532/a7fbe476-0416-4c16-8c7d-82676de4644f)

**Comment by Staudey** [comment]
What's that gamepad icon on the bottom panel represent? Is that not Steam perhaps? Looks like it's active too

**Comment by SethStormR** [comment]
It's Plank in the bottom. Steam Appears there. But not on the panel to the left with Icon Task List.

**Comment by SethStormR** [comment]
I have now tried removing Plank to see if it makes any different, no cigar. Still no Steam icon(s).

![Snapshot_2024-02-16_08-53-56](https://github.com/getsolus/packages/assets/60283532/73d93018-2c62-499b-b84d-a62176b2a5e0)

**Comment by Staudey** [comment]
Oh, I should've realized that was not a native Budgie panel/dock (in my defence it was 3 AM or so ^^)

Unfortunately I can't reproduce this issue at all on my machine (no matter where I put the panel).

Do you perhaps have the option "Only show favorited" active in "Budgie Desktop Settings > Panel > Icon Tasklist"?

**Comment by EbonJaeger** [comment]
Is Steam installed from the Solus package, or from flatpak?

**Comment by infinitymdm** [comment]
> Is Steam installed from the Solus package, or from flatpak?

From his earlier reply:

> I installed it from eopkg.

**Comment by SethStormR** [comment]
The only thing I have out of the ordinary is that I have compiled Ubuntu Budgies'/elementary OS' App Menu, but that shouldn't have any impact on the native panels?

**Comment by EbonJaeger** [comment]
@infinitymdm ah, I missed that. Thanks. For those it does show up for, same question: flatpak or eopkg?

**Comment by infinitymdm** [comment]
> For those it does show up for, same question: flatpak or eopkg?

I use eopkg steam

**Comment by Staudey** [comment]
Same, `.eopkg` Steam shows up fine for me. Tried a few things like repositioning the panel, switching applet options on and off, but nothing causes the icon to disappear.

**Comment by SethStormR** [comment]
If I'm the only one with this bug. The conclusion must be the menu I compiled that somwhow affect the panel and Steam. I can't see otherwise.

**Comment by infinitymdm** [comment]
> If I'm the only one with this bug. The conclusion must be the menu I compiled that somwhow affect the panel and Steam. I can't see otherwise.

That's a testable item. I may try building that in a VM and see if I can replicate the bug.

**Comment by infinitymdm** [comment]
Steam has a panel icon for me when using UbuntuBudgie/applications-menu@c93e8fa instead of the default Budgie menu. This is in a fully updated Solus 4.5 VM.

![Snapshot_2024-02-18_16-11-28](https://github.com/getsolus/packages/assets/35574527/f5765b54-f696-4343-8080-58a6e6797824)

**Comment by SethStormR** [comment]
I guess we can close this case, as the bug on my end is not producable and I have no idea what caused it.

**Comment by infinitymdm** [comment]
I probably should have thought of this earlier, but have you checked for broken packages? There's a helpful one-liner in the [troubleshooting docs](https://help.getsol.us/docs/user/troubleshooting/) that might help you out.

**Comment by SethStormR** [comment]
I'll look into it.

Meanwhile I made a clean install and the same happen again.
1) updated the system
2) install chrome via software center
3) install Nvidia driver
4) Installed Steam

Still Steam doesn't show.

![Snapshot_2024-02-23_15-01-10](https://github.com/getsolus/packages/assets/60283532/47eb6b7c-ac5f-4555-bb18-dcdd101a9cd3)

**Comment by infinitymdm** [comment]
> Meanwhile I made a clean install and the same happen again.
>     1. updated the system
>     2. install chrome via software center
>     3. install Nvidia driver
>     4. Installed Steam
> Still Steam doesn't show.

I'll try testing this in a fresh VM; I didn't install Chrome last time. I can't help test with Nvidia drivers though, as I don't have any Nvidia hardware.

A few follow-up questions:
- In this fresh install, do you have UbuntuBudgie/applications-menu installed? If so, did you install that using [these instructions](https://discuss.getsol.us/d/10312-howto-install-slingshotapp-menu-in-solus), or did you use some other method?
- How did you install the Nvidia driver? Using the Hardware Drivers app, or something else?
- Could you paste the output of `sudo eopkg check | grep Broken`?
- It's a stretch, but if you sign out of Steam, does the sign-in window show an icon in the icon tasklist?
- What icon theme do you have set in Budgie Desktop Settings?
- Could you post a screenshot of your icon tasklist settings? (i.e. [this screen](https://imgur.com/a/NMuSb0z). I want to make sure I test with the same configuration as you have)

**Comment by SethStormR** [comment]
* In the fresh install I didn't install application-menu
* I used Hardware Driver App
* It came up empty

![Snapshot_2024-02-24_00-22-57](https://github.com/getsolus/packages/assets/60283532/7d065744-b901-48a8-9514-38b2874b10b6)

* As you mention it, no icons showed up in the sign-in window or any other Steam related icons.
* The default - Papirus, then I tried one of my own theme as well.

![Snapshot_2024-02-24_00-21-17](https://github.com/getsolus/packages/assets/60283532/17a1c8d2-8092-4a74-8e90-9e9513c613d9)

**Comment by infinitymdm** [comment]
Well, unfortunately all of that looks fine. That's about all the troubleshooting I can think of, but if I have any other ideas I'll post them here. I think you need help from people more knowledgeable than myself.

**Comment by SethStormR** [comment]
Today (or should a say night) I tried again and suddenly it's now Steam is shown in the Icon view list. It may be that a Steam update or something.

**Comment by malfisya** [comment]
> Today (or should a say night) I tried again and suddenly it's now Steam is shown in the Icon view list. It may be that a Steam update or something.

Does that means this was solved?

**Comment by SethStormR** [comment]
Ah sorry. I forgot to report back. Yes, it's solved :)
