### ISSUE TITLE
Attached "Budgie Desktop Settings" to "Icon Task List"

### ISSUE THREAD

**Issue by SethStormR** [getsolus/packages#1628]
### Summary

Hello,

I'm not sure if this is a bug or feature, but here we go.
When Budgie Desktop Settings is shown in the Icon Task List, there's no "Star" shown, so you can attached it to the icon Task List.

### Steps to reproduce

1. Launch Budgie Desktop Settings
2. Right click on it
3. No star icon

### Expected result

That you can attach Budgie Desktop Settings to Icon Task List.

### Actual result

No cigar, if you want the Budgie Desktop Settings attached.

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Budgie

### System details

System:
  Host: universe Kernel: 6.6.16-273.current arch: x86_64 bits: 64
    Desktop: Budgie v: 10.9.1 Distro: Solus 4.5 resilience
Machine:
  Type: Desktop Mobo: ASUSTeK model: PRIME X370-A v: Rev X.0x
    serial: <superuser required> UEFI: American Megatrends v: 5222
    date: 10/15/2019
CPU:
  Info: 8-core AMD Ryzen 7 1700X [MT MCP] speed (MHz): avg: 2553
    min/max: 2200/3400
Graphics:
  Device-1: NVIDIA GP104 [GeForce GTX 1070] driver: nvidia v: 535.154.05
  Display: x11 server: X.Org v: 21.1.11 with: Xwayland v: 23.2.4 driver:
    gpu: nvidia,nvidia-nvswitch resolution: 1920x1080~60Hz
  API: OpenGL v: 4.6.0 vendor: nvidia v: 535.154.05 renderer: NVIDIA
    GeForce GTX 1070/PCIe/SSE2
Network:
  Device-1: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet
    driver: r8169
  Device-2: Intel Wi-Fi 6 AX200 driver: iwlwifi
Drives:
  Local Storage: total: 938.72 GiB used: 169.52 GiB (18.1%)
Info:
  Processes: 405 Uptime: 1h 47m Memory: total: 32 GiB available: 31.29 GiB
  used: 3.33 GiB (10.6%) Shell: Zsh inxi: 3.3.31

**Comment by EbonJaeger** [comment]
Budgie Desktop Settings is special in that it isn't actually a separate program; it's actually a part of the panel process. As such, it cannot he pinned.
