### ISSUE TITLE
antibody is deprecated

### ISSUE THREAD

**Issue by androidnisse** [getsolus/packages#1647]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

The application antibody has been deprecated by it's author.
https://github.com/getantibody/antibody

**Comment by davidjharder** [comment]
Calling this blocked by https://github.com/getsolus/packages/issues/1776

**Comment by androidnisse** [comment]
> Calling this blocked by #1776

That one is fixed now.

**Comment by malfisya** [comment]
The antidote package probably needs replace key added:
```
replace:
      - antibody
      - antibody-dbginfo
```

Then we can deprecate antibody

**Comment by androidnisse** [comment]
Well this shouldn't be closed yet. Antibody is still in the repo.
