### ISSUE TITLE
Fritzing doesn't start after solus update on 17th Feb 

### ISSUE THREAD

**Issue by tresjam** [getsolus/packages#1651]
### Please confirm there isn't an existing open bug report

- [x] I have searched open bugs for this issue

### Summary

Fritzing from menu doesn't show any message, from Terminal it shows "Fritzing: symbol lookup error: Fritzing: undefined symbol: _Zls6QDebugRK11QDockWidget, version Qt_6"

### Steps to reproduce

starting from terminal with :
**env QT_AUTO_SCREEN_SCALE_FACTOR=0 Fritzing**
this start-command is from the fritzing .destop file in /usr/share/applications

### Expected result

instand errormessage :   
**Fritzing: symbol lookup error: Fritzing: undefined symbol: _Zls6QDebugRK11QDockWidget, version Qt_6**

### Actual result

possibly an issue from the updated qt6 that comes with this update.

from eopkg history I get :  
...
    * qt6-base wurde aktualisiert von 6.6.1-18-1-x86_64 auf 6.6.2-19-1-x86_64.
    * qt6-shadertools wurde aktualisiert von 6.6.1-8-1-x86_64 auf 6.6.2-9-1-x86_64.
    * qt6-declarative wurde aktualisiert von 6.6.1-6-1-x86_64 auf 6.6.2-7-1-x86_64.
    * qt6-5compat wurde aktualisiert von 6.6.1-12-1-x86_64 auf 6.6.2-13-1-x86_64.
...

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Budgie

### System details

System:
  Host: solus-legion Kernel: 6.6.16-275.current arch: x86_64 bits: 64
  Desktop: Budgie v: 10.9.1 Distro: Solus 4.5 resilience
Machine:
  Type: Laptop System: LENOVO product: 82JY v: Legion 5 17ACH6H
    serial: <superuser required>
  Mobo: LENOVO model: LNVNB161216 v: SDK0J40709 WIN
    serial: <superuser required> UEFI: LENOVO v: GKCN60WW date: 03/07/2023
Battery:
  ID-1: BAT0 charge: 74.9 Wh (100.0%) condition: 74.9/80.0 Wh (93.7%)
CPU:
  Info: 6-core AMD Ryzen 5 5600H with Radeon Graphics [MT MCP] speed (MHz):
    avg: 1451 min/max: 400/4280
Graphics:
  Device-1: NVIDIA GA106M [GeForce RTX 3060 Mobile / Max-Q] driver: N/A
  Device-2: AMD Cezanne [Radeon Vega Series / Radeon Mobile Series]
    driver: amdgpu v: kernel
  Device-3: Bison Integrated Camera driver: uvcvideo type: USB
  Display: x11 server: X.Org v: 21.1.11 with: Xwayland v: 23.2.4 driver: X:
    loaded: amdgpu unloaded: fbdev,modesetting,vesa dri: radeonsi gpu: amdgpu
    resolution: 1920x1080~144Hz
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 24.0.1 renderer: AMD
    Radeon Graphics (radeonsi renoir LLVM 16.0.6 DRM 3.54 6.6.16-275.current)
Network:
  Device-1: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet
    driver: r8169
  Device-2: Intel Wi-Fi 6 AX200 driver: iwlwifi
Drives:
  Local Storage: total: 953.88 GiB used: 383.78 GiB (40.2%)
Info:
  Memory: total: 16 GiB note: est. available: 13.51 GiB used: 3.51 GiB (26.0%)
  Processes: 330 Uptime: 50m Shell: Bash inxi: 3.3.33

**Comment by joebonrichie** [comment]
@ReillyBrogan this needed another rebuild, no idea why

**Comment by palto42** [comment]
Is this somehow similar to the issue with darktable #1497, which also required another rebuilt?
For darktable an extra option ` -DBINARY_PACKAGE_BUILD=1` was added to cmake-ninja. This forces a generic darktable build instead of building it for the specific machine it is built on.
My local re-build was also fixing it w/o this extra option, so I have the impression that the issue is somehow caused by the build system.

I tried local rebuild of Fritzing against current stable and it worked as already commented by @joebonrichie

**Comment by ReillyBrogan** [comment]
No, the issue here is that fritzing was just missed when I was pushing packages to the build server. It needed a rebuild for the Qt6 stack update, I did it locally but since it never happened on the build server users never got an updated package. That has been corrected now.
