### ISSUE TITLE
XFCE: Plank again--last update (2/16) changed it 

### ISSUE THREAD

**Issue by brent111** [getsolus/packages#1657]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

no dots for open apps--no, wait it gets worse. if terminal or chrome is minimized you cant fetch it. a new instance launches instead.

disappearing dots and makes open apps disappear

### Steps to reproduce

1) open terminal in plank, observe no dot on terminal in plank.
2) minimize terminal in plank and it cannot be retrieved. Plank opens up a new image.

Substitute terminal for: firefox, chromium, keepassxc, Thunar, and Libre Writer

6 apps, no dots active, all DISAPPEARED upon minimizing

### Expected result

Open terminal, see dot, minimize terminal, bring it up later to see if its done with whatever task you made it do.

Substitute terminal for: firefox, chromium, keepassxc, Thunar, and Libre Writer

### Actual result

Open terminal, see no dot at all, minimize terminal, go and press terminal icon on plank again, and a new instance opens and the original disappeared.

Weird man

### Environment

- [x] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Xfce

### System details

In Budgie writing this, I broke XFCE again (and it's up to date)

### Other comments

ME: Dear XFCE, every single time I try to spend time with you you snub me.
XFCE: It's not you, it's me.

:
EDIT: Plank works as it should in Budgie.

**Comment by brent111** [comment]
UPDATE
Plank still unusable, ergo xfce unusable for me at this point. I thought a second reboot would do it. I played with refresh rate, that solved the dot thing last time (but did not disappear the app gui like this time...). That did not work. Played with screen resolution as well. No luck.

**Comment by Staudey** [comment]
Fixed by 5d4b890e003ec3067dc89567cb514da6086943e8
