### ISSUE TITLE
Powertop not working

### ISSUE THREAD

**Issue by rav101** [getsolus/packages#1667]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

When trying to use powertop, you get an error making it completely unusable

### Steps to reproduce

1. Install Powertop from stable (v2.14)
2. Use command "sudo powertop" to run powertop
3. Should work but comes back with error

### Expected result

App works as expected to show a variety of information

### Actual result

This is the response you get when running powertop
```
ravi@RaviFW13 ~ $ sudo powertop
[sudo] password for ravi:
modprobe cpufreq_stats failedFailed to mount debugfs!
exiting...
```

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

GNOME

### System details

```
System:
  Host: RaviFW13 Kernel: 6.6.16-275.current arch: x86_64 bits: 64
  Desktop: GNOME v: 45.4 Distro: Solus 4.5 resilience
Machine:
  Type: Laptop System: Framework product: Laptop 13 (AMD Ryzen 7040Series)
    v: A7 serial: <superuser required>
  Mobo: Framework model: FRANMDCP07 v: A7 serial: <superuser required>
    UEFI: INSYDE v: 03.03 date: 10/17/2023
Battery:
  ID-1: BAT1 charge: 59.1 Wh (96.6%) condition: 61.2/60.7 Wh (100.8%)
CPU:
  Info: 8-core AMD Ryzen 7 7840U w/ Radeon 780M Graphics [MT MCP] speed (MHz):
    avg: 579 min/max: 400/5132:6076:5289:5760:5447:5918:5605
Graphics:
  Device-1: AMD Phoenix1 driver: amdgpu v: kernel
  Display: wayland server: X.Org v: 23.2.4 with: Xwayland v: 23.2.4
    compositor: gnome-shell driver: gpu: amdgpu resolution: 1803x1202~60Hz
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 24.0.1 renderer: AMD
    Radeon Graphics (radeonsi gfx1103_r1 LLVM 16.0.6 DRM 3.54
    6.6.16-275.current)
Network:
  Device-1: MEDIATEK MT7922 802.11ax PCI Express Wireless Network Adapter
    driver: mt7921e
Drives:
  Local Storage: total: 3.73 TiB used: 123.1 GiB (3.2%)
Info:
  Memory: total: 64 GiB available: 62.01 GiB used: 3.65 GiB (5.9%)
  Processes: 402 Uptime: 3m Shell: Bash inxi: 3.3.33

```

### Other comments

I have tried updating powertop to v2.15 in a Gnome virtual machine on unstable but that comes back with exactly the same error around eing unable to mount debugfs.

Doing some quick googling, I've seen another distro has disabled debug_fs in kernel for security concerns though I don't know if this is the case for Solus. If debug_fs is disabled in kernel, I think there are three potential options:

1. Enable debug_fs in kernel to allow powertop to work again
2. Find another solution that might work without enabling debug_fs in kernel
3. Depreciate powertop as it's not functional anyway

**Comment by davidjharder** [comment]
Can confirm I get the same error.

**Comment by davidjharder** [comment]
This is caused by our kernel config

https://github.com/getsolus/packages/blob/b71e072859d76c207685bc150b3b2c6c6f66889a/packages/l/linux-lts/files/config#L8957

https://github.com/getsolus/packages/blob/9fb669f93375320148655e710ffbe017bb5b0c7c/packages/l/linux-current/files/config#L9924

powertop seems to work on `linux-lts`
