### ISSUE TITLE
User cannot unlock Plasma 4.5 live environment if it locks

### ISSUE THREAD

**Issue by TraceyC77** [getsolus/packages#1671]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

If a system is booted into the Plasma 4.5 live environment, and it locks, it is not possible to unlock with the lock screen

### Steps to reproduce

1. Boot a system / VM with the Plasma 4.5 ISO (problem exists as of snapshot 2024-02-18)
2. Wait for VM to lock automatically
3. Attempt to unlock

### Expected result

The user can unlock the session with no password

### Actual result

The user cannot unlock the session with a blank password or "live"

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Plasma

### System details

Plasma live ISO 2024-02-18

**Comment by TraceyC77** [comment]
That works
By default, Plasma uses ctrl+alt+F2 for the GUI

**Comment by sheepman4267** [comment]
Interesting. On my installed system, TTY 2 is SDDM while TTY 1 is my session. Maybe this is a Wayland session thing.

**Comment by ermo** [comment]
@ReillyBrogan Assigning this to you in the vain hope that you might be able to figure it out.

**Comment by joebonrichie** [comment]
Should be fixed as of https://github.com/getsolus/plasma-desktop-branding/commit/2fad986b414a0e0f2127b7bec4a3cfc454ae3df0

**Comment by TraceyC77** [comment]
Confirmed that I was able to unlock a live session with 4.6 RC 2024-10-09
