### ISSUE TITLE
Systemd v254 update made the 50-systemd-user.sh not executable

### ISSUE THREAD

**Issue by 01random** [getsolus/packages#1673]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

The latest `systemd` update made the `50-systemd-user.sh` file not executable. Therefore, the script does not run and the `DISPLAY` and `XAUTHORITY` environment variables are not imported into the `systemd` user manager. This is causing problems, most notably, with the XDG Desktop Portal.

**I have only reproduced this issue on Solus XFCE and have not tested any other version.**

### Steps to reproduce

1. Do an Upgrade to get the latest version of `systemd`.
2.  Go to `/etc/X11/xinit/xinitrc.d` and check file permissions on `50-systemd-user.sh`

### Expected result

The file is executable.

### Actual result

The file is not executable.

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Xfce

### System details

Up-to-date Solus XFCE.

### Other comments

Use `systemctl --user import-environment` on every login to obtain the two missing environment variables or simply `chmod` the ` 50-systemd-user.sh` to make it executable.

**Comment by Staudey** [comment]
Making that file executable also seems to fix the issue with plank in #1657

**Comment by brent111** [comment]
> Making that file executable also seems to fix the issue with plank in #1657

working in budgie rest of night. will try this in xfce for #1657 tomorrow and report back. thanks for bringing it to my attention (you and Random).
