### ISSUE TITLE
HP Device Manager doesn't show the correct icon in dash and overview on GNOME Wayland

### ISSUE THREAD

**Issue by malfisya** [getsolus/packages#1674]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

HP Device Manager doesn't show the correct icon ( only generic gear icon) in dash and overview on GNOME Wayland. it has different `wm_class` between X11 and waylandn session. On X11 it correctly show "hplip.desktop" while in wayland it identifies itself as "python3". I usually add StartupWMClass=app.wm_class in desktop file like in `frozen-bubble`, but i am not sure anymore this is the right way. `frozen-bubble` identifies itself as `perl` for whatever reason.

### Steps to reproduce

1. Login to wayland session
2. Launch HP Device Manager

### Expected result

It should show its own icon  in dash/panel and overview

### Actual result

Only generic gear icon is shown in dash/panel and overview

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

GNOME

### System details

System:
  Host: dev-solus Kernel: 6.6.17-276.current arch: x86_64 bits: 64
  Desktop: GNOME v: 45.4 Distro: Solus 4.5 resilience
Machine:
  Type: Desktop Mobo: Wibtek model: H77-M v: V1.3 serial: <superuser required>
    BIOS: American Megatrends v: 4.6.5 date: 09/03/2012
CPU:
  Info: quad core Intel Core i5-3570K [MCP] speed (MHz): avg: 1677
    min/max: 1600/3800
Graphics:
  Device-1: AMD Lexa PRO [Radeon 540/540X/550/550X / RX 540X/550/550X]
    driver: amdgpu v: kernel
  Device-2: Jieli USB PHY 2.0 driver: snd-usb-audio,uvcvideo type: USB
  Display: wayland server: X.Org v: 23.2.4 with: Xwayland v: 23.2.4
    compositor: gnome-shell driver: X: loaded: amdgpu
    unloaded: fbdev,modesetting,radeon,vesa dri: radeonsi gpu: amdgpu
    resolution: 1366x768~60Hz
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 23.3.6 renderer: AMD
    Radeon RX 550 / 550 Series (radeonsi polaris12 LLVM 16.0.6 DRM 3.54
    6.6.17-276.current)
Network:
  Device-1: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet
    driver: r8169
  Device-2: Realtek RTL8192EE PCIe Wireless Network Adapter
    driver: rtl8192ee
  Device-3: Realtek RTL8188EUS 802.11n Wireless Network Adapter
    driver: rtl8xxxu type: USB
Drives:
  Local Storage: total: 700.51 GiB used: 341.88 GiB (48.8%)
Info:
  Memory: total: 16 GiB available: 15.6 GiB used: 9.36 GiB (60.0%)
  Processes: 314 Uptime: 1h 23m Shell: fish inxi: 3.3.33

**Comment by TraceyC77** [comment]
I'm not able to reproduce the problem in an up to date Gnome VM, with a Wayland session
After starting HP Device Manager, I see ... in the system tray, and if I click it, I see the HP icon.

There are no extensions installed in this test VM. Do you have an extension related to the system tray icons?

```bash
System:
  Host: tracey-solus-gnome-vm Kernel: 6.6.20-279.current arch: x86_64 bits: 64
  Desktop: GNOME v: 45.4 Distro: Solus 4.5 resilience
Machine:
  Type: Kvm System: QEMU product: Standard PC (Q35 + ICH9, 2009) v: pc-q35-8.1

tracey-solus-gnome-vm% loginctl show-session 7 -p Type
Type=wayland
```

![gnome_hp_icon_20240313_175916](https://github.com/getsolus/packages/assets/10402612/e05b6ad4-cd3f-4496-803c-f7ccff222620)

**Comment by malfisya** [comment]
I just realize dash and panel in gnome means different thing. it is not system tray (Yes, I have "Appindicator and KstatusNotifier Support" extension installed and enabled), this is what i mean (very minor) : 
![Screenshot from 2024-03-14 07-42-23](https://github.com/getsolus/packages/assets/101771435/27712d48-041a-4639-a976-cc6be3466cbd)

You can also check the Window WM_CLASS value by pressing ALT + F2 and type "lg" without the parentheses, It will launch Looking Glass. Then click on "Windows" tab, you will see that WM_CLASS of "HP Device Manager" is "pyhton3".  Cheers!

**Comment by malfisya** [comment]
Updated the title and description to present the issue better.

**Comment by TraceyC77** [comment]
Thank you for clarifying the issue. I was able to replicate it. Interestingly, the correct icon displays when hp-toolbox is pinned to the dash, but the incorrect gear icon is shown in the active area.

![gnome_hp_icon_dash_20240313_175916](https://github.com/getsolus/packages/assets/10402612/b982affe-b207-483e-8e3a-2d08bab9f0bc)

I'll take a look

**Comment by TraceyC77** [comment]
This is an upstream issue, and not due to the way we package `hplip`
There is an issue on [the HPLIP bug tracker](https://bugs.launchpad.net/hplip/+bug/1995715) for it

Also see [a similar bug with yad](https://github.com/getsolus/packages/issues/894) for an explanation of how Wayland determines what icon to use for software based on the .desktop file. We ship those as-is.
