### ISSUE TITLE
Use SQLite in Akonadi (or offer it as an optional backend) (T9922)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#168]
<div dir="rtl"><b>Fabio</b>&nbsp;(<em>&#35;livingsilver94</em>),&nbsp;2021-09-25&nbsp;08:55:46&nbsp;UTC</div><br/>

We currently build Akonadi with both MariaDB and SQLite3 support. MariaDB is the go-to database backend in Akonadi, as upstream developers suggest. This is in my opinion too much, because I need a server-grade DBMS daemon running just to manage my personal contact ands calendar. On my sole home PC.

SQLite3 is somehow discouraged by upstream, but I strongly think that on Solus, a home computing OS, SQLite3 is not only a better choice in terms of performance and complexity, but also we don't need what a full fledged DBMS provides. Debian provides the SQLite3 backend as a [separate package](https://packages.debian.org/bullseye/akonadi-backend-sqlite), so we could easily do the same by patterning the relevant files, since as I said we already build the SQLite3 backend.

Now the harder part is to discuss what we want to ship by default, and how to migrate users' database from one DMBS to the other (if needed).

**Comment by ReillyBrogan** [comment]
@joebonrichie Let's do this for Gear 23.08
