### ISSUE TITLE
Ugly/non theme window decoration for qt apps

### ISSUE THREAD

**Issue by JoroMarin** [getsolus/packages#1681]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

Some qt application as qbittorrent and keepassxc not meet theme window decoration

### Steps to reproduce

![Screenshot from 2024-02-21 07-48-07](https://github.com/getsolus/packages/assets/58250813/ac8281b3-7076-4b4b-9d19-3c68a4586f37)
![Screenshot from 2024-02-21 07-48-35](https://github.com/getsolus/packages/assets/58250813/6394ae93-fffe-4196-8622-19645e82c726)

### Expected result

![Screenshot from 2024-02-21 07-49-18](https://github.com/getsolus/packages/assets/58250813/5cc0037f-3b78-4019-9fc7-2e21cdbe6522)

### Actual result

Window decoration not applied for some qt applications. I'm using dark mode

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

GNOME

### System details

user01@desktp ~ $ inxi -b
System:
  Host: desktp Kernel: 6.6.16-275.current arch: x86_64 bits: 64
  Desktop: GNOME v: 45.4 Distro: Solus 4.5 resilience
Machine:
  Type: Desktop System: Dell product: OptiPlex 7050 v: N/A
    serial: <superuser required>
  Mobo: Dell model: 0NW6H5 v: A00 serial: <superuser required>
    UEFI-[Legacy]: Dell v: 1.27.0 date: 09/18/2023
CPU:
  Info: quad core Intel Core i7-7700 [MT MCP] speed (MHz): avg: 2470
    min/max: 800/4200
Graphics:
  Device-1: Intel HD Graphics 630 driver: i915 v: kernel
  Device-2: NVIDIA GP108 [GeForce GT 1030] driver: nvidia v: 535.154.05
  Device-3: Logitech Brio 100 driver: snd-usb-audio,uvcvideo type: USB
  Display: wayland server: X.Org v: 23.2.4 with: Xwayland v: 23.2.4
    compositor: gnome-shell driver: gpu: nvidia,nvidia-nvswitch
    resolution: 1920x1080~60Hz
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: nvidia mesa v: 535.154.05
    renderer: NVIDIA GeForce GT 1030/PCIe/SSE2
Network:
  Device-1: Intel Ethernet I219-LM driver: e1000e
Drives:
  Local Storage: total: 1.82 TiB used: 718.48 GiB (38.6%)
Info:
  Memory: total: 32 GiB available: 31.22 GiB used: 5.96 GiB (19.1%)
  Processes: 312 Uptime: 1h 22m Shell: Bash inxi: 3.3.33

**Comment by joebonrichie** [comment]
See #632, targeted for gnome 46.

**Comment by malfisya** [comment]
@joebonrichie this is already solved right?
