### ISSUE TITLE
Can no longer suspend (T9504)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#169]
<div dir="rtl"><b>Sam</b>&nbsp;(<em>&#35;samteezy</em>),&nbsp;2021-01-05&nbsp;03:09:40&nbsp;UTC</div><br/>

After the last set of updates that were synced to the repo last Friday, I can no longer suspend my PC.

I think it's related to wpa_supplicant or NetworkManager? Running 
```
sudo gnome-logs
``` 

I see the following lines:

```
Failed to start Suspend.
/usr/lib64/systemd/system-sleep/wpa_supplicant.sh failed with exit status 255.
Freezing of tasks failed after 20.005 seconds (0 tasks refusing to freeze, wq_busy=1):
Failed to suspend system. System resumed again: Device or resource busy

```
For what it's worth, while I do have a hardware wifi antenna installed, I have wifi disabled in the NetworkManager applet since I primarily connect this desktop via Ethernet.

**Comment by TraceyC77** [comment]
Closing this issue due to age and lack of updates.. If this is still an issue for anyone, please open a new bug on our tracker.
