### ISSUE TITLE
Update Zeal to 0.7.0

### ISSUE THREAD

**Issue by androidnisse** [getsolus/packages#1698]
### Please confirm there isn't already an existing package update request

- [X] I have searched through package update requests

### Name

Zeal

### Version

0.7.0

### Link to the release notes or announcement.

https://github.com/zealdocs/zeal/releases/tag/v0.7.0

### Reason for updating

Multiple bug fixes, changed web view to QT WebEngine.

**Comment by davidjharder** [comment]
This was just updated by https://github.com/getsolus/packages/commit/5455bc65d7ba4e95aa8ceba3f4f9896f8870c1c0
The updated package will be part of the next sync
