### ISSUE TITLE
Firefox font rendering issue (emoji numbers)

### ISSUE THREAD

**Issue by Staudey** [getsolus/packages#1727]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

Firefox seems to select the emoji font for numbers on some pages, for example:
https://www.msi.com/Laptop/GF65-Thin-9SX-GTX/Specification

### Steps to reproduce

1. Visit https://www.msi.com/Laptop/GF65-Thin-9SX-GTX/Specification
2. Scroll down a bit and look at the numbers in the specification details

### Expected result

Numbers are rendered in a "normal" font

### Actual result

Numbers are rendered as emojis

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

Budgie

### System details

```
System:
  Host: solus-pc Kernel: 6.6.17-277.current arch: x86_64 bits: 64
  Desktop: Budgie v: 10.9.1 Distro: Solus 4.5 resilience
Machine:
  Type: Desktop Mobo: MSI model: Z170A PC MATE (MS-7971) v: 2.0
    serial: <superuser required> UEFI-[Legacy]: American Megatrends v: A.60
    date: 12/17/2015
CPU:
  Info: quad core Intel Core i7-6700K [MT MCP] speed (MHz): avg: 802
    min/max: 800/4200
Graphics:
  Device-1: NVIDIA GP106 [GeForce GTX 1060 6GB] driver: nvidia v: 535.154.05
  Display: x11 server: X.Org v: 21.1.11 with: Xwayland v: 23.2.4 driver: X:
    loaded: nvidia gpu: nvidia,nvidia-nvswitch resolution: 1920x1080~60Hz
  API: OpenGL v: 4.6.0 vendor: nvidia v: 535.154.05 renderer: NVIDIA
    GeForce GTX 1060 6GB/PCIe/SSE2
Network:
  Device-1: Realtek RTL8192CE PCIe Wireless Network Adapter driver: rtl8192ce
  Device-2: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet
    driver: r8169
Drives:
  Local Storage: total: 1.82 TiB used: 760.36 GiB (40.8%)
Info:
  Memory: total: 32 GiB available: 31.32 GiB used: 6.28 GiB (20.1%)
  Processes: 309 Uptime: 7h 32m Shell: Zsh inxi: 3.3.33

```

**Comment by endumiuz** [comment]
I have the same issue. Removing the second match element in `/etc/fonts/conf.d/66-noto-color-emoji.conf` fixes it. But there's probably a reason for it being there.

**Comment by Justinzobel** [comment]
Is this what you see?
![Uploading image.png…]()

Looks hideous

**Comment by Staudey** [comment]
@Justinzobel Yes, exactly.

**Comment by TraceyC77** [comment]
Possibly related
https://bbs.archlinux.org/viewtopic.php?id=289321
