### ISSUE TITLE
Update shellcheck to 0.9.0 (T10510)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#173]
<div dir="rtl"><b>TraceyC</b>&nbsp;(<em>@TraceyC77</em>),&nbsp;2023-04-30&nbsp;16:50:35&nbsp;UTC</div><br/>

Update shellcheck to the latest version
This depends on T10289 since shellcheck now has a dependency of parsec >=3.1.14 && <3.2

haskell-parsec in the repos does not meet this requirement.
`Name                : haskell-parsec, version: 3.1.13.0, release: 5`

**Comment by algent-al** [comment]
Resolved by https://github.com/solus-packages/ghc/commit/6ed0f7fabff0ba8cd9dd882a50b5e9efce254dbe
