### ISSUE TITLE
Bibata Cursor as default on Solus? (T10354)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#174]
<div dir="rtl"><b>solarmass</b>&nbsp;(<em>&#35;solarmass</em>),&nbsp;2022-08-22&nbsp;22:04:05&nbsp;UTC</div><br/>

I am using Bibata Cursor (Classic) for several months now. It's looks so good, what about making it default?

https://github.com/ful1e5/Bibata_Cursor
(there are screenshots)

**Comment by davidjharder** [comment]
Nah
