### ISSUE TITLE
Autologin issue after the last update

### ISSUE THREAD

**Issue by IOTech17** [getsolus/packages#1757]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

I think I am facing the same root cause.

Since the update last week if Nvidia driver are install I am having issue booting or even displaying the login page.

I also enabled autologin but it doesn't work anymore after the latest sync from last week

I have a XMG P705 - I7 5700HQ - GTX 980M.

I am using Solus OS 4.5 budgie

I also did a fresh install same issue after doing the updates

When I remove the NVidia driver the issue is gone.

Edit 1 :

This is happening with all version of the NVidia driver (current/Beta/Developers). There is something in the update that broke the display/login into the OS. it only work after several restart.

Edit 2 :

This is also happening on Solus OS KDE version, but if I disable autologin I can login by entering my password

### Steps to reproduce

1. Use a nvidia optimus laptop
2. Install the latest update
3. enable autologin
4. install nvidia driver
5. restart

### Expected result

Should login without any issue

### Actual result

black screen, several restart required to get the login screen on budgie.

For KDE the login screen show but autologin fails

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Budgie

### System details

XMG P705 - I7 5700HQ - GTX 980M.

32 GB DDR3

**Comment by ermo** [comment]
@IOTech17 Is this still an issue for you? If not, please close.
