### ISSUE TITLE
Newsboat

### ISSUE THREAD

**Issue by 3knight** [getsolus/packages#1768]
### Please confirm there isn't an existing package request

- [X] I have searched through package requests

### Homepage

https://newsboat.org/

### Maintainer

- [ ] Would you like to be the maintainer for this package?

### Why should this be included in the repository?

Newsboat is an RSS/Atom feed reader for the text console. It’s an actively maintained fork of Newsbeuter.

### Are we allowed to redistribute it?

MIT

### What kind of user will use this package, and how many users do you think will use this package?

People who prefer terminal based apps and who use rss/atom

### Link to source archive file

https://newsboat.org/releases/2.34/newsboat-2.34.tar.xz

**Comment by joebonrichie** [comment]
Conditionally approved providing there is a maintainer

https://help.getsol.us/docs/packaging/procedures/maintainership
