### ISSUE TITLE
Problem using simple-scan when scanning document exceeds one page

### ISSUE THREAD

**Issue by PennyFarthing-GH** [getsolus/packages#1771]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

I am a Budgie Desktop user and I use an HP Officejet 2622 printer.
Unable actually to scan a document exceeding one page with `simple-scan`.
![2024-03-01_17-30_error_simple-scan](https://github.com/getsolus/packages/assets/146464942/f3c8412c-46f9-48c8-a237-023345f3f29c)

### Steps to reproduce

When I want to scan a document of several pages with this application, the first page is scanned without any problem, but when I get to the second page, an error message "Impossible de se connecter au périphérique de numérisation" (unable to connect to scanning device) appears systematically.

### Expected result

I want to scan documents with `simple-scan` whatever the number of pages to scan.

### Actual result

The following error message appears when scanning the 2nd page:
`"Impossible de se connecter au périphérique de numérisation"` (unable to connect to scanning device)

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Budgie

### System details

```
administrateur@solus-budgie ~ $ inxi -b
System:
  Host: solus-budgie Kernel: 6.6.17-277.current arch: x86_64 bits: 64
  Desktop: Budgie v: 10.9.1 Distro: Solus 4.5 resilience
Machine:
  Type: Desktop Mobo: Gigabyte model: B85M-D3H v: x.x
    serial: <superuser required> UEFI: American Megatrends v: F15
    date: 08/20/2015
CPU:
  Info: dual core Intel Core i3-4160 [MT MCP] speed (MHz): avg: 3595
    min/max: 800/3600
Graphics:
  Device-1: Intel 4th Generation Core Processor Family Integrated Graphics
    driver: i915 v: kernel
  Device-2: NVIDIA GP107 [GeForce GTX 1050 Ti] driver: nvidia v: 535.154.05
  Device-3: Logitech Webcam C270 driver: snd-usb-audio,uvcvideo type: USB
  Display: x11 server: X.Org v: 21.1.11 with: Xwayland v: 23.2.4 driver: X:
    loaded: nvidia gpu: nvidia,nvidia-nvswitch resolution: 1920x1080
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: nvidia mesa v: 535.154.05
    renderer: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
Network:
  Device-1: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet
    driver: r8169
Drives:
  Local Storage: total: 1.02 TiB used: 732.03 GiB (70.2%)
Info:
  Memory: total: 16 GiB available: 15.52 GiB used: 2.65 GiB (17.1%)
  Processes: 301 Uptime: 22m Shell: Bash inxi: 3.3.33
administrateur@solus-budgie ~ $ 


```

### Other comments

With the software `Skanpage`, I was able to scan all the pages of my document. But, from the 2nd page, by clicking on the Numériser button (scan), I obtained the message "`Argument incorrect`"; so, by clicking this button a 2nd time, scanning was normally done.

With another one called Master PDF Editor someone in the Solus Forum suggested to try, it says "`Error open device`".

It's as if `simple-scan` (or other software like this) didn't recognize correctly the device printer.

**Comment by PennyFarthing-GH** [comment]
Issue opened at the request of @alfisya

**Comment by malfisya** [comment]
Putting these similiar issue  here :
- https://gitlab.gnome.org/GNOME/simple-scan/-/issues/260
- https://gitlab.gnome.org/GNOME/simple-scan/-/issues/352
- https://gitlab.gnome.org/GNOME/simple-scan/-/issues/358

**Comment by malfisya** [comment]
Okay, I managed to solve this on my printer (HP Deskjet 5820) by installing `sane-airscan`. After installing that , `simple-scan` will have another scanner named : "eSCL - Your Printer" in the drop-down menu. Select that and now I can scan multiple pages without any error. To read more abaout `sane-airscan`, here is their [github page](https://github.com/alexpevzner/sane-airscan). There is a little quirk with `sane-airscan`: Usually it shows scanning process in real-time, now with "eSCL", it only shows the page when the scan is completed.
 
Now, the question is would it be good to just add `sane-airscan` as rundeps on`simple-scan` and `skanpage`  or any scanner utility for good OOTB experience? Thoughts @ReillyBrogan @joebonrichie ?

**Comment by PennyFarthing-GH** [comment]
New elements:

From this day (01/08/2024) I scanned a 2-page document withsimple-scan, 3 updates were produced for the packages hplip and hplip-drivers:


- 02/16/2024  v 3.23.5-56-1  -> v 3.23.12-57-1
- 02/24/2024  v 3.23.12-57-1 -> v 3.23.12-58-1
- 03/07/2024  v 3.23.12-58-1 -> v 3.23.12-59-1

NB. The previous update then dates back to 07/29/2023.

I tested each version, from the most recent to the one that took place before my last scan.

I was this one that worked, by typing the following terminal command:
sudo eopkg it hplip-3.23.5-56-1-x86_64.eopkg hplip-drivers-3.23.5-56-1-x86_64.eopkg
and then reboot.

An important (and surprising) note: I was able to scan a 2-page document using a single page (Page unique) instead of multiple pages from a flat scanner (Pages multiples depuis un numériseur à plat)!

**Comment by PennyFarthing-GH** [comment]
@malfisya ask me to precise that this issue concerns @TraceyC77 (the maintainer of `hplip`)

**Comment by malfisya** [comment]
@TraceyC77 Maybe you already saw it, but this is the forum post where it all started https://discuss.getsol.us/d/10368-simple-scan-hp-printer-scanner.  (With much unnecessary details  😅).

**Comment by TraceyC77** [comment]
@malfisya Yes, I was already following that forum thread. No need to ping me here. I keep an eye on printer related forum threads

 If you have any specific details to add, please add them here.
