### ISSUE TITLE
antidote

### ISSUE THREAD

**Issue by androidnisse** [getsolus/packages#1776]
### Please confirm there isn't an existing package request

- [X] I have searched through package requests

### Homepage

https://getantidote.github.io/

### Maintainer

- [X] Would you like to be the maintainer for this package?

### Why should this be included in the repository?

This replaces antibody which is deprecated by it's author. Would solve this issues https://github.com/getsolus/packages/issues/1647

### Are we allowed to redistribute it?

MIT

### What kind of user will use this package, and how many users do you think will use this package?

Current users of antibody.

### Link to source archive file

https://github.com/mattmc3/antidote/archive/refs/tags/v1.9.4.tar.gz

**Comment by davidjharder** [comment]
Hey @androidnisse still interested in this?

**Comment by androidnisse** [comment]
> Hey @androidnisse still interested in this?

Yes I am.
