### ISSUE TITLE
Feature Request | an OpenQA like webpage for consulting sync reports in real time. (T10548)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#179]
<div dir="rtl"><b>Arnaud&nbsp;Mez</b>&nbsp;(<em>@theunclemez</em>),&nbsp;2023-06-05&nbsp;22:17:03&nbsp;UTC</div><br/>

To help Solus user get better insight, understanding and knowledge of what have been done in recent/latest sync/build.
I suggest a web page to be arrange to inform the userbase.

I'm getting my references from the well known OpenQA webpage of OpenSUSE where you can check the status of a build/sync in real time, thus knowing what have changed or added etc.
Implementing this would benefit people a lot and also help with better targeting of request, by knowing what have been done, people can either thank the team for achieved task or wait for next implementation or just base their task request on here according to the info they get from that one place

to give an idea, this link is an example where people can view full list of builds (or sync in our case) and click on the build/sync they want to know more about.
https://openqa.opensuse.org/snapshot-changes/opensuse/Tumbleweed/

Here,after clicking let's say the latest build/snapshot of Tumbleweed user can get a better insight/understanding of the job done by the respective teams.
https://openqa.opensuse.org/snapshot-changes/opensuse/Tumbleweed/diff/20230604

I believe this will help a lot and drop a certain stress level, then if something is not found by a requester into a build/sync report page he can then ask to respective team in dedicated rooms.

from Dev perspective it is also useful as one can track the changes over the year, as all sync report should be consultable from that place anytime, arranged per years, month, weeks etc.

Thanks y'all for your impressive work

**Comment by ermo** [comment]
@theunclemez We have developed a script called `worklog.py` (available in `common/Scripts/`) in the tree, which shows the full gamut of changes on the build server during a given date interval and in git.

We have also begun making sync notes available on the forum based on the info this script applies.

In addition, you can check the git log for changes to a given package by going to it's directory in the monorepo and running `git log .` to see the changes for a given package.

Closing as completed for now.
