### ISSUE TITLE
eza: Missing nerd fonts for icons

### ISSUE THREAD

**Issue by Justinzobel** [getsolus/packages#1794]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

Missing nerd fonts for icons

### Steps to reproduce

ls-l --icons

### Expected result

Icons

### Actual result

![Screenshot_20240304_165956](https://github.com/getsolus/packages/assets/1370117/39bc2c62-fc76-49c6-8d2f-9a8d00fc5ba4)

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

Plasma

### System details

System:
  Host: lenovo-laptop Kernel: 6.6.18-278.current arch: x86_64 bits: 64
  Desktop: KDE Plasma v: 6.0.0 Distro: Solus 4.5 resilience
Machine:
  Type: Laptop System: LENOVO product: 20Y1001SAU v: ThinkPad P14s Gen 1
    serial: <superuser required>
  Mobo: LENOVO model: 20Y1001SAU v: SDK0J40697 WIN
    serial: <superuser required> UEFI: LENOVO v: R1BET77W(1.46 )
    date: 10/24/2023
Battery:
  ID-1: BAT0 charge: 22.3 Wh (51.4%) condition: 43.4/50.5 Wh (85.9%)
    volts: 11.6 min: 11.6
CPU:
  Info: 8-core AMD Ryzen 7 PRO 4750U with Radeon Graphics [MT MCP]
    speed (MHz): avg: 1876 min/max: 1400/1700
Graphics:
  Device-1: AMD Renoir [Radeon RX Vega 6 ] driver: amdgpu v: kernel
  Device-2: Chicony Integrated Camera driver: uvcvideo type: USB
  Display: wayland server: X.Org v: 23.2.4 with: Xwayland v: 23.2.4
    compositor: kwin_wayland driver: gpu: amdgpu resolution: 1: 3200x1800~144Hz
    2: 3200x1800~60Hz 3: 1920x1080~60Hz
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 24.0.2 renderer: AMD
    Radeon Graphics (radeonsi renoir LLVM 16.0.6 DRM 3.54 6.6.18-278.current)
Network:
  Device-1: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet
    driver: r8169
  Device-2: Intel Wi-Fi 6 AX200 driver: iwlwifi
  Device-3: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet
    driver: r8169
  Device-4: Realtek RTL8153 Gigabit Ethernet Adapter driver: r8152 type: USB
Drives:
  Local Storage: total: 476.94 GiB used: 310.34 GiB (65.1%)
Info:
  Memory: total: 28 GiB note: est. available: 29.11 GiB
    used: 17.27 GiB (59.3%)
  Processes: 513 Uptime: 5h 58m Shell: fish inxi: 3.3.33

**Comment by HarveyDevel** [comment]
`font-firacode-nerd`

**Comment by EbonJaeger** [comment]
Even if a nerd font is installed, your terminal still needs to be configured to use it, which is something we cannot do. I don't like the idea of adding a dependency on a specific font when it may or may not actually be used, especially when people can download and use a different font of their choice.

**Comment by Justinzobel** [comment]
Yeah, that makes sense, kinda annoying that it needs the terminal font set.
