### ISSUE TITLE
Discord Icon tray cause crashes on Wayland

### ISSUE THREAD

**Issue by harolkd** [getsolus/packages#1796]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

I started using Solus 3 weeks ago, since I started using Solus the discord app has this same error.

When I open discord and close the window, and try to re-open discord by clicking on the icon tray, discord crashes.

### Steps to reproduce

1. Open Discord
2. Close Discord window and let it working on the background
3. Click the icon tray
4. Click "Open Discord"

### Expected result

Open Discord app

### Actual result

Discord crashes, if you run discord using the terminal you get this error message (translated to english):

```
[6283:0228/111321.367692:ERROR:wayland_event_watcher.cc(36)] libwayland: wl_surface@46: error 0: gtk_shell::get_gtk_surface already requested

'trap' for stop/follow-up point ('core' generated)
```

Original error message:

```
[6283:0228/111321.367692:ERROR:wayland_event_watcher.cc(36)] libwayland: wl_surface@46: error 0: gtk_shell::get_gtk_surface already requested

'trap' para punto de parada/seguimiento ('core' generado)
```

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

GNOME

### System details

harold@hp-15-solus ~ $ inxi -b
System:
  Host: hp-15-solus Kernel: 6.6.17-277.current arch: x86_64 bits: 64
  Desktop: GNOME v: 45.4 Distro: Solus 4.5 resilience
Machine:
  Type: Laptop System: HP product: HP Laptop 15-da0xxx v: Type1ProductConfigId
    serial: <superuser required>
  Mobo: HP model: 84A7 v: 80.50 serial: <superuser required> UEFI: Insyde
    v: F.45 date: 05/23/2023
Battery:
  ID-1: BAT1 charge: 5.7 Wh (16.4%) condition: 34.7/40.9 Wh (84.9%)
    volts: 10.4 min: 11.3
CPU:
  Info: quad core Intel Core i7-8550U [MT MCP] speed (MHz): avg: 793
    min/max: 400/4000
Graphics:
  Device-1: Intel UHD Graphics 620 driver: i915 v: kernel
  Device-2: NVIDIA GM108M [GeForce MX130] driver: nvidia v: 535.154.05
  Device-3: Quanta HP TrueVision HD Camera driver: uvcvideo type: USB
  Display: wayland server: X.Org v: 23.2.4 with: Xwayland v: 23.2.4
    compositor: gnome-shell driver: gpu: i915 resolution: 1600x900~60Hz
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: intel mesa v: 23.3.6
    renderer: Mesa Intel UHD Graphics 620 (KBL GT2)
Network:
  Device-1: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet
    driver: r8169
  Device-2: Realtek RTL8723DE 802.11b/g/n PCIe Adapter driver: rtw_8723de
Drives:
  Local Storage: total: 476.94 GiB used: 33.02 GiB (6.9%)
Info:
  Memory: total: 12 GiB available: 11.6 GiB used: 4.01 GiB (34.6%)
  Processes: 289 Uptime: 21m Shell: Bash inxi: 3.3.33

**Comment by TraceyC77** [comment]
I'm not able to reproduce this currently on KDE Plasma
Are you still seeing this crash? If so i can add Discord to a test VM and see if I can reproduce there.

**Comment by harolkd** [comment]
I tried to reproduce this bug recently in the same device where i found the bug. It seams to be solved, the "open" option in the discord icon tray works just fine now. It could be just an issue with discord and not Solus.

**Comment by harolkd** [comment]
I tried to reproduce this bug recently in the same device where i found the bug. It seams to be solved, the "open" option in the discord icon tray works just fine now. It could be just an issue with discord and not Solus.
