### ISSUE TITLE
Login screen: text of unselected usernames is white, without shadow/outline (T4917)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#18]
<div dir="rtl"><b>yaomtc</b>&nbsp;(<em>&#35;yaomtc</em>),&nbsp;2017-11-01&nbsp;02:56:56&nbsp;UTC</div><br/>

This is a problem when the default background is nearly half white. If you select the second username, the first username becomes practically invisible.
![IMG_20180317_110816861](https://github.com/getsolus/packages/assets/23007135/b001a7f4-8e74-40cf-9c12-301f11c6162e)
![IMG_20180317_110807581](https://github.com/getsolus/packages/assets/23007135/9c9e824e-f272-485e-8b39-6e3167f824bb)

**Comment by davidjharder** [comment]
Still an issue on Budgie

**Comment by TraceyC77** [comment]
Still an issue on Budgie.

**Comment by TraceyC77** [comment]
@EbonJaeger - is this something we can / should address in Solus as a theming thing or is it an upstream Budgie issue?

**Comment by EbonJaeger** [comment]
Themes usually only barely theme LightDM greeters; the way it's implemented makes it a bit of a pain to theme, and some parts you really can't change at all. The best thing to do would be to file an issue to Slick Greeter.

**Comment by ermo** [comment]
Closing as 1) It's old and 2) it's primarily an upstream problem.
