### ISSUE TITLE
XFCE No sound when volume changes

### ISSUE THREAD

**Issue by minhhut** [getsolus/packages#1801]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

It's a helpful feature to get feedback of volume changes event, this help to know which speaker is active and also knowing if the volume is high enough without opening any audio media to test the volume.

### Steps to reproduce

1. Open PulseAudio Panel Plugin by a right click on Audio icon and select Properties, in General tab, make sure "Play system sound when volume changes" is checked.
3. Open Setting Manager -> Appearance -> Settings, and make sure "Enable event sounds" is checked.
4. Change volume by media keys on Keyboard or any other way.

### Expected result

Hear the sound of volume changes

### Actual result

Hear nothing

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Xfce

### System details

System:
  Host: solus Kernel: 6.6.17-277.current arch: x86_64 bits: 64
  Desktop: Xfce v: 4.18.1 Distro: Solus 4.5 resilience

**Comment by EbonJaeger** [comment]
If you install the package `sound-theme-freedesktop`, the sounds should play as long as you've enabled the correct settings, which it seems you already have. It'll also get pulled in on update once the linked Pull Request is merged.

**Comment by minhhut** [comment]
I just installed the `sound-theme-freedesktop` and it works right away without any further changes. Thank you!
