### ISSUE TITLE
fan2go

### ISSUE THREAD

**Issue by stalebrim** [getsolus/packages#1809]
### Please confirm there isn't an existing package request

- [X] I have searched through package requests

### Homepage

https://github.com/markusressel/fan2go

### Maintainer

- [ ] Would you like to be the maintainer for this package?

### Why should this be included in the repository?

Fan2go is a simple daemon providing dynamic fan speed control based on temperature sensors. It is similar to fancontrol, but doesn't rely on absolute hwmon paths, allows setting up multiple-point fan curves and averaging multiple sensor readings if needed. The daemon is written in Go and configuration is YAML.

### Are we allowed to redistribute it?

AGPL-3.0

### What kind of user will use this package, and how many users do you think will use this package?

Users who are looking for a more flexible and powerful alternative to Fancontrol or who have lackluster UEFI options for case fan control. 

### Link to source archive file

https://github.com/markusressel/fan2go/archive/refs/tags/0.8.1.tar.gz

**Comment by joebonrichie** [comment]
Conditionally approved given a maintainer

**Comment by malfisya** [comment]
Already closed by https://github.com/getsolus/packages/pull/2192
