### ISSUE TITLE
firestarter (T10137)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#181]
<div dir="rtl"><b>nazar</b>&nbsp;(<em>&#35;nazar</em>),&nbsp;2022-01-29&nbsp;15:45:21&nbsp;UTC</div><br/>

- firestarter
- https://tu-dresden.de/zih/firestarter
- A Processor Stress Test Utility
- open source
- https://github.com/tud-zih-energy/FIRESTARTER/archive/refs/tags/v2.0.tar.gz

This is esp. handy for users of s-tui

**Comment by silkeh** [comment]
@nazar-stasiv: as asked above, what it can do that other tools such as stress-ng cannot?

**Comment by nazar-stasiv** [comment]
> @nazar-stasiv: as asked above, what it can do that other tools such as stress-ng cannot?

Legitimate question, and the answer is not much. s-tui will pick any supported and available stress tool e.g. stress-ng will do just fine.

How do I close this?

**Comment by silkeh** [comment]
> How do I close this?

By asking :slightly_smiling_face:
