### ISSUE TITLE
Replace fbdev with SimpleDRM

### ISSUE THREAD

**Issue by EbonJaeger** [getsolus/packages#1816]
### Please confirm there isn't already an existing package update request

- [X] I have searched through package update requests

### Name

`linux-current`, `linux-lts`

### Version

n/a

### Link to the release notes or announcement.

n/a

### Reason for updating

The same topic was brought up and addressed in Serpent OS, so I'll just link that issue: https://github.com/serpent-os/recipes/issues/155

**Comment by joebonrichie** [comment]
Along these lines: https://gitlab.archlinux.org/archlinux/packaging/packages/linux/-/commit/78d0321a90ad7d0591599975c7192bbdd13d6f0d

We still ship nvidia 470 driver which doesn't have GBM support which may be a blocker for simpledrm.

**Comment by ermo** [comment]
> We still ship nvidia 470 driver which doesn't have GBM support which may be a blocker for simpledrm.

Unless it can be determined with certainty that 470 is NOT a blocker, this should probably be downgraded to not be a part of the 4.6 release timeline?
