### ISSUE TITLE
Update GnuPG to latest 2.4.x (T10483)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#182]
<div dir="rtl"><b>nazar</b>&nbsp;(<em>&#35;nazar</em>),&nbsp;2023-04-23&nbsp;11:47:02&nbsp;UTC</div><br/>

Here are release notes https://dev.gnupg.org/source/gnupg/browse/master/NEWS

**Comment by ReillyBrogan** [comment]
Resolved by 4b17ec54307e04b3f93964c44e6d5219106b8516
