### ISSUE TITLE
Need new maintainer for Staudey packages (T10553)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#184]
<div dir="rtl"><b>Thomas&nbsp;Staudinger</b>&nbsp;(<em>@Staudey</em>),&nbsp;2023-06-09&nbsp;19:39:58&nbsp;UTC</div><br/>

Due to me no longer (reliably) having time for Solus, we need new maintainers for the following packages that were updated (almost) exclusively by me:
- [x] amfora (@ermo)
- [x] anki | and exclusive dependencies:
 - [x] python-maturin (@GZGavinZhao)
 - [x] python-orjson
 - [x] python-stringcase
 - [x] python-waitress
 - [x] flask-cors
Note: Anki can be a huge annoyance, and they seem to regularly change their build system completely, requiring you to restructure the whole package recipe again
- [x] drawing (@algent-al)
- [x] dolphin-emu (@ZachBacon )
- [x] gradience | and exclusive dependencies: (@EbonJaeger )
 - [x] adw-gtk3-theme
 - [x] blueprint-compiler
 - [x] material-color-utilities-python
 - [x] python-anyascii
 - [x] python-cssselect2
 - [x] python-svglib
 - [x] python-yapsy
- [ ] gmmlib
- [ ] intel compute stuff:
 - [ ] igsc
 - [ ] intel-compute-runtime
 - [ ] intel-graphics-compiler
 - [ ] intel-level-zero
 - [ ] intel-metee
- [x] lollypop
- [x] lyrebird
- [x] m64py (@ZachBacon)
- [x] noisetorch (@ReillyBrogan)
- [x] nvidia drivers
- [x] obs-studio | and exclusive dependencies (@ZachBacon)
 - [x] librist
- [x] obs-vkcapture (@ZachBacon)
- [x] onedrive (@davidjharder)
- [x] pipewire (@ReillyBrogan)
- [x] polari
- [x] protontricks | and exclusive dependency: (@HarveyDevel)
 - [x] python-vdf (@HarveyDevel)
- [x] python-moddb | and exclusive dependencies
 - [x] python-pyrate-limiter
 - [x] python-toolz
- [x] scrcpy (@chax )
- [x] steamtinkerlaunch
- [x] tagainijisho
- [x] tealdeer (@davidjharder)
- [x] terminator (@algent-al)
- [x] vivaldi-stable/snapshot (@HarveyDevel)
 - [x] ffmpeg-chromium (@HarveyDevel)
 - [x] ffmpeg-chromium-vivaldi-stable (@HarveyDevel)
- [x] wireplumber (@ReillyBrogan)
- [x] yad (@HarveyDevel)
- [x] yt-dlp  (@HarveyDevel)

**Comment by Justinzobel** [comment]
@Staudey since you're back, you want to keep some of these?

**Comment by Justinzobel** [comment]
Sounds good, let's close this then. Maybe if we find someone that comes along and asks for an update on it we can rope them into ownership :)
