### ISSUE TITLE
ipcalc

### ISSUE THREAD

**Issue by androidnisse** [getsolus/packages#1843]
### Please confirm there isn't an existing package request

- [X] I have searched through package requests

### Homepage

https://jodies.de/ipcalc

### Maintainer

- [X] Would you like to be the maintainer for this package?

### Why should this be included in the repository?

This is an easy tool for calculating IP-adresses. It would be nice to have it right at the CLI when working with IP-adresses.

### Are we allowed to redistribute it?

GPL-2.0-or-later

### What kind of user will use this package, and how many users do you think will use this package?

Network engineers, students learning networks.

### Link to source archive file

https://github.com/kjokjo/ipcalc/archive/refs/tags/0.51.tar.gz

**Comment by joebonrichie** [comment]
Conditionally approved given a maintainer
