### ISSUE TITLE
Get VAAPI working with Firefox for nVidia GPUs (T10532)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#186]
<div dir="rtl"><b>TraceyC</b>&nbsp;(<em>@TraceyC77</em>),&nbsp;2023-05-10&nbsp;15:42:01&nbsp;UTC</div><br/>

Get VAAPI working with nVidia GPUs for Firefox

Testing
https://fedoraproject.org/wiki/Firefox_Hardware_acceleration#Troubleshooting

**Comment by davidjharder** [comment]
Going to close this in favor of #205 *Firefox VAAPI test task for AMD/Intel GPUs w/OSS drivers*
