### ISSUE TITLE
warpinator

### ISSUE THREAD

**Issue by SlowNicoFish** [getsolus/packages#1863]
### Please confirm there isn't an existing package request

- [X] I have searched through package requests

### Homepage

https://warpinator.com/

### Maintainer

- [ ] Would you like to be the maintainer for this package?

### Why should this be included in the repository?

To easily be able to transfer files between devices

### Are we allowed to redistribute it?

GPL-3.0-only

### What kind of user will use this package, and how many users do you think will use this package?

Average user

### Link to source archive file

https://github.com/linuxmint/warpinator/archive/1.8.3/warpinator-1.8.3.tar.gz

**Comment by joebonrichie** [comment]
Conditionally approved given there is a maintainer for it.

**Comment by malfisya** [comment]
> https://warpinator.com/

This is most likely a bogus website, impersonating warpinator. Warpinator is part of Linux Mint project, there is no mention of that here and link to source code.
