### ISSUE TITLE
Update shotcut to 22.06.23 (T10344)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#187]
<div dir="rtl"><b>Xon</b>&nbsp;(<em>&#35;xonus</em>),&nbsp;2022-08-18&nbsp;05:25:12&nbsp;UTC</div><br/>

fixing some bugs (theme bug, unexpected crashes), adding new functionality
link to source: https://www.shotcut.org/download/

**Comment by maikwoehl** [comment]
I will step up and try to package the updated version

**Comment by luzpaz** [comment]
[23.09.29](https://github.com/mltframework/shotcut/releases/tag/v23.09.29) has been released

**Comment by luzpaz** [comment]
Any traction on this ?

**Comment by ReillyBrogan** [comment]
It's just that nobody has gotten around to it yet. Sometimes applications that the Solus maintainers don't use don't really get the attention they deserve. Have you considered learning how to package yourself? It's really not that hard and it's a great way to learn more about how software and Linux works.

**Comment by malfisya** [comment]
This is the last version that support Qt5. For newer version, we should update to Qt6 first. I guess around Plasma 6 release? Cheers!
