### ISSUE TITLE
vscode: Dev Containers fail to start

### ISSUE THREAD

**Issue by MKuranowski** [getsolus/packages#1878]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

The build of VS Code in Solus suffers from https://github.com/microsoft/vscode-remote-release/issues/1097

The [Dev Containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) extension fails to start, giving the following error in the developer console:

```
workbench.desktop.main.js:422785 Activating extension 'ms-vscode-remote.remote-containers' failed: Extension 'ms-vscode-remote.remote-containers' CANNOT use API proposal: resolvers.
Its package.json#enabledApiProposals-property declares:  but NOT resolvers.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-vscode-remote.remote-containers.
 ```

### Steps to reproduce

1. Install [Dev Containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers)
2. Open a project
3. Try to re-open it in a container, e.g. by selecting the _Dev Containers: Reopen in Container_ command

### Expected result

The project should be opened in a dev container

### Actual result

An error pop-up shows up with `command 'remote-containers.reopenInContainer' not found`

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Budgie

### System details

```
System:
  Host: orion-linux-extra Kernel: 6.6.20-279.current arch: x86_64 bits: 64
  Desktop: Budgie v: 10.9.1 Distro: Solus 4.5 resilience
Machine:
  Type: Desktop System: ASUS product: N/A v: N/A serial: <superuser required>
  Mobo: ASUSTeK model: TUF GAMING B550-PLUS (WI-FI) v: Rev X.0x
    serial: <superuser required> UEFI: American Megatrends v: 2604
    date: 02/25/2022
CPU:
  Info: 8-core AMD Ryzen 7 5800X [MT MCP] speed (MHz): avg: 2568
    min/max: 2200/4850
Graphics:
  Device-1: AMD Navi 32 [Radeon RX 7700 XT / 7800 XT] driver: amdgpu v: kernel
  Display: x11 server: X.Org v: 21.1.11 with: Xwayland v: 23.2.4 driver:
    gpu: amdgpu resolution: 3840x2160~60Hz
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 24.0.2 renderer: AMD
    Radeon RX 7800 XT (radeonsi navi32 LLVM 16.0.6 DRM 3.54
    6.6.20-279.current)
Network:
  Device-1: Intel Wi-Fi 6 AX200 driver: iwlwifi
  Device-2: Realtek RTL8125 2.5GbE driver: r8169
Drives:
  Local Storage: total: 5.05 TiB used: 31.73 GiB (0.6%)
Info:
  Memory: total: 32 GiB available: 31.26 GiB used: 3.26 GiB (10.4%)
  Processes: 408 Uptime: 11m Shell: Bash inxi: 3.3.33
```

**Comment by malfisya** [comment]
It seems you can enable it yourself with this command (I haven't tested it) :
```
$ code-oss --enable-proposed-api ms-vscode-remote.remote-containers 
```
From https://bugs.archlinux.org/task/63374

**Comment by MKuranowski** [comment]
I've tried that, however it gives a different error; I'll investigate further a bit later

**Comment by MKuranowski** [comment]
After some misconfiguration (I presume on my side) the dev container has built, but code-oss can't connect to it with the following error:
```
Failed to connect to the remote extension host server (Error: Connection error: Unauthorized client refused)
```

**Comment by ReillyBrogan** [comment]
Certain extensions available in the extension store are DRMed. They require official vscode binaries provided by Microsoft in order to work, and to my knowledge there's no know workaround for that (believe me I tried REALLY hard to get the remote SSH extension to work). Those are available as a tar from Microsoft or you can install the flatpak.

Since there's not really anything else for us to do here (as you saw adding that flag won't actually enable anything) I'm going to go ahead and close this.
