### ISSUE TITLE
Pinta package is outdated, latest version is 2.0.2 (T10274)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#188]
<div dir="rtl"><b>Abhinav&nbsp;Kulshreshtha</b>&nbsp;(<em>&#35;Abhinav1217</em>),&nbsp;2022-06-01&nbsp;13:09:14&nbsp;UTC</div><br/>

Pinta project has released a major update in Jan 2022. Pinta-2.0.2. The latest package in repo is still 1.7.1.  This package needs updates.
The major release has ported the project to GTK3, and dotnet 6. There are various UI and performance improvements in this release too. 

On my machine, It build and installs without any issue. I should note that my system has dotnet core 6 installed from microsoft, and the build script used that over system mono libraries.   
The project claims that it can be build using mono libraries too which Ubuntu uses, but I haven't tried building it.

**Comment by malfisya** [comment]
unblocked by https://github.com/getsolus/packages/pull/1498

**Comment by ReillyBrogan** [comment]
7fdf6cf49013e846721bd24e080acb05cdcad8d9
