### ISSUE TITLE
After updating from Plasma 5 to 6 via eopkg, unable to shut system down

### ISSUE THREAD

**Issue by TraceyC77** [getsolus/packages#1898]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

I had run `eopkg up` to update the system. This included the update to Plasma 6.
The system was unable to perform a normal shutdown.

### Steps to reproduce

1. System on Plasma 5 before updating to Plasma 6
2. Run `eopkg up`
3. Attempt to shut down the system via App Menu - Shut Down

### Expected result

The system shuts down

### Actual result

 The UI disappeared but the laptop did not shut down. It cycled between no power to the screen and a blank black screen (with backlight). When I tried to get to a TTY it flashed between the login prompt and a blank black screen.

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

Plasma

### System details

Operating System: Solus 4.5
KDE Plasma Version: 6.0.2
KDE Frameworks Version: 6.0.0
Qt Version: 6.6.2
Kernel Version: 6.6.21-280.current (64-bit)
Graphics Platform: X11
Processors: 16 × 11th Gen Intel® Core™ i7-11800H @ 2.30GHz
Memory: 62.5 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2
Manufacturer: Dell Inc.
Product Name: XPS 17 9710

### Other comments

After rebooting again (and a third time due to another issue), shutdown works normally

This was not an issue on my Flex, where I had switched to the Plasma6 repo and updated from 5 to 6 a couple of weeks ago.

**Comment by Justinzobel** [comment]
Honestly, I think this is another reason offline updates are required, replacing system libraries and binaries while they're in use is just asking for trouble.

**Comment by TraceyC77** [comment]
No longer an issue, closing
