### ISSUE TITLE
Deprecate haskell-nats (T10346)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#190]
<div dir="rtl"><b>Gavin&nbsp;Zhao</b>&nbsp;(<em>&#35;GZGavinZhao</em>),&nbsp;2022-08-18&nbsp;19:03:33&nbsp;UTC</div><br/>

`haskell-nats` (R1272) is [merged into](https://hackage.haskell.org/package/nats-1.1.2/src/src/Numeric/Natural.hs) `base` version 4.8 or greater. We're on `base` 4.12.

**Comment by algent-al** [comment]
Resolved by https://github.com/getsolus/solus-sc/pull/239
