### ISSUE TITLE
Vivaldi-stable won't launch on my Plasma 6 VM

### ISSUE THREAD

**Issue by WetGeek** [getsolus/packages#1906]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

I created a clone of my Solus 4.5 Plasma VM to use with the unstable repository without making any permanent changes to my daily-driver laptop (the VMs host).  While configuring the cloned VM for its intended purpose, I tried to run Vivaldi, which was already in use on the VM I'd cloned.  I was unable to launch vivaldi-stable at all.  On a hunch, I installed vivaldi-snapshot, and found I could launch that normally.  I configured it as needed for the clone's intended purpose.

### Steps to reproduce

On a machine using the unstable repository, attempt to launch vivaldi-stable.

### Expected result

I expected that Vivaldi would launch with no problem, and I could configure it as needed.

### Actual result

I tried many times to launch it from its virtual workspace, with no success.  I attempted to launch it from the Intenet menu section, also without success.  Eventually I gave up and installed vivaldi-snapshot, which launched normally.

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

Plasma

### System details

![image](https://github.com/getsolus/packages/assets/6805994/131abcb4-1755-45d2-905d-ddb46af0d59b)

### Other comments

The whole purpose of creating this cloned VM was to prevent making permanent changes to my laptop, so I have not tested this issue on hardware, just the VM.  The first step in dealing with this bug would obviously be to try it on a hardware computer before spending any further time on it.  I assume that would be easy for most team members.

**Comment by TraceyC77** [comment]
If you run vivaldi-stable from command line, what output do you see? Can you save that to a file or a pastebin and attach it to the issue?

Also, I have noted that there are times I launch Vivaldi and the window appears on another virtual desktop. Check all your virtual desktops for it. See if the icon is in the task bar at all. See if the process is running with

```bash
pgrep -fla vivaldi
```

Vivaldi Stable launches for me on Plasma 6 (unstable)

**Comment by WetGeek** [comment]
[vivaldi_stable_in_terminal.txt](https://github.com/getsolus/packages/files/14625353/vivaldi_stable_in_terminal.txt)

[vivaldi_snapshot_in_terminal.txt](https://github.com/getsolus/packages/files/14625354/vivaldi_snapshot_in_terminal.txt)

Note that there was no other instance of Vivaldi present when I started vivaldi-stable in the terminal.  I don't know what the message means by that.  To be sure, I closed the VM, then restarted it, and launched nothing but terminology and attempted to start vivvaldi-stable.

Despite the stderr output from vivaldi-snashot, it did indeed launch, and worked as expected.

**Comment by WetGeek** [comment]
I just realized that the extra profile might be due to this VM's being a clone of that original VM.  And Vivaldi was installed there before it was cloned.  I'm going to try to find the vivaldi-stable profile in the /home directory and remove it, then reinstall vivaldi-stable to create a new profile. If I'm right, vivaldi-stable shoulld run then, and I can close this issue.

**Comment by WetGeek** [comment]
YES!  The new vivaldi-stable launches without any drama.  The stderr output looks the same as what was produced by vivaldi-snapshot, but clearly the culprit was the profile.
