### ISSUE TITLE
Update firetools to 0.9.64 (T10165)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#191]
<div dir="rtl"><b>Marshall</b>&nbsp;(<em>&#35;Marshallishere</em>),&nbsp;2022-02-13&nbsp;14:33:48&nbsp;UTC</div><br/>

The repository version is too out-of-date, problably has many bugfixes and new features.

Source: https://sourceforge.net/projects/firejail/files/firetools/firetools-0.9.64.tar.xz/download

**Comment by androidnisse** [comment]
There is an pull request for this now https://github.com/getsolus/packages/issues/191
