### ISSUE TITLE
Error Installing system.utils - unfulfilled dependecies

### ISSUE THREAD

**Issue by diagnostics0** [getsolus/packages#1917]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

Running `sudo eopkg it -c system.utils` rerturns an error for unsatisfied dependency:

`system error. Program terminated.
haskell-primitive release >= 7 dependency of package vgrep is not satisfied`

### Steps to reproduce

1. run `sudo eopkg it -c system.utils`
2. Try installing vgrep by itself - just to be sure

### Expected result

system.utils is installed

### Actual result

Run with debug flag:

`Traceback:
  File "/usr/bin/eopkg", line 78, in <module>
    cli.run_command()
  File "/usr/lib/python2.7/site-packages/pisi/cli/pisicli.py", line 138, in run_command
    self.command.run()
  File "/usr/lib/python2.7/site-packages/pisi/cli/install.py", line 109, in run
    pisi.api.install(packages, ctx.get_option('reinstall') or reinstall)
  File "/usr/lib/python2.7/site-packages/pisi/api.py", line 65, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python2.7/site-packages/pisi/api.py", line 449, in install
    return pisi.operations.install.install_pkg_names(packages, reinstall)
  File "/usr/lib/python2.7/site-packages/pisi/operations/install.py", line 57, in install_pkg_names
    G_f, order = plan_install_pkg_names(A)
  File "/usr/lib/python2.7/site-packages/pisi/operations/install.py", line 299, in plan_install_pkg_names
    raise Exception(_('%s dependency of package %s is not satisfied') % (dep, pkg.name))`

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Plasma

### System details

System:
  Host: solus Kernel: 6.6.21-280.current arch: x86_64 bits: 64
  Desktop: KDE Plasma v: 5.27.10 Distro: Solus 4.5 resilience
Machine:
  Type: Laptop System: Dell product: Inspiron 16 5635 v: 1.3.0
    serial: <superuser required>
  Mobo: Dell model: 0C7J35 v: A00 serial: <superuser required> UEFI: Dell
    v: 1.3.0 date: 04/11/2023
Battery:
  ID-1: BAT0 charge: 54.4 Wh (100.0%) condition: 54.4/54.0 Wh (100.7%)
CPU:
  Info: 8-core AMD Ryzen 7 7730U with Radeon Graphics [MT MCP] speed (MHz):
    avg: 598 min/max: 400/4546
Graphics:
  Device-1: AMD Barcelo driver: amdgpu v: kernel
  Device-2: Microdia Integrated_Webcam_FHD driver: uvcvideo type: USB
  Display: x11 server: X.Org v: 21.1.11 with: Xwayland v: 23.2.4 driver:
    gpu: amdgpu resolution: 2560x1600~120Hz
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 24.0.2 renderer: AMD
    Radeon Graphics (radeonsi renoir LLVM 16.0.6 DRM 3.54 6.6.21-280.current)
Network:
  Device-1: Intel Wi-Fi 6E AX210/AX1675 2x2 [Typhoon Peak] driver: iwlwifi
Drives:
  Local Storage: total: 953.87 GiB used: 9.74 GiB (1.0%)
Info:
  Memory: total: 16 GiB note: est. available: 14.91 GiB used: 4.01 GiB (26.9%)
  Processes: 353 Uptime: 57m Shell: Bash inxi: 3.3.33

**Comment by davidjharder** [comment]
Hi Brendan, what are you trying to use `system.utilts` for?

**Comment by diagnostics0** [comment]
Helping to follow up with this Reddit post: https://www.reddit.com/r/SolusProject/comments/1bgz8bz/error_on_installing_systemutils/

**Comment by davidjharder** [comment]
Thanks for the context.

Although it's not stated anywhere, the advice for installing whole components *other* than the ones mentioned in our docs (`system.devel`, the various desktop specific one like `desktop.xfce`) is "Don't" Still, this is a valid bug I think.

**Comment by ReillyBrogan** [comment]
b3a3fc2fc60e3131254da070011a651caf8dce9e
