### ISSUE TITLE
GHCi randomly SIGABRT/SIGSEV (Cannot allocate memory) (T10540)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#192]
<div dir="rtl"><b>Gavin&nbsp;Zhao</b>&nbsp;(<em>@GZGavinZhao</em>),&nbsp;2023-05-23&nbsp;01:15:16&nbsp;UTC</div><br/>

I haven't found a way to reliably reproduce this. Sometimes you get this immediately after you invoke `ghci`, sometimes you get this after feeding `ghci` a few statements. Usually, try invoking and Ctrl+D exiting `ghci` several times, and you'll get a error like below:
```
gavinzhao&#35;solus ~> /usr/bin/ghci
GHCi, version 8.6.5: http://www.haskell.org/ghc/  :? for help
ghc: mmap 131072 bytes at (nil): Cannot allocate memory
ghc: Try specifying an address with +RTS -xm<addr> -RTS
ghc: internal error: m32_allocator_init: Failed to map
    (GHC version 8.6.5 for x86_64_unknown_linux)
    Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug
fish: Job 1, '/usr/bin/ghci' terminated by signal SIGABRT (Abort)
```
I tried the official binaries provided by `ghcup`, and I get a similar error, so I think it's not on our fault:
```
gavinzhao&#35;solus ~> ghci
GHCi, version 9.2.7: https://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /home/gavinzhao/.ghci
ghc: mmap 4096 bytes at (nil): Cannot allocate memory
ghc: Try specifying an address with +RTS -xm<addr> -RTS
fish: Job 1, 'ghci' terminated by signal SIGSEGV (Address boundary error)
```

cc &#35;liontiger23. Maybe we need [this](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/4497) patch stemming from [this](https://gitlab.haskell.org/ghc/ghc/-/issues/19421) issue? What confuses me is that I never recall this appearing until recently, but if it is indeed the same problem outlined in the patch I should've encountered this multiple times in the past few months.

[Backported patches](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/6288) worth considering when updating to 8.10, which includes this patch.

**Comment by GZGavinZhao** [comment]
This is no longer an issue.
