### ISSUE TITLE
Tenacity

### ISSUE THREAD

**Issue by 3knight** [getsolus/packages#1920]
### Please confirm there isn't an existing package request

- [X] I have searched through package requests

### Homepage

https://tenacityaudio.org/

### Maintainer

- [ ] Would you like to be the maintainer for this package?

### Why should this be included in the repository?

"Our project initially started as a fork of [Audacity](https://audacityteam.org/) as a result of multiple controversies and public relation crises, which you can find out more about here:

[Privacy policy which may violate the original project's GPL license](https://github.com/audacity/audacity/issues/1213)
[Contributor's License Agreement (CLA) which may violate the same GPL license](https://github.com/audacity/audacity/discussions/932)
[Attempts at adding telemetry using Google services for data collection](https://github.com/audacity/audacity/pull/835)

Nevertheless, the goal of this project is to pick up what the original developers of Audacity the decades-long work by the original creators of Audacity and create an audio editor that is fresh, more modern, convenient and practical to use, with the help and the guidance of our users and our community."

### Are we allowed to redistribute it?

GNU General Public License; see LICENSE.txt

### What kind of user will use this package, and how many users do you think will use this package?

Audio editors, Audacity users

### Link to source archive file

https://codeberg.org/tenacityteam/tenacity/archive/v1.3.3.tar.gz

**Comment by davidjharder** [comment]
It's still way too early to consider Tenacity as a replacement for Audacity, even if I buy the arguments for it We would need to maintain two packages that are almost-but-not-quite identical. 

I'm going to close this. We may reconsider in future if this fork gains more users, or if someone really passionate about it will commit to maintaining it.

**Comment by davidjharder** [comment]
Additional note: our Audacity package disables the various telemetry features. See [here](https://github.com/getsolus/packages/blob/b8a95e2f15c44636b988b48300b8c67bba55ecc9/packages/a/audacity/package.yml#L47)
