### ISSUE TITLE
activate-linux

### ISSUE THREAD

**Issue by davidjharder** [getsolus/packages#1923]
### Please confirm there isn't an existing package request

- [X] I have searched through package requests

### Homepage

https://github.com/MrGlockenspiel/activate-linux

### Maintainer

- [X] Would you like to be the maintainer for this package?

### Why should this be included in the repository?

Will remind users running both Wayland and Xorg to activate their installations.

### Are we allowed to redistribute it?

GPL-3.0

### What kind of user will use this package, and how many users do you think will use this package?

I think all solus users could benefit.

### Link to source archive file

https://github.com/MrGlockenspiel/activate-linux/archive/refs/tags/v1.1.0.tar.gz

**Comment by malfisya** [comment]
> I think all solus users could benefit.

Yeah, we could. (Really david?)😆

**Comment by silkeh** [comment]
> I have searched through package requests

Making use of the fact that we're no longer [on Phab](https://phab.getsol.us/T10534) are we?

**Comment by androidnisse** [comment]
@davidjharder Do you want to package this or would it be OK for you if I did?

**Comment by davidjharder** [comment]
You certainly can
