### ISSUE TITLE
vscode: bug: dialog windows open behind main window on Plasma6

### ISSUE THREAD

**Issue by TraceyC77** [getsolus/packages#1925]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

When a dialog opens in VS Code, it is behind the main window rather than in front

### Steps to reproduce

1. Start VS Code
2. Trigger any dialog such as File - Open

### Expected result

The dialog window is on top of all other windows

### Actual result

The dialog window is behind VS Code

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

Plasma

### System details

Operating System: Solus 4.5
KDE Plasma Version: 6.0.2
KDE Frameworks Version: 6.0.0
Qt Version: 6.6.2
Kernel Version: 6.6.21-280.current (64-bit)
Graphics Platform: X11
Processors: 16 × 11th Gen Intel® Core™ i7-11800H @ 2.30GHz
Memory: 62.5 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2
Manufacturer: Dell Inc.
Product Name: XPS 17 9710

### Other comments

This had been patched for QT5. I can't find an issue or PR for it.

**Comment by ermo** [comment]
@TraceyC77 Does this still happen? If it does, re-assign to @ReillyBrogan whom I think may know the solution.

**Comment by TraceyC77** [comment]
I just re-tested and this bug no longer happens. Dialog windows open in front of the active windows, even when VS Code is maximized.
