### ISSUE TITLE
ryujinx (was: suyu)

### ISSUE THREAD

**Issue by infinitymdm** [getsolus/packages#1947]
### Please confirm there isn't an existing package request

- [X] I have searched through package requests

### Homepage

https://suyu.dev/

### Maintainer

- [X] Would you like to be the maintainer for this package?

### Why should this be included in the repository?

Replaces yuzu

### Are we allowed to redistribute it?

GPL-3.0-or-later

### What kind of user will use this package, and how many users do you think will use this package?

Anyone who previously used yuzu

### Link to source archive file

https://git.suyu.dev/suyu/suyu/archive/v0.0.1.tar.gz

**Comment by malfisya** [comment]
Too soon https://www.gamingonlinux.com/2024/03/gitlab-takes-down-nintendo-switch-emulator-suyu-due-to-the-dmca/. Better let it sit for a while ? It is not like `yuzu` is broken, isn't it?

**Comment by infinitymdm** [comment]
Actually they just DMCA'd gitlab. As you might notice, I linked to suyu's own git instance at https://git.suyu.dev.

**Comment by malfisya** [comment]
Yes, i just realized that. Also a few things : 
1. `yuzu` might become a problem, if it needs a rebuild against its dependency. Maybe just point the source to `suyu`, but might as well add `suyu` then.
2. `suyu` is still in its infancy and it is still looking for more devs (also your link to source seems broken?).
3. I am still in the opinion to hold off, until yuzu is broken. I see a few distro are already pull it down from their repo tho.

**Comment by infinitymdm** [comment]
Yeah, my main concern is that yuzu will stop being viable soon once dependencies are updated. Trying to get ahead of that. I've already built and tested it - it's mostly a drop-in replacement for yuzu, with just a little more setup since you have to provide your own firmware and everything. 

As for the link to source, looks like they went and changed their tags 🤦‍♂️

**Comment by EbonJaeger** [comment]
Given how this is all playing out, I would be a bit (a lot, actually) hesitant to have any Nintendo emulator in the repo. Certainly not until we see what distros with lawyers do in response.

**Comment by malfisya** [comment]
Fair point. We just added melonDS, lol.

**Comment by infinitymdm** [comment]
I definitely understand the need for caution here. But recall that yuzu settled with Nintendo; there has been no new precedent passed down from any court. In my opinion (disclaimer: not a lawyer, this is not legal advice, et cetera) things should be business as usual in the emulation world.

As I said though, I definitely understand the need for caution. Waiting to see how things play out with other distros seems like a very reasonable path forward.

**Comment by TraceyC77** [comment]
Agreed with letting this sit until we see what other distros with lawyers do. I'm not so worried about Solus getting sued (the most I'd expect is a DMCA takedown request). I'd be concerned that with so many packages already needing maintainers and updates, if we add a new package that we then have to take down, it's a lot of unnecessary work. That work is better spent right now on maintaining what we have.

**Comment by malfisya** [comment]
@infinitymdm do you have package.yml for this? If not too bothersome, can you share it with me?

**Comment by infinitymdm** [comment]
> @infinitymdm do you have package.yml for this? If not too bothersome, can you share it with me?

Here you go: https://github.com/infinitymdm/packages/blob/add_suyu/packages%2Fs%2Fsuyu%2Fpackage.yml

**Comment by infinitymdm** [comment]
At this stage I'm not super confident in suyu as a yuzu replacement - their dev branch hasn't seen a single commit in a month. Ryujinx is probably a more viable alternative.

**Comment by malfisya** [comment]
If it is ryujinx (which I am fine with), then it is not exactly a replacement for yuzu but completely new package. I should try the flatpak first and see if I like it. It is a shame suyu doesn't become a viable fork.

**Comment by ReillyBrogan** [comment]
> Edit: Oh, ryunjinx is using dotnet, lucky we got that updated and have a person with experience with it. Still looks like will be a pain writing the recipe.

Luckily I had a completely working package.yml just sitting in my private repo.
