### ISSUE TITLE
OOM Killer never kick-in (T7226)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#195]
<div dir="rtl"><b>Yurizal&nbsp;Susanto</b>&nbsp;(<em>&#35;yursan9</em>),&nbsp;2018-11-21&nbsp;07:39:13&nbsp;UTC</div><br/>

I have small device, 2 GB of RAM, that I use daily. I like to browse website and take lecture notes using that small laptop. Whenever the primary memory get full (usually from Browser usage), it's always lock up, and I can't do anything, even accessing the TTY is a no go.

**Comment by Justinzobel** [comment]
Can confirm OOM killer does work, happened to me the other day.
