### ISSUE TITLE
signal-desktop

### ISSUE THREAD

**Issue by kmarud** [getsolus/packages#1962]
### Please confirm there isn't already an existing package update request

- [X] I have searched through package update requests

### Name

signal-desktop

### Version

v7.3.1

### Link to the release notes or announcement.

https://github.com/signalapp/Signal-Desktop/releases/tag/v7.3.1

### Reason for updating

Current version is 6.44.1, which is one major version behind.

**Comment by HarveyDevel** [comment]
Updating this package is currently blocked due to an issue with our package history for `signal-desktop`

**Comment by algent-al** [comment]
Resolved with https://github.com/getsolus/packages/commit/c9c667b8181fea168bd248051e10114770aaf4c7

**Comment by joebonrichie** [comment]
Had to pull from index as eopkg is still py2 and can't parse the emoji in the commit log for this package. As ypkg is now py3 you can now successfully build this package. We're working on a fix in solbuild now to strip emojis from commit logs so python2 tooling won't choke on it.

**Comment by silkeh** [comment]
The emoji encoding issues are now (mostly) fixed via  #2098 and https://github.com/getsolus/ferryd/pull/27. Signal Desktop 7.3.1 is now available in unstable and will be included in the next sync!
