### ISSUE TITLE
Packaging rest of the ROCm stack (T10310)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#197]
<div dir="rtl"><b>Jacek&nbsp;Jagosz</b>&nbsp;(<em>&#35;Jacek</em>),&nbsp;2022-07-12&nbsp;10:03:31&nbsp;UTC</div><br/>

Now that T6614 is mostly complete Solus should soon hae OpenCL support on AMD as well as the base HIP package. But this is not enough for most programs that support AMD GPU acceleration using ROCm to work. Here is an incomplete list of packages that could make use of ROCm and necessary dependencies:

## Locally
See the [rocm-5.5.x](https://github.com/GZGavinZhao/packages/tree/rocm-5.5) branch.
- [x] hipify
- [x] rocBLAS
- [x] hipBLAS
- [x] rocFFT
- [x] hipFFT
- [x] rocPRIM
- [x] hipCUB
- [x] rocRAND
- [x] hipRAND
- [x] rocSPARSE
- [x] hipSPARSE
- [x] rocSOLVER
- [x] hipSOLVER
- [x] hipmagma
- [x] miopen
- [x] rccl
- [x] amd-aql-profile
- [x] rocprofiler
- [x] roctracer
- [x] PyTorch
- [x] torchvision
- [ ] torchaudio
- [x] Blender
- [ ] Tensorflow

## Submitted
- [x] hipify
- [x] rocBLAS
- [x] hipBLAS
- [x] rocFFT
- [x] hipFFT
- [x] rocPRIM
- [x] hipCUB
- [x] rocRAND
- [x] hipRAND
- [x] rocSPARSE
- [x] hipSPARSE
- [x] rocSOLVER
- [x] hipSOLVER
- [x] hipmagma
- [x] miopen
- [x] rccl
- [x] amd-aql-profile
- [x] rocprofiler
- [x] roctracer
- [x] PyTorch
- [x] torchvision
- [ ] torchaudio
- [x] Blender ~~(turn off GPU Subdivision if you're getting crashes; this is a separate issue from ROCm that we're investigating)~~ this issue has been fixed
- [ ] Tensorflow

[Here is my repository where I gather all I do with ROCm stack](https://github.com/JacekJagosz/rocm-Solus/blob/main/rocblas/package.yml), including WIP packages. Another one by @GZGavinZhao is [here](https://github.com/GZGavinZhao/solus-rocm).
All help with packaging and testing is welcome, as well as ideas on useful packages.
Also, all packages dependent on HIP seem to have spotty GPU support and take a lot of time to compile, because there is a separate kernel generated for each supported GPU.

**Comment by davidjharder** [comment]
Hey @GZGavinZhao can you take a look at this. 
I ticked off Blender

**Comment by TraceyC77** [comment]
@GZGavinZhao  & @joebonrichie , what's the status of this? Can we get this wrapped up for 4.7?

**Comment by infinitymdm** [comment]
I was tinkering with trying to build the ROCm version of TF just today (not that I made any real progress). What are the blockers on that?

**Comment by TraceyC77** [comment]
Thanks for the update, Gavin. I'm closing out the issue as completed.

Marcus, please reach out via Matrix in our packaging room or open a new issue. Thanks.
