### ISSUE TITLE
eglinfo crashes with SIGABRT (T10558)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#199]
<div dir="rtl"><b>TraceyC</b>&nbsp;(<em>@TraceyC77</em>),&nbsp;2023-06-17&nbsp;01:08:09&nbsp;UTC</div><br/>

# Summary 
When running eglinfo it crashes

...

## Steps to reproduce

In terminal run `eglinfo`

## Expected result

All information is reported

## Actual result

The output ends with this:

```
    EGL_NV_stream_socket_unix, EGL_NV_stream_sync, EGL_NV_system_time, 
    EGL_NV_triple_buffer, EGL_WL_bind_wayland_display, 
    EGL_WL_wayland_eglstream
corrupted size vs. prev_size
fish: Job 1, 'eglinfo' terminated by signal SIGABRT (Abort)
```

## Environment

  - Is system up to date? y
  - Repo: unstable  
  - Desktop Environment: Plasma 

## System details

Operating System: Solus 4.4
KDE Plasma Version: 5.27.5
KDE Frameworks Version: 5.106.0
Qt Version: 5.15.9
Kernel Version: 6.3.6-239.current (64-bit)
Graphics Platform: X11
Processors: 16 × 11th Gen Intel® Core™ i7-11800H @ 2.30GHz
Memory: 62.5 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2
Manufacturer: Dell Inc.
Product Name: XPS 17 9710

## Other comments 

This is related to testing VA-API and Firefox, so we can test the version of GLES on the system. T10532, T10440, T10554

**Comment by Justinzobel** [comment]
@TraceyC77 this still happening? I can run eglinfo fine on current unstable.

**Comment by joebonrichie** [comment]
Hmm this may be why you can't login to wayland session an longer tracey, egl borked with the nvidia driver?

**Comment by TraceyC77** [comment]
eglinfo now runs properly, all output shown, no errors

@joebonrichie I don't have a problem logging into a Wayland session. I can login fine. It warns about doing software rendering. With external monitors attached it is too laggy to be usable

xeglgears crashes
```
❯ xeglgears                                                                                                                                          ✘ 2
fish: Job 1, 'xeglgears' terminated by signal SIGSEGV (Address boundary error)
```

Currently have these installed
```
nvidia-glx-driver-current, version: 535.154.05, release: 505
nvidia-vaapi-driver, version: 0.0.11, release: 14
```

I'll open a separate issue for xeglgears

**Comment by TraceyC77** [comment]
There is an [upstream issue](https://gitlab.freedesktop.org/mesa/mesa/-/issues/10513) for xeglgears.
