### ISSUE TITLE
Steam game issues related to missing libraries  (T4961)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#2]
<div dir="rtl"><b>cody</b>&nbsp;(<em>&#35;codythedragondude</em>),&nbsp;2017-11-05&nbsp;06:52:00&nbsp;UTC</div><br/>

Painkiller hell and damnation gives 

error while loading shared libraries: libGLEW.so.1.6: cannot open shared object file: No such file or directory

Overlord 2 gives

error while loading shared libraries: libopenal-soft.so.1: cannot open shared object file: No such file or directory

**Comment by davidjharder** [comment]
Old, closing
