### ISSUE TITLE
Fan at full speed after sleep (T4403)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#20]
<div dir="rtl"><b>Please&nbsp;delete&nbsp;my&nbsp;account</b>&nbsp;(<em>&#35;n5332</em>),&nbsp;2017-08-27&nbsp;09:01:32&nbsp;UTC</div><br/>

The fan of my Thinkpad X1 Carbon (4th gen) are at full speed after sleep. This occurs if I let my laptop on sleep for some times (this doesn't kick right away, it's after 10 minutes). 

I'll join any log you might need (I don't really know which one are important)

**Comment by davidjharder** [comment]
Old. Closing
