### ISSUE TITLE
Update firejail to 0.9.68 (T10164)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#200]
<div dir="rtl"><b>Marshall</b>&nbsp;(<em>&#35;Marshallishere</em>),&nbsp;2022-02-13&nbsp;14:32:01&nbsp;UTC</div><br/>

A lot of bugfixes and new features, and some removals. As it is a sandboxing software it's important to keep it up-to-date.

Source: https://sourceforge.net/projects/firejail/files/firejail/firejail-0.9.68.tar.xz/download

**Comment by androidnisse** [comment]
There is an pull request for this now https://github.com/getsolus/packages/pull/2254
