### ISSUE TITLE
libadwaita update to 1.5.0

### ISSUE THREAD

**Issue by androidnisse** [getsolus/packages#2002]
### Please confirm there isn't already an existing package update request

- [X] I have searched through package update requests

### Name

libadwaita

### Version

1.5.0

### Reason for updating

I'm trying to update tuba but it needs libadwaita 1.5.0

**Comment by joebonrichie** [comment]
Part of https://github.com/getsolus/packages/pull/1950

Waiting for GNOME 46.1 before landing, please don't create any related requests unless i've missed them in that PR.

**Comment by malfisya** [comment]
Already done by https://github.com/getsolus/packages/commit/7bf25fdb3a35e7264816123fdc4831a14df324e9
