### ISSUE TITLE
Plasma 6 SDDM: selected theme not used

### ISSUE THREAD

**Issue by TraceyC77** [getsolus/packages#2040]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

The login screen (SDDM) does not use the theme selected in settings
sddm-kcm
It uses some default theme that does not appear in the settings screen

### Steps to reproduce

1. In Login Screen (SDDM) select a custom theme and apply
2. Log out to get back to the login screen

### Expected result

The login screen has the theme selected in SDDM settings

### Actual result

The theme shown does not match anything shown in SDDM settings

![20240330_145351](https://github.com/getsolus/packages/assets/10402612/7291abdf-fee4-43c8-99b2-a8c638a4a967)

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

Plasma

### System details

Operating System: Solus 4.5
KDE Plasma Version: 6.0.3
KDE Frameworks Version: 6.0.0
Qt Version: 6.6.3
Kernel Version: 6.6.22-281.current (64-bit)
Graphics Platform: X11
Processors: 16 × 11th Gen Intel® Core™ i7-11800H @ 2.30GHz
Memory: 62.5 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2
Manufacturer: Dell Inc.
Product Name: XPS 17 9710

### Other comments

I did a pretty thorough search but couldn't find an upstream bug that looked related.

On my system, I had the Dexy-SDDM theme selected prior to the update. I switched to a different theme, and then back to this one. No matter what I choose, the login screen looks the same.
Might our custom settings locations due to stateless configs be related?

SDDM themes set their background via "theme.conf" in  /usr/share/sddm/themes/<theme>
If the user has customized the background its in theme.conf.user

In my case, with Dexy-SDDM

```bash
/usr/share/sddm/themes/Dexy-SDDM # cat theme.conf
[General]
type=image
color=#d1d5e9
highlight_color=#d1d5e9
selected_color=#7580bc
selected_fg_color=#d1d5e9
fontSize=12.0
Background="background.png"
font="Noto Sans"

/usr/share/sddm/themes/Dexy-SDDM # cat theme.conf.user
[General]
type=image
```

The file background.png has the expected background
I don't see anything in the cli output that looks like a problem:

```bash
~ ❯❯❯ kcmshell6 kcm_sddm
qt.qml.typeresolution.cycle: Cyclic dependency detected between "qrc:/qt/qml/org/kde/desktop/private/TextFieldContextMenu.qml" and "qrc:/qt/qml/org/kde/desktop/MenuItem.qml"
qrc:/kcm/kcm_sddm/main.qml:161:5: QML OverlaySheet: Binding loop detected for property "implicitHeight"
qrc:/kcm/kcm_sddm/main.qml:131:5: QML OverlaySheet: Binding loop detected for property "implicitHeight"
qrc:/kcm/kcm_sddm/main.qml:128:5: QML DetailsDialog: Binding loop detected for property "implicitHeight"
qrc:/kcm/kcm_sddm/main.qml:128:5: QML DetailsDialog: Binding loop detected for property "implicitHeight"
qrc:/kcm/kcm_sddm/main.qml:176:13: QML QQuickImage*: Protocol "" is unknown
qrc:/kcm/kcm_sddm/main.qml:161:5: QML OverlaySheet: Binding loop detected for property "implicitHeight"
```

 sddm's home dir (/var/lib/sddm by default)

**Comment by TraceyC77** [comment]
Another user [reported the same issue in the forums](https://discuss.getsol.us/d/10470-plasma-6-megathread/11)

**Comment by andiskufi** [comment]
### **System details:**
Operating System: Solus 4.5
KDE Plasma Version: 6.0.3
KDE Frameworks Version: 6.0.0
Qt Version: 6.6.3
Kernel Version: 6.6.22-281.current (64-bit)
Graphics Platform: X11
CPU: AMD Ryzen 7 5800X (16) @ 3.800GHz 
GPU: AMD ATI Radeon RX 6700 XT
Memory: 16 GiB of RAM

### **Repo**

Unstable

I reported the same issue in the forums and thought it might be helpful to write my system details as well.
