### ISSUE TITLE
unittest-cpp is not activley maintained 

### ISSUE THREAD

**Issue by androidnisse** [getsolus/packages#2045]
### Please confirm there isn't already an existing package update request

- [X] I have searched through package update requests

### Name

unittest-cpp

### Link to the release notes or announcement.

https://github.com/unittest-cpp/unittest-cpp/issues/180

### Reason for updating

The software has been on a pause since 2020.

**Comment by EbonJaeger** [comment]
As far as I can tell, the only package depending on `unittest-cpp` is `libopenshot`. Luckily, they migrated to Catch2 in 2021, so I've opened a PR to switch the framework in use in our package.
