### ISSUE TITLE
Marknote

### ISSUE THREAD

**Issue by TraceyC77** [getsolus/packages#2051]
### Please confirm there isn't an existing package request

- [X] I have searched through package requests

### Homepage

https://apps.kde.org/marknote/

### Maintainer

- [X] Would you like to be the maintainer for this package?

### Why should this be included in the repository?

While we have other applications for Markdown notes, this one offers advantages the others don''t.
- WYSIWYG editor (inline preview)
- Supports organizing notes into Notebooks

### Are we allowed to redistribute it?

GPL-2.0-or-later

### What kind of user will use this package, and how many users do you think will use this package?

People who keep notes in Markdown.
People using an Electron based markdown editor looking for a non-Electron alternative (e.g. the popular Obsidian app)

Source code: https://invent.kde.org/office/marknote

### Link to source archive file

https://invent.kde.org/office/marknote/-/archive/v1.0.0/marknote-v1.0.0.tar.bz2

**Comment by joebonrichie** [comment]
Not yet part of kde gear but i assume it will be in due time
