### ISSUE TITLE
Update helix editor

### ISSUE THREAD

**Issue by davidjharder** [getsolus/packages#2053]
### Please confirm there isn't already an existing package update request

- [X] I have searched through package update requests

### Name

helix

### Version

2024.03

### Link to the release notes or announcement.

https://github.com/helix-editor/helix/blob/master/CHANGELOG.md#2403-2024-03-30

### Reason for updating

Ping @maveonair

**Comment by maveonair** [comment]
Hey, I am unfortunately don’t have a Solus machine anymore since I moved completely back to Mac :(. Can someone take this over?

**Comment by davidjharder** [comment]
Not a problem. Thanks for responding
