### ISSUE TITLE
Initramfs missing mdadm (T5596)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#206]
<div dir="rtl"><b>oO.o</b>&nbsp;(<em>&#35;dotdigital-digital</em>),&nbsp;2018-01-20&nbsp;18:21:13&nbsp;UTC</div><br/>

I am migrating my Solus installation from the default MBR installation to GPT/EFI/MD/LUKS/LVM.

I believe I have completed all of the steps properly, but I am missing md support in the initramfs. I am able to boot into initram via UEFI, but dracut times out saying it can't find my disks. All the UUID's are correct, but the MD mirror isn't assembled. No mdadm.

My /boot partition was generated from the live usb via chroot using CBM v1.5.5 (I ran eopkg up before running CBM).

Should there be an md/raid option in /boot/loaders/entries/Solus-current-4.14.13-46.conf?

Not sure where to go from here.

**Comment by ReillyBrogan** [comment]
This is old, and while not yet resolved there doesn't appear to have been any additional demand for this.
