### ISSUE TITLE
gocode

### ISSUE THREAD

**Issue by androidnisse** [getsolus/packages#2070]
### Please confirm there isn't an existing package request

- [X] I have searched through package requests

### Homepage

https://github.com/visualfc/gocode

### Maintainer

- [X] Would you like to be the maintainer for this package?

### Why should this be included in the repository?

Golang autocomplete for LiteIDE.

### Are we allowed to redistribute it?

MIT

### What kind of user will use this package, and how many users do you think will use this package?

Users of LiteIDE.

### Link to source archive file

https://github.com/visualfc/gocode/archive/refs/tags/v1.5.2.tar.gz

**Comment by silkeh** [comment]
Thanks for the request! The latest release (and commit) is over a year ago, is this still actively maintained?

**Comment by androidnisse** [comment]
> Thanks for the request! The latest release (and commit) is over a year ago, is this still actively maintained?

I would guess it is. This is developed by the same authors of LiteIDE. That one is maintained and when you start it, it says this one is not installed. So can't say for 100% but the author is active on the other project.
