### ISSUE TITLE
`serif` font family defaults to `Clear Sans` instead of a serif font (T8739)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#208]
<div dir="rtl"><b>Nathan&nbsp;Caldwell</b>&nbsp;(<em>&#35;saintdev</em>),&nbsp;2020-02-16&nbsp;06:40:49&nbsp;UTC</div><br/>

Fontconfig selects `Clear Sans` as the default serif font.

```
$ fc-match serif
ClearSans-Regular.ttf: "Clear Sans" "Regular"
```

This seems to be caused by a misconfiguration in fontconfig

`/usr/share/fontconfig/conf.avail/60-latin.conf:`
```lang=xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <its:rules xmlns:its="http://www.w3.org/2005/11/its" version="1.0">
    <its:translateRule translate="no" selector="/fontconfig/*[not(self::description)]"/>
  </its:rules>

  <description>Set preferable fonts for Latin</description>
	<alias>
		<family>serif</family>
		<prefer>
			<family>Clear Sans</family>
[...snip...]
```

Additionally, the default `sans-serif` family font is also `Clear Sans` instead of `Noto Sans`.
```
$ fc-match sans-serif
ClearSans-Regular.ttf: "Clear Sans" "Regular"
```

**Comment by EbonJaeger** [comment]
Budgie edition now uses full Noto Sans for fonts (except monospace) as of https://github.com/solus-packages/budgie-desktop-branding/commit/95433316889a7da3104d20b1c0c771eeffdb0a4d

**Comment by ermo** [comment]
We have agreed to switch the default to Noto Sans and Noto Serif.

Update branding packages accordding @ZachBacon @ReillyBrogan @joebonrichie

**Comment by TraceyC77** [comment]
I've created subtasks so the different branding packages can be worked on independently. This task can be marked done when all branding has been updated.
