### ISSUE TITLE
Convert py2 scripts in common/ to py3

### ISSUE THREAD

**Issue by ermo** [getsolus/packages#2091]
As part of #270 and the landing of #1526 , we need to begin the process of porting existing py2 scripts in `common/` to py3 to be able to complete the migration off of py2.

As part of this porting effort, please remember to run the script you are porting through the `black` [python formatter tool](https://black.readthedocs.io/en/stable/index.html) (similar in scope to `gofmt` for Go code).

**NB:** These scripts need to depend on `python-eopkg` instead of `pisi`, as `python-eopkg` contains the non-nuitka-compiled ported py3 scripts and libraries necessary for things to work.

Status:
- [x] `Scripts/dloader.py`
- [x] `Scripts/epcsearch.py`
- [x] `Scripts/ep-update.py`
- [x] `Scripts/find_deps.py`
- [x] `Scripts/gettag.py`
- [x] `Scripts/latent-rebuilds.py`
- [x] `Scripts/pbump.py`
- [x] `Scripts/yauto.py`
- [x] `Scripts/yconvert.py`
- [x] `Legacy/Scripts/dep_check.py`
- [x] `Legacy/Scripts/find-old-packages.py`

----

This is the current list:

    ermo@solbox:~/repos/getsolus/soluspkgs/common [python-eopkg* +7 ~4 -0 !]
    $ rg '/usr/bin/env python' |grep -v python3 |sort
    Legacy/Scripts/dep_check.py:#!/usr/bin/env python
    Legacy/Scripts/find-old-packages.py:#!/usr/bin/env python2.7
    Scripts/dloader.py:#!/usr/bin/env python
    Scripts/epcsearch.py:#!/usr/bin/env python
    Scripts/ep-update.py:#!/usr/bin/env python
    Scripts/find_deps.py:#!/usr/bin/env python2
    Scripts/gettag.py:#!/usr/bin/env python
    Scripts/latent-rebuilds.py:#!/usr/bin/env python2.7
    Scripts/pbump.py:#!/usr/bin/env python
    Scripts/yauto.py:#!/usr/bin/env python
    Scripts/yconvert.py:#!/usr/bin/env python

**Comment by livingsilver94** [comment]
Everybody please commit your edits in this branch https://github.com/getsolus/packages/tree/common-to-py3 with one commit per script. We'll squash them if you don't like having multiple commits, but for the sake of the PR review I think multiple commits are clearer.
