### ISSUE TITLE
vscode: installs extensions from marketplace to ~/.vscode but cannot use them

### ISSUE THREAD

**Issue by mark-nicholson** [getsolus/packages#2094]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

VSCode package mostly works, but when I use its extension installer, they install to the correct location, but the application is unable to use them.

### Steps to reproduce

1. Clear out any existing VSCode crumbs
`rm -rf ~/.vscode ~/.config/Code`
2. Launch VSCode from the menu or `/usr/bin/code`
3. Go to the extension manager and install `remote-ssh`  (hugely popular)
4. Press `F1` to get to the command selector
5. type:  `remote-ssh` and it will start to filter the available tools (all the ones with the prefix of `Remote-SSH` tie back to the extension)
6. Select `Connect to host`
7. You get an error message dialog box:
`Command 'Remote-SSH: Connect to host ...' resulted in an error`
`command 'opesshremotes.openEmptyWindow not found`

### Expected result

When I directlydownload the vscode "tarball" from the website -- I unpacked it (as root) to `/usr/test/vscode` and ran _exactly_ the same steps and it works properly.

You _should_ see  a list of hosts (appear to be snooped from `~/.ssh/config`)  and you can click on the hostname to connect remotely via SSH to that.

### Actual result

There is an error instead of a list of hosts appearing.

![image](https://github.com/getsolus/packages/assets/5815500/b7a6fd7c-13a1-4764-ad0e-418a6c8145d5)

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Budgie

### System details

System:
  Host: milliways Kernel: 6.6.22-281.current arch: x86_64 bits: 64
  Desktop: Budgie v: 10.9.1 Distro: Solus 4.5 resilience
Machine:
  Type: Laptop System: Dynabook product: PORTEGE X40-J v: PPH13U-061002E1
    serial: Z1057589H
  Mobo: Dynabook model: A010D/0000 v: Version A0 serial: C0467619F01YV0FH
    UEFI: Dynabook v: Version 6.30 date: 10/18/2021
Battery:
  ID-1: BAT1 charge: 52.2 Wh (100.0%) condition: 52.2/53.1 Wh (98.3%)
CPU:
  Info: quad core 11th Gen Intel Core i7-1185G7 [MT MCP] speed (MHz): avg: 616
    min/max: 400/4800
Graphics:
  Device-1: Intel TigerLake-LP GT2 [Iris Xe Graphics] driver: i915 v: kernel
  Device-2: Chicony Web Camera - HD driver: uvcvideo type: USB
  Display: x11 server: X.Org v: 21.1.11 with: Xwayland v: 23.2.4 driver: X:
    loaded: modesetting unloaded: fbdev,vesa dri: iris gpu: i915 resolution:
    1: 2560x1440~60Hz 2: 1920x1080~60Hz
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: intel mesa v: 24.0.4
    renderer: Mesa Intel Xe Graphics (TGL GT2)
Network:
  Device-1: Intel Wi-Fi 6 AX201 driver: iwlwifi
  Device-2: Dynabook USB 10/100/1000 LAN driver: cdc_ether type: USB
Drives:
  Local Storage: total: 476.94 GiB used: 220.25 GiB (46.2%)
Info:
  Memory: total: 32 GiB note: est. available: 30.98 GiB used: 9.88 GiB (31.9%)
    igpu: 64 MiB
  Processes: 375 Uptime: 3d 14h 36m Shell: Sudo inxi: 3.3.33

### Other comments

When I did a `diff` between the canonical `/usr/share/vscode` and my tarball extraction at `/usr/test/vscode` there are _tonnes_ of differences. (I was quite surprised at the delta.)

Something was modified/remove improperly to corrupt the installation's ability to _use_ the "personal" extensions, even though the installation support installs them properly.  (I could switch between `/usr/bin/code` and the tarball executable and when the extension was installed by `/usr/bin/code` the extension _worked_ when I ran the tarball executable -- indicating that the extension installation was proper.

**Comment by infinitymdm** [comment]
Could you post a link to where you got your "canonical" vscode tarball? 

My guess is that you're using the Microsoft-distributed Visual Studio Code, which includes non-free elements that Solus cannot include in the package. See the link below for a bit more info: https://opensource.stackexchange.com/questions/4288/is-microsoft-vs-code-really-open-source

**Comment by ReillyBrogan** [comment]
Certain Microsoft vscode extensions use DRM and cannot be used with unofficial builds, and the remote ssh plugin is one of them. I spent a considerable amount of time to try to get it work and was unable, to my knowledge nobody currently has this working with unofficial builds (yes, I'm sure you can find posts out there of people who managed to get them to work but all of those posts are outdated and the workarounds have been broken). Given that there's nothing for us to do here I'm going to go ahead and close this.

**Comment by mark-nicholson** [comment]
I got the tarball here:

https://code.visualstudio.com/download

And under the Penguin, it lists:

.deb
.rpm
.tar.gz
Snap
CLI

and if you click on the "architecture" square, beside `.tar.gz` it will trigger the download of the arch-specific tarball.

https://code.visualstudio.com/sha/download?build=stable&os=linux-x64

which pulls down:

code-stable-x64-1709910909.tar.gz

You can just extract that into a directory and run it.  Even on Solus, it is fully functional and can run the remote-ssh extension (after you install it)

~Mark



________________________________________
