### ISSUE TITLE
Bootloader behaviour broken when EFIVARS stores Goofiboot/SystemD-Boot/Gummitboot default entry (T5128)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#21]
<div dir="rtl"><b>Eric&nbsp;Molitor</b>&nbsp;(<em>&#35;emolitor</em>),&nbsp;2017-11-26&nbsp;09:46:48&nbsp;UTC</div><br/>

GoofiBoot, SystemD-Boot and GummiBoot support a (relatively poorly documented) feature to store a default entry in an EFIVAR by pressing 'D' when in the bootloader menu. When present the EFIVAR default takes precedence over any defaults in loader.conf. Apparently I had accidentally hit 'D' on the autodetected goofiboot entry for the windows bootloader at some point which caused Solus to only boot windows even when selecting Linux Boot Loader in my bios's boot menu. No amount of reinstallation of the bootloader or manipulating the loader.conf can fix this as EFIVAR is cleared. I finally cleared the issue by manually manipulating the efivar via sysfs although adding a timeout to the loader.conf and selecting a new default in the bootloader menu would have been easier.

1) This may be an upstream issue but the hidden commands in GoofiBoot, SystemD-Boot and GummiBoot for debugging (hitting 'P') and setting defaults via EFIVARS (hitting 'D') are poorly documented.
2) I suggest adding an option in loader.conf to ignore any EFIVARS settings or changing the default to prefer any defaults in loader.conf over any entries in EFIVARS (changing the order of precedence may be hard as it risks breaking things)
<del>3) Solus should honor timeouts and/or any other customization made to loader.conf</del> (Just discovered clr-boot-manager timeout option)
4) Just close this as won't fix as I suspect its a pretty odd edge-case. :)

**Comment by davidjharder** [comment]
Remarkably old. Closing
