### ISSUE TITLE
Package request: ttyplot (T10584)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#210]
<div dir="rtl"><b>nazar</b>&nbsp;(<em>&#35;nazar</em>),&nbsp;2023-07-15&nbsp;06:05:22&nbsp;UTC</div><br/>

- ttyplot
- https://github.com/tenox7/ttyplot
- a realtime plotting utility for terminal/console with data input from stdin
- open source, Apache-2.0 license
- https://github.com/tenox7/ttyplot/archive/refs/tags/1.4.tar.gz

**Comment by nazar-stasiv** [comment]
Bumping it

**Comment by silkeh** [comment]
@nazar-stasiv: bumping an issue doesn't really do anything for visibility.

Having said that, this request is approved and I'm looking forward for your PR!
