### ISSUE TITLE
Package request: EPM (T10585)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#211]
<div dir="rtl"><b>Vitaly&nbsp;Lipatov</b>&nbsp;(<em>@vitlav</em>),&nbsp;2023-07-15&nbsp;21:23:22&nbsp;UTC</div><br/>

EPM

https://github.com/Etersoft/eepm

EPM simplify package management for new users (who has an experience with apt/dnf).

AGPL 3.0

https://github.com/Etersoft/eepm/archive/refs/tags/3.58.0.tar.gz

I have tried make the package:
https://github.com/Etersoft/eepm/blob/master/packaging/eepm.yml

**Comment by silkeh** [comment]
Closing this as we generally don't want so support other package managers, even if just as an abstraction.
