### ISSUE TITLE
Update Request: Power Profiles Daemon v0.21

### ISSUE THREAD

**Issue by rav101** [getsolus/packages#2117]
### Please confirm there isn't already an existing package update request

- [X] I have searched through package update requests

### Name

Power Profiles Daemon

### Version

v0.21

### Link to the release notes or announcement.

https://gitlab.freedesktop.org/upower/power-profiles-daemon/-/releases/0.21

### Reason for updating

Provides more power efficient battery consumption on laptops for both intel and AMD based computers.

Changelog:

Since this release power-profiles-daemon is battery-state aware and some drivers
use a more power efficient state when using the balanced profile on battery.
In particular both the AMD and Intel P-State drivers will use the
balance_power EPP profile, while for Intel one we also set the energy
performance bias to 8 (instead of 6).
This release also contains various fixes for the powerprofilesctl command line
tool when using the launch or version commands.
The tool is now better documented as we generate a manual page for it (if
python3-argparse is installed) and bash completions. We're even generating the
ZSH completions, but the install path must be provided.
The daemon command line interface has been improved for debugging, so use
--help-debug for further information.
The systemd service lockdown settings have been restricted even more.
Various code optimizations.

**Comment by davidjharder** [comment]
I see you updated this package last time. If you plan to update it yourself, no need to file an issue
