### ISSUE TITLE
Gnome Screen Sharing - Post 3.38 Stack Upgrade (T9407)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#213]
<div dir="rtl"><b>Saijin_Naib</b>&nbsp;(<em>&#35;Saijin_Naib</em>),&nbsp;2020-11-28&nbsp;02:12:42&nbsp;UTC</div><br/>

If I read/understood the announcement properly, vino (which used to handle the functionality) has been removed and replaced with gnome-remote-desktop to handle this sharing through Mutter.

To that end, I compiled and installed gnome-remote-desktop from source and the Sharing toggle still can't be toggled properly, and the functionality still isn't present.

{F6755981}

Is this something that is planned to be fixed, or is it out of scope? I know that others have had issues in the past when it was vino-based, but it seemed that the issue at the time was upstream.

Thanks.

**Comment by ermo** [comment]
@joebonrichie Does this feature work now?

**Comment by davidjharder** [comment]
This bug is ancient
