### ISSUE TITLE
eopkg-deps is deprecated

### ISSUE THREAD

**Issue by androidnisse** [getsolus/packages#2142]
### Please confirm there isn't already an existing package update request

- [X] I have searched through package update requests

### Name

eopkg-deps

### Link to the release notes or announcement.

https://github.com/datadrake/eopkg-deps

### Reason for updating

The repository has been archived by the owner on Apr 27, 2023.

**Comment by joebonrichie** [comment]
This still has some useful functionality that isn't fulfilled by other eopkg related tooling so I'm not in favour of deprecating it as is.

**Comment by androidnisse** [comment]
> This still has some useful functionality that isn't fulfilled by other eopkg related tooling so I'm not in favour of deprecating it as is.

No problem, I just wanted to add a heads up that it is archived.

**Comment by HarveyDevel** [comment]
Thanks for the report. As it is needed for now, closing.
