### ISSUE TITLE
Update ghc (and the Haskell stack) to 9 (T10289)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#216]
<div dir="rtl"><b>Gavin&nbsp;Zhao</b>&nbsp;(<em>&#35;GZGavinZhao</em>),&nbsp;2022-06-13&nbsp;03:12:55&nbsp;UTC</div><br/>

Rationale: it's been almost 2 years since the last update.

I'd like to help with the stack upgrade.

**Comment by davidjharder** [comment]
@GZGavinZhao you get the honor of closing this one

**Comment by algent-al** [comment]
Resolved by https://github.com/solus-packages/ghc/commit/6ed0f7fabff0ba8cd9dd882a50b5e9efce254dbe
