### ISSUE TITLE
heroic game launcher

### ISSUE THREAD

**Issue by nrroyal19** [getsolus/packages#2170]
### Please confirm there isn't already an existing package update request

- [X] I have searched through package update requests

### Name

HeroicGamesLauncher 

### Version

v2.14.1

### Link to the release notes or announcement.

https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases

### Reason for updating

gaming

**Comment by malfisya** [comment]
Done in https://github.com/getsolus/packages/commit/525cb442825449cd998869589be9dff649bb8df3
