### ISSUE TITLE
Plasma System Monitor weird lines

### ISSUE THREAD

**Issue by joluveba** [getsolus/packages#2171]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

Since I updated to Plasma 6.0.3, I started to see weird lines on the CPU history of the Plasma System Monitor. Please see pic.
![Plasma system monitor weird lines](https://github.com/getsolus/packages/assets/153130348/933d45af-0575-468f-9f4b-9c13cdc9ff31)

### Steps to reproduce

Open the Plasma System Monitor, go to CPU History.

### Expected result

I expect to see the CPU History graphics without any weird lines.

### Actual result

I see weird lines on the CPU history graphics.
![Uploading Plasma system monitor weird lines.jpg…]()

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Plasma

### System details

Operating System: Solus 4.5
KDE Plasma Version: 6.0.3
KDE Frameworks Version: 6.0.0
Qt Version: 6.6.3
Kernel Version: 6.6.22-281.current (64-bit)
Graphics Platform: Wayland
Processors: 4 × Intel® Core™ i5-6400 CPU @ 2.70GHz
Memory: 7.7 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 530
Manufacturer: MSI
Product Name: MS-7994
System Version: 1.0

### Other comments

This bug on the KDE site may be relevant:
https://bugs.kde.org/show_bug.cgi?id=434462
This bug happens on both Wayland and xorg.

**Comment by Justinzobel** [comment]
The linked bug says it's fixed in Frameworks 6.1 which is coming out this week, and I've got the update prepared already. So we'll get you to test this to see if it fixes the issue.

**Comment by ReillyBrogan** [comment]
Should be fixed now
