### ISSUE TITLE
Hide screen record button on PrintScreen menu by default on GNOME (T10572)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#218]
<div dir="rtl"><b>Muhammad&nbsp;Alfi&nbsp;Syahrin</b>&nbsp;(<em>@malfisya</em>),&nbsp;2023-07-09&nbsp;00:48:10&nbsp;UTC</div><br/>

# Summary 

GNOME 43 (?)  adds ability to record screen natively via their print screen menu, but it seems only work on Pipewire. By default Solus still uses pulseaudio, so whenever user try to screen record it will just crash. 
For example in Manjaro screen record button is hidden by default because they still uses pulseaudio (like Solus). If user enable pipewire, the button will appear on printscreen menu. 

## Steps to reproduce

1. Press Prt Scr key or Click Screenshot on Quick menu
2. Click Screen Record on PrintScreen menu
3. Click record

## Expected result

What you expected to happen : It starts recording and show timer on panel

## Actual result

What actually happened : It shows timer for brief second and disappear

## Environment

  - Is system up to date? y
  - Repo: Shannon  
  - Desktop Environment: Gnome   

## System details

Provide the output of About This System from the Application Menu

## Other comments 

Any other details that might help diagnose the issue

**Comment by malfisya** [comment]
Now that we use pipewire and wayland by default, this no longer necessary. closing
