### ISSUE TITLE
Grim Fandango Remastered (GOG) fails to start (T5274)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#219]
<div dir="rtl"><b>Marius</b>&nbsp;(<em>&#35;MJ</em>),&nbsp;2017-12-14&nbsp;09:45:34&nbsp;UTC</div><br/>

Hi,

I can't launch Grim Fandango Remastered (purchased on GOG) on Solus, I get the following error: 

```
marius&#35;marius-laptop ~/GOG Games/Grim Fandango Remastered $ ./start.sh 
Running Grim Fandango Remastered
./GrimFandango: symbol lookup error: /usr/lib32/libXext.so.6: undefined symbol: _XEatDataWords
```

**Comment by davidjharder** [comment]
Very old. Closing
