### ISSUE TITLE
linux-current

### ISSUE THREAD

**Issue by Xdavius** [getsolus/packages#2191]
### Please confirm there isn't already an existing package update request

- [X] I have searched through package update requests

### Name

linux-current  / linux-current-headers

### Version

6.8

### Link to the release notes or announcement.

https://www.kernel.org

### Reason for updating

Actually, linux-current is 6.6 as the linux-lts.

**Comment by davidjharder** [comment]
Our kernel maintainer keeps a close eye on available versions. No need to file an issue in this very specific case.

**Comment by Xdavius** [comment]
> Our kernel maintainer keeps a close eye on available versions. No need to file an issue in this very specific case.

Ok thank you. But we have some hardware that need at less 6.8 to work (wifi 7, Alienware laptop) and I have installed the distribution today and see that I wasn't able to have a more recent kernel, so no wifi available...)

**Comment by sebo505** [comment]
> Ok thank you. But we have some hardware that need at less 6.8 to work (wifi 7, Alienware laptop) and I have installed the distribution today and see that I wasn't able to have a more recent kernel, so no wifi available...)

As far as I can tell, linux-current-6.8.6 has landed in unstable by now and will probably land in stable repo on next sync on next friday.

**Comment by ReillyBrogan** [comment]
> As far as I can tell, linux-current-6.8.6 has landed in unstable by now and will probably land in stable repo on next sync on next friday.

This is accurate.
