### ISSUE TITLE
Diagnosis scripts for eopkg (T4984)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#22]
<div dir="rtl"><b>Pierre-Yves</b>&nbsp;(<em>&#35;kyrios123</em>),&nbsp;2017-11-08&nbsp;21:24:20&nbsp;UTC</div><br/>

It could be useful to make some diagnosis (and eventually self-repair) scripts.
* Warn if running an older kernel of the used branch
* If kernel headers are installed, warn about version mismatch with the loaded kernel
* Warn about `-lts` packages installed on `-current` kernel and vice-versa

There could be some actions around eopkg as well, it could be presented with a menu like
1. Repair broken packages
2. Rebuild the index
3. Restore default source (Shannon)

And throws commands like
1. `sudo eopkg check | grep Broken | awk '{print $4}' | xargs sudo eopkg it --reinstall`
2. `sudo eopkg rdb`
3. `eopkg lr -N | head -n1 | awk '{print $1}' | xargs sudo eopkg rr`   
    `sudo eopkg ar Solus https://packages.solus-project.com/shannon/eopkg-index.xml.xz`

and so on...

**Comment by TraceyC77** [comment]
Keeping in mind that we are moving to Serpent basing tooling, we have evaluate how much work this would be and how much time it would take vs. getting Serpent tooling to do this kind of thing

**Comment by TraceyC77** [comment]
We are moving to deprecating Solus Software Center in favor of Discover and GNOME Software Center.
This kind of work might be feasible in eopkg, but hooking into those software centers would require upstream feature requests. Closing this since the baseline has changed so much.
