### ISSUE TITLE
Gnome Sound Recorder (T10349)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#220]
<div dir="rtl"><b>solarmass</b>&nbsp;(<em>&#35;solarmass</em>),&nbsp;2022-08-21&nbsp;02:07:28&nbsp;UTC</div><br/>

New Package Request: Gnome Sound Recorder

https://gitlab.gnome.org/GNOME/gnome-sound-recorder

It is a simple sound recording app. 
I don't see a similar app in the Solus repo. It could be included now because libhandy already in the repo.

**Comment by silkeh** [comment]
Completed in 96eaca4bc01e78dc36661cbb11e398ded4d6603f.
