### ISSUE TITLE
deprecate replaysorcery

### ISSUE THREAD

**Issue by JTCPingas** [getsolus/packages#2202]
### Please confirm there isn't already an existing package update request

- [X] I have searched through package update requests

### Name

replaysorcery

### Link to the release notes or announcement.

https://github.com/matanui159/ReplaySorcery

### Reason for updating

replaysorcery is no longer maintained upstream

**Comment by androidnisse** [comment]
Some more information 
https://github.com/matanui159/ReplaySorcery/issues/146
