### ISSUE TITLE
gnome-online-accounts-gtk

### ISSUE THREAD

**Issue by Staudey** [getsolus/packages#2206]
### Please confirm there isn't an existing package request

- [X] I have searched through package requests

### Homepage

https://github.com/linuxmint/gnome-online-accounts-gtk

### Maintainer

- [ ] Would you like to be the maintainer for this package?

### Why should this be included in the repository?

This is a standalone app that provides the GNOME online accounts functionality that was previously integrated into e.g. the Budgie control center but had to be removed due to libadwaita/gtk4 requirements of new versions.

### Are we allowed to redistribute it?

GPL-3.0

### What kind of user will use this package, and how many users do you think will use this package?

Everyone who previously used the GNOME online accounts functionality

### Link to source archive file

https://github.com/linuxmint/gnome-online-accounts-gtk/archive/refs/tags/3.50.1.tar.gz

**Comment by EbonJaeger** [comment]
Will include this after GNOME #1950 lands.
