### ISSUE TITLE
ibus-bamboo

### ISSUE THREAD

**Issue by minhhut** [getsolus/packages#2229]
### Please confirm there isn't an existing package request

- [X] I have searched through package requests

### Homepage

https://github.com/BambooEngine/ibus-bamboo

### Maintainer

- [X] Would you like to be the maintainer for this package?

### Why should this be included in the repository?

The similar package is `ibus-unikey` but no longer maintained. The owner recommends to use `ibus-bamboo` as well

### Are we allowed to redistribute it?

GPL-3.0

### What kind of user will use this package, and how many users do you think will use this package?

Normal users want to type Vietnamese

### Link to source archive file

https://github.com/BambooEngine/ibus-bamboo/releases/tag/v0.8.1-RC1

**Comment by ReillyBrogan** [comment]
@minhhut I'm curious why you closed this, do you not need this package?

**Comment by minhhut** [comment]
I have built the package on my local and tried it. The typing that use ibus on linux is not good as I expected. I decided to use online keyboard instead local one.

**Comment by minhhut** [comment]
The new version [v0.8.4.RC1](https://github.com/BambooEngine/ibus-bamboo/releases/tag/v0.8.4-RC1) works fine on my XFCE. I would give it another try if the team agrees.

**Comment by minhhut** [comment]
Fixed in #4017

**Comment by EbonJaeger** [comment]
Closed by #4017
