### ISSUE TITLE
USB printer not found (Epson XP-625) (T5551)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#223]
<div dir="rtl"><b>Nils&nbsp;Asmussen</b>&nbsp;(<em>&#35;nils</em>),&nbsp;2018-01-14&nbsp;13:02:55&nbsp;UTC</div><br/>

Hi all,

after reinstalling my Solus system in December, CUPS is not able to find my printer anymore. I tried to install the printer using the system settings (GNOME) and also using the CUPS web interface (http://localhost:631 -> "Find New Printers") but the printer does not show up at all. My impression is, that the problem might be related to installing USB printers in general, so I'm sorry, if this bug report is a duplicate.

- The printer is an Epson XP-625 connected via USB.
- The package epson-inkjet-printer-escpr is installed.
- The printer is not shown in CUPS at all
- The printer used to work perfectly before the reinstalling Solus.

The output of dmesg is:
```
[ 6961.431201] usb 1-2: new high-speed USB device number 5 using xhci_hcd
[ 6961.598601] usb 1-2: New USB device found, idVendor=04b8, idProduct=08c8
[ 6961.598609] usb 1-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 6961.598613] usb 1-2: Product: EPSON XP-620 Series
[ 6961.598617] usb 1-2: Manufacturer: EPSON
[ 6961.598621] usb 1-2: SerialNumber: *****************
[ 6961.628371] usblp 1-2:1.1: usblp0: USB Bidirectional printer dev 5 if 1 alt 0 proto 2 vid 0x04B8 pid 0x08C8
[ 6961.632135] usb-storage 1-2:1.2: USB Mass Storage device detected
[ 6961.632708] scsi host2: usb-storage 1-2:1.2
[ 6962.650544] scsi 2:0:0:0: Direct-Access     EPSON    Storage          1.00 PQ: 0 ANSI: 2
[ 6962.663463] scsi 2:0:0:1: Direct-Access     EPSON    Storage          1.00 PQ: 0 ANSI: 2
[ 6962.979779] sd 2:0:0:0: [sdb] Attached SCSI removable disk
[ 6963.000808] sd 2:0:0:1: [sdc] Attached SCSI removable disk
```
Please ask if you have any questions.

Thank you,
Nils

**Comment by TraceyC77** [comment]
Closing this issue due to age and lack of updates.. If this is still an issue for anyone, please open a new bug on our tracker.
