### ISSUE TITLE
Solus Budgie and GNOME allow PC to suspend even when settings for this option are set to 'never' (T6440)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#224]
<div dir="rtl"><b>Isaac&nbsp;Paczkowski</b>&nbsp;(<em>&#35;The_Linux_Gooroo</em>),&nbsp;2018-05-26&nbsp;01:35:04&nbsp;UTC</div><br/>

Recently after upgrading Solus from 3.999 to 3.9999, my PC still suspends after 15 minutes of being idle even though in the settings, I have set suspend to never. I'm curious to know if anyone else has had this error or has found a fix. Budgie also warns me in the Raven side-panel about my pc is about to suspend.

**Comment by TraceyC77** [comment]
Closing this issue due to age and lack of updates.. If this is still an issue for anyone, please open a new bug on our tracker.
