### ISSUE TITLE
diffoscope

### ISSUE THREAD

**Issue by joebonrichie** [getsolus/packages#2247]
### Please confirm there isn't an existing package request

- [X] I have searched through package requests

### Homepage

https://diffoscope.org/

### Maintainer

- [ ] Would you like to be the maintainer for this package?

### Why should this be included in the repository?

Useful for comparing two complicated artefacts e.g. .eopkg files

### Are we allowed to redistribute it?

GPL-3.0-or-later

### What kind of user will use this package, and how many users do you think will use this package?

misc

### Link to source archive file

https://salsa.debian.org/reproducible-builds/diffoscope/-/archive/264/diffoscope-264.tar.bz2

**Comment by malfisya** [comment]
How many tools/rundeps should be added? [Arch style](https://gitlab.archlinux.org/archlinux/packaging/packages/diffoscope/-/blob/main/PKGBUILD?ref_type=heads), [Fedora style](https://src.fedoraproject.org/rpms/diffoscope/blob/rawhide/f/diffoscope.spec), [Alpine style](https://git.alpinelinux.org/aports/tree/community/diffoscope/APKBUILD), or our own ?

**Comment by joebonrichie** [comment]
I'm not sure, how nice/scary is the error reporting when a needed rundep isn't installed?

**Comment by malfisya** [comment]
With the recipe as is right now. It can run and check missing tool (`diffoscope --list-missing-tools`). Haven't tried any other command.
