### ISSUE TITLE
LVM Encryption Install broken in Plasma ISO (T6444)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#225]
<div dir="rtl"><b>Christian&nbsp;Brooker</b>&nbsp;(<em>&#35;jedibrooker</em>),&nbsp;2018-05-27&nbsp;01:29:32&nbsp;UTC</div><br/>

I downloaded the latest plasma ISO from patreon (slightly less broken). I installed as normal, wiping the entire drive and selected the LVM encyption option during install. When I restarted the system wouldn't boot.

I tried again using legacy instead of UEFI and the same thing happened but instead of booting it went to grub rescue. I tried to access the hdd but it couldn't recognise the filesystem of the encrypted drive.

I then tried to install using UEFI again but with no encryption and everything went fine, it booted into Solus Plasma.

**Comment by davidjharder** [comment]
Old, no new info, closing
