### ISSUE TITLE
system quasi-hang (T6649)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#226]
<div dir="rtl"><b>Curtis&nbsp;Vaughan</b>&nbsp;(<em>&#35;cavaughan</em>),&nbsp;2018-07-12&nbsp;03:07:47&nbsp;UTC</div><br/>

My laptop tends to hang fairly consistently. The only apps open are Firefox, usually 3 to 5 tabs open, gnome terminal, and sometime evolution. Over the past 3 days with just Firefox and evolution open the following issue occurred every day. Basically the system comes to a halt. Although actually not entirely, using the mouse pad the cursor will slowly (very slowly!) move a few minutes after the input. If I have the patients I can wait some 5-10 minutes (I've never tracked the time) and one of two things tend to occur: either the system continues where it was, or the desktop crashes, I log back in and no apps are running. Usually I just force shutdown the computer and reboot.
I have tried going to a tty(?) screen (Ctrl+alt+f1) to log in there and kill misbehaving apps, but that won't work. I simply can't log in. The time between typing in username and password is so great that obviously the login ttl has past.
I don't know how best to get logs to you to help identify the issue. Or which logs...
I can only attest to this happenig on one laptop: surface pro 3.

**Comment by davidjharder** [comment]
Old, no new info, closing
