### ISSUE TITLE
proton-vpn-gnome-desktop

### ISSUE THREAD

**Issue by eshavkun** [getsolus/packages#2297]
### Please confirm there isn't an existing package request

- [X] I have searched through package requests

### Homepage

https://github.com/ProtonVPN/proton-vpn-gtk-app

### Maintainer

- [ ] Would you like to be the maintainer for this package?

### Why should this be included in the repository?

There is an outdated `protonvpn-gui` package in the Solus repo. The official github for this package is readonly now and Proton VPN has a new Linux app. It would be nice to have this new app in Solus so Proton VPN users won't have to rely on unofficial flatpak 

### Are we allowed to redistribute it?

GPLv3

### What kind of user will use this package, and how many users do you think will use this package?

Normal users, experienced users, existing Proton users. Can't say how many of them are on Solus though

### Link to source archive file

https://github.com/ProtonVPN/proton-vpn-gtk-app/archive/refs/tags/v4.3.0.tar.gz

**Comment by malfisya** [comment]
Duplicate https://github.com/getsolus/packages/issues/981

**Comment by silkeh** [comment]
> Duplicate [#981](https://github.com/getsolus/packages/issues/981)

Closing because of this.
