### ISSUE TITLE
gnome-terminal: no way to toggle "Show Menubar"  and broken shortcut configuration (T7028)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#23]
<div dir="rtl"><b>Rayson&nbsp;O.</b>&nbsp;(<em>&#35;sfproxy</em>),&nbsp;2018-10-07&nbsp;05:38:22&nbsp;UTC</div><br/>

Did a quick search for "terminal" and read page 1, didn't find anything.

The button works but there is no shortcut to Show Menubar after toggling it off. Strangely there is no default shortcut to hide and show which is usually Ctrl+M or Ctrl+Shift+M. When configuring a shortcut to hide and show the menubar, the keypress is not sent to the terminal indicating it is partially working but the menubar is not affected.

cat /etc/lsb-release:
LSB_VERSION=1.4
DISTRIB_ID=Solus
DISTRIB_DESCRIPTION="Solus"
DISTRIB_RELEASE=3.9999
DISTRIB_CODENAME=shannon

**Comment by davidjharder** [comment]
Old, no new info, closing
