### ISSUE TITLE
Solus Plasma freezes (T10529)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#231]
<div dir="rtl"><b>Alex&nbsp;Semenov</b>&nbsp;(<em>&#35;Semenov</em>),&nbsp;2023-05-09&nbsp;15:10:29&nbsp;UTC</div><br/>

After the last update the bottom panel looks broken, fonts are hidden behind graphic artifacts, and then the system just freezes dead at a random moment, and the only thing I can do is hard reset. Before Friday's sync on May 5, it was working fine.
{F10726875}

**Comment by ReillyBrogan** [comment]
Still an issue?

**Comment by TraceyC77** [comment]
This may have been related to an upstream issue that was recently resolved
https://bugs.kde.org/show_bug.cgi?id=469016

If this is still an issue for anyone, please create a new issue in our tracker. Thanks.
