### ISSUE TITLE
gumbo-parser is deprecated

### ISSUE THREAD

**Issue by androidnisse** [getsolus/packages#2321]
### Please confirm there isn't already an existing package update request

- [X] I have searched through package update requests

### Name

gumbo-parser

### Link to the release notes or announcement.

https://github.com/google/gumbo-parser

### Reason for updating

The package is archived at it's source.

**Comment by txgk** [comment]
Hi, I'm a new maintainer of gumbo-parser repo, it's located at https://codeberg.org/gumbo-parser/gumbo-parser Some repos already bumped to the 0.12.1 version of the project https://repology.org/project/gumbo-parser/versions

**Comment by androidnisse** [comment]
> Hi, I'm a new maintainer of gumbo-parser repo, it's located at https://codeberg.org/gumbo-parser/gumbo-parser Some repos already bumped to the 0.12.1 version of the project https://repology.org/project/gumbo-parser/versions

Thanks for the information, I have pushed an update for this against the new source.
