### ISSUE TITLE
our implementation of CP sigsegvs when copying in -a (archival) mode (T10601)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#233]
<div dir="rtl"><b>lucy</b>&nbsp;(<em>@anoraktrend</em>),&nbsp;2023-07-31&nbsp;02:25:07&nbsp;UTC</div><br/>

# Summary 

the version of the Copy (cp) command we use is broken

## Steps to reproduce

1.  cp -a a large folder from one drive to another
2. wait

## Expected result

For the copy to successfully go through

## Actual result

it fails to copy with a sigsegv

## Environment

  - Is system up to date? yes  
  - Repo: Shannon, but the issue also exists in the unstable repo  
  - Desktop Environment: Plasma  

## System details

Operating System: Solus 4.4
KDE Plasma Version: 5.27.6
KDE Frameworks Version: 5.107.0
Qt Version: 5.15.10
Kernel Version: 6.3.12-241.current (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 2700 Eight-Core Processor
Memory: 15.5 GiB of RAM
Graphics Processor: AMD Radeon RX 570 Series
Manufacturer: Micro-Star International Co., Ltd.
Product Name: MS-7C37
System Version: 3.0

## Other comments 

See Also: the Rust Core Utils.

**Comment by ReillyBrogan** [comment]
Is this still a problem?

**Comment by TraceyC77** [comment]
I was able to reproduce this bug.
System has default ulimits (details below).
64GB RAM, no swap
Plasma DE


To reproduce:
Copy 308GB of data from my system to an attached USB drive with `cp -a /home/ /run/media/tracey/LinuxLapBack/hometmp`

Within a few moments, I saw the error:

```
fish: Job 1, 'cp -a /home/ /run/media/tracey/…' terminated by signal SIGSEGV (Address boundary error)
```


ulimits

```
 ulimit -a
Maximum size of core files created                              (kB, -c) 0
Maximum size of a process’s data segment                        (kB, -d) unlimited
Control of maximum nice priority                                    (-e) 0
Maximum size of files created by the shell                      (kB, -f) unlimited
Maximum number of pending signals                                   (-i) 255893
Maximum size that may be locked into memory                     (kB, -l) 8192
Maximum resident set size                                       (kB, -m) unlimited
Maximum number of open file descriptors                             (-n) 1024
Maximum bytes in POSIX message queues                           (kB, -q) 800
Maximum realtime scheduling priority                                (-r) 0
Maximum stack size                                              (kB, -s) 8192
Maximum amount of CPU time in seconds                      (seconds, -t) unlimited
Maximum number of processes available to current user               (-u) 255893
Maximum amount of virtual memory available to each process      (kB, -v) unlimited
Maximum contiguous realtime CPU time                                (-y) unlimited
```
## System

Operating System: Solus 4.4
KDE Plasma Version: 5.27.7
KDE Frameworks Version: 5.109.0
Qt Version: 5.15.10
Kernel Version: 6.5.3-256.current (64-bit)
Graphics Platform: X11
Processors: 16 × 11th Gen Intel® Core™ i7-11800H @ 2.30GHz
Memory: 62.5 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2
Manufacturer: Dell Inc.
Product Name: XPS 17 9710

**Comment by ermo** [comment]
@TraceyC77

There are a couple of avenues of exploration here.

- The first is to attempt to run the copy after running `ulimit -s unlimited` (for unlimited stack frame size -- it's currently 8MiB on your system according to your `ulimit -a` invocation)
- The second is to run this as a gdb invocation with the necessary dbginfo files installed.
- The second is to do a full valgrind invocation with the necessary dbginfo files installed.

Are you up for that challenge? Our coreutils package is quite heavily optimised (for speed and with link time optimisation) and the 9.x series releases changed how cp works compared to earlier versions, so it's not out of the realm of possibility that we're hitting an actual bug.
