### ISSUE TITLE
GNOME 46 Testing

### ISSUE THREAD

**Issue by joebonrichie** [getsolus/packages#2330]
## Known Issues or WIPs

- Mouse cursor is blurry over GTK4 applications when display scaling is enabled
- You may experience visual artifacting with the new gtk4 renderer with older hardware (set `GSK_RENDERER=gl` in environment to use the old renderer)
- snapshot is laggy

## New Applications

- gnome-connections

## Testing List

**Testing Notes:**

1. This list may not be comprehensive. Feel free to report other things!
2. github may indicate something is complete even if it isn't explicitly checked off. Ignore that and only look for the checkbox.

- [x] Bluetooth
  - Tested with Bluetooth pairing in GNOME Control Center with phone.
- [ ] Desktops
  - [ ] Budgie Desktop
     - [x] GDM (when co-installed with GNOME Shell)
     - [ ] LightDM + slick-greeter
  - [x] GNOME Shell
    - [x] GDM
- [x] Geolocation
  - Tested with GNOME Weather
- [ ] IBUS
- [x] Networking
  - [ ] Shares (Samba via Nautilus)
  - [x] Wireless
  - [x] Wired
- [ ] Applications
  - [x] Baobab (Disk Usage Analyzer)
  - [x] Celluloid
  - [x] D-Spy
  - [x] Dconf Editor
  - [x] Evince
  - [x] Evolution
  - [x] Eye of GNOME
  - [x] File Roller (archive)
  - [x] Four-in-a-Row
  - [x] GEdit
  - [x] GHex
  - [x] GNote
  - [x] GNOME 2048
  - [ ] GNOME Boxes
  - [ ] GNOME Builder
  - [x] GNOME Calculator
  - [x] GNOME Calendar
  - [x] GNOME Characters
  - [x] GNOME Clocks
  - [x] GNOME Connections
  - [x] GNOME Console
  - [x] GNOME Contacts
  - [ ] GNOME Control Center (Settings)
    - [x] Background
    - [x] Bluetooth
    - [ ] Devices
        - [ ] Color
        - [x] Displays
        - [ ] Keyboard
        - [ ] Mouse & Touchpad
        - [ ] Printers
        - [x] Removable Media
    - [x] Networking
        - [x] Wi-Fi
        - [x] Wired
    - [x] Notifications
    - [x] Online Accounts
    - [x] Power
    - [x] Search (only applies to GNOME Shell)
    - [ ] Sharing
    - [x] Sound
    - [ ] Accessibility
      - [ ] Seeing
      - [ ] Hearing
      - [ ] Typing
      - [ ] Pointing and Clicking
      - [ ] Zoom
    - [x] Privacy and Security
      - [x] Screen Lock
      - [x] Location (tested via gweather)
      - [x] File History & Wastebasket
      - [x] Cameras (tested via disabling snapshot camera access)
      - [x] Device Security 
    - [ ] System
      - [x] About
      - [ ] Region & Language
      - [x] Secure Shell
      - [ ] Remote Desktop
      - [ ] Users
      - [ ] Date & Time
  - [x] GNOME Disks
  - [x] GNOME Help / Yelp
  - [x] GNOME Image Viewer (loupe)
  - [x] GNOME Logs
  - [x] GNOME Nibbles
  - [x] GNOME Mines
  - [x] GNOME Mahjongg
  - [x] GNOME Maps
  - [x] GNOME Music
  - [ ] GNOME Pomodoro
  - [ ] GNOME Power Statistics (GNOME Power Manager)
  - [x] GNOME Shell features
    - [x] Screencast recording selection
    - [x] Screencast recording whole screen
    - [x] Take a screenshot selection
    - [x] Take a screenshot window
    - [x] Take a screenshot wholescreen
    - [x] Night Light
    - [x] Dark theme toggle
  - [ ] GNOME Remote Desktop
  - [ ] GNOME Sudoku
  - [ ] GNOME Sushi
  - [x] GNOME Text Editor
  - [x] GNOME Tweaks
  - [x] GNOME Weather
  - [x] GNOME Web (epiphany)
  - [ ] GNOME Videos (Totem)
  - [x] Nautilus
  - [ ] Orca
  - [ ] Polari
  - [ ] Quodlibet
  - [ ] Rhythmbox
  - [x] Seahorse
  - [ ] Simple Scan
  - [x] snapshot (laggy)
  - [ ] sysprof
  - [x] Tecla (on-screen keyboard)
  - [ ] Transmission

**Comment by sebo505** [comment]
As I have already mentioned in the packaging room, simple-scan 46 has an issue where you can neither start a new scan with ctrl+1 nor stop/abort a scan with Esc after you have set a cropping area via right-click context-menu. This persists until you either click on scan button to scan another page or click on the cropping button (missing icon) at bottom. 
Also, after you have set cropping area via right-click context menu while scanning, cropping area sometimes can only be moved via dragging after several attempts.

**Comment by malfisya** [comment]
GNOME 45
![Screenshot from 2024-02-19 20-55-19](https://github.com/getsolus/packages/assets/101771435/4cebd024-a95b-4673-a900-9eb61f2dfef2)
GNOME 46
![Screenshot from 2024-04-21 06-05-33](https://github.com/getsolus/packages/assets/101771435/6d70d011-7be0-43fd-b185-c245902d46ae)

The problems : 
- Apps icon is slightly bigger than before
- Panel size and icon is smaller than before

**Comment by malfisya** [comment]
Working so far :
- [x] Baobab (Disk Usage Analyzer)
- [x] Celluloid
- [x] Dconf Editor
- [x] Evince
- [x] Evolution
- [x] File Roller (archive)
- [x] GNOME Calculator
- [x] GNOME Calendar
- [x] GNOME Characters
- [x] GNOME Clocks
- [x] GNOME Console
- [x] GNOME Contacts
- [x] GNOME Disks
- [x] GNOME Help / Yelp
- [x] GNOME Image Viewer (loupe)
- [x] GNOME Text Editor
- [x] GNOME Tweaks
- [x] GNOME Weather
- [x] GNOME Web (epiphany)
- [x] Nautilus

**Comment by endumiuz** [comment]
The new "Remote Login with RDP" does not work; it just gives me an empty settings page. 
GNOME Settings -> System -> Remote Desktop

**Comment by sebo505** [comment]
Restarting GNOME shell in Xorg with Alt+F2, r, Enter leads to crash of session, if any window  is open. We had same behaviour intoducing GNOME45, which then got fixed.

**Comment by sebo505** [comment]
Restarting GNOME shell in Xorg with Alt+F2, r, Enter leads to crash of session, if any window  is open. We had same behaviour intoducing GNOME45, which then got fixed.

**Comment by sebo505** [comment]
Anyone else has observed absurd huge window bars for some programs in X11? I have seen this for example for SimpleScreenRecorder and Nheko. See screenshots below, always gnome-terminal window as reference:

Wayland:
![Bildschirmfoto vom 2024-04-21 20-07-32](https://github.com/getsolus/packages/assets/65250211/a986b1c5-8402-493b-a1a8-78f8e8ac99de)

X11:
![Bildschirmfoto vom 2024-04-21 20-12-36](https://github.com/getsolus/packages/assets/65250211/e41091cc-9213-46a9-8d7b-81b795606419)

**Comment by joebonrichie** [comment]
> Remote Login with RDP does not work; it just gives me an empty settings page. Steps to reproduce: Open GNOME Settings, Go to System, Click Remote Desktop.

Do you have `gnome-remote-desktop` installed?

**Comment by joebonrichie** [comment]
> Anyone else has observed absurd huge window bars for some programs in X11? I have seen this for example for SimpleScreenRecorder and Nheko. See screenshots below, always gnome-terminal window as reference:
> 
> Wayland: ![Bildschirmfoto vom 2024-04-21 20-07-32](https://private-user-images.githubusercontent.com/65250211/324269684-a986b1c5-8402-493b-a1a8-78f8e8ac99de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3Mjk2MzgsIm5iZiI6MTcxMzcyOTMzOCwicGF0aCI6Ii82NTI1MDIxMS8zMjQyNjk2ODQtYTk4NmIxYzUtODQwMi00OTNiLWExYTgtNzhmOGU4YWM5OWRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDE5NTUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0YThhMmY2OWVhZWU4MTViOWI0ZWM3MTJjYjFkNTc0MTA5ZmU4YmQ4MDU5MTY5YzM2M2RlMTAzYzg3NmY5MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r_yT4ooy8vN0rQbpzDkiXuxzYzXb5XTBPnV3DCxF2Is)
> 
> X11: ![Bildschirmfoto vom 2024-04-21 20-12-36](https://private-user-images.githubusercontent.com/65250211/324269707-e41091cc-9213-46a9-8d7b-81b795606419.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3Mjk2MzgsIm5iZiI6MTcxMzcyOTMzOCwicGF0aCI6Ii82NTI1MDIxMS8zMjQyNjk3MDctZTQxMDkxY2MtOTIxMy00NmE5LThkN2ItODFiNzk1NjA2NDE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDE5NTUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwNTY2ZTg5OGYxNWVmNTVlYTViMWZkMjBkMDkxZmQzYWI1NjNiMTZkZmFlZmUwMzYyODlkZjg1N2FhM2UyZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V8fm0QFF9ZDSyKFUcydwVUfsj_MKN3LEnGP3f6kTe3I)

Does mutter/gnome-shell 46.1 help?

**Comment by sebo505** [comment]
> Does mutter/gnome-shell 46.1 help?

Not sure about how to Interpret that question. I am on unstable and thus mutter/gnome-shell 46.1 are installed.

**Comment by endumiuz** [comment]
> > Remote Login with RDP does not work; it just gives me an empty settings page. Steps to reproduce: Open GNOME Settings, Go to System, Click Remote Desktop.
> 
> Do you have `gnome-remote-desktop` installed?

No, I did not; now that I have, I can go to that page. It feels like it should have some kind of hint that you need to install additional software for it to work.

**Comment by endumiuz** [comment]
> > > Remote Login with RDP does not work; it just gives me an empty settings page. Steps to reproduce: Open GNOME Settings, Go to System, Click Remote Desktop.
> > 
> > 
> > Do you have `gnome-remote-desktop` installed?
> 
> No, I did not; now that I have that installed, I can go to that page. It feels like it should have some kind of hint that you need to install additional software for it to work.

I should have checked GNOME Control Center's issue tracker; they seem to be aware of the issue: https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/2977

**Comment by sebo505** [comment]
Is it known and intended behaviour that `man nautilus` won't bring up a man page?

**Comment by ReillyBrogan** [comment]
> Is it known and intended behaviour that `man nautilus` won't bring up a man page?

Should be there now

**Comment by sebo505** [comment]
> > Does mutter/gnome-shell 46.1 help?
> 
Regarding window/title bar size: turned out I had Materia Theme enabled for legacy applications. Switching to Adwaita or Adw-gtk3 solved this.

**Comment by sebo505** [comment]
Regarding top panel height and icon size and text size, there is cleary something going on. Best I could do was to install Solus 4.5 GNOME, update, put a post it on screen where panel ends, switch to unstable GNOME46 and compare. 
With the same fonts, there is a significant difference between GMOME 45 and 46:

GNOME45
![IMG_20240422_202059](https://github.com/getsolus/packages/assets/65250211/fd4a4dc5-a9f7-4b48-9b74-87330ee89aec)

GNOME46
![IMG_20240422_202130](https://github.com/getsolus/packages/assets/65250211/20798899-ecf7-4383-bd77-c991c16fbc7a)

**Comment by sebo505** [comment]
Also be aware of this graphics [issue](https://github.com/getsolus/packages/issues/2351). Turns out it only occurs after switching to unstable and updating to Gnome 46.

**Comment by endumiuz** [comment]
> Regarding top panel height and icon size and text size, there is cleary something going on. Best I could do was to install Solus 4.5 GNOME, update, put a post it on screen where panel ends, switch to unstable GNOME46 and compare.
> With the same fonts, there is a significant difference between GMOME 45 and 46:

I took some screenshots in a VM for comparison.

GNOME 45:
![GNOME45](https://github.com/getsolus/packages/assets/7122445/f5a86afd-0881-4d10-a7b9-8cca124aae1d)

GNOME 46
![GNOME46](https://github.com/getsolus/packages/assets/7122445/cb025d2e-1209-4f6d-87c6-b81df692b893)

They are both using the same font sizes, and no scaling or font scaling.

**Comment by sebo505** [comment]
> Also be aware of this graphics [issue](https://github.com/getsolus/packages/issues/2351). Turns out it only occurs after switching to unstable and updating to Gnome 46.

Did some research here. This issue seems to be related to a newly introduced [GTK renderer.](https://www.phoronix.com/news/GTK-State-Of-New-Renderers)

Returning to classic OpenGL renderer by adding `GSK_RENDERER=gl` to `/etc/environment` as described [here](https://bbs.archlinux.org/viewtopic.php?id=294168) solves this issue for me.
Using classic OpenGL renderer is advised for older hardware, which I am using.

**Comment by TraceyC77** [comment]
It was reported [in the forums](https://discuss.getsol.us/d/10648-gnome-46-desktop-sharing-and-remote-login-missing) that Desktop Sharing and Remote Login are missing in the Control Center. On the user's system, the preference panel is blank.

`rygel` and `gnome-user-share` need to be included in the default package list.
