### ISSUE TITLE
tracker-miners doesn't start

### ISSUE THREAD

**Issue by malfisya** [getsolus/packages#2334]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

- tracker-miners doesn't start
- gnome-music throw error : GNOME music could not connect to Tracker
- totem throw erro : Browser error Failed query org.freedesktop.Tracker3.Miner.Files
- gnome-logs throw out some error and doesn't to work. The app launches but there is some logs with red banner at always showing
- 

### Steps to reproduce

1. launch gnome-logs/gnome-music/totem
2. See the error

### Expected result

No error

### Actual result

GNOME Music
![Screenshot from 2024-04-21 16-53-04](https://github.com/getsolus/packages/assets/101771435/9e733ea6-204b-466c-9f9e-8cb38d977426)

Totem
![Screenshot from 2024-04-21 16-53-17](https://github.com/getsolus/packages/assets/101771435/0e449cd7-7713-431c-a0cb-635181b03434)

There is error and also red banner without text
![Screenshot from 2024-04-21 10-20-50](https://github.com/getsolus/packages/assets/101771435/dc2ddbcc-a70e-45e1-bfa9-2161d45a0686)

From Terminal :
```
 alfisya  ~  gnome-logs                                                                                                                                                

(gnome-logs:5067): GLib-GIO-WARNING **: 10:20:59.577: Translated default ''24h'' for key 'clock-format' in schema 'org.gnome.desktop.interface' is outside of valid range

(gnome-logs:5067): GLib-GIO-WARNING **: 10:20:59.591: Translated default ''24h'' for key 'clock-format' in schema 'org.gnome.desktop.interface' is outside of valid range

(gnome-logs:5067): GLib-GIO-WARNING **: 10:20:59.592: Translated default ''24h'' for key 'clock-format' in schema 'org.gnome.desktop.interface' is outside of valid range

(gnome-
logs:5067): Gtk-CRITICAL **: 10:20:59.592: gtk_label_set_label: assertion 'GTK_IS_LABEL (self)' failed
```

The logs : 
[log messages.txt](https://github.com/getsolus/packages/files/15050525/log.messages.txt)

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

GNOME

### System details

System:
  Host: desktop-solus Kernel: 6.8.7-286.current arch: x86_64 bits: 64
  Desktop: GNOME v: 46.0 Distro: Solus 4.5 resilience
Machine:
  Type: Desktop Mobo: Wibtek model: H77-M v: V1.3 serial: <superuser required>
    BIOS: American Megatrends v: 4.6.5 date: 09/03/2012
CPU:
  Info: quad core Intel Core i5-3570K [MCP] speed (MHz): avg: 1684
    min/max: 1600/3800
Graphics:
  Device-1: Intel IvyBridge GT2 [HD Graphics 4000] driver: i915 v: kernel
  Device-2: AMD Lexa PRO [Radeon 540/540X/550/550X / RX 540X/550/550X]
    driver: amdgpu v: kernel
  Device-3: Jieli USB PHY 2.0 driver: snd-usb-audio,uvcvideo type: USB
  Display: wayland server: X.Org v: 23.2.6 with: Xwayland v: 23.2.6
    compositor: gnome-shell driver: gpu: amdgpu,i915 resolution:
    1: 1366x768~60Hz 2: 1366x768~60Hz
  API: OpenGL v: 4.6 compat-v: 4.2 vendor: amd mesa v: 24.0.5 renderer: AMD
    Radeon RX 550 / 550 Series (radeonsi polaris12 LLVM 16.0.6 DRM 3.57
    6.8.7-286.current)
Network:
  Device-1: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet
    driver: r8169
  Device-2: Realtek RTL8188EUS 802.11n Wireless Network Adapter
    driver: rtl8xxxu type: USB
Drives:
  Local Storage: total: 700.51 GiB used: 393.18 GiB (56.1%)
Info:
  Memory: total: 16 GiB available: 15.53 GiB used: 3.29 GiB (21.2%)
  Processes: 283 Uptime: 12m Shell: fish inxi: 3.3.34

### Other comments

Related to #2330

**Comment by ReillyBrogan** [comment]
@joebonrichie our branding packages might need to be adjusted for this if this is one of the settings we have.

**Comment by malfisya** [comment]
It was `tracker3-reset -s` for me. It is working. Cheers!
