### ISSUE TITLE
Screen brightness act with delay since Friday Sync (T8621)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#235]
<div dir="rtl"><b>Pourcelot&nbsp;Leo</b>&nbsp;(<em>&#35;josephscade</em>),&nbsp;2020-01-19&nbsp;16:15:18&nbsp;UTC</div><br/>

Since this week's friday sync, screen brightness does not work as before.
Now there is a delay of about 0.1 or 0.2 seconds between the time at which the 'backlight up/down' key is pressed and the time at which screen brightness is modified.
The same behaviour happens if I use `xbacklight` to change it.
It doesn't look like a kernel problem. I tested it on `linux-current` and `linux-lts`, and the problem happens for both kernel.
The kernel command line has not been modified, I use UEFI.

Maybe it can help: if I repeatedly press the light up/down key on my keyboard, fan start spinning and `htop` shows that `gsd-backlight-helper` is taking a lot of CPU for a short time.

I'm using a Lenovo Thinkpad E480, with Solus Budgie edition on it.

Please don't hesitate to ask more info about my setup if it can help

Information to help:
  - [output of `inxi`](https://pastebin.com/8FYRPUZj)
  - [output of `dmesg`](https://pastebin.com/YSwe5Lnd)

**Comment by davidjharder** [comment]
Old, no new info. Closing
