### ISSUE TITLE
GIMP crashes on exit if you choose Discard Changes

### ISSUE THREAD

**Issue by endumiuz** [getsolus/packages#2350]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

GIMP crashes on exit if you choose Discard Changes

### Steps to reproduce

1. Open GIMP
2. Open any image or create a new one
3. Make any edits
4. Quit the application
5. Click on Discard Changes

### Expected result

GIMP should close

### Actual result

GIMP closes, but a "GIMP Crash Debug" window opens.

Here's the log: [gimp.log](https://github.com/getsolus/packages/files/15052944/gimp.log) 
journal entries: [journal.log](https://github.com/getsolus/packages/files/15053086/journal1.log)

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

GNOME

### System details

```
System:
  Host: kim-solus Kernel: 6.8.7-286.current arch: x86_64 bits: 64
  Desktop: GNOME v: 46.1 Distro: Solus 4.5 resilience
Machine:
  Type: Desktop System: ASUS product: N/A v: N/A serial: <superuser required>
  Mobo: ASUSTeK model: ROG STRIX B550-F GAMING v: Rev X.0x
    serial: <superuser required> UEFI: American Megatrends v: 3405
    date: 12/13/2023
CPU:
  Info: 8-core AMD Ryzen 7 5800X [MT MCP] speed (MHz): avg: 2414
    min/max: 2200/4850
Graphics:
  Device-1: AMD Navi 32 [Radeon RX 7700 XT / 7800 XT] driver: amdgpu v: kernel
  Display: wayland server: X.Org v: 23.2.6 with: Xwayland v: 23.2.6
    compositor: gnome-shell driver: X: loaded: amdgpu
    unloaded: fbdev,modesetting,radeon,vesa dri: radeonsi gpu: amdgpu
    resolution: 3840x1600~144Hz
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 24.0.5 renderer: AMD
    Radeon RX 7800 XT (radeonsi navi32 LLVM 16.0.6 DRM 3.57
    6.8.7-286.current)
Network:
  Device-1: Intel Ethernet I225-V driver: igc
Drives:
  Local Storage: total: 17.28 TiB used: 11.15 TiB (64.5%)
Info:
  Memory: total: 64 GiB note: est. available: 62.72 GiB used: 6.07 GiB (9.7%)
  Processes: 415 Uptime: 58m Shell: fish inxi: 3.3.34
```

### Other comments

Edit: added journal entries

**Comment by HarveyDevel** [comment]
Seems like an upstream issue:
https://gitlab.gnome.org/GNOME/gimp/-/issues/8831#note_1826243
