### ISSUE TITLE
Failed to start app-gnome-ldm\x2dsession\x2dinit-1537.scope - Application launched by gnome-session-binary.

### ISSUE THREAD

**Issue by malfisya** [getsolus/packages#2360]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

Another red message from gnome-logs :  
`Failed to start app-gnome-ldm\x2dsession\x2dinit-1537.scope - Application launched by gnome-session-binary.`

### Steps to reproduce

Check gnome-logs

### Expected result

No red message error

### Actual result

There is error. 
![Screenshot from 2024-04-23 17-52-30](https://github.com/getsolus/packages/assets/101771435/1f4329cf-9358-47a0-867f-dddb49fb0c66)
[log messages.txt](https://github.com/getsolus/packages/files/15075658/log.messages.txt)

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

GNOME

### System details

System:
  Host: desktop-solus Kernel: 6.8.7-287.current arch: x86_64 bits: 64
  Desktop: GNOME v: 46.1 Distro: Solus 4.5 resilience
Machine:
  Type: Desktop Mobo: Wibtek model: H77-M v: V1.3 serial: <superuser required>
    BIOS: American Megatrends v: 4.6.5 date: 09/03/2012
CPU:
  Info: quad core Intel Core i5-3570K [MCP] speed (MHz): avg: 2164
    min/max: 1600/3800
Graphics:
  Device-1: Intel IvyBridge GT2 [HD Graphics 4000] driver: i915 v: kernel
  Device-2: AMD Lexa PRO [Radeon 540/540X/550/550X / RX 540X/550/550X]
    driver: amdgpu v: kernel
  Device-3: Jieli USB PHY 2.0 driver: snd-usb-audio,uvcvideo type: USB
  Display: wayland server: X.Org v: 23.2.6 with: Xwayland v: 23.2.6
    compositor: gnome-shell driver: X: loaded: amdgpu,modesetting
    unloaded: fbdev,radeon,vesa dri: radeonsi,crocus gpu: amdgpu,i915
    resolution: 1: 1366x768~60Hz 2: 1366x768~60Hz
  API: OpenGL v: 4.6 compat-v: 4.2 vendor: amd mesa v: 24.0.5 renderer: AMD
    Radeon RX 550 / 550 Series (radeonsi polaris12 LLVM 16.0.6 DRM 3.57
    6.8.7-287.current)
Network:
  Device-1: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet
    driver: r8169
  Device-2: Realtek RTL8188EUS 802.11n Wireless Network Adapter
    driver: rtl8xxxu type: USB
Drives:
  Local Storage: total: 700.51 GiB used: 401.47 GiB (57.3%)
Info:
  Memory: total: 16 GiB available: 15.53 GiB used: 4.2 GiB (27.1%)
  Processes: 278 Uptime: 16m Shell: fish inxi: 3.3.34

### Other comments

Related to #2330

**Comment by malfisya** [comment]
I honestly don't know if the error matter at all

**Comment by Staudey** [comment]
Seems like this a mostly harmless, if unsolved, issue

https://gitlab.gnome.org/GNOME/gnome-desktop/-/issues/160
https://gitlab.gnome.org/GNOME/gnome-session/-/issues/120

**Comment by malfisya** [comment]
Harmless, closing
