### ISSUE TITLE
citra is deprecated

### ISSUE THREAD

**Issue by androidnisse** [getsolus/packages#2376]
### Please confirm there isn't already an existing package update request

- [X] I have searched through package update requests

### Name

citra

### Link to the release notes or announcement.

https://citra-emu.org/

### Reason for updating

Citra has been deprecated by it's author.

**Comment by ReillyBrogan** [comment]
Note that we are less worried about the continued existence of citra in the repos than we are Yuzu. Citra was more or less fallout from the Yuzu shutdown and we can switch to a fork for it.
