### ISSUE TITLE
Apps killed after waking from suspend or opening lid. (T9907)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#238]
<div dir="rtl"><b>Nick&nbsp;Jacobs</b>&nbsp;(<em>&#35;jakes</em>),&nbsp;2021-09-08&nbsp;03:32:13&nbsp;UTC</div><br/>

I am on a Lenovo Legion 5 with a NVIDIA GeForce GTX 1660, 24GB of memory and 8GB swap.  I am having an issue on Budgie using Lightdm on shannon. If I suspend, close lid or try to switch TTYs. The session will reset and kill all applications.  I was able to get a decent output from journactl that will hopefully help. I will attach it here. Basically the journalctl is everything from the moment I cleared it to when I was able to gain control of the session again. Towards the middle there is mention of Budgie-wm and panel crashing with a code.
{F8079789}

**Comment by TraceyC77** [comment]
Closing this issue due to age and lack of updates.. If this is still an issue for anyone, please open a new bug on our tracker.
