### ISSUE TITLE
gnome-sharp is deprecated

### ISSUE THREAD

**Issue by androidnisse** [getsolus/packages#2389]
### Please confirm there isn't already an existing package update request

- [X] I have searched through package update requests

### Name

gnome-sharp

### Link to the release notes or announcement.

https://github.com/mono/gnome-sharp

### Reason for updating

It is archived at it's source.

**Comment by TraceyC77** [comment]
Please note that the tag on a deprecation request should be "Deprecation or removal from repository"
It's fine to use the package update template as a starting point, just change the label.

**Comment by androidnisse** [comment]
> Please note that the tag on a deprecation request should be "Deprecation or removal from repository" It's fine to use the package update template as a starting point, just change the label.

I did not know I could do that myself. Could you please guide me how to do this and I will do this forward?

**Comment by TraceyC77** [comment]
My apologies. I thought the labels could be edited by an issue creator, but this is not the case.
