### ISSUE TITLE
Solus USB drive won't boot: amd-vi unable to write to iommu perf counter (T8780)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#239]
<div dir="rtl"><b>Moonglow</b>&nbsp;(<em>&#35;moonglow</em>),&nbsp;2020-02-29&nbsp;18:01:09&nbsp;UTC</div><br/>

Hello, I've installed Solus on my desktop PC last week and it works perfectly.
Today I've tried to install it on my laptop, but the USB drive won't boot.
It stops before reaching the installer and returns this error:
"amd-vi unable to write to iommu perf counter"
It won't let me proceed or type anything, the only thing I can do is forcedly shutdown the PC.
My laptop is an Acer Aspire 3 A315-42-R3E0 with an AMD Ryzen3 3200U CPU and an AMD Radeon Vega 3 GPU.
According to some posts I've found online, it could mean that the kernel doesn't support the CPU very well.
However, I've managed to install Ubuntu on the same PC just fine, even though it has an older kernel.
Some people also suggested to disable IOMMU in the BIOS, but my PC has a very basic BIOS and no option to do that.
So, how can I install Solus on that PC?

**Comment by TraceyC77** [comment]
Closing this issue due to age and lack of updates.. If this is still an issue for anyone, please open a new bug on our tracker.
