### ISSUE TITLE
gnome-system-tools should be deprecated

### ISSUE THREAD

**Issue by androidnisse** [getsolus/packages#2390]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

gnome-system-tools does not build for me. Tried to add a homepage to the package.yml

### Steps to reproduce

1. Try to build.

### Expected result

It builds.

### Actual result

It does not build.

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

Xfce

### System details

System:
  Host: solus-dev Kernel: 6.8.7-287.current arch: x86_64 bits: 64
  Desktop: Xfce v: 4.18.1 Distro: Solus 4.5 resilience
Machine:
  Type: Virtualbox System: innotek GmbH product: VirtualBox v: 1.2
    serial: <superuser required>
  Mobo: Oracle model: VirtualBox v: 1.2 serial: <superuser required>
    UEFI: innotek GmbH v: VirtualBox date: 12/01/2006
Battery:
  ID-1: BAT0 charge: 28.5 Wh (57.0%) condition: 50.0/50.0 Wh (100.0%)
    volts: 10.0 min: 10.0
CPU:
  Info: quad core 11th Gen Intel Core i5-1135G7 [MCP] speed (MHz): avg: 1382
Graphics:
  Device-1: VMware SVGA II Adapter driver: vmwgfx v: 2.20.0.0
  Display: x11 server: X.Org v: 21.1.13 with: Xwayland v: 23.2.6 driver:
    gpu: vmwgfx resolution: 1360x768~60Hz
  API: OpenGL v: 4.5 vendor: mesa v: 24.0.6 renderer: llvmpipe (LLVM 16.0.6
    256 bits)
Network:
  Device-1: Intel 82540EM Gigabit Ethernet driver: e1000
  Device-2: Intel 82371AB/EB/MB PIIX4 ACPI type: network bridge
    driver: piix4_smbus
Drives:
  Local Storage: total: 32 GiB used: 24.75 GiB (77.3%)
Info:
  Memory: total: 4 GiB available: 3.82 GiB used: 1007.8 MiB (25.8%)
  Processes: 235 Uptime: 35m Shell: Zsh inxi: 3.3.34

**Comment by joebonrichie** [comment]
Last updated 2011, should be deprecated
