### ISSUE TITLE
Update kicad to 8.0.1

### ISSUE THREAD

**Issue by androidnisse** [getsolus/packages#2398]
### Please confirm there isn't already an existing package update request

- [X] I have searched through package update requests

### Name

Kicad

### Version

8.0.1

### Link to the release notes or announcement.

https://www.kicad.org/blog/2024/02/Version-8.0.0-Released/

### Reason for updating

New major version, multiple bug fixes and improvements. Added release notes for 8.0.0 as 8.0.1 is just a bug fix release. This package has an maintainer file so I cannot update it.

**Comment by malfisya** [comment]
If you want, you can update it. The maintainer is no longer using Solus.
