### ISSUE TITLE
Backlight Issue on Optimus Laptop Budgie (T5999)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#24]
<div dir="rtl"><b>Mauro&nbsp;Lombarda</b>&nbsp;(<em>&#35;meetmauro</em>),&nbsp;2018-03-09&nbsp;13:58:50&nbsp;UTC</div><br/>

Hi all,
I have a brightness issue on my laptop, it's stuck at 100% all the time.
I tried using acpi_backlight=native as someone suggested in the forums here but this is not working.
If I use the brightness keys the sysfs gets updated but the brightness remains stuck at 100%.
Also xbacklight does not work, increasing or decreasing the brightness using it produces no messages and does not change the brightness of the screen.
the OSD always changes and reflects what is in the sysfs.
I have an intel and Nvidia 1070 qmax with the native drivers.
let me know if there are other missing info. I can do whatever is needed to track this down.
thank you very much

**Comment by TraceyC77** [comment]
Closing this issue due to age and lack of updates. If this is still an issue for anyone, please open a new bug on our tracker.
