### ISSUE TITLE
Audio Cuts Off After Every Reboot (due to remembered HDMI device) (T9512)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#240]
<div dir="rtl"><b>Anthony&nbsp;M.&nbsp;Cook</b>&nbsp;(<em>&#35;acook</em>),&nbsp;2021-01-09&nbsp;00:21:57&nbsp;UTC</div><br/>

Here's another weird one. I just spent a while debugging an issue today, here are my findings. 

Some part of the audio pipeline was remembering an unplugged HDMI device from yesterday and sending audio to it instead of the visible settings in the Settings/Sound tab. No amount of changing the options there could fix it. The issue persisted through multiple reboots, rollback of today's update, and re-updating.

**Workaround:** I reconnected the HDMI device, switched to it, and then switched away from it. But //I have to do this after every reboot//.

There's a second interrelated issue around today's updates. An NVidia driver update went out but did not update the 32bit drivers leading to a ton of weird issues. Including Steam and MPV crashes until I manually reinstalled the drivers and rebooted.

I've been grepping around in `/etc` for HDMI audio devices but I'm not finding where it is being persisted. If anyone has a suggestion of what to try next I would appreciate it.

**Below only for historical purposes:**

//(this was written before I got to the workaround step)//

> 
> Original title: No Audio via Settings Dialog, RhythmBox, etc
> 
> Broken: Since today's update (I also tried rolling back) the Settings dialog's Sound tab's "Test" output button no longer makes an audible sound. The VU meter does not detect sound playing either.
> 
> Broken: RhythmBox and standalone Spotify also do not output sound of any kind. Although they appear to play songs through and even produce notifications.
> 
> Broken: While `gnome-mpv` just crashes on launch stating on the commandline: `libEGL warning: DRI2: failed to authenticate` and `Floating point exception (core dumped)`.
> 
> Working: However, Firefox (including YouTube and the Spotify web player) and BitWig Studio DO produce sound just fine. (the Settings VU meters do not display either, though they do display the Firefox level sliders).

**Comment by TraceyC77** [comment]
Closing this issue due to age and lack of updates.. If this is still an issue for anyone, please open a new bug on our tracker.
