### ISSUE TITLE
Font display problem on some websites

### ISSUE THREAD

**Issue by TraceyC77** [getsolus/packages#2406]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

After the latest updates to fontconfig, fonts on certain websites look jagged, as if there is a hinting issue, affects multiple browsers

### Steps to reproduce

1. Visit Reddit and view the font of post bodies. Ex [this thread](https://www.reddit.com/r/movies/comments/1cdm2oj/which_song_is_forever_linked_to_a_movie_for_you/)
2. Open up the developer console

### Expected result

Fonts are legible and smooth on sites and in the dev console

### Actual result

The font is jagged looking

![firefox_reddit_font_20240426_115109](https://github.com/getsolus/packages/assets/10402612/5a69b8f8-3737-4ecb-a90d-47cada4e82c4)

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

Plasma

### System details

Operating System: Solus 4.5
KDE Plasma Version: 6.0.4
KDE Frameworks Version: 6.1.0
Qt Version: 6.6.3
Kernel Version: 6.8.7-287.current (64-bit)
Graphics Platform: Wayland
Processors: 16 × 11th Gen Intel® Core™ i7-11800H @ 2.30GHz
Memory: 62.5 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics
Manufacturer: Dell Inc.
Product Name: XPS 17 9710

### Other comments

There had just been an update to the fontconfig logic to work around emoji fonts being picked incorrectly on sites (like MSI) and emojis not displaying correctly in Nheko's input area

**Comment by malfisya** [comment]
Element on firefox display similar issue. The kerning doesn't look right. Weirdly, it only affects chat view.

![Screenshot from 2024-04-27 15-35-22](https://github.com/getsolus/packages/assets/101771435/f7d18a37-8ae7-4cb6-afd1-9c0135944267)

![Screenshot from 2024-04-27 15-29-31](https://github.com/getsolus/packages/assets/101771435/4d7266b7-a100-4951-94fd-37b10a537c32)

**Comment by malfisya** [comment]
This fixed it for me. Courtesy of ReilyBrogan on forum.
```
cd /usr/share/fonts/conf.d/
sudo rm 10-hinting-full.conf
sudo ln -srv /usr/share/fontconfig/conf.avail/10-hinting-slight.conf 10-hinting-slight.conf
sudo fc-cache -f -s
```

**Comment by ReillyBrogan** [comment]
Closing as the default hinting type has been changed to slight, and Tracey mentioned that she had overridden the font in Vivaldi which was causing her issue.
