### ISSUE TITLE
qt6ct reports it's not configured correctly.

### ISSUE THREAD

**Issue by androidnisse** [getsolus/packages#2412]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

When I start qt6ct it says on the top that it's not configured properly.
![Snapshot_2024-04-27_08-10-01](https://github.com/getsolus/packages/assets/8074155/128a066a-912c-4adb-9889-c3b2e1d8052e)

### Steps to reproduce

1. Start the program.
2. Notice the issue
3. Click on information

### Expected result

No error message is shown.

### Actual result

Error message is shown.

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Budgie

### System details

System:
  Host: vesslan Kernel: 6.8.7-287.current arch: x86_64 bits: 64
  Desktop: Budgie v: 10.9.1 Distro: Solus 4.5 resilience
Machine:
  Type: Laptop System: Dell product: Latitude 5420 v: N/A
    serial: <superuser required>
  Mobo: Dell model: 047J2X v: A01 serial: <superuser required> UEFI: Dell
    v: 1.33.0 date: 11/10/2023
Battery:
  ID-1: BAT0 charge: 8.8 Wh (20.6%) condition: 42.8/63.0 Wh (67.9%)
    volts: 14.7 min: 15.2
CPU:
  Info: quad core 11th Gen Intel Core i5-1135G7 [MT MCP] speed (MHz): avg: 985
    min/max: 400/4200
Graphics:
  Device-1: Intel TigerLake-LP GT2 [Iris Xe Graphics] driver: i915 v: kernel
  Device-2: Sunplus Innovation Integrated_Webcam_HD driver: uvcvideo
    type: USB
  Display: x11 server: X.Org v: 21.1.13 with: Xwayland v: 23.2.6 driver:
    gpu: i915 resolution: 1920x1080~60Hz
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: intel mesa v: 24.0.6
    renderer: Mesa Intel Xe Graphics (TGL GT2)
Network:
  Device-1: Intel Wi-Fi 6 AX201 driver: iwlwifi
  Device-2: Intel Ethernet I219-V driver: e1000e
Drives:
  Local Storage: total: 238.47 GiB used: 87.84 GiB (36.8%)
Info:
  Memory: total: 16 GiB note: est. available: 15.21 GiB used: 5.31 GiB (34.9%)
  Processes: 342 Uptime: 17m Shell: Zsh inxi: 3.3.34

### Other comments

Seems this would fix it, found on their Github:

Add line 'export QT_QPA_PLATFORMTHEME=qt6ct' to ~/.profile and re-login.
Alternatively, create the file /etc/X11/Xsession.d/100-qt6ct with
the following line:

export QT_QPA_PLATFORMTHEME=qt6ct

(or qt5ct for compatibility with Qt5 Configuration Tool)

Now restart X11 server to take the changes effect.

**Comment by malfisya** [comment]
You should make `/etc/environment` manually. Add `QT_QPA_PLATFORMTHEME=qt5ct` or `qt6ct` , doesn't matter both qt5ct and qt6ct are compatible. This my `/etc/environment` file as an example : 


```
$ cat /etc/environment                                                                                                    
QT_WAYLAND_DECORATION=adwaita
QT_QPA_PLATFORM=wayland
QT_QPA_PLATFORMTHEME=qt5ct
XCURSOR_SIZE=24
XCURSOR_THEME=Bibata-Modern-Classic

```

**Comment by malfisya** [comment]
User can add that env variable to `/etc/environment`. I think this should be handled by user, not by package manager. Though a documentation on help center should be better.

**Comment by ReillyBrogan** [comment]
Yes, this doesn't look like an issue to me. Qt6 applications need to be told to load the theme settings from qt6ct and that environmental variable is how they do it.
