### ISSUE TITLE
ypkg installed from the repo does not work (T8611)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#242]
<div dir="rtl"><b>Hazem</b>&nbsp;(<em>&#35;hyphens</em>),&nbsp;2020-01-17&nbsp;12:31:23&nbsp;UTC</div><br/>

running ypkg or any of its subcommands produces a traceback that says ypkg2 module doesn't exist:
```
Traceback (most recent call last):
  File "/usr/bin/ypkg", line 14, in <module>
    from ypkg2 import console_ui
ImportError: No module named ypkg2
```

steps to reproduce:
 - eopkg install ypkg
 - $ ypkg

**Comment by TraceyC77** [comment]
Closing, as ypkg works for myself and the other packagers.
