### ISSUE TITLE
PulseAudio Incorrect Microphone Volume (T8061)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#243]
<div dir="rtl"><b>Alec&nbsp;Scott</b>&nbsp;(<em>&#35;alecbcs</em>),&nbsp;2019-06-17&nbsp;18:33:44&nbsp;UTC</div><br/>

I've been experiencing issues using my microphone in electron apps for the past couple of weeks.  When trying to call others in Slack, Wire, or using Google Hangouts through Chrome no one was ever able to hear me. Checking in the GNOME settings panel I could see that the system was reading the input from my microphone. However, this signal seemed not to be getting through to the electron apps. (I tried recording a video through GNOME cheese and was able to hear the input from the microphone.) So finally this morning I decided to dig through my system configuration and I tracked the issue down to `PulseAudio`. Although the volume of my microphone was set correctly in the default settings, I saw that when I started up a call, Pulse Audio had set the input stream volume to the application to 0. (In `pavucontrol` this can be seen in the "recording section.") By dragging the slider up from 0, I was finally able see that the electron apps were getting the microphone signal. I'm unsure if this is an issue with electron incorrectly setting the stream volume or if this is an issue with our configuration in Solus. I've experienced this issue on two separate machines running Solus so I don't think it is a hardware issue but I'd be interested to know, has anyone else has experienced this issue?

**Comment by ReillyBrogan** [comment]
Fixed by Pipewire 0.3.78
