### ISSUE TITLE
Update mullvad to 2024.2

### ISSUE THREAD

**Issue by Yannnd** [getsolus/packages#2435]
### Please confirm there isn't already an existing package update request

- [X] I have searched through package update requests

### Name

mullvad

### Version

2024.2

### Link to the release notes or announcement.

https://github.com/mullvad/mullvadvpn-app/releases/tag/2024.2

### Reason for updating

For security and/or privacy applications like this VPN client it is a good thing to keep up with the newest releases

**Comment by davidjharder** [comment]
ping @tarkah

**Comment by tarkah** [comment]
On it :+1:

**Comment by tarkah** [comment]
https://github.com/getsolus/packages/pull/2437
