### ISSUE TITLE
Update gmic 3.0.2 to 3.2.6  (T10479)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#245]
<div dir="rtl"><b>Fabio</b>&nbsp;(<em>&#35;Fabio</em>),&nbsp;2023-04-22&nbsp;13:23:42&nbsp;UTC</div><br/>

Home page https://gmic.eu/download.html
Link to source stable https://gmic.eu/files/source/gmic_3.2.6.tar.gz
(which I believe is the sum of https://github.com/GreycLab/gmic + https://github.com/c-koi/gmic-qt)
Because
denoise don't work:

```
$ gmic input_cached gmic_denoise_cnn.gmz
[gmic]-0./ Start G'MIC interpreter.
[gmic]-0./ Input cached file 'gmic_denoise_cnn.gmz'.
[gmic] *** Error in ./ *** Command 'input_cached': Unknown filename 'gmic_denoise_cnn.gmz'.
```
I attach the output of
$ gmic debug input_cached gmic_denoise_cnn.gmz
{F10690350}

There was a name change for value type in the .gmz and .cimgz that has been introduced in G’MIC 3.1.0. so 3.0.2 does not recognize the macic number of gmz.
https://discuss.pixls.us/t/machine-learning-library-in-gmic/25746/73?u=fab7d

**Comment by FAb7D** [comment]
At the same time I think Krita and perhaps digicam should also be updated because of gmic-qt

**Comment by luzpaz** [comment]
3.3.1 is current stable https://github.com/GreycLab/gmic/releases/tag/v.3.3.1

**Comment by luzpaz** [comment]
3.3.2 is current stable https://github.com/GreycLab/gmic/releases/tag/v.3.3.2

**Comment by FAb7D** [comment]
[https://gmic.eu/files/source/gmic_3.3.2.tar.gz](https://gmic.eu/files/source/gmic_3.3.2.tar.gz )but (I beleieve)  krita now use this  [https://github.com/amyspark/gmic/releases/tag/v3.2.4.1/gmic-3.2.4.1-patched.tar.xz2.tar.gz](https://github.com/amyspark/gmic/releases/tag/v3.2.4.1/gmic-3.2.4.1-patched.tar.xz2.tar.gz ) that can be build with krita package.

**Comment by GZGavinZhao** [comment]
Working on it, mostly blocked on Krita because the new version introduced a lot of dependency :sweat_smile:
