### ISSUE TITLE
Kdenlive is missing the Track Movement effect

### ISSUE THREAD

**Issue by TraceyC77** [getsolus/packages#2465]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

Kdenlive is supposed to include an effect called Track Movement. It is not present in the Solus package.

### Steps to reproduce

1. Install and launch Kdenlive
2. In the effects pane, type in "track" (or manually look through the effects under Alpha, Mask and Keyring

### Expected result

Motion Tracking is shown

### Actual result

Motion Tracking is not present

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

Plasma

### System details

Operating System: Solus 4.5
KDE Plasma Version: 6.0.4
KDE Frameworks Version: 6.1.0
Qt Version: 6.6.3
Kernel Version: 6.8.8-288.current (64-bit)
Graphics Platform: Wayland
Processors: 16 × 11th Gen Intel® Core™ i7-11800H @ 2.30GHz
Memory: 62.5 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics
Manufacturer: Dell Inc.
Product Name: XPS 17 9710

### Other comments

The package in Solus is the latest one available from upstream
The effect is available in the flatpak version, so this is a packaging issue.

[Documentation](https://docs.kdenlive.org/en/effects_and_compositions/video_effects/alpha_mask_keying/motion_tracker.html)
I'm not sure why this effect is missing, I don't see anything in the package.yml or patches that should affect this.

This effect is one of the easiest ways to blur a part of a screen recording or video, making its lack a bad experience of kdenlive

**Comment by HarveyDevel** [comment]
`mlt` needs to be built with:
pkgconfig(opencv4) and `-DMOD_OPENCV=ON `

This makes the option appear but I do not know how to use it properly so I am unable to test it.
