### ISSUE TITLE
Weird Touchpad problem (T8192)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#247]
<div dir="rtl"><b>Dinh&nbsp;Tien&nbsp;Nam</b>&nbsp;(<em>&#35;dinhnamhihi</em>),&nbsp;2019-07-30&nbsp;13:27:24&nbsp;UTC</div><br/>

My Solus 4 Plasma has 3 problems with Touchpad option in Setting:
1. Resume after sleep have 'Tapping' and 'Two-finger tap' option are greyed-out, but after few minutes these option comeback to normal.
2. Option 'Middle-click' doesn't display well in 2 different display stages, one directly from Setting open page, one throught 'Input Devices' option
{F4988994}

{F4988995}
3. 'Right-Click' option alway grey-out

**Comment by davidjharder** [comment]
Old, no new info. Closing
