### ISSUE TITLE
Trackpad and Touchpad problems after the latest updates - Lenovo Thinkpad L480 (T6930)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#248]
<div dir="rtl"><b>Jacek&nbsp;Kubiak</b>&nbsp;(<em>&#35;Zaff</em>),&nbsp;2018-09-20&nbsp;14:24:57&nbsp;UTC</div><br/>

Hi,

just wanted to let you know that a trackpad and touchpad stopped working on a Lenovo Thinkpad L480 after the latest updates. When I did a one week rollback everything is ok, but I wanted to let you know about it. I run Solus 3.9999 with Budgie desktop on Lenovo Thinkpad L480 as the only OS. Unfortunately I'm not able to pin down which update exactly was it.

**Comment by davidjharder** [comment]
Old, no new info. Closing
