### ISSUE TITLE
Gamescope - crash on Polaris cards

### ISSUE THREAD

**Issue by poolee98** [getsolus/packages#2486]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

There's currently bug that affects AMD Polaris GPUs: https://github.com/ValveSoftware/gamescope/issues/1218

User "ammgws" bisected and found the commit [82e3632](https://github.com/ValveSoftware/gamescope/commit/82e3632504bc9252def1a10096942bc032ae544d) which breaks the Gamescope on Polaris cards.

I propose a downgrade of the gamescope to the 3.14.2 (with HDR patch) for the time being. I've successfully built [this version](https://github.com/getsolus/packages/tree/7f861c7d20346d40cf2da410c5212b642e9b1c46/packages/g/gamescope) and ran it -  tested with Halo: MCC, everything seems fine. Haven't tested HDR though.

### Steps to reproduce

0. Get a PC with Polaris card (others may be affected, I am not sure)
1. Install Gamescope (currently there's a version 3.14.11 in the repo)
2. Run "gamescope glxgears"

### Expected result

Glxgears opening up in a nested gamescope compositor and working properly.

`poolee@poolee-solus ~/Desktop $ gamescope glxgears
No CAP_SYS_NICE, falling back to regular-priority compute and threads.
Performance will be affected.
ATTENTION: default value of option vk_khr_present_wait overridden by environment.
ATTENTION: default value of option vk_khr_present_wait overridden by environment.
vulkan: selecting physical device 'AMD Radeon RX 580 Series (RADV POLARIS10)': queue family 1 (general queue family 0)
vulkan: physical device does not support DRM format modifiers
wlserver: [backend/headless/backend.c:67] Creating headless backend
vulkan: supported DRM formats for sampling usage:
vulkan:   AR24 (0x34325241)
vulkan:   XR24 (0x34325258)
vulkan:   AB24 (0x34324241)
vulkan:   XB24 (0x34324258)
vulkan:   RG16 (0x36314752)
vulkan:   NV12 (0x3231564E)
vulkan:   AB4H (0x48344241)
vulkan:   XB4H (0x48344258)
vulkan:   AB48 (0x38344241)
vulkan:   XB48 (0x38344258)
vulkan:   AB30 (0x30334241)
vulkan:   XB30 (0x30334258)
vulkan:   AR30 (0x30335241)
vulkan:   XR30 (0x30335258)
vulkan: Creating Gamescope nested swapchain with format 64 and colorspace 0
wlserver: Running compositor on wayland display 'gamescope-0'
wlserver: [backend/headless/backend.c:17] Starting headless backend
wlserver: [xwayland/sockets.c:63] Failed to bind socket @/tmp/.X11-unix/X0: Address already in use
wlserver: [xwayland/server.c:108] Starting Xwayland on :2
wlserver: [types/wlr_compositor.c:692] New wlr_surface 0x5646bf3967f0 (res 0x5646bf39cd20)
wlserver: [xwayland/server.c:273] Xserver is ready
pipewire: stream state changed: connecting
pipewire: stream state changed: paused
pipewire: stream available on node ID: 70
vblank: Using timerfd.
vulkan: Creating Gamescope nested swapchain with format 64 and colorspace 0
pipewire: renegotiating stream params (size: 1280x720)
wlserver: [types/wlr_compositor.c:692] New wlr_surface 0x5646bf377310 (res 0x5646bf3a0a30)
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
xwm: got the same buffer committed twice, ignoring.`

### Actual result

Gamescope doesn't start up, aborts with "Assertion table_len > 0 failed." and core dumped.

`poolee@poolee-solus ~ $ gamescope glxgears
No CAP_SYS_NICE, falling back to regular-priority compute and threads.
Performance will be affected.
ATTENTION: default value of option vk_khr_present_wait overridden by environment.
ATTENTION: default value of option vk_khr_present_wait overridden by environment.
vulkan: selecting physical device 'AMD Radeon RX 580 Series (RADV POLARIS10)': queue family 1 (general queue family 0)
vulkan: physical device does not support DRM format modifiers
wlserver: [backend/headless/backend.c:67] Creating headless backend
xdg_backend: Seat name: 
vulkan: supported DRM formats for sampling usage:
gamescope: types/wlr_linux_dmabuf_v1.c:532: feedback_compile: Assertion table_len > 0 failed.
Aborted (core dumped)`

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Plasma

### System details

`System:
  Host: poolee-solus Kernel: 6.8.8-288.current arch: x86_64 bits: 64
  Desktop: KDE Plasma v: 6.0.4 Distro: Solus 4.5 resilience
Machine:
  Type: Desktop System: Gigabyte product: B85M-D3H-A v: N/A
    serial: <superuser required>
  Mobo: Gigabyte model: B85M-D3H-A v: x.x serial: <superuser required>
    UEFI: American Megatrends v: F1 date: 03/30/2015
CPU:
  Info: quad core Intel Core i7-4790K [MT MCP] speed (MHz): avg: 846
    min/max: 800/4600
Graphics:
  Device-1: AMD Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
    driver: amdgpu v: kernel
  Device-2: Microdia USB 2.0 Camera driver: snd-usb-audio,uvcvideo type: USB
  Display: wayland server: X.org v: 1.21.1.13 with: Xwayland v: 23.2.6
    compositor: kwin_wayland driver: N/A resolution: 2560x1080
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 24.0.6 renderer: AMD
    Radeon RX 580 Series (radeonsi polaris10 LLVM 16.0.6 DRM 3.57
    6.8.8-288.current)
Network:
  Device-1: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet
    driver: r8169
Drives:
  Local Storage: total: 1.38 TiB used: 94.54 GiB (6.7%)
Info:
  Memory: total: 20 GiB available: 19.5 GiB used: 4.93 GiB (25.3%)
  Processes: 265 Uptime: 4h 1m Shell: Bash inxi: 3.3.34
`

**Comment by ReillyBrogan** [comment]
Does this work? `sudo eopkg it https://shared.getsol.us/reilly/2024-04-2486/gamescope-3.14.12-26-1-x86_64.eopkg`

**Comment by ReillyBrogan** [comment]
Note that they gamescope-polaris will be going away in the next packaged version of gamescope. Instead please use `--backend=sdl` with the normal gamescope binary.
