### ISSUE TITLE
Intel Smarth Sound (T10581)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#250]
<div dir="rtl"><b>Luis</b>&nbsp;(<em>&#35;lluduena</em>),&nbsp;2023-07-13&nbsp;00:38:36&nbsp;UTC</div><br/>

Pruebo mediante USB Solus 4.4 en una Notebook que cuenta con la tecnología Intel Smarth sound y no tengo sonido. Si tengo sonido si conecto auriculares por Bluetooth. El resto funciona espectacular y solucionando el problema del audio estoy dispuesto a cambiarlo por windows 11.

#intel smarth sound

Agradecido

//I try using USB Solus 4.4 on a Notebook that has Intel Smarth sound technology and I have no sound. If I have sound if I connect headphones via Bluetooth. The rest works spectacularly and solving the audio problem I am willing to change it for windows 11.//

**Comment by davidjharder** [comment]
Old, closing
