### ISSUE TITLE
Please include VBoxGuestAdditions.iso with the packages that install virtualbox and virtualbox-current (T10602)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#252]
<div dir="rtl"><b>Jerry&nbsp;Houston</b>&nbsp;(<em>&#35;WetGeek</em>),&nbsp;2023-08-02&nbsp;19:42:10&nbsp;UTC</div><br/>

I'm putting this request here, because I'm //not// requesting that a new product package be created. 
 I'm just requesting that another file be added to an existing package.

According to the VirtualBox documentation, the guest additions .ISO should be located in the installation folder for VirtualBox.  I suspect that they've been a separate download so that FOSS-only distributions are able to install VirtualBox without any of the non-FOSS device drivers and applications that the guest additions .ISO contains.  

If this is not a constraint for Solus, it would help users to have them installed at the same time VirtualBox is.  Then, the host computer would be able to insert them into the guest's DVD drive when required to do that, as per the user manual.

This would eliminate the requirement for a user to download them separately, which can be error-prone, and frustrating.  At present, the web site for [VirtualBox 7.0.10](https://www.virtualbox.org/wiki/Downloads) doesn't even offer a link to download them.

**Comment by malfisya** [comment]
I am thinking of doing this. If I understand this correctly, I should just modify `package.yml` of `virtualbox`. Add `guest-iso` source, subpackage it( add `guest-iso` pattern), install it to`usr/share/virtualbox/`.
I shouldn't create new package for this (i.e: create new folder named `virtualbox-guest-iso` on `getsolus/packages/packages/v/`).
Is this correct?

**Comment by malfisya** [comment]
> **Can I redistribute VirtualBox Guest Additions?** 
 Yes. The GPLv2 allows you to distribute the VirtualBox Guest Additions, in modified or unmodified form, as long as you adhere to the terms and conditions of the GPLv2.

According to [FAQ](https://www.virtualbox.org/wiki/Licensing_FAQ), Solus can indeed distribute it.

**Comment by ReillyBrogan** [comment]
0ffb89f40ef59136644cf5528f792f76bb9bee9e
