### ISSUE TITLE
Gedit theme turned Light after 5/10 Update

### ISSUE THREAD

**Issue by brent111** [getsolus/packages#2528]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

https://discuss.getsol.us/d/10594-sync-updates-for-week-19-2024/7

saga, pics, and troubleshooting here ^^. Tried everything to make it dark again.

**_As of this writing this problem is confirmed by at least one other Budgie user_; thread above

### Steps to reproduce

1. Rock the Dark Theme in Budgie with Solus icons and Solus widgets.
2. Do the 5/10/2024 Solus System Update. REBOOT.
3. Open Gedit.
4.  Gasp it's light-themed. Yuck.

### Expected result

1. Rock the Dark Theme in Budgie with Solus icons and Solus widgets.
2. Do the 5/10/2024 Solus System Update. REBOOT.
3. Open Gedit.
4.  Awesome, the app is still dark.

### Actual result

`Gedit` turned from Dark Theme to Light. Yuck.

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Budgie

### System details

$ inxi -b
Machine:
  Type: Desktop Mobo: MSI model: B85M ECO (MS-7817) v: 5.0
    serial: <superuser required> UEFI: American Megatrends v: 25.8
    date: 02/18/2016
CPU:
  Info: quad core Intel Core i5-4460 [MCP] speed (MHz): avg: 800
    min/max: 800/3400
Graphics:
  Device-1: NVIDIA GF108 [GeForce GT 430] driver: nouveau v: kernel
  Device-2: Logitech Webcam C270 driver: snd-usb-audio,uvcvideo type: USB
  Display: x11 server: X.Org v: 21.1.13 with: Xwayland v: 23.2.6 driver: X:
    loaded: modesetting dri: nouveau gpu: nouveau resolution: 1920x1080
  API: OpenGL v: 4.5 compat-v: 4.3 vendor: mesa v: 24.0.6-arch1.2
    renderer: NVC1
Network:
  Device-1: Intel Ethernet I218-V driver: e1000e
Drives:
  Local Storage: total: 763.85 GiB used: 155.62 GiB (20.4%)
Info:
  Memory: total: 16 GiB available: 15.55 GiB used: 3.03 GiB (19.5%)
  Processes: 232 Uptime: 26m Shell: Bash inxi: 3.3.34

### Other comments

![ged](https://github.com/getsolus/packages/assets/143135556/74eea5fe-4fc2-4ef4-878b-e230311f625b)

**Comment by joebonrichie** [comment]
Upstream issue: https://gitlab.gnome.org/GNOME/gedit/-/issues/590

**Comment by joebonrichie** [comment]
Resolved b3427535e52bcc84a28a170d86d9c4f449108adc

**Comment by brent111** [comment]
thanks for looking into this. should I wait for package fix? or is the gsettings fix the way to go here? thanks

**Comment by malfisya** [comment]
Just wait for the next sync. The changes Joey made was reverting all the weird change upstream made with this release.

**Comment by brent111** [comment]
thank you!
