### ISSUE TITLE
Solus breaks in hibernation (T8055)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#253]
<div dir="rtl"><b>Denis&nbsp;Clopotaritei</b>&nbsp;(<em>&#35;denis</em>),&nbsp;2019-06-16&nbsp;20:01:56&nbsp;UTC</div><br/>

Hello, I'm sorry I have to bother you guys for this, but I am new to Linux and honestly I couldn't get as well as I do with Solus with any other Distro, so I'd really love to have this sorted if possible ? 

Whenever any of my installations go into hibernation, something breaks: 

--On my PackardBell (kinda old computer, but not Moon-landing old) the Network manager just switches off. The computer does not have a built-in Wi-Fi card, so I need a USB (TP-Link) thingy to connect to the router. This just stops working at all. Taking the USB out and back in doesn't work and the only way I found to fix it was rebooting, which would just make hibernation pointless.

--On my Laptop (HP Pavillion Energystar Intel-i5) the menu bar at the bottom (with the start-menu, the applications running, and all the other things. I think it's called task-bar? unsure) just stopped working all-together, I right-clicked the desktop to reach terminal and reboot to make it work again.

--On my University Laptop (HP Notebook -- the worst version the University could find me I suppose) everything works just great. Nothing found that I can complain about relating to hibernation.

Thank you very much in advance, and please guys, make it easier for people to donate to the Solus project and things like that: Ubuntu prompts you to a page as soon as you download their ISO where you can donate however much you want, and Zorin (please don't follow their example, but that's out there) made a Pro version with some additional software preinstalled and touch-screen implementation.
This way at least who wants to contribute towards the project somehow and doesn't have the time to study coding and all them fancy things you know to sort OS problems out can give out some funds towards it.

Good luck and keep making me proud of you,

Denis.

**Comment by TraceyC77** [comment]
Closing this issue due to age and lack of updates.. If this is still an issue for anyone, please open a new bug on our tracker.
