### ISSUE TITLE
manaplus does not build

### ISSUE THREAD

**Issue by androidnisse** [getsolus/packages#2530]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

manaplus does not build. I get the below error:

utils/dumplibs.cpp: In function ‘void dumpLibs()’:
utils/dumplibs.cpp:142:49: error: invalid conversion from ‘const char* const*’ to ‘const char**’ [-fpermissive]
  142 |     const char **xmlVersion = __xmlParserVersion();
      |                               ~~~~~~~~~~~~~~~~~~^~
      |                                                 |
      |                                                 const char* const*
make[1]: *** [Makefile:19531: utils/manaplus-dumplibs.o] Error 1
make[1]: *** Waiting for unfinished jobs....
mv -f resources/.deps/manaplus-wallpaper.Tpo resources/.deps/manaplus-wallpaper.Po
mv -f utils/.deps/manaplus-fuzzer.Tpo utils/.deps/manaplus-fuzzer.Po
mv -f utils/.deps/manaplus-env.Tpo utils/.deps/manaplus-env.Po
make[1]: Leaving directory '/home/build/YPKG/root/manaplus/build/manaplus-v1.9.3.23/src'
make: *** [Makefile:480: all-recursive] Error 1
Command '['/bin/bash', '--norc', '--noprofile', '/tmp/ypkg-build_2hn6gnz']' returned non-zero exit status 2.
[Build] build failed for manaplus
 ✗  Failed to build packages err="Failed to start build of package, reason: exit status 1\n"
task: Failed to run task "build": exit status 1

### Steps to reproduce

1. Try to build the package

### Expected result

It would build.

### Actual result

It does not build.

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

Budgie

### System details

System:
  Host: solus-dev Kernel: 6.8.9-289.current arch: x86_64 bits: 64
  Desktop: Xfce v: 4.18.1 Distro: Solus 4.5 resilience
Machine:
  Type: Virtualbox System: innotek GmbH product: VirtualBox v: 1.2
    serial: <superuser required>
  Mobo: Oracle model: VirtualBox v: 1.2 serial: <superuser required>
    UEFI: innotek GmbH v: VirtualBox date: 12/01/2006
Battery:
  ID-1: BAT0 charge: 17.5 Wh (35.0%) condition: 50.0/50.0 Wh (100.0%)
    volts: 10.0 min: 10.0
CPU:
  Info: quad core 11th Gen Intel Core i5-1135G7 [MCP] speed (MHz): avg: 1382
Graphics:
  Device-1: VMware SVGA II Adapter driver: vmwgfx v: 2.20.0.0
  Display: x11 server: X.Org v: 21.1.13 with: Xwayland v: 23.2.6 driver:
    gpu: vmwgfx resolution: 1360x768~60Hz
  API: OpenGL v: 4.5 vendor: mesa v: 24.0.7 renderer: llvmpipe (LLVM 16.0.6
    256 bits)
Network:
  Device-1: Intel 82540EM Gigabit Ethernet driver: e1000
  Device-2: Intel 82371AB/EB/MB PIIX4 ACPI type: network bridge
    driver: piix4_smbus
Drives:
  Local Storage: total: 32 GiB used: 24.01 GiB (75.0%)
Info:
  Memory: total: 4 GiB available: 3.82 GiB used: 770.2 MiB (19.7%)
  Processes: 231 Uptime: 50m Shell: Zsh inxi: 3.3.34

### Other comments

First this patch is needed to get to this error:
https://gitlab.archlinux.org/archlinux/packaging/packages/manaplus/-/blob/main/fix-missing-ctime-include.patch?ref_type=heads

So there are at least two issues. I have tried to add libxml2-devel as a build dependency but it does not help.

**Comment by algent-al** [comment]
Looks like another patch is needed:
https://gitlab.com/manaplus/manaplus/-/issues/33

**Comment by androidnisse** [comment]
> Looks like another patch is needed: https://gitlab.com/manaplus/manaplus/-/issues/33

Great you got it to work. I found that patch but could not apply it somehow. :)
