### ISSUE TITLE
inkscape crashes

### ISSUE THREAD

**Issue by SethStormR** [getsolus/packages#2532]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

Inkscape crashes every time I try to open a .svg image file.

### Steps to reproduce

1. right click on a .svg file
2. select "Open with Inkscape"

### Expected result

Editing the .svg file in Inkscape.

### Actual result

It crashes with the output of

<pre>
 0# Inkscape::Application::crash_handler(int) in /usr/bin/../lib64/inkscape/libinkscape_base.so.1.3.2.0
 1# 0x00007F8B8E45A300 in /usr/lib64/glibc-hwcaps/x86-64-v3/libc.so.6
 2# 0x00007F8B8DB0EB07 in /usr/bin/../lib64/inkscape/../libgio-2.0.so.0
 3# 0x00007F8B8DB0F5B5 in /usr/bin/../lib64/inkscape/../libgio-2.0.so.0
 4# g_dbus_connection_register_object in /usr/bin/../lib64/inkscape/../libgio-2.0.so.0
 5# g_dbus_connection_export_menu_model in /usr/bin/../lib64/inkscape/../libgio-2.0.so.0
 6# 0x00007F8B8CD2433B in /usr/lib64/gtk-3.0/modules/libappmenu-gtk-module.so
 7# Gtk::Widget_Class::realize_callback(_GtkWidget*) in /usr/bin/../lib64/inkscape/../libgtkmm-3.0.so.1
 8# g_closure_invoke in /usr/bin/../lib64/inkscape/../libgobject-2.0.so.0
 9# 0x00007F8B8DF23D0A in /usr/bin/../lib64/inkscape/../libgobject-2.0.so.0
10# 0x00007F8B8DF25572 in /usr/bin/../lib64/inkscape/../libgobject-2.0.so.0
11# g_signal_emit_valist in /usr/bin/../lib64/inkscape/../libgobject-2.0.so.0
12# g_signal_emit in /usr/bin/../lib64/inkscape/../libgobject-2.0.so.0
13# gtk_widget_realize in /usr/bin/../lib64/inkscape/../libgtk-3.so.0
14# InkscapeWindow::setup_view() in /usr/bin/../lib64/inkscape/libinkscape_base.so.1.3.2.0
15# InkscapeWindow::InkscapeWindow(SPDocument*) in /usr/bin/../lib64/inkscape/libinkscape_base.so.1.3.2.0
16# InkscapeApplication::window_open(SPDocument*) in /usr/bin/../lib64/inkscape/libinkscape_base.so.1.3.2.0
17# InkscapeApplication::create_window(SPDocument*, bool) in /usr/bin/../lib64/inkscape/libinkscape_base.so.1.3.2.0
18# InkscapeApplication::process_document(SPDocument*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) in /usr/bin/../lib64/inkscape/libinkscape_base.so.1.3.2.0
19# InkscapeApplication::on_open(std::vector<Glib::RefPtr<Gio::File>, std::allocator<Glib::RefPtr<Gio::File> > > const&, Glib::ustring const&) in /usr/bin/../lib64/inkscape/libinkscape_base.so.1.3.2.0
20# 0x00007F8B8EAFECC3 in /usr/lib64/libgiomm-2.4.so.1
21# g_closure_invoke in /usr/bin/../lib64/inkscape/../libgobject-2.0.so.0
22# 0x00007F8B8DF23F4B in /usr/bin/../lib64/inkscape/../libgobject-2.0.so.0
23# 0x00007F8B8DF25572 in /usr/bin/../lib64/inkscape/../libgobject-2.0.so.0
24# g_signal_emit_valist in /usr/bin/../lib64/inkscape/../libgobject-2.0.so.0
25# g_signal_emit in /usr/bin/../lib64/inkscape/../libgobject-2.0.so.0
26# 0x00007F8B8DB025B4 in /usr/bin/../lib64/inkscape/../libgio-2.0.so.0
27# g_application_run in /usr/bin/../lib64/inkscape/../libgio-2.0.so.0
28# main in /usr/bin/inkscape
29# 0x00007F8B8E44030E in /usr/lib64/glibc-hwcaps/x86-64-v3/libc.so.6
30# __libc_start_main in /usr/lib64/glibc-hwcaps/x86-64-v3/libc.so.6
31# _start in /usr/bin/inkscape
</pre>
<details><summary>System info</summary>
Inkscape 1.3.2 (091e20ef0f, 2023-11-25)

    GLib version:     2.80.2
    GTK version:      3.24.41
    glibmm version:   2.66.6
    gtkmm version:    3.24.9
    libxml2 version:  2.12.6
    libxslt version:  1.1.37
    Cairo version:    1.18.0
    Pango version:    1.52.2
    HarfBuzz version: 8.4.0

    OS version:       Solus 4.5 Resilience
</details>

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Plasma

### System details

System:
  Host: universe Kernel: 6.8.9-289.current arch: x86_64 bits: 64
  Desktop: KDE Plasma v: 6.0.4 Distro: Solus 4.5 resilience
Machine:
  Type: Desktop Mobo: ASUSTeK model: PRIME X370-A v: Rev X.0x
    serial: <superuser required> UEFI: American Megatrends v: 5222
    date: 10/15/2019
CPU:
  Info: 8-core AMD Ryzen 7 1700X [MT MCP] speed (MHz): avg: 2320
    min/max: 2200/3400
Graphics:
  Device-1: NVIDIA GP104 [GeForce GTX 1070] driver: nvidia v: 550.78
  Display: x11 server: X.Org v: 21.1.13 with: Xwayland v: 23.2.6 driver:
    gpu: nvidia,nvidia-nvswitch resolution: 1920x1080~60Hz
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: nvidia mesa v: 550.78
    renderer: NVIDIA GeForce GTX 1070/PCIe/SSE2
Network:
  Device-1: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet
    driver: r8169
  Device-2: Intel Wi-Fi 6 AX200 driver: iwlwifi
Drives:
  Local Storage: total: 960.33 GiB used: 185.37 GiB (19.3%)
Info:
  Memory: total: 32 GiB available: 31.28 GiB used: 2.38 GiB (7.6%)
  Processes: 377 Uptime: 6m Shell: Zsh inxi: 3.3.34

**Comment by EbonJaeger** [comment]
I can reproduce this. I opened an issue [here](https://gitlab.com/inkscape/inbox/-/issues/10375); I'm wondering if it's related to the GLib update last week.

**Comment by EbonJaeger** [comment]
Someone on Arch also has this issue. Marking as upstream.
