### ISSUE TITLE
onefetch release 7 update fails

### ISSUE THREAD

**Issue by Staudey** [getsolus/packages#2545]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

Running `sudo eopkg up` with a previous release of `onefetch` installed fails on the update to `version 2.21.0, release 7` with the following error 
```
Installing onefetch, version 2.21.0, release 7
Upgrading to new upstream version
Extracting the files of onefetch
 [✓] Syncing filesystems                                                success
System error. Program terminated.
[Errno 21] Is a directory: 'usr/share/bash-completion/completions/onefetch'
```

### Steps to reproduce

1. Install the previous stable `onefetch` version 
`sudo eopkg it https://packages.getsol.us/shannon/o/onefetch/onefetch-2.20.0-5-1-x86_64.eopkg`
2. Run `sudo eopkg up`

### Expected result

onefetch package gets upgraded to `version 2.21.0, release 7`

### Actual result

`sudo eopkg upgrade` fails with above error message

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

Budgie

### System details

```
System:
  Host: solus-pc Kernel: 6.8.9-289.current arch: x86_64 bits: 64
  Desktop: Budgie v: 10.9.1 Distro: Solus 4.5 resilience
Machine:
  Type: Desktop Mobo: MSI model: Z170A PC MATE (MS-7971) v: 2.0
    serial: <superuser required> UEFI-[Legacy]: American Megatrends v: A.60
    date: 12/17/2015
CPU:
  Info: quad core Intel Core i7-6700K [MT MCP] speed (MHz): avg: 4000
    min/max: 800/4200
Graphics:
  Device-1: NVIDIA GP106 [GeForce GTX 1060 6GB] driver: nvidia v: 550.40.61
  Display: x11 server: X.Org v: 21.1.13 with: Xwayland v: 23.2.6 driver: X:
    loaded: nvidia gpu: nvidia,nvidia-nvswitch resolution: 1920x1080~60Hz
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: nvidia mesa v: 550.40.61
    renderer: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2
Network:
  Device-1: Realtek RTL8192CE PCIe Wireless Network Adapter driver: rtl8192ce
  Device-2: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet
    driver: r8169
Drives:
  Local Storage: total: 1.82 TiB used: 769.66 GiB (41.3%)
Info:
  Memory: total: 32 GiB available: 31.31 GiB used: 10.67 GiB (34.1%)
  Processes: 308 Uptime: 1h 24m Shell: Zsh inxi: 3.3.34
```

### Other comments

The corresponding packaging change: https://github.com/getsolus/packages/commit/7a9ab9728499bcf0af8c2098ca512f9d679733dd

The path mentioned in the error message was previously a directory containing the shell completions, while with this commit the path now corresponds to the shell completions file itself

**Comment by EbonJaeger** [comment]
I think this is because the completions were accidentally installed as directories, and eopkg doesn't know how to turn a directory into a file (curse lack of atomic updates). For now, the completions have been removed so we can focus on fixing the `/usr`-merge thing, and we can revisit this later.

**Comment by malfisya** [comment]
Can we consider this solved?

**Comment by Staudey** [comment]
The original issue has been solved. The underlying eopkg issue is still there of course, but that's better handled as a ticket in the eopkg repository directly. I'll create one there.
