### ISSUE TITLE
ALSA doesn't remember volume settings (T4411)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#255]
<div dir="rtl"><b>Peter</b>&nbsp;(<em>&#35;piotrpalek</em>),&nbsp;2017-08-28&nbsp;06:50:14&nbsp;UTC</div><br/>

I have a laptop I use with a dock (Carbon X1 3rd gen) and every time I restart the system or dock / undock the laptop the external sound card I use via USB has it's ALSA volume reset to 50%. This is pretty annoying as it's not obvious why the sound isn't as loud, since the alsa sound settings are "hidden".

**Comment by davidjharder** [comment]
Old, no new info, see Tracey's comment above
