### ISSUE TITLE
Laptop keyboard & touchpad cannot wake system from sleep (T10616)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#256]
<div dir="rtl"><b>TraceyC</b>&nbsp;(<em>@TraceyC77</em>),&nbsp;2023-08-06&nbsp;22:18:24&nbsp;UTC</div><br/>

# If the laptop is set to sleep while docked it cannot be woken with its keyboard or touchpad.

## Steps to reproduce

1. With the system connected to a dock, set it to sleep either with the menu option or a keyboard shortcut
2. Undock the system (unplug the Thunderbolt cable)
3. Attempt to wake the system by pressing the keyboard or touchpad

## Expected result

The system wakes from sleep

## Actual result

Nothing, the system does not respond and stays asleep

## Environment

  - Is system up to date? y 
  - Repo: unstable
  - Desktop Environment Plasma

## System details

Operating System: Solus 4.4
KDE Plasma Version: 5.27.6
KDE Frameworks Version: 5.107.0
Qt Version: 5.15.10
Kernel Version: 6.4.8-247.current (64-bit)
Graphics Platform: X11
Processors: 16 × 11th Gen Intel® Core™ i7-11800H @ 2.30GHz
Memory: 62.5 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2
Manufacturer: Dell Inc.
Product Name: XPS 17 9710

## Other comments 

Workaround: Plug in the dock cable. The external monitor comes on and the system wakes. This is even before plugging in the external mouse and keyboard.

This has been happening for about a week, since very recent updates to the kernel.
I'm not able to test with the 6.3 kernel because I can't get to a graphical environment with that (even with nomodeset). It boots to a black screen with a blinking cursor at the upper left hand corner.

**Comment by TraceyC77** [comment]
This is no longer a problem. I am able to wake the laptop from sleep using the exact reproduction steps. I'm assuming kernel updates fixed it.
