### ISSUE TITLE
Arduino doesn't build

### ISSUE THREAD

**Issue by malfisya** [getsolus/packages#2564]
Building `arduino` from the recipe as-is is failing right now

**Comment by HarveyDevel** [comment]
This patch fixes the package build https://gist.github.com/HarveyDevel/22b25c8b2929991b859242272d61721e (Patch was modified for file paths due us not building arduno-ctags as its own package).

Patch must be applied after line 58 (after arduino-ctags source is extracted). It builds but the package has not been tested.

A new contributor had expressed interest in submitting this fix so I haven't submitted it myself. Commenting here in case that does not occur and someone else wants to tackle it.
