### ISSUE TITLE
yasm doesn't build

### ISSUE THREAD

**Issue by malfisya** [getsolus/packages#2569]
Building `yasm` from the recipe as-is is failing right now

**Comment by androidnisse** [comment]
This one builds if I use the latest commit. However the author doesn't want to create new releases. https://github.com/yasm/yasm/issues/235 So I don't know what to do here. If I can use the latest commit or not. Fedora seems to do so.

**Comment by malfisya** [comment]
Judging from past converstion about [other package](https://matrix.to/#/!oxwGTPuyIYEUPjFVbL:matrix.org/$twGFCza-1Wkk99338C4DxusjzpwI130fr3TIjAlyyU8?via=matrix.org&via=kde.org&via=envs.net) . It seems you can use git commit hash, just append x.99 to version number so we know it is not official release
