### ISSUE TITLE
wine-nine-standalone doesn't build

### ISSUE THREAD

**Issue by malfisya** [getsolus/packages#2571]
Building `wine-nine-standalone` from the recipe as-is is failing right now. This error popped up : 
 `meson.build:62:14: ERROR: C shared or static library 'dl' not found`

**Comment by algent-al** [comment]
Also as the recipe as it is, still requires `wine-32bit-devel` which is deprecated [here](https://github.com/algent-al/solus-sc/commit/8677373e34c68f14fe60768c2cc7f9a35f52e6e8)

**Comment by malfisya** [comment]
Probably want to deprecate this too? Is there still a use case for this ? Let me look into this

**Comment by Staudey** [comment]
Related: https://www.phoronix.com/news/Mesa-Gallium3D-Nine-Sunset

**Comment by malfisya** [comment]
RIP. Deprecation PR incoming.
