### ISSUE TITLE
Intel-One-Mono Font

### ISSUE THREAD

**Issue by uni-dos** [getsolus/packages#2580]
### Please confirm there isn't an existing package request

- [X] I have searched through package requests

### Homepage

https://www.intel.com/content/www/us/en/company-overview/one-monospace-font.html

### Maintainer

- [X] Would you like to be the maintainer for this package?

### Why should this be included in the repository?

This is an alternative font intended for programmers. Hack, Firacode, and jetbrains mono are good programming fonts and adding one more does not hurt.

### Are we allowed to redistribute it?

 OFL-1.1

### What kind of user will use this package, and how many users do you think will use this package?

People who like to customize their desktops and workflows.

### Link to source archive file

https://github.com/intel/intel-one-mono/archive/refs/tags/V1.3.0.tar.gz

**Comment by EbonJaeger** [comment]
One compelling reason for this font is that it was made specifically with people with vision impairment in mind, something that I'm not sure is true of other programming fonts.

**Comment by davidjharder** [comment]
Fonts are fun
