### ISSUE TITLE
Update openconnect to 9.12

### ISSUE THREAD

**Issue by ammunoz** [getsolus/packages#2584]
### Please confirm there isn't already an existing package update request

- [X] I have searched through package update requests

### Name

openconnect

### Version

9.12

### Link to the release notes or announcement.

https://www.infradead.org/openconnect/changelog.html

### Reason for updating

OpenConnect on solus repos are still on version 8.10 which released 4 years ago. This version of OpenConnect is keeping me from connecting to corporate vpn. I imagine it's affecting others as well.

The openconnect project doesn't seem to use gitlab's release feature but their changelog page seems to imply that the versions listed on there are stable versions.

This is a link to the most recently tagged version:
https://gitlab.com/openconnect/openconnect/-/tree/v9.12

**Comment by davidjharder** [comment]
This builds fine when I bump it to 9.12. Any idea how to test it? Are there public VPNs that use this?

**Comment by ammunoz** [comment]
> This builds fine when I bump it to 9.12. Any idea how to test it? Are there public VPNs that use this?

Great to hear! Appreciate you taking a stab at this.

I don't actually know of a good way for you to test it without setting up a vpn server yourself, which is going to be a hassle. Is there any way I can test it for you? Is that a thing?

I'm on stable repos still but I think you can share a *.eopkg file that I can install locally right?

**Comment by davidjharder** [comment]
Re: testing: That's what I figured.

I will share a test eopkg after the next sync (likely Friday). Right now the package would not install on a stable system. Are you in our matrix room by chance?

**Comment by ammunoz** [comment]
#2654 seems to also be necessary for networkmanager-openconnect to authenticate via 2fa

**Comment by androidnisse** [comment]
I can test this with a Any Connect connection if that helps.

**Comment by davidjharder** [comment]
@androidnisse that would be great

**Comment by androidnisse** [comment]
> @androidnisse that would be great

It could connect the tunnel I tried, but I never got any MFA prompt which is needed so it got to authentication failure.

**Comment by androidnisse** [comment]
@davidjharder I got this to work now. I managed to test with another vpn/firewall and there I got the MFA prompt. So something funky with the first one I tried.
