### ISSUE TITLE
iOS screen glitch (AppStore version)

### ISSUE THREAD

**Issue by JD9871** [getsolus/packages#2585]
Having graphical issues on the AppStore release of retrarch 1.18.0 [https://github.com/getsolus/packages/assets/164794137/1557ad51-482e-4b5b-8dec-0915759bab3f]()

https://github.com/getsolus/packages/assets/164794137/645f73eb-a4c8-40f6-b226-eb70f0d85b5d

**Comment by malfisya** [comment]
I think you filed this issue on the wrong place. This issue tracker is meant for [Solus](https://getsol.us/), a Linux-based operating system that is designed for home computing. What you are showing is looks like RetroArch, please file your issue [there](https://github.com/libretro/RetroArch/issues). Thank you.

**Comment by JD9871** [comment]
So sorry idk how I did that when trying to send an issue
