### ISSUE TITLE
Removing Chinese (China) Input Sources causes problems in Displays (T1695)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#26]
<div dir="rtl"><b>lange&nbsp;icarus</b>&nbsp;(<em>&#35;icarus</em>),&nbsp;2016-11-22&nbsp;11:59:25&nbsp;UTC</div><br/>

When I removed the Chinese (China) Input Sources from Region & Language setting, these problems were observed:
1) The Displays setting would appear blank
2) Background's wallpaper would be restored back to the default one
3) Changing of background's wallpaper would not work
4) Clicking on Budgie Menu button and Raven Sidebar indicator would blackout the desktop
5) All minimize, maximize button on application windows were missing (except in-built system apps)

Once I reinstated the input source, all these issues were resolved.

**Comment by TraceyC77** [comment]
If this can be reproduced with an up to date version of Budgie, please create a new issue. Thanks.
