### ISSUE TITLE
Sound not playing through headphones (T8563)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#261]
<div dir="rtl"><b>mate-user</b>&nbsp;(<em>&#35;mate-user</em>),&nbsp;2019-12-29&nbsp;18:01:56&nbsp;UTC</div><br/>

I think after the last update on Friday 27th Dec 2019, sound is not playing on my headphones.
In Sound Preferences > Output, Connector is stuck on Speakers.
In Terminal, lspci shows a different CPU to the one on my laptop. My laptop has Intel Core i5-8250U, but lspci shows Xeon E3-1200:
{F5479098}
Maybe sound isn't playing because Solus or the kernel is detecting my hardware incorrectly ?
Update:
I restarted with the previous kernel 5.3.15, sound didn't work there. On the latest kernel 5.3.18, no sound either.
Last night I was playing Diablo 2 LoD on my original Windows 10 partition, and I left my laptop unplugged and it went into hibernation or something and became unresponsive, so I forced it off. Could this be the reason my sound is messed up on Solus ? Some sound configuration got locked to Windows or the BIOS ?
Sound plays fine though my headphones on Windows 10.

**Comment by TraceyC77** [comment]
Closing due to age. If this is still an issue for anyone, please open a new bug on our tracker.
