### ISSUE TITLE
Deprecate unittest-cpp

### ISSUE THREAD

**Issue by malfisya** [getsolus/packages#2613]
### Please confirm there isn't already an existing package deprecation request

- [X] I have searched through package deprecation requests

### Name

unittest-cpp

### Last Update Date

14-01-2017

### Link to an announcement of archival or deprecation, if applicable.

https://github.com/unittest-cpp/unittest-cpp/issues/180

### Reason for deprecation

There is no new release since 2017. The has been on hiatus since 26 November 2020. I also don't found this package as revdeps.

**Comment by androidnisse** [comment]
Duplicate of https://github.com/getsolus/packages/issues/2045

**Comment by malfisya** [comment]
Clearly, I lied about searching the issue😆. Closing
