### ISSUE TITLE
nano-syntax-highlighting

### ISSUE THREAD

**Issue by malfisya** [getsolus/packages#2615]
### Please confirm there isn't an existing package request

- [X] I have searched through package requests

### Homepage

https://github.com/galenguyer/nano-syntax-highlighting

### Maintainer

- [ ] Would you like to be the maintainer for this package?

### Why should this be included in the repository?

This is a fork of unmaintained `nanorc`

### Are we allowed to redistribute it?

GPL-3.0-or-later

### What kind of user will use this package, and how many users do you think will use this package?

nano user

### Link to source archive file

https://github.com/galenguyer/nano-syntax-highlighting/archive/refs/tags/2022.11.02.tar.gz

**Comment by androidnisse** [comment]
I will try to package this.
