### ISSUE TITLE
Deprecate nitroshare-desktop

### ISSUE THREAD

**Issue by malfisya** [getsolus/packages#2627]
### Please confirm there isn't already an existing package deprecation request

- [X] I have searched through package deprecation requests

### Name

nitroshare-desktop

### Last Update Date

13-10-2017

### Reason for deprecation

Last release 2017. Last activity in repository is 5 years ago

**Comment by davidjharder** [comment]
Note: `localsend` looks like a decent alternative https://github.com/localsend/localsend

**Comment by malfisya** [comment]
For sending files between devices on the same local network, we also already have `warpinator` in repo.
