### ISSUE TITLE
Synaptics Touchpad only partially working after resuming from hibernate/suspend (T5023)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#264]
<div dir="rtl"><b>Tim&nbsp;Leonhard</b>&nbsp;(<em>&#35;timleonhard</em>),&nbsp;2017-11-14&nbsp;10:36:33&nbsp;UTC</div><br/>

Hey guys, 
after resuming from hibernate/suspend the touchpad on my Lenovo-X240 is sometimes lacking the two-finger-scroll-function. After rebooting the system everything is ok again. The issue occurs with and without xorg-driver-input-synaptics installed.

**Comment by davidjharder** [comment]
Old, no new info, closing
