### ISSUE TITLE
Chronic LibreOffice launch error popup

### ISSUE THREAD

**Issue by brent111** [getsolus/packages#2650]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

https://discuss.getsol.us/d/10612-whats-with-this-libre-office-startup-message/16

Could get no help at forum. 
How do I get rid of this message?
Is me installing JDK the only way I can run LibreOffice in Solus?

### Steps to reproduce

1-Launch LibreOffice Writer

### Expected result

LibreOffice Writer opens a new Writer document.

### Actual result

Annoying popup window asking me to install JDK pops up. I have to hit "NO" I dont want to install right now. then app launches.

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Budgie

### System details

Host: workstation Kernel: 6.8.10-291.current arch: x86_64 bits: 64
  Desktop: Budgie v: 10.9.1 Distro: Solus 4.5 resilience
Machine:
  Type: Desktop Mobo: MSI model: B85M ECO (MS-7817) v: 5.0
    serial: <superuser required> UEFI: American Megatrends v: 25.8
    date: 02/18/2016
CPU:
  Info: quad core Intel Core i5-4460 [MCP] speed (MHz): avg: 800
    min/max: 800/3400
Graphics:
  Device-1: NVIDIA GF108 [GeForce GT 430] driver: nouveau v: kernel
  Device-2: Logitech Webcam C270 driver: snd-usb-audio,uvcvideo type: USB
  Display: x11 server: X.Org v: 21.1.13 with: Xwayland v: 23.2.6 driver: X:
    loaded: nouveau unloaded: fbdev,modesetting,vesa dri: nouveau gpu: nouveau
    resolution: 1920x1080
  API: OpenGL v: 4.5 compat-v: 4.3 vendor: mesa v: 24.0.7 renderer: NVC1
Network:
  Device-1: Intel Ethernet I218-V driver: e1000e
Drives:
  Local Storage: total: 763.85 GiB used: 99.22 GiB (13.0%)
Info:
  Memory: total: 16 GiB available: 15.56 GiB used: 4.57 GiB (29.4%)
  Processes: 297 Uptime: 2h 18m Shell: Bash inxi: 3.3.34

### Other comments

unsuccessful uploading picture after 15 minutes.

**Comment by brent111** [comment]
![writer resized](https://github.com/getsolus/packages/assets/143135556/66e8902b-f3a2-48ff-be51-72286ff3bf60)

**Comment by brent111** [comment]
Yes. Annoying but there are worse things. Thank you for following up.
For the record I `rm`'d & re-`it`'d all libre base/common elements. No change.

A forum user suggested trashing all `/home` and `/root` folders of Libre and purge the system. I was not comfortable trying that but I can.

**Comment by malfisya** [comment]
>A forum user suggested trashing all /home and /root folders of Libre and purge the system.

Lets not do that.

I am having trouble reproducing the bug, I will tell you if I found anything. Cheers!

**Comment by brent111** [comment]
Is the reason you are having trouble reproducing the bug is because you are enabling the use of JRE?

**Comment by malfisya** [comment]
Things I try to reproduce it:
- Enable/disable  "Use java runtime environment" 
- Install/uninstall `openjdk-11`, `openjdk-17`, or `openjdk-21` 
- Run it via terminal or desktop
- Gnome/Budgie/Plasma/Xfce

So far , couldn't found anything.

**Comment by brent111** [comment]
I

> Things I try to reproduce it:
> 
>     * Enable/disable  "Use java runtime environment"
> 
>     * Install/uninstall `openjdk-11`, `openjdk-17`, or `openjdk-21`
> 
>     * Run it via terminal or desktop
> 
>     * Gnome/Budgie/Plasma/Xfce
> 
> 
> So far , couldn't found anything.

Will try that stuff and get back.

**Comment by brent111** [comment]
Since no one can Solve this, I caved in and installed JDK22 to get rid of that annoying popup. Will mark Solved.
