### ISSUE TITLE
Update networkmanager to 1.46

### ISSUE THREAD

**Issue by ammunoz** [getsolus/packages#2654]
### Please confirm there isn't already an existing package update request

- [X] I have searched through package update requests

### Name

networkmanager

### Version

1.46

### Link to the release notes or announcement.

https://networkmanager.dev/blog/networkmanager-1-46/

### Reason for updating

NetworkManager 1.46 brings in plug-in support for 2fa which is necessary for a lot of corporate vpns.

**Comment by ReillyBrogan** [comment]
Thanks for the report, I was already aware of the release of 1.46 and am waiting for 1.46.1 or 1.46.2 to update our package to it. Considering how integral NetworkManager is to the desktop we tend to be very conservative with it. Given the rate that upstream releases new versions I would not expect this update for several months at least.

**Comment by ammunoz** [comment]
I understand the caution though that's quite unfortunate to hear. NetworkManager 1.46 seems to be necessary for me to connect to company vpn for the 2fa support.
