### ISSUE TITLE
[RFC] Needs Maintainer: Julia (T10611)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#266]
<div dir="rtl"><b>Joey&nbsp;Riches</b>&nbsp;(<em>@joebonrichie</em>),&nbsp;2023-08-04&nbsp;21:54:39&nbsp;UTC</div><br/>

Repo: R1510
Homepage: https://julialang.org/

As part of a sweeping effort I am doing to reduce outdated package count, begin regularly enforcing maintainership file inclusion in old(er) repos, and increase the likelihood of a package having a maintainer (should it be required, outside of those being handled by Solus Staff, this task is being created to effectively "notify" the current maintainer of the package that it needs to be updated or modified to indicate its maintainership and ensure it is regularly maintained. In the event there is no specific maintainer, either one may be specified that has regularly updated it in the past, or this task shall also be considered an RFC for a new maintainer.

During the patch submission process, the MAINTAINERS.md file should be included if it is not already, and have the following content (replace REPLACEME with the correct value):

Without a dedicated maintainer julia is difficult for maintain and we will encourage users to [install it directly from upstream](https://julialang.org/downloads/)

**Comment by FriesischScott** [comment]
Should this go into a new package or just update the current one?

**Comment by joebonrichie** [comment]
New package juliaup, which has a `replaces: julia` key in the package.yml and we deprecate julia
