### ISSUE TITLE
kernel Oops / General Protection Fault / NULL pointer dereference on write operations on samba smb:// mounts

### ISSUE THREAD

**Issue by ermo** [getsolus/packages#2677]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

Certain write operations to a mounted smb:// share in the Dolphin file manager appear to cause kernel BUG/Oops/GPF events.

#####  `/etc/samba/smb.conf` repro_share configuration on server:

        [repro_share]
                comment = solus kernel oops repro_share
                path = /srv/repro_share
                public = no
                writeable = yes
                write list = your_user
                printable = no
                force group = users
                create mask = 0644
                directory mask = 2775

##### creation of repro_share on server filesystem

        sudo mkdir -pv /srv/repro_share
        sudo chown -c your_user:users /srv/repro_share
        # setting the setgid bit on repro_share keeps the rws permissions and group
        # ownership on newly created directories inside the share
        sudo chmod -c g+rws /srv/repro_share
        ls -ld /srv/repro_share

##### ensure samba picks up the new share definition

        sudo systemctl restart smb
        sudo smbstatus
        sudo smbclient -U your_user -L //localhost

##### mount point setup

    sudo mkdir -pv /mnt/repro_share

##### /etc/fstab line on client

    # please double check uid and gid for your user in, say, /etc/passwd or with ls -lan ${HOME}
    //server/repro_share /mnt/repro_share cifs noauto,_netdev,username=your_user,uid=1000,gid=100,file_mode=00644,dir_mode=02755,vers=3.1.1,sec=ntlmssp  0   0

##### Mount the share

        sudo systemctl daemon-reload # systemctl will need to refresh its internal /etc/fstab representation
        sudo mount /mnt/repro_share

#### Repro steps after doing the above

1. Install dbginfo for better debugging output:
   - `sudo eopkg it {linux-current,glibc,kate,kio,kio-fuse,kio-extras,kio-admin}-dbginfo`
1. Open dolphin and navigate to the mounted /mnt/repro_share
1. Right click in empty dir, select "Create New Text File" and save it as "test.txt"
1. Double click on "test.txt" (should open in an editor -- this makes it hang for me with the above steps)
1. If it doesn't hang, write the word "foo" and save the file (on my end, this has exhibited hangs)
1. If the above didn't hang, close kwrite and delete the file to the Recycle Bin (on my end with an existing file, this has exhibited hangs)
1. If you see a hang, open a terminal and type in `sudo dmesg` and check for a kernel oops
1. Any attempt to create a new file on the SMB share afterwards fails and makes Dolphin or the App in which the file is created hang in my tests

kernel oops output from `dmesg`:
- [kernel-bug-oops-kio-and-kwrite.txt](https://github.com/getsolus/packages/files/15409270/kernel-bug-oops-kio-and-kwrite.txt)
- [oops-when-creating-new-file-on-mounted-smb-drive.txt](https://github.com/getsolus/packages/files/15415875/oops-when-creating-new-file-on-mounted-smb-drive.txt)
- [kernel-bug-oops-opening-kwrite.txt](https://github.com/getsolus/packages/files/15421146/kernel-bug-oops-opening-kwrite.txt)

### Expected result

Mount a read/write smb share and create/save/delete files as normal with no observed hangs or Kernel BUG/Oops/GPF events.

### Actual result

Mount a read/write smb share and create/save/delete files, Dolphin hangs and the system experiences reproducible Kernel BUG/Oops/GPF events.

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

Plasma

### System details

Operating System: Solus 4.5
KDE Plasma Version: 6.0.4
KDE Frameworks Version: 6.2.0
Qt Version: 6.7.1
Kernel Version: 6.8.10-291.current (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 2700X Eight-Core Processor
Memory: 31,3 GiB of RAM
Graphics Processor: AMD Radeon RX 580 Series

**Comment by TraceyC77** [comment]
I'm not able to follow the reproduction steps. By default, mount.cifs is not setuid, so I need to use sudo to mount the samba share. Thus, my user is not able to create a file in the mounted directory.

Do you have anything set up that allows your normal user to use the mount command as written?
Or is there something else that might be missing from the steps?

Also wanted to note that after mounting a samba share, I didn't see any errors in dmesg.

**Comment by ermo** [comment]
> I'm not able to follow the reproduction steps. By default, mount.cifs is not setuid, so I need to use sudo to mount the samba share. Thus, my user is not able to create a file in the mounted directory.
> 
> Do you have anything set up that allows your normal user to use the mount command as written? Or is there something else that might be missing from the steps?
> 

I added a  `sudo` prefix to the command.

> Also wanted to note that after mounting a samba share, I didn't see any errors in dmesg.

The errors only show up after I attempt to write/delete on the mounted share (never seen things behave like that before, despite having used the exact same type of setup for literally as long as I've been maintaining Samba, because it gives higher throughput this way).

**Comment by TraceyC77** [comment]
Thanks for the updated reproduction steps. I also got errors in dmesg after trying to edit the text file I created, but not an oops. I got a general protection fault. Attaching.

[samba_kernel_gen_proteciton_fault.txt](https://github.com/getsolus/packages/files/15421377/samba_kernel_gen_proteciton_fault.txt)

**Comment by TraceyC77** [comment]
Today I can't even browse samba mounts with Dolphin. I see the error
"The process for the smb://htpc protocol died unexpectedly."

I see more general protection faults in the logs

**Comment by ReillyBrogan** [comment]
Is this an issue with the LTS kernel as well?

**Comment by TraceyC77** [comment]
I can't test on the XPS with the LTS kernel because Plasma won't start with that kernel
(I've tried removing all the optional kernel boot parameters one by one but no joy)
However, this may be related to something in the Plasma settings.

I'm able to browse samba shares in Dolphin on my Flex, running the same kernel and version of Plasma and version of Dolphin (both systems are on unstable)

Kernel 6.8.11-292.current
Dolphin 24.02.2

Also, I remembered about [this upstream bug](https://bugs.kde.org/show_bug.cgi?id=483897) which was opened in March. I'm adding debug info to it. I'll keep this issue open so if other Solus users have the problem, and don't search the KDE bug tracker, hopefully they can find this issue.

**Comment by Jezurko** [comment]
Hey, I've been having similar issue as described by @TraceyC77, although for me it's a page fault caused by null pointer dereference.
The thing is, I'm not using KDE software and therefore it's not triggered by kioworker.
I am using caja as a file browser and gedit to edit a text file. I am able to perform some small writes, but if I try to add something bigger to the file (I tried few hundred characters) it triggers the bug.
I have also encountered this when using restic (which is how I discovered it). It was basically unable to write any files and just hangs infintely.

I have been using the same samba share for a long time and it suddenly stopped working a few weeks ago.

Not sure what's the correct place where should I report this bug, as I don't think it's KDE related. I can provide the systemd/dmesg log documenting the kernel error, if relevant.

**Comment by ermo** [comment]
> Not sure what's the correct place where should I report this bug, as I don't think it's KDE related. I can provide the systemd/dmesg log documenting the kernel error, if relevant.

Please do!

And thanks for the report, +1 informative!

**Comment by Jezurko** [comment]
Huh, looking at the `systemd` log I also noticed some `gvfsd` issues, that I didn't see earlier because they were far away from the GPF.
```
čen 11 18:50:59 paddle gvfsd[2202]: smbXcli_negprot_smb1_done: No compatible protocol selected by server.
čen 11 18:50:59 paddle gvfsd[2202]: smbXcli_negprot_smb1_done: No compatible protocol selected by server.
čen 11 18:50:59 paddle gvfsd-network[2188]: GFileInfo created without standard::content-type
čen 11 18:50:59 paddle gvfsd-network[2188]: file ../gio/gfileinfo.c: line 1821 (g_file_info_get_content_type): should not be reached
čen 11 18:50:59 paddle gvfsd-network[2188]: g_ref_string_new_intern: assertion 'str != NULL' failed
čen 11 18:50:59 paddle gvfsd-network[2188]: GFileInfo created without standard::content-type
čen 11 18:50:59 paddle gvfsd-network[2188]: file ../gio/gfileinfo.c: line 1821 (g_file_info_get_content_type): should not be reached
čen 11 18:50:59 paddle gvfsd-network[2188]: g_ref_string_new_intern: assertion 'str != NULL' failed
čen 11 18:50:59 paddle gvfsd-network[2188]: GFileInfo created without standard::content-type
čen 11 18:50:59 paddle gvfsd-network[2188]: file ../gio/gfileinfo.c: line 1821 (g_file_info_get_content_type): should not be reached
čen 11 18:50:59 paddle gvfsd-network[2188]: g_ref_string_new_intern: assertion 'str != NULL' failed
čen 11 18:50:59 paddle gvfsd-network[2188]: g_ref_string_release: assertion 'str != NULL' failed
čen 11 18:50:59 paddle gvfsd-network[2188]: g_ref_string_release: assertion 'str != NULL' failed
čen 11 18:50:59 paddle gvfsd-network[2188]: GFileInfo created without standard::content-type
čen 11 18:50:59 paddle gvfsd-network[2188]: file ../gio/gfileinfo.c: line 1821 (g_file_info_get_content_type): should not be reached
čen 11 18:50:59 paddle gvfsd-network[2188]: g_ref_string_new_intern: assertion 'str != NULL' failed
čen 11 18:50:59 paddle gvfsd-network[2188]: GFileInfo created without standard::content-type
čen 11 18:50:59 paddle gvfsd-network[2188]: file ../gio/gfileinfo.c: line 1821 (g_file_info_get_content_type): should not be reached
čen 11 18:50:59 paddle gvfsd-network[2188]: g_ref_string_new_intern: assertion 'str != NULL' failed
čen 11 18:50:59 paddle gvfsd-network[2188]: GFileInfo created without standard::content-type
čen 11 18:50:59 paddle gvfsd-network[2188]: file ../gio/gfileinfo.c: line 1821 (g_file_info_get_content_type): should not be reached
čen 11 18:50:59 paddle gvfsd-network[2188]: g_ref_string_new_intern: assertion 'str != NULL' failed
čen 11 18:50:59 paddle gvfsd-network[2188]: g_ref_string_release: assertion 'str != NULL' failed
čen 11 18:50:59 paddle gvfsd-network[2188]: g_ref_string_release: assertion 'str != NULL' failed
čen 11 18:50:59 paddle gvfsd-network[2188]: g_ref_string_release: assertion 'str != NULL' failed
čen 11 18:50:59 paddle gvfsd-network[2188]: GFileInfo created without standard::content-type
čen 11 18:50:59 paddle gvfsd-network[2188]: file ../gio/gfileinfo.c: line 1821 (g_file_info_get_content_type): should not be reached
čen 11 18:50:59 paddle gvfsd-network[2188]: g_ref_string_new_intern: assertion 'str != NULL' failed
čen 11 18:50:59 paddle gvfsd-network[2188]: GFileInfo created without standard::content-type
čen 11 18:50:59 paddle gvfsd-network[2188]: file ../gio/gfileinfo.c: line 1821 (g_file_info_get_content_type): should not be reached
čen 11 18:50:59 paddle gvfsd-network[2188]: g_ref_string_new_intern: assertion 'str != NULL' failed
čen 11 18:50:59 paddle gvfsd-network[2188]: GFileInfo created without standard::content-type
čen 11 18:50:59 paddle gvfsd-network[2188]: file ../gio/gfileinfo.c: line 1821 (g_file_info_get_content_type): should not be reached
čen 11 18:50:59 paddle gvfsd-network[2188]: g_ref_string_new_intern: assertion 'str != NULL' failed
čen 11 18:50:59 paddle gvfsd-network[2188]: g_ref_string_release: assertion 'str != NULL' failed
čen 11 18:50:59 paddle gvfsd-network[2188]: g_ref_string_release: assertion 'str != NULL' failed
čen 11 18:50:59 paddle gvfsd-network[2188]: g_ref_string_release: assertion 'str != NULL' failed
čen 11 18:50:59 paddle gvfsd-network[2188]: g_file_info_set_content_type: assertion 'content_type != NULL' failed
čen 11 18:50:59 paddle gvfsd-network[2188]: g_file_info_set_content_type: assertion 'content_type != NULL' failed
čen 11 18:50:59 paddle gvfsd-network[2188]: g_file_info_set_content_type: assertion 'content_type != NULL' failed
```
I tried looking into it and discovered this [Linux Mint forum post](https://forums.linuxmint.com/viewtopic.php?t=363511) mentioning [Ubuntu Launchpad report](https://bugs.launchpad.net/ubuntu/+source/gvfs/+bug/1828107).

But I don't understand this, as I believe `cifs` should not interact with `gvfs`, right? For the record, my mount is created using  `systemd` mount service

**Comment by TraceyC77** [comment]
I don't think gvfs is related to this particular failure. The upstream [gvfs bug](https://gitlab.gnome.org/GNOME/gvfs/-/issues/307) was fixed (apparently Ubuntu still has to implement it in their distro)

Also, while I have those same gvfsd errors in my logs, they do *not* appear when I trigger the bug (by attempting to browse a Samba share in Dolphin).

**Comment by TraceyC77** [comment]
Interestingly, I was able to browse Samba shares from a live environment on the 4.6 RC 2024-10-09 ISO in a VM. I was also able to write to files and access them on the host.

**Comment by Jezurko** [comment]
Seems like mine also started working! Uploaded few hundred megabytes through samba. I'm just on the standard Solus repository with all updates applied

**Comment by TraceyC77** [comment]
I am no longer able to reproduce the bug with the original reproduction steps. 
@ermo , can you still reproduce? If not, we should close this. If you can, please re-test with Plasma 6.2 when we release it.

**Comment by ermo** [comment]
I can no longer reproduce this.

Closing.
