### ISSUE TITLE
Vscodium

### ISSUE THREAD

**Issue by Renarde-dev** [getsolus/packages#2678]
### Please confirm there isn't an existing package request

- [X] I have searched through package requests

### Homepage

https://vscodium.com/

### Maintainer

- [ ] Would you like to be the maintainer for this package?

### Why should this be included in the repository?

While VScodium has a flatpak, it's a lot more practical as a native package. The VScode version in the repo seems to be VScode OSS and while being similar it's not really the same as Vscodium.

### Are we allowed to redistribute it?

MIT

### What kind of user will use this package, and how many users do you think will use this package?

Mainly developers and student that want a lightweight and modular editor.

### Link to source archive file

https://github.com/VSCodium/vscodium/releases/download/1.89.1.24130/VSCodium-1.89.1.24130-src.tar.gz

**Comment by silkeh** [comment]
> The VScode version in the repo seems to be VScode OSS and while being similar it's not really the same as Vscodium.

Can you elaborate on what the value add of VScodium is?

**Comment by vyvir** [comment]
> > The VScode version in the repo seems to be VScode OSS and while being similar it's not really the same as Vscodium.
> 
> Can you elaborate on what the value add of VScodium is?

VSCodium does a more thorough job of removing MS telemetry access compared to Code - OSS. It also maintains its own extensions store to ensure complete absence of telemetry on there.

**Comment by ReillyBrogan** [comment]
I understand the desire for this, but frankly building and maintaining vscode is a PITA and we're not going to maintain a second package of essentially the same thing. This is available as a maintained flatpak, please use that.

**Comment by vyvir** [comment]
> I understand the desire for this, but frankly building and maintaining vscode is a PITA and we're not going to maintain a second package of essentially the same thing. This is available as a maintained flatpak, please use that.

Unfortunate, but understandable. 
I am switching from Solus. Cheers.
