### ISSUE TITLE
Darkest Dungeon installed via Steam closes when performing any system action like volume up and down (T5438)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#27]
<div dir="rtl"><b>Nikki&nbsp;Kononov</b>&nbsp;(<em>&#35;Nikki1993</em>),&nbsp;2018-01-02&nbsp;12:56:52&nbsp;UTC</div><br/>

Pretty much in the description. I installed darkest dungeon via steam, have linux steam integration app installed and run with default settings. Whenever I increase or decrease volume, I see a bubble appearing with volume and the game closes as if it crashed.

Here is a brief log with app closed at the end 

https://gist.github.com/Nikki1993/fed3496ca9e782c097fa3a92392b0009

**Comment by davidjharder** [comment]
Old as dirt. Closing.
