### ISSUE TITLE
leveldb doesn't build

### ISSUE THREAD

**Issue by malfisya** [getsolus/packages#2702]
Building leveldb from the recipe as-is is failing right now

**Comment by GZGavinZhao** [comment]
Passing for me as of 33e86d818ed3573bcedfd3a0515dda2cb5bce614. Please re-open if otherwise.

**Comment by malfisya** [comment]
Still does not build for me. Attached build error: https://gist.github.com/malfisya/333a632192dec9f450df9c38a547f7b5

**Comment by A108384** [comment]
Also fails for me with the same build error as noted above.

**Comment by androidnisse** [comment]
This will build if we use the latest commit. So somewhere this has been fixed. If we find the commit that fix this we can just backport that patch.
