### ISSUE TITLE
Php7.4

### ISSUE THREAD

**Issue by elite6adger** [getsolus/packages#2730]
### Please confirm there isn't an existing package request

- [X] I have searched through package requests

### Homepage

Https://www.Homicity.com

### Maintainer

- [ ] Would you like to be the maintainer for this package?

### Why should this be included in the repository?

To develop in PHP there are two flavours of PHP 8 and 7. Would it be possible to have a seperate PHP7 package to allow for us developers to have both installed? It would make supporting our projects better. I know there is a history of installing php7 in the past so hopefully it is just a re-packing of an older package with a different name. Ideally the php7 package would need to be the latest of the that major version which as of writing this is 7.4

### Are we allowed to redistribute it?

MIT

### What kind of user will use this package, and how many users do you think will use this package?

Full stack developers 

### Link to source archive file

https://github.com/php/php-src/archive/refs/tags/php-7.4.31.tar.gz

**Comment by silkeh** [comment]
Thanks for the request!

> https://www.homicity.com/

I don't think that's the PHP homepage? 😅 

> Would it be possible to have a seperate PHP7 package to allow for us developers to have both installed?

PHP 7.4 is [no longer supported](https://www.php.net/supported-versions.php) and therefore [dead on arrival](https://help.getsol.us/docs/packaging/procedures/package-inclusion#software-age). This means that we won't include it in the repository.
