### ISSUE TITLE
Kamoso (T10461)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#274]
<div dir="rtl"><b>Thomas</b>&nbsp;(<em>&#35;tgorzka</em>),&nbsp;2022-12-25&nbsp;18:19:47&nbsp;UTC</div><br/>

**Name:** Kamoso
**Website: ** https://invent.kde.org/multimedia/kamoso
**Why should this be included in the repository?:** ....
**Is it Open Source:** yes
**Who and how many users do you anticipate will use this software?:** ...
**Link to source tarball/zip file:** https://invent.kde.org/multimedia/kamoso/-/archive/v22.12.0/kamoso-v22.12.0.tar.gz

**Comment by Justinzobel** [comment]
@joebonrichie do you still have the package.yml for this?

**Comment by joebonrichie** [comment]
> @joebonrichie do you still have the package.yml for this?

No :(

**Comment by Justinzobel** [comment]
All good just checking before I do it.

**Comment by palto42** [comment]
@Justinzobel @celticmagic I'm using another webcam tool [webcamoid](https://webcamoid.github.io/) which is based on C++ and Qt. If you are interested, you can find the `package.yml` in my fork of solus packages in the [branch webcamoid](https://github.com/palto42/solus-packages/tree/webcamoid/packages/w/webcamoid).
For me it works fine on Solus Budgie.

**Comment by Justinzobel** [comment]
> @Justinzobel @celticmagic I'm using another webcam tool [webcamoid](https://webcamoid.github.io/) which is based on C++ and Qt. If you are interested, you can find the `package.yml` in my fork of solus packages in the [branch webcamoid](https://github.com/palto42/solus-packages/tree/webcamoid/packages/w/webcamoid). For me it works fine on Solus Budgie.

This isn't the place for discussing alternatives. If you want something else in the repository, please create a new package request.
