### ISSUE TITLE
Update fprintd

### ISSUE THREAD

**Issue by TraceyC77** [getsolus/packages#2760]
### Please confirm there isn't already an existing package update request

- [X] I have searched through package update requests

### Name

fprintd

### Version

1.94.3

### Link to the release notes or announcement.

https://gitlab.freedesktop.org/libfprint/fprintd/-/releases

### Reason for updating

The version in the repo, 1.94.2, is 2 years old. We are looking to improve fingerprint support.

cc @sheepman4267 
Note: libprint is up to date

**Comment by sheepman4267** [comment]
I have a locally working package.yml for this update which I will PR tomorrow.
