### ISSUE TITLE
vala-panel-appmenu-budgie-desktop crashes session

### ISSUE THREAD

**Issue by vyvir** [getsolus/packages#2762]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

The new version (24.02-19-1) of vala-panel-appmenu-budgie-desktop now crashes more frequently compared to the prior (0.7.6-18-1) version.

### Steps to reproduce

1. Install the latest version of vala-panel-appmenu-budgie-desktop, put it in the Budgie Panel
2. Install and open Kolourpaint from Solus repos
3. Draw anything on canvas
4. Select it with the rectangle selection tool
5. Drag it around for a bit
6. The panel will crash, and then an error will pop up saying "Oops! Something went wrong".

### Expected result

For the panel (and the session) not to crash.

### Actual result

The panel, and then the session crashed.

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Budgie

### System details

.

**Comment by vyvir** [comment]
I have suspicion this has to do with QT applications in particular.

**Comment by SethStormR** [comment]
Do you have Global menu enabled? Because mine crashes with Chrome, only when I'm using Global Menu enabled.

**Comment by vyvir** [comment]
> Do you have Global menu enabled? Because mine crashes with Chrome, only when I'm using Global Menu enabled.

I have it enabled. On latest, it randomly crashes when interacting with QT applications.
On previous version, it seems to be considerably more stable than latest.

**Comment by vyvir** [comment]
I don't know if Chrome counts as QT, but it doesn't crash for me.

**Comment by vyvir** [comment]
At least revert the packages to their previous versions. Current version is unusable until the issue gets fixed, and eopkg doesn't support locking packages to a version.

**Comment by malfisya** [comment]
@vyvir Is this still happening? I saw in the forum post, the latest update solves their problem. (Just to be clear, I still cannot reproduce this bug).

**Comment by vyvir** [comment]
The new update fixed the issue. Thank you.
