### ISSUE TITLE
Update libffi

### ISSUE THREAD

**Issue by malfisya** [getsolus/packages#2795]
### Please confirm there isn't already an existing package update request

- [X] I have searched through package update requests

### Name

libffi

### Version

Latest-3.4.6

### Link to the release notes or announcement.

https://github.com/libffi/libffi/releases/tag/v3.4.6

### Reason for updating

I am not quite sure if updating this package is necessary, but there a few bug fixes that might benefit us. This update require quite major rebuilds. All packages mentioned in this draft PR https://github.com/getsolus/packages/pull/2785

**Comment by androidnisse** [comment]
This looks done now. :+1:
