### ISSUE TITLE
gnuplot - gtk2-engine-murrine container mismatch... (T6028)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#28]
<div dir="rtl"><b>Klaus&nbsp;Burkart</b>&nbsp;(<em>&#35;klausb</em>),&nbsp;2018-03-15&nbsp;17:04:09&nbsp;UTC</div><br/>

I am using pyFoam which in turn needs gnuplot which in turn needs gtk2-engine-murrine.

When using gnuplot, there's an error message about a "container version mismatch between between gnuplot and gtk2-engine-murrine"

When running pyFoam, I keep getting errors like:

gnuplot> BSR
         ^
         line 0: invalid command

gnuplot> X -1 1 1 -1 -1
         ^
         line 0: invalid command

gnuplot> X -1 1 1 -1 -1
         ^
         line 0: invalid command

This may or may not be caused by the issue mentioned above but considering the importance of OpenFoam and the support application PyFoam for scientific computing we should try to resolve the issue.

**Comment by davidjharder** [comment]
Old as dirt. Closing.
