### ISSUE TITLE
steam-devices

### ISSUE THREAD

**Issue by uni-dos** [getsolus/packages#2805]
### Please confirm there isn't an existing package request

- [X] I have searched through package requests

### Homepage

https://github.com/ValveSoftware/steam-devices

### Maintainer

- [ ] Would you like to be the maintainer for this package?

### Why should this be included in the repository?

Solus users who install steam as a flatpak cannot use controllers without these udev rules. 

### Are we allowed to redistribute it?

MIT

### What kind of user will use this package, and how many users do you think will use this package?

Users who install steam as a flatpak. Possibly snap?

### Link to source archive file

https://github.com/ValveSoftware/steam-devices/releases/tag/v1.0.0.61

**Comment by silkeh** [comment]
Thanks for the package request!

> Solus users who install steam as a flatpak cannot use controllers without these udev rules.

Have you verified that these udev rules work on Solus, or are there things that need to be changed?

**Comment by ReillyBrogan** [comment]
Those udev rules are already part of the main steam package and could just be sub-packaged out. This would be superior to re-packaging them from a third-party repo.
