### ISSUE TITLE
Boot hang on LUKS+Swap+Hibernate on clean install

### ISSUE THREAD

**Issue by silkeh** [getsolus/packages#2813]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

Boot hangs after installing Solus with LUKS and swap with hibernate.

### Steps to reproduce

1. Install Solus with LUKS and swap+hibernate.
2. Reboot.
3. Enter password.
4. Wait forever!

### Expected result

Boot to login prompt.

### Actual result

![afbeelding](https://github.com/getsolus/packages/assets/5798032/2b0e8eb8-3a27-461f-b4b1-77a82e692a51)

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

Budgie

### System details

Qemu VM

**Comment by silkeh** [comment]
This is caused by `/etc/kernel/cmdline` being created by the installer with the `resume=` parameters set, but without an `rd.luks.uuid` entry for the swap partition.

Things that need to be done:
- `/etc/kernel/cmdline` should not actually be created.
- `/etc/kernel/cmdline.d/10_resume.conf` should be created with something like:
  ```
  rd.luks.uuid=8883df61-a15f-4118-aa6b-47de8f8d0049
  resume=/dev/mapper/luks-8883df61-a15f-4118-aa6b-47de8f8d0049
  ```
- Verify that hibernation actually works.

**Comment by GanonFreeman** [comment]
Since yesterday I have this issue. 
I booted up my Notebook for the first time in 2, or maybe 3 weeks. applied all updates. Did a reboot and now it stuck at the screen above.  Please give advice

**Comment by silkeh** [comment]
@GanonFreeman: does your previous kernel still boot? You can get the boot menu by pressing space or shift if it's hidden.
