### ISSUE TITLE
tensorflow does not build

### ISSUE THREAD

**Issue by androidnisse** [getsolus/packages#2824]
I'm trying to build tensorflow against a new version of cython. However the package does not even build with the current recipe so I can't verify this. 

[Here](https://gist.github.com/androidnisse/489a78d1c2807c92c988ebc3a954d9da) is the full output of the build.

**Comment by GZGavinZhao** [comment]
Fixed by dfc56ba57a8af8233a635e309b499ff5d27992f4.
