### ISSUE TITLE
qt6ct: qt incompability

### ISSUE THREAD

**Issue by Facundo-c-c** [getsolus/packages#2826]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

The qt6ct app seem to be build with an incompatible qt version than make the app unusable.  

`qt6ct: qt6ct is compiled against incompatible Qt version (6.6.3).`

### Steps to reproduce

1. install qt6ct
2. launch it 
4. read the app warning or read terminal warning

### Expected result

The app actually changing qt app themes, icons, etc.

### Actual result

the app doesn't work how it's suppose to be, it launches but it doesn't change any qt config

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

Other

### System details

System:
  Host: compaq Kernel: 6.8.11-292.current arch: x86_64 bits: 64
  Desktop: LabWC v: N/A Distro: Solus 4.5 resilience
Machine:
  Type: Laptop System: COMPAQ product: Presario 21 v: 0.1
    serial: <superuser required>
  Mobo: COMPAQ model: Presario 21 v: FAB1 serial: <superuser required>
    UEFI: Phoenix v: 77B date: 07/05/2012
Battery:
  ID-1: BAT0 charge: 7.7 Wh (97.5%) condition: 7.9/44.4 Wh (17.7%)
CPU:
  Info: dual core Intel Core i3-3227U [MT MCP] speed (MHz): avg: 905
    min/max: 800/1900
Graphics:
  Device-1: Intel 3rd Gen Core processor Graphics driver: i915 v: kernel
  Device-2: Silicon Motion - Taiwan (formerly Feiya ) Motion Camera
    driver: uvcvideo type: USB
  Display: wayland server: X.Org v: 23.2.7 with: Xwayland v: 23.2.7
    compositor: LabWC driver: X: loaded: fbdev,modesetting,vesa gpu: i915
    resolution: 1366x768~60Hz
  API: OpenGL v: 4.5 compat-v: 4.2 vendor: intel mesa v: 24.0.8
    renderer: Mesa Intel HD Graphics 4000 (IVB GT2)
Network:
  Device-1: Realtek RTL8723BE PCIe Wireless Network Adapter driver: rtl8723be
  Device-2: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet
    driver: r8169
Drives:
  Local Storage: total: 223.57 GiB used: 57.46 GiB (25.7%)
Info:
  Memory: total: 8 GiB available: 7.6 GiB used: 1.96 GiB (25.8%)
  Processes: 180 Uptime: 9h 52m Shell: Zsh inxi: 3.3.34

**Comment by malfisya** [comment]
I can confirm this.

**Comment by malfisya** [comment]
Resolved in https://github.com/getsolus/packages/commit/07c04f1f8c7c30d58a3ab15372c7701a536cedf3
