### ISSUE TITLE
include gnome-clocks & gnome-weather in ISO

### ISSUE THREAD

**Issue by sebo505** [getsolus/packages#2841]
When installed, gnome-clocks and gnome-weather both integrate seamlessly, not to say natively, into notification area and enhance desktop experience. Both packages are fairly small and should be part of default GNOME installation in my opinion.

**Comment by ermo** [comment]
@joebonrichie This is your call. Yay or nay?

**Comment by TraceyC77** [comment]
This is not being included in 4.6, deferring to 4.7
@joebonrichie , could you make a determination on this?
