### ISSUE TITLE
Jellyfin Media Player (T9796)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#286]
<div dir="rtl"><b>theo</b>&nbsp;(<em>&#35;tadopai</em>),&nbsp;2021-06-28&nbsp;09:47:56&nbsp;UTC</div><br/>

Name of the software: **Jellyfin Media Player**

Project/product Homepage: **https://jellyfin.org/ **

Is it open source?: **Yes**

If it is open source, please provide a link to the most up to date, versioned source tarball/zipfile.: **https://github.com/jellyfin/jellyfin-media-player/archive/refs/tags/v1.6.1.tar.gz **

Who and how many users do you anticipate will use this software? **For all users with an jellyfin media server. Sorry I have no Idea how many users using jellyfin. But the community is growing fast.**

Why should this be included in the repository? If we already offer similar software in our repository or third party, please provide information on what your proposed software does that our existing offerings don’t: **This is an open source alternative to PLEX**

Thanks in Advance!

- Theo

**Comment by TraceyC77** [comment]
The documentation for package inclusion has changed since this was last updated. Current info, supplemental to what was already provided:
- License: [GPL v2.0](https://github.com/jellyfin/jellyfin/blob/master/LICENSE)
- Current source archive file: https://github.com/jellyfin/jellyfin/archive/refs/tags/v10.8.11.tar.gz

This can be included in the repository

**Comment by rav101** [comment]
Jellyfin is updated to v10.8.13:

Release notes: https://github.com/jellyfin/jellyfin/releases/tag/v10.8.13
Comparison to 10.8.11: https://github.com/jellyfin/jellyfin/compare/v10.8.11...v10.8.13
Package: https://github.com/jellyfin/jellyfin/archive/refs/tags/v10.8.13.tar.gz

**Comment by codewizard1975** [comment]
Did this switch from the player to the server software by the Jellyfin project?

**Comment by rav101** [comment]
It does look like there is a separate media player on GitHub:

Release Page: https://github.com/jellyfin/jellyfin-media-player/releases
Package: https://github.com/jellyfin/jellyfin-media-player/archive/refs/tags/v1.9.1.tar.gz

**Comment by codewizard1975** [comment]
I'll tackle the player later today and test.  If all goes well, I'll create a PR for inclusion.
