### ISSUE TITLE
fooyin (a foobar2000 clone with Directory Browsing)

### ISSUE THREAD

**Issue by brucetheelephant** [getsolus/packages#2886]
### Please confirm there isn't an existing package request

- [X] I have searched through package requests

### Homepage

https://github.com/ludouzi/fooyin

### Maintainer

- [ ] Would you like to be the maintainer for this package?

### Why should this be included in the repository?

It has Directory Browsing. Audacious has a similar feature but it's extremely limited. It also has a nice, clean and customizable UI.

edit: For clarification purposes: Directory Browsing is an always-visible Music Library which updates in real-time and from which you can drag-and-drop files to various playlists.

### Are we allowed to redistribute it?

GPL 3.0

### What kind of user will use this package, and how many users do you think will use this package?

I think a good number of Plasma users will use this package. I made a poll [here](https://discuss.getsol.us/d/10624-fooyin-a-foobar2000-clone).

### Link to source archive file

https://github.com/ludouzi/fooyin/archive/refs/tags/v0.4.5.tar.gz

**Comment by silkeh** [comment]
Thanks for the package request!

> No response

Please provide the license the software is published under.

> I made a poll [here](https://discuss.getsol.us/d/10624-fooyin-a-foobar2000-clone).

Awesome! Can you share the results (screenshot is fine) now the poll has ended?

**Comment by silkeh** [comment]
@brucetheelephant: Thanks, that's all I needed to know. Approved!
