### ISSUE TITLE
Virtualbox Seamless mode broken after update (1/29/18) (T5670)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#29]
<div dir="rtl"><b>Ben&nbsp;Daines</b>&nbsp;(<em>&#35;spacecase</em>),&nbsp;2018-01-30&nbsp;15:40:40&nbsp;UTC</div><br/>

It appears that seamless mode is not working properly.  Might not be the best screenshot, but as you can see the X window is ghosted across the seamless vbox window.  That large blue area is meant to be the windows start menu. 

https://i.imgur.com/Qgt5I02.jpg

At work, so I just quickly threw up a ticket.  Let me know what details you may need.

**Comment by davidjharder** [comment]
Old, closing
