### ISSUE TITLE
TV-Lite IPTV viewer (T9682)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#291]
<div dir="rtl"><b>Murat&nbsp;SAYGILI</b>&nbsp;(<em>&#35;saygili</em>),&nbsp;2021-04-17&nbsp;16:02:34&nbsp;UTC</div><br/>

Hi,
Is it possible to have TV-Lite in repo?

TV-Lite is a IPTV viewer, with Sopcast and Acestream handling capabilities. It uses the well known VLC for displaying media. We also plan to add MPV as media player in the future. This program currently runs on Linux and Windows operating systems,

TV-Lite wants to be a replacement for the older TV-Maxe. It does not have all the features that TV-Maxe offers. It uses the same principle of "subscriptions" and uses the same playlist format TV-Maxe uses. Apart from that, it can handle the ubiquitous M3U format used for many IPTV playlists. It aims to streamline a bit the behavior of TV-Maxe in respect to subscriptions. The subscriptions can be downloaded and saved as local playlists, that can be edited and new channels can be added, or the existent channels can be edited.

The subscriptions can only be updated, of course, but copies of them can be always saved locally, and modified as stated above.

https://gitlab.com/cburneci/tv-lite/-/tags/0.4.0

BR

Murat

**Comment by sheepman4267** [comment]
Resolved by #1735
