### ISSUE TITLE
rxvt-unicode does not build

### ISSUE THREAD

**Issue by malfisya** [getsolus/packages#2941]
rxvt-unicode does not build with the recipe as is

**Comment by ermo** [comment]
```
[Dependency] /usr/bin/urxvt adds dependency on libm.so.6 from glibc
[Package] Creating /home/build/work/rxvt-unicode-9.31-16-1-x86_64.eopkg ...
[Package] rxvt-unicode-9.31-16-1-x86_64.eopkg took 0:00:00.152632 to emit
[Package] Building complete
 ✓  Building succeeded
```

rxvt-unicode builds for me when I use PRs #3850 and #4063 with `go-task local`.

**Comment by ermo** [comment]
@malfisya Can you reproduce my findings?

**Comment by malfisya** [comment]
I can reproduce. I will file the PR after these tooling changes landed and deployed in build server.
