### ISSUE TITLE
forticlient vpn connected: no network available

### ISSUE THREAD

**Issue by FTouzain** [getsolus/packages#2947]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

Hello,

Since last solus update, forticlient vpn connection is telling it is working (communication with token ok) but no connexion is possible (http in or out proxy, ssh ...). It is working very well on another computer running previous version of solus, not updated yet.

In journalctl, I see the error message:
```
pppd[2602]: Failed to create /etc/ppp/resolv.conf: No such file or directory
NetworkManager[2602]: Can't execute /etc/ppp/ip-up: Permission denied
``` 

Solus with this problem is:
- Solus 4.5 resilience
- Linux 6.8.11-292-current
- Budgie-10.9.1

Thank you in advance.
Fabrice

### Steps to reproduce

Try to connect to a vpn (forticlient) using the graphical interface.

### Expected result

- tells connexion is working
- vpn acces is possible, internet access is possible (addresses in and out of vpn)

### Actual result

- tells connexion is working
- no network connexion is possible:
  - ssh (even with IP adress)
  - http/https in and out vpn

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Budgie

### System details

- Solus 4.5 resilience
- Linux 6.8.11-292-current
- Budgie-10.9.1

### Other comments

In journalctl, I see the error message:

```
pppd[2602]: Failed to create /etc/ppp/resolv.conf: No such file or directory
NetworkManager[2602]: Can't execute /etc/ppp/ip-up: Permission denied
``` 
Maybe some other lines are interesting for you, just tell me. I am almost sure I can at less link these one to the bug.

Adding DNS in the VPN configuration does not change anything (do not solve the problem).

**Comment by ReillyBrogan** [comment]
What does `eopkg history` say was updated in your last set of updates?

Does `/etc/ppp` exist on your system? If not, does creating it with `sudo mkdir /etc/ppp` solve the issue?

**Comment by FTouzain** [comment]
```eopkg history``` tells me:

Date : 2024-06-03 01:11

    * libcroco 0.6.13-13-1-x86_64 est supprimé.
    * libcroco-32bit 0.6.13-13-1-x86_64 est supprimé.
    * systemd est mis à jour de 254.12-155-1-x86_64 à 254.13-156-1-x86_64.
    * libnss est mis à jour de 3.99-60-1-x86_64 à 3.100-61-1-x86_64.
    * glibc est mis à jour de 2.39-112-1-x86_64 à 2.39-113-1-x86_64.
    * attr est mis à jour de 2.5.2-22-1-x86_64 à 2.5.2-23-1-x86_64.
    * shadow est mis à jour de 4.14.7-32-1-x86_64 à 4.14.6-33-1-x86_64.
    * ncurses est mis à jour de 6.5.20240427-25-1-x86_64 à 6.5.20240525-26-1-x86_64.
    * e2fsprogs est mis à jour de 1.47.0-26-1-x86_64 à 1.47.1-27-1-x86_64.
    * libao est mis à jour de 1.2.2-13-1-x86_64 à 1.2.2-14-1-x86_64.
    * openrazer-common est mis à jour de 3.8.0-319-1-x86_64 à 3.8.0-320-1-x86_64.
    * llvm est mis à jour de 16.0.6-116-1-x86_64 à 18.1.6-119-1-x86_64.
    * mesalib est mis à jour de 24.0.8-233-1-x86_64 à 24.0.8-234-1-x86_64.
    * qt5-base est mis à jour de 5.15.13-101-1-x86_64 à 5.15.14-102-1-x86_64.
    * qt5-script est mis à jour de 5.15.12-36-1-x86_64 à 5.15.14-37-1-x86_64.
    * qtstyleplugins est mis à jour de 5.0.0-29-1-x86_64 à 5.0.0-30-1-x86_64.
    * gstreamer-1.0 est mis à jour de 1.24.3-51-1-x86_64 à 1.24.4-52-1-x86_64.
    * gstreamer-1.0-plugins-base est mis à jour de 1.24.3-59-1-x86_64 à 1.24.4-60-1-x86_64.
    * gstreamer-editing-services est mis à jour de 1.24.3-36-1-x86_64 à 1.24.4-37-1-x86_64.
    * qt5-declarative est mis à jour de 5.15.13-49-1-x86_64 à 5.15.14-50-1-x86_64.
    * qt5-x11extras est mis à jour de 5.15.13-33-1-x86_64 à 5.15.14-34-1-x86_64.
    * gstreamer-1.0-plugins-good est mis à jour de 1.24.3-60-1-x86_64 à 1.24.4-61-1-x86_64.
    * libav est mis à jour de 0.8.21-3-1-x86_64 à 0.8.21-4-1-x86_64.
    * openrazer est mis à jour de 3.8.0-319-1-x86_64 à 3.8.0-320-1-x86_64.
    * yt-dlp est mis à jour de 2024.04.09-214-1-x86_64 à 2024.05.27-216-1-x86_64.
    * libdbusmenu est mis à jour de 16.04.0-10-1-x86_64 à 16.04.0-11-1-x86_64.
    * libdbusmenu-32bit est mis à jour de 16.04.0-10-1-x86_64 à 16.04.0-11-1-x86_64.
    * grub2 est mis à jour de 2.04-37-1-x86_64 à 2.12-39-1-x86_64.
    * qt5-websockets est mis à jour de 5.15.13-35-1-x86_64 à 5.15.14-36-1-x86_64.
    * virtualbox-common est mis à jour de 7.0.14-316-1-x86_64 à 7.0.14-317-1-x86_64.
    * virtualbox est mis à jour de 7.0.14-316-1-x86_64 à 7.0.14-317-1-x86_64.
    * virtualbox-devel est mis à jour de 7.0.14-316-1-x86_64 à 7.0.14-317-1-x86_64.
    * gstreamer-1.0-plugins-ugly est mis à jour de 1.24.3-62-1-x86_64 à 1.24.4-63-1-x86_64.
    * libepoxy est mis à jour de 1.5.10-13-1-x86_64 à 1.5.10-14-1-x86_64.
    * libepoxy-32bit est mis à jour de 1.5.10-13-1-x86_64 à 1.5.10-14-1-x86_64.
    * python-tornado est mis à jour de 6.3.3-13-1-x86_64 à 6.4.0-14-1-x86_64.
    * qt5-3d est mis à jour de 5.15.13-26-1-x86_64 à 5.15.14-27-1-x86_64.
    * qt5-quickcontrols2 est mis à jour de 5.15.13-35-1-x86_64 à 5.15.14-36-1-x86_64.
    * cjson 1.7.17-2-1-x86_64 est installé.
    * freerdp 3.5.1-37-1-x86_64 est installé.
    * qt6-tools est mis à jour de 6.7.1-18-1-x86_64 à 6.7.1-19-1-x86_64.
    * nvidia-glx-driver-common est mis à jour de 550.78-523-1-x86_64 à 550.78-524-1-x86_64.
    * nvidia-glx-driver-current est mis à jour de 550.78-523-1-x86_64 à 550.78-524-1-x86_64.
    * python3 est mis à jour de 3.11.9-62-1-x86_64 à 3.11.9-63-1-x86_64.
    * glibc-32bit est mis à jour de 2.39-112-1-x86_64 à 2.39-113-1-x86_64.
    * libbytesize est mis à jour de 1.2-9-1-x86_64 à 2.10-10-1-x86_64.
    * libabw est mis à jour de 0.1.3-3-1-x86_64 à 0.1.3-4-1-x86_64.
    * qt5-xmlpatterns est mis à jour de 5.15.13-34-1-x86_64 à 5.15.14-35-1-x86_64.
    * nvidia-470-glx-driver-modaliases est mis à jour de 470.239.06-84-1-x86_64 à 470.239.06-85-1-x86_64.
    * qt5-quickcontrols est mis à jour de 5.15.13-35-1-x86_64 à 5.15.14-36-1-x86_64.
    * libvncserver 0.9.14-10-1-x86_64 est installé.
    * gnome-remote-desktop 46.2-15-1-x86_64 est installé.
    * gnome-control-center est mis à jour de 46.0.1-156-1-x86_64 à 46.0.1-157-1-x86_64.
    * ncurses-32bit est mis à jour de 6.5.20240427-25-1-x86_64 à 6.5.20240525-26-1-x86_64.
    * opusfile est mis à jour de 0.12-8-1-x86_64 à 0.12-9-1-x86_64.
    * opusfile-32bit est mis à jour de 0.12-8-1-x86_64 à 0.12-9-1-x86_64.
    * qt5-imageformats est mis à jour de 5.15.13-27-1-x86_64 à 5.15.14-28-1-x86_64.
    * qt5-datavis3d est mis à jour de 5.15.13-17-1-x86_64 à 5.15.14-18-1-x86_64.
    * e2fsprogs-devel est mis à jour de 1.47.0-26-1-x86_64 à 1.47.1-27-1-x86_64.
    * virtualbox-current est mis à jour de 7.0.14-316-1-x86_64 à 7.0.14-317-1-x86_64.
    * qt5-tools est mis à jour de 5.15.13-44-1-x86_64 à 5.15.14-46-1-x86_64.
    * pipewire-lib est mis à jour de 1.0.7-102-1-x86_64 à 1.0.7-103-1-x86_64.
    * pipewire est mis à jour de 1.0.7-102-1-x86_64 à 1.0.7-103-1-x86_64.
    * pipewire-32bit est mis à jour de 1.0.7-102-1-x86_64 à 1.0.7-103-1-x86_64.
    * llvm-32bit est mis à jour de 16.0.6-116-1-x86_64 à 18.1.6-119-1-x86_64.
    * libetonyek est mis à jour de 0.1.10-6-1-x86_64 à 0.1.10-7-1-x86_64.
    * qt5-wayland est mis à jour de 5.15.13-52-1-x86_64 à 5.15.14-53-1-x86_64.
    * libedit est mis à jour de 20230828.3.1-12-1-x86_64 à 20240517.3.1-13-1-x86_64.
    * libedit-32bit est mis à jour de 20230828.3.1-12-1-x86_64 à 20240517.3.1-13-1-x86_64.
    * qt5-svg est mis à jour de 5.15.13-37-1-x86_64 à 5.15.14-38-1-x86_64.
    * movit est mis à jour de 1.6.3-7-1-x86_64 à 1.7.1-8-1-x86_64.
    * svt-av1 est mis à jour de 2.0.0-8-1-x86_64 à 2.1.0-9-1-x86_64.
    * libsodium est mis à jour de 1.0.19-9-1-x86_64 à 1.0.20-10-1-x86_64.
    * mlt est mis à jour de 7.22.0-42-1-x86_64 à 7.22.0-43-1-x86_64.
    * ncurses-devel est mis à jour de 6.5.20240427-25-1-x86_64 à 6.5.20240525-26-1-x86_64.
    * wayland est mis à jour de 1.22.0-29-1-x86_64 à 1.23.0-30-1-x86_64.
    * wayland-32bit est mis à jour de 1.22.0-29-1-x86_64 à 1.23.0-30-1-x86_64.
    * wayland-devel est mis à jour de 1.22.0-29-1-x86_64 à 1.23.0-30-1-x86_64.
    * nvidia-glx-driver-modaliases est mis à jour de 550.78-523-1-x86_64 à 550.78-524-1-x86_64.
    * qt5-multimedia est mis à jour de 5.15.13-40-1-x86_64 à 5.15.14-41-1-x86_64.
    * qt5-webchannel est mis à jour de 5.15.13-35-1-x86_64 à 5.15.14-36-1-x86_64.
    * opera-stable est mis à jour de 110.0.5130.39-291-1-x86_64 à 110.0.5130.49-292-1-x86_64.
    * mono est mis à jour de 6.12.0.122-24-1-x86_64 à 6.12.0.199-25-1-x86_64.
    * github-cli est mis à jour de 2.49.2-47-1-x86_64 à 2.50.0-48-1-x86_64.
    * qt6-designer est mis à jour de 6.7.1-18-1-x86_64 à 6.7.1-19-1-x86_64.
    * linux-lts est mis à jour de 6.6.31-245-1-x86_64 à 6.6.32-246-1-x86_64.
    * lib2geom est mis à jour de 1.3-3-1-x86_64 à 1.3-4-1-x86_64.
    * lash est mis à jour de 0.5.4-10-1-x86_64 à 0.5.4-11-1-x86_64.
    * python-tinycss2 est mis à jour de 1.2.1-6-1-x86_64 à 1.3.0-7-1-x86_64.
    * libass est mis à jour de 0.17.1-15-1-x86_64 à 0.17.1-16-1-x86_64.
    * ruamel-yaml-clib 0.2.8-1-1-x86_64 est installé.
    * ruamel_yaml est mis à jour de 0.18.6-5-1-x86_64 à 0.18.6-6-1-x86_64.
    * libavc1394 est mis à jour de 0.5.4-3-1-x86_64 à 0.5.4-4-1-x86_64.
    * qt5-base-devel est mis à jour de 5.15.13-101-1-x86_64 à 5.15.14-102-1-x86_64.
    * pciutils est mis à jour de 3.7.0-12-1-x86_64 à 3.7.0-13-1-x86_64.
    * pciutils-32bit est mis à jour de 3.7.0-12-1-x86_64 à 3.7.0-13-1-x86_64.
    * libffi6 est mis à jour de 3.2.1-1-1-x86_64 à 3.2.1-2-1-x86_64.
    * libffi6-32bit est mis à jour de 3.2.1-1-1-x86_64 à 3.2.1-2-1-x86_64.
    * mesalib-devel est mis à jour de 24.0.8-233-1-x86_64 à 24.0.8-234-1-x86_64.
    * libdvbpsi est mis à jour de 1.3.3-3-1-x86_64 à 1.3.3-4-1-x86_64.
    * opusfile-devel est mis à jour de 0.12-8-1-x86_64 à 0.12-9-1-x86_64.
    * qt5-serialport est mis à jour de 5.15.13-33-1-x86_64 à 5.15.14-34-1-x86_64.
    * attr-32bit est mis à jour de 2.5.2-22-1-x86_64 à 2.5.2-23-1-x86_64.
    * qt5-location est mis à jour de 5.15.13-53-1-x86_64 à 5.15.14-54-1-x86_64.
    * libevent est mis à jour de 2.1.12-13-1-x86_64 à 2.1.12-14-1-x86_64.
    * qt5-webengine est mis à jour de 5.15.17-69-1-x86_64 à 5.15.17-70-1-x86_64.
    * gstreamer-1.0-32bit est mis à jour de 1.24.3-51-1-x86_64 à 1.24.4-52-1-x86_64.
    * python3-tkinter est mis à jour de 3.11.9-62-1-x86_64 à 3.11.9-63-1-x86_64.
    * nvidia-glx-driver est mis à jour de 550.78-523-1-x86_64 à 550.78-524-1-x86_64.
    * firefox est mis à jour de 126.0-316-1-x86_64 à 126.0.1-317-1-x86_64.
    * libepoxy-devel est mis à jour de 1.5.10-13-1-x86_64 à 1.5.10-14-1-x86_64.
    * qt5-sensors est mis à jour de 5.15.13-34-1-x86_64 à 5.15.14-35-1-x86_64.
    * libcryptui est mis à jour de 3.12.2-15-1-x86_64 à 3.12.2-16-1-x86_64.
    * openfortivpn est mis à jour de 1.20.2-12-1-x86_64 à 1.22.0-13-1-x86_64.
    * libexttextcat est mis à jour de 3.4.5-3-1-x86_64 à 3.4.6-4-1-x86_64.
    * mesalib-32bit est mis à jour de 24.0.8-233-1-x86_64 à 24.0.8-234-1-x86_64.
    * gstreamer-1.0-plugins-base-32bit est mis à jour de 1.24.3-59-1-x86_64 à 1.24.4-60-1-x86_64.
    * ostree est mis à jour de 2023.6-22-1-x86_64 à 2023.6-23-1-x86_64.
    * google-cloud-sdk est mis à jour de 476.0.0-33-1-x86_64 à 477.0.0-34-1-x86_64.
    * systemd-devel est mis à jour de 254.12-155-1-x86_64 à 254.13-156-1-x86_64.
    * binutils-libs est mis à jour de 2.42-69-1-x86_64 à 2.42-70-1-x86_64.
    * linux-current est mis à jour de 6.8.10-291-1-x86_64 à 6.8.11-292-1-x86_64.
    * qt5-speech est mis à jour de 5.15.13-24-1-x86_64 à 5.15.14-25-1-x86_64.
    * qt5-graphicaleffects est mis à jour de 5.15.13-33-1-x86_64 à 5.15.14-34-1-x86_64.
    * qt5-networkauth est mis à jour de 5.15.13-24-1-x86_64 à 5.15.14-25-1-x86_64.
    * rust est mis à jour de 1.78.0-122-1-x86_64 à 1.78.0-126-1-x86_64.
    * libassuan est mis à jour de 2.5.7-12-1-x86_64 à 2.5.7-13-1-x86_64.
    * pcsc-lite est mis à jour de 1.9.9-15-1-x86_64 à 1.9.9-16-1-x86_64.
    * lollypop est mis à jour de 1.4.37-159-1-x86_64 à 1.4.39-160-1-x86_64.
    * pcaudiolib est mis à jour de 1.0-5-1-x86_64 à 1.2-6-1-x86_64.
    * libblockdev est mis à jour de 3.1.1-20-1-x86_64 à 3.1.1-21-1-x86_64.
    * glibc-devel est mis à jour de 2.39-112-1-x86_64 à 2.39-113-1-x86_64.
    * jemalloc est mis à jour de 5.3.0-11-1-x86_64 à 5.3.0-12-1-x86_64.
    * gnuplot est mis à jour de 6.0.0-23-1-x86_64 à 6.0.1-24-1-x86_64.
    * llvm-devel est mis à jour de 16.0.6-116-1-x86_64 à 18.1.6-119-1-x86_64.
    * llvm-clang est mis à jour de 16.0.6-116-1-x86_64 à 18.1.6-119-1-x86_64.
    * gnome-builder est mis à jour de 46.2-96-1-x86_64 à 46.2-97-1-x86_64.
    * libnss-32bit est mis à jour de 3.99-60-1-x86_64 à 3.100-61-1-x86_64.
    * libfreeaptx est mis à jour de 0.1.1-1-1-x86_64 à 0.1.1-2-1-x86_64.
    * qt5-webkit est mis à jour de 5.212.0_4-49-1-x86_64 à 5.212.0_4-50-1-x86_64.
    * virtualbox-guest-common est mis à jour de 7.0.14-316-1-x86_64 à 7.0.14-317-1-x86_64.
    * virtualbox-guest est mis à jour de 7.0.14-316-1-x86_64 à 7.0.14-317-1-x86_64.
    * gstreamer-1.0-plugins-bad est mis à jour de 1.24.3-103-1-x86_64 à 1.24.4-104-1-x86_64.
    * e2fsprogs-32bit est mis à jour de 1.47.0-26-1-x86_64 à 1.47.1-27-1-x86_64.
    * ypkg est mis à jour de 31-189-1-x86_64 à 31-190-1-x86_64.
    * pulseaudio-qt est mis à jour de 1.4.0-6-1-x86_64 à 1.5.0-7-1-x86_64.
    * snapd est mis à jour de 2.62-80-1-x86_64 à 2.63-81-1-x86_64.
    * ldns est mis à jour de 1.8.3-6-1-x86_64 à 1.8.3-7-1-x86_64.
    * openrazer-current est mis à jour de 3.8.0-319-1-x86_64 à 3.8.0-320-1-x86_64.
    * qt5-connectivity est mis à jour de 5.15.13-38-1-x86_64 à 5.15.14-39-1-x86_64.
    * gstreamer-1.0-libav est mis à jour de 1.24.3-36-1-x86_64 à 1.24.4-37-1-x86_64.
    * dav1d est mis à jour de 1.4.1-27-1-x86_64 à 1.4.2-28-1-x86_64.
    * strace est mis à jour de 6.7-9-1-x86_64 à 6.9-10-1-x86_64.
    * qt6-wayland est mis à jour de 6.7.1-11-1-x86_64 à 6.7.1-12-1-x86_64.
    * systemd-32bit est mis à jour de 254.12-155-1-x86_64 à 254.13-156-1-x86_64.
    * libcdio-paranoia est mis à jour de 10.2.2.0.1-7-1-x86_64 à 10.2.2.0.1-8-1-x86_64.
    * fakeroot est mis à jour de 1.34-19-1-x86_64 à 1.34-20-1-x86_64.
    * binutils est mis à jour de 2.42-69-1-x86_64 à 2.42-70-1-x86_64.
    * libcryptui-devel est mis à jour de 3.12.2-15-1-x86_64 à 3.12.2-16-1-x86_64.
    * glibc-dbginfo est mis à jour de 2.39-112-1-x86_64 à 2.39-113-1-x86_64.

It includes __openfortivpn est mis à jour de 1.20.2-12-1-x86_64 à 1.22.0-13-1-x86_64__

* `etc/ppp` did not exist on my system, I created it but it does not solve the issue (I tried after but did not reboot before testing)

**Comment by ReillyBrogan** [comment]
I've committed an update to openfortivpn to the repo with a presumed fix for this issue based off of the release notes. Unfortunately I don't have a fortivpn VPN to test with, but please let me know if this works after the next sync or not.

**Comment by FTouzain** [comment]
Previous version `https://cdn.getsol.us/repo/shannon/o/openfortivpn/openfortivpn-1.20.2-12-1-x86_64.eopkg` works prefectly for me (ssh, http in and out proxy).

Yes, I will let you know if it works after the next sync.

Many thanks.

**Comment by FTouzain** [comment]
New sync not working `openfortivpn-1.22.0-13-1-x86_64.eopkg` (same bug), sorry.

I go back to `https://cdn.getsol.us/repo/shannon/o/openfortivpn/openfortivpn-1.20.2-12-1-x86_64.eopkg`
Thank you for the effort, and the solution until the bug fix.

**Comment by malfisya** [comment]
@FTouzain We haven't done any sync yet this week. `openfortivpn` will come as `openfortivpn-1.22.0-14-1-x86_64` next sync.

**Comment by FTouzain** [comment]
Sync done. It is working very well. Huge thanks for this great job

**Comment by ReillyBrogan** [comment]
@FTouzain FYI we're going to be updating a major dependency of openfortivpn (see [here](https://github.com/getsolus/packages/pull/3288) for details) as well as giving it a minor version bump and adding a stateless patch. Any chance you could switch to the unstable channel once we land that so that you can test that it still works?

**Comment by FTouzain** [comment]
@ReillyBrogan . If I can help, why not. IS there a way to only install this package with its dependencies without switching all the distrib to unstable? If I have a clear recipe of:
- how to install instable and dependencies
- how to recover stable version

It is ok for me (I have never be testing until now, so I am a kind of newbie in the field).

**Comment by ReillyBrogan** [comment]
Unfortunately not since this is scheduled to go in after we rebuild a bunch of packages for libicu. That said, you can switch back from unstable to stable without having to roll back packages so you can wait for us to give you the go ahead, switch to unstable and update, and then switch back to stable to test. You should join our Matrix if that sounds like something you might be willing to do.

**Comment by FTouzain** [comment]
And if fortivpn fail after this procedure, will 'doing an update in stable version again' recover fortivpn functionalities or do I need a special procedure please?

**Comment by FTouzain** [comment]
Bug reappeared. VPN Connection supposed to be ok, bug not working.
Journalctl messages:
```
pppd[26523]: Can't execute /etc/ppp/ip-up: Permission denied
NetworkManager[1053]: <info>  [1721893679.6014] device (ppp0): state change: unavailable -> disconnected (reason 'none', sys-iface-state: 'external')
```

Budgie: 10.9.2
Kernel version: Linux 6.9.10-295.current
Solus: 4.5 Resilience

**Comment by FTouzain** [comment]
Hello. Sorry, still not working for me.
Some of lines given by executing the following command:
```sudo journalctl | grep -E 'pppd|Network' | tail -n 60```
```
NetworkManager[2781]: Failed to create /etc/ppp/resolv.conf: No such file or directory
pppd[2781]: Failed to create /etc/ppp/resolv.conf: No such file or directory
...
NetworkManager[2781]: Can't execute /etc/ppp/ip-up: Permission denied
NetworkManager[1043]: <info>  [1723628309.7201] device (ppp0): state change: unavailable -> disconnected (reason 'none', sys-iface-state: 'external')
```
Budgie: 10.9.2
Kernel version: Linux 6.9.12-297.current
Solus: 4.5 Resilience

but I think there are some progress (IP attribution is done, DNS are obtained)

**Comment by ReillyBrogan** [comment]
Can you change `sudo journalctl` to `sudo journalctl -b0` to make sure those are from the current boot?

**Comment by FTouzain** [comment]
I have cheched, still the same with `-b0`. 
The computer clearly 'believe' the vpn is on:
```
NetworkManager[40213]: INFO:   Tunnel is up and running.
```
> Just for information, I use link aggregation (I do not believe it can trigger problem as it was working with it, but not sure)

**Comment by ReillyBrogan** [comment]
Does it work if you do `sudo touch /etc/ppp/resolv.conf` before you start the VPN?

**Comment by FTouzain** [comment]
No. Strangely, it still tells that it cannot create this file.
The lines with journalctl and grep are:
```
NetworkManager[45162]: Failed to create /etc/ppp/resolv.conf: No such file or directory
pppd[45162]: Failed to create /etc/ppp/resolv.conf: No such file or directory
pppd[45162]: local  IP address xxx.xxx.xxx.x
NetworkManager[1043]: <info>  [1723667305.2182] device (ppp0): state change: unmanaged -> unavailable (reason 'connection-assumed', sys-iface-state: 'external')
```
NetworkManager tells IP address and DNSs 
then
```
NetworkManager[45162]: Can't execute /etc/ppp/ip-up: Permission denied
```
Then ppp list remote ip address and DNSs
then
```
pppd[45162]: Can't execute /etc/ppp/ip-up: Permission denied
NetworkManager[1043]: <info>  [1723667305.2190] device (ppp0): state change: unavailable -> disconnected (reason 'none', sys-iface-state: 'external')
systemd[1]: Starting NetworkManager-dispatcher.service - Network Manager Script Dispatcher Service...
systemd[1]: Started NetworkManager-dispatcher.service - Network Manager Script Dispatcher Service.
kernel: audit: type=1130 audit(1723667305.248:426): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=NetworkManager-dispatcher comm="systemd" exe="/usr/lib64/systemd/systemd" hostname=? addr=? terminal=? res=success'
NetworkManager[1043]: <info>  [1723667305.2510] policy: set 'MYVPN' (ppp0) as default for IPv4 routing and DNS
NetworkManager[45161]: INFO:   Interface ppp0 is UP.
NetworkManager[45161]: INFO:   Tunnel is up and running.
systemd[1]: NetworkManager-dispatcher.service: Deactivated successfully.
kernel: audit: type=1131 audit(1723667315.283:427): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=NetworkManager-dispatcher comm="systemd" exe="/usr/lib64/systemd/systemd" hostname=? addr=? terminal=? res=success'
```

I started the log at the moment when I think I have the first error message.

**Comment by ReillyBrogan** [comment]
Hop on our Matrix tomorrow and ping me. I bet we can figure this out.

My guess is that the connection is being made correctly but something in the routing or DNS configuration isn't getting setup correctly.

**Comment by ReillyBrogan** [comment]
Still waiting on Matrix so I can do interactive debugging.

**Comment by FTouzain** [comment]
Yes, this is still an issue. I have not a classical connexion but a bond (link aggregation). I send you in matrix the messages appearing in journalctl output just after vpn connexion. Maybe you will find clue.

**Comment by FTouzain** [comment]
I installed Solus last version on a old mac mini, without link aggregation and have the same issue.
My VPN connection use a proxy, defined using a .pac file on both my solus computers.

What must I expect from the command you gave please? (`ip addr`, `ip route`, `resolvectl status`). Thank you.

**Comment by ReillyBrogan** [comment]
Does this help at all? `sudo eopkg it https://cdn.getsol.us/repo/unstable/n/network-manager-fortisslvpn/network-manager-fortisslvpn-1.4.0-23-1-x86_64.eopkg`
