### ISSUE TITLE
Jellyfin Media Server

### ISSUE THREAD

**Issue by vtmarik** [getsolus/packages#2982]
### Please confirm there isn't an existing package request

- [X] I have searched through package requests

### Homepage

https://jellyfin.org/

### Maintainer

- [ ] Would you like to be the maintainer for this package?

### Why should this be included in the repository?

While there is a flathub (which is managed by a third party) and a docker image  for the Jellyfin media server (an open source alternative to PLEX), being able to run the server via a native package would ease updates, installs, and configurations especially regarding hardware transcoding.

### Are we allowed to redistribute it?

GPL-2.0

### What kind of user will use this package, and how many users do you think will use this package?

Anyone with a media collection looking to create a way to organize and watch their saved movies, shows, etc. without having to mess with virtualization.

### Link to source archive file

https://github.com/jellyfin/jellyfin/archive/refs/tags/v10.9.6.tar.gz

**Comment by androidnisse** [comment]
Is these two different? Otherwise it is approved. 

https://github.com/getsolus/packages/issues/286

**Comment by silkeh** [comment]
Thanks for the package request! However, Solus generally does not include server software, see our [package inclusion policy](https://help.getsol.us/docs/packaging/procedures/package-inclusion#server-software).

In this case, the following applies:

> Anything outside of [mail/web servers] may be catered to by the usage of Docker, or other container technology. Thus, container technology must be supported by Solus to support access to ancillary cases.

Please let me know if I have misunderstood something and there is a way to provide Jellyfin Media Server as a complete media experience for desktop users.
