### ISSUE TITLE
deprecate sparsehash

### ISSUE THREAD

**Issue by androidnisse** [getsolus/packages#2986]
### Please confirm there isn't already an existing package deprecation request

- [X] I have searched through package deprecation requests

### Name

sparsehash

### Last Update Date

2020-08-11

### Reason for deprecation

Added in the repo and then never updated. Last commit 4 years ago. Nothing depends on it.

**Comment by ReillyBrogan** [comment]
Sparsehash is still used. It's a builddep of graph-tool (see where it's pulled in with `pkgconfig(libsparsehash)`)
