### ISSUE TITLE
flickering issue with SSR (T720)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#3]
<div dir="rtl"><b>Djalel</b>&nbsp;(<em>&#35;sniper1720</em>),&nbsp;2016-09-17&nbsp;16:03:20&nbsp;UTC</div><br/>

hello 

I try to recording my screen with simplescreenrecoder but the video has a `random flickering` !!!

**Hardware** 

```
Motherboard : HP
processor : Intel i3 
Gpu: intel hd 4400 
Ram : 4gb  
```

if you need a sample i can provide a link to my vid.

Regard. Djalel

**Comment by davidjharder** [comment]
Fixed in 2017 apparently. 
Also very old
