### ISSUE TITLE
Input lag after computer awakes from sleep mode with Linux 5.5.x (T8700)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#300]
<div dir="rtl"><b>Fabio</b>&nbsp;(<em>&#35;livingsilver94</em>),&nbsp;2020-02-08&nbsp;16:26:58&nbsp;UTC</div><br/>

My computer introduces a noticeable input lag after it wakes up from sleeping mode. Animations on screen are choppy and dragged windows are moving distantly from cursor position. I suspect it's some buffering issue but I'm not sure.
My main suspect my GPU, a R9 290 which is a Sea Islands GPU. I also tried to enable AMDGPU DC by passing `amdgpu.dc=1` to kernel flags to no avail.
Since I'm using Plasma, I tried to disable the screen compositor but nothing changes even so.

**Comment by ReillyBrogan** [comment]
Closing as the fix for this should have landed in 6.4.11

**Comment by ReillyBrogan** [comment]
See commit titled `ACPI: resource: Fix regressions from "Remove "Zen" specific match and quirks"`
