### ISSUE TITLE
deprecate system-tools-backends

### ISSUE THREAD

**Issue by androidnisse** [getsolus/packages#3014]
### Please confirm there isn't already an existing package deprecation request

- [X] I have searched through package deprecation requests

### Name

system-tools-backends

### Last Update Date

2011-08-02

### Reason for deprecation

Last update 13 years ago.

**Comment by Staudey** [comment]
Note that `liboobs` requires `pkgconfig(system-tools-backends-2.0)` in the package recipe, but I guess that's probably no longer *actually* required?

**Comment by androidnisse** [comment]
> Note that `liboobs` requires `pkgconfig(system-tools-backends-2.0)` in the package recipe, but I guess that's probably no longer _actually_ required?

Well it actually needs it, it won't  build without it. That one is old as well, from 2011. Should I deprecate it as well?

**Comment by HarveyDevel** [comment]
Given `liboobs` description states it is a  "Wrapper library for System Tools Backends" and we are deprecating `system-tools-backends` then the wrapper serves no purpose and should be deprecated too.

**Comment by Staudey** [comment]
I'm more of a `libass` man myself anyway
