### ISSUE TITLE
opentabletdriver: non-functioning binaries

### ISSUE THREAD

**Issue by triplefox** [getsolus/packages#3026]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

A continuation from my package request with @nelsontkq 

_Originally posted by @triplefox in https://github.com/getsolus/packages/issues/972#issuecomment-2169486971_

This new package installs dependencies and binaries to run OTD, but the application binaries cannot start and produce the message:

```
Failure processing application bundle; possible file corruption.
Arithmetic overflow while reading bundle.
A fatal error occurred while processing application bundle
```

The binaries installed in /usr/lib appear to have been truncated to 72520 bytes in length each:

```
-rwxr-xr-x 1 root root 72520 Jun 14 18:39 OpenTabletDriver.Console
-rwxr-xr-x 1 root root 72520 Jun 14 18:39 OpenTabletDriver.Daemon
-rwxr-xr-x 1 root root 72520 Jun 14 18:39 OpenTabletDriver.UX.Gtk
```

The original binaries from [OTD's release](https://github.com/OpenTabletDriver/OpenTabletDriver/releases/download/v0.6.4.0/opentabletdriver-0.6.4.0-x64.tar.gz) have this size:

```
-rwxr-xr-x 1 root root  5619946 Jun 16 21:37 OpenTabletDriver.Console
-rwxr-xr-x 1 root root  5608228 Jun 16 21:37 OpenTabletDriver.Daemon
-rwxr-xr-x 1 root root 13052765 Jun 16 21:37 OpenTabletDriver.UX.Gtk
```

### Steps to reproduce

1. Install opentabletdriver 6.4.0-1.
2. Run "otd" from the console, or "OpenTabletDriver" from the launcher.

### Expected result

OpenTabletDriver runs.

### Actual result

OpenTabletDriver does not run.

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Xfce

### System details

System:
  Host: silverball2 Kernel: 6.8.12-293.current arch: x86_64 bits: 64
  Desktop: MATE v: 1.28.2 Distro: Solus 4.5 resilience
Machine:
  Type: Laptop System: Acer product: Swift SF114-32 v: V1.11
    serial: <superuser required>
  Mobo: GLK model: Sapporo_GL_S v: V1.11 serial: <superuser required>
    UEFI: Insyde v: 1.11 date: 09/27/2019
Battery:
  ID-1: BAT0 charge: 38.9 Wh (100.0%) condition: 38.9/54.2 Wh (71.9%)
CPU:
  Info: quad core Intel Pentium Silver N5000 [MCP] speed (MHz): avg: 812
    min/max: 800/2700
Graphics:
  Device-1: Intel GeminiLake [UHD Graphics 605] driver: i915 v: kernel
  Device-2: Chicony HD WebCam driver: uvcvideo type: USB
  Display: x11 server: X.Org v: 21.1.13 with: Xwayland v: 23.2.7 driver: X:
    loaded: modesetting unloaded: fbdev,vesa dri: iris gpu: i915
    resolution: 1920x1080~60Hz
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: intel mesa v: 24.1.1
    renderer: Mesa Intel UHD Graphics 605 (GLK 3)
Network:
  Device-1: Intel Gemini Lake PCH CNVi WiFi driver: iwlwifi
Drives:
  Local Storage: total: 524 GiB used: 37.31 GiB (7.1%)
Info:
  Memory: total: 4 GiB available: 3.63 GiB used: 2.4 GiB (66.0%)
  Processes: 208 Uptime: 1d 16h 43m Shell: Bash inxi: 3.3.34

### Other comments

Replacing the packaged binaries with the larger ones from the upstream release produces a .net versioning error:

```
You must install or update .NET to run this application.

App: /usr/lib64/opentabletdriver/OpenTabletDriver.Console
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '6.0.0' (x64)
.NET location: /usr/lib64/dotnet

The following frameworks were found:
  8.0.6 at [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]

Learn more:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=x64&rid=solus.4.5-x64&os=solus.4.5

```

This is using a fresh machine that hasn't previously handled any .net dependencies.

**Comment by nelsontkq** [comment]
Interesting. Perhaps my tablet has some native support and that gave me the false positive. I'll give this a look later today when I'm finished with work.

**Comment by HarveyDevel** [comment]
Fix has been cherry-picked https://github.com/getsolus/packages/commit/1132243ad601321a03eea32ebec688018daddfe1

Closing issue. Report back if problems persist.
