### ISSUE TITLE
Deprecate python-geoip

### ISSUE THREAD

**Issue by malfisya** [getsolus/packages#3027]
### Please confirm there isn't already an existing package deprecation request

- [X] I have searched through package deprecation requests

### Name

 python-geoip

### Link to an announcement of archival or deprecation, if applicable.

https://github.com/appliedsec/pygeoip/blob/2a725df0b727e8b08f217ab84f7b8243c42554f5/README.md?plain=1#L3-L4

### Reason for deprecation

It is deprecated upstream. It was based on legacy MaxMind API that was [retired as of 2022](https://github.com/maxmind/geoip-api-c). Upstream recommend to use [this](https://github.com/maxmind/GeoIP2-python) instead. A few packages still depends on it, namely `deluge`, `os-installer`, and `python-txtorcon`. Investigate those packages.

**Comment by androidnisse** [comment]
I think this can be removed now.
