### ISSUE TITLE
Plasma is missing dependencies needed for Settings - Devices - Firmware Security (T10528)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#307]
<div dir="rtl"><b>TraceyC</b>&nbsp;(<em>@TraceyC77</em>),&nbsp;2023-05-09&nbsp;14:52:49&nbsp;UTC</div><br/>

Opening Settings - Devices - Firmware Security shows "The aha tool is required to display this page, but could not be found"

Update: Now depends on D13506

**Comment by TraceyC77** [comment]
Depends on https://github.com/getsolus/packages/issues/292

**Comment by TraceyC77** [comment]
This is still an issue in the 4.5 test ISO. #292 has been closed as it has been merged.
