### ISSUE TITLE
Hugin: error (hugin:31470): Gtk-CRITICAL **: 16:38:58.104: gtk_widget_set_size_request: assertion 'height >= -1' failed (T10620)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#308]
<div dir="rtl"><b>Fabio</b>&nbsp;(<em>&#35;Fabio</em>),&nbsp;2023-08-16&nbsp;14:59:28&nbsp;UTC</div><br/>

Hugin don't work, the error is the following:

```

(hugin:47330): Gtk-CRITICAL **: 22:23:39.368: gtk_widget_set_size_request: assertion 'height >= -1' failed
(hugin:47330): Gtk-CRITICAL **: 22:23:39.368: gtk_widget_set_size_request: assertion 'height >= -1' failed
ERROR: 22:23:39.774333 (/home/build/YPKG/root/hugin/build/hugin-2022.0.0/src/hugin1/hugin/GLViewer.cpp:133) SetUpContext(): Error initialising GLEW: Unknown error.
Errore di segmentazione (core dump creato)
```
Maybe this [https://bbs.archlinux.org/viewtopic.php?pid=2047674#p2047674](https://bbs.archlinux.org/viewtopic.php?pid=2047674#p2047674), but the work around 
```
export XDG_DATA_HOME=""^C
```
don't work...

**Comment by FAb7D** [comment]
The problem is probably related to the need to update glue  to 2.2 using as source [https://github.com/nigels-com/glew.git](https://github.com/nigels-com/glew.git) instead of sourceforce.net or add a putch to 2.1.
See also: [https://bbs.archlinux.org/viewtopic.php?id=278127](https://bbs.archlinux.org/viewtopic.php?id=278127)

**Comment by ReillyBrogan** [comment]
![Screenshot_20231013_201746](https://github.com/getsolus/packages/assets/4309817/6806c836-bbfe-4df5-9deb-33e0a2d672e7)

Loads now. It's slow but that's probably just the app?

**Comment by FAb7D** [comment]
It seems to work well to me
