### ISSUE TITLE
update Tux Paint to 0.9.32

### ISSUE THREAD

**Issue by androidnisse** [getsolus/packages#3081]
### Please confirm there isn't already an existing package update request

- [X] I have searched through package update requests

### Name

Tux Paint

### Version

0.9.32

### Link to the release notes or announcement.

https://tuxpaint.org/latest/tuxpaint-0.9.32-press-release.php

### Reason for updating

They have switched over to SDL2 instead of SDL1.

**Comment by A108384** [comment]
This package also needs a homepage added.  
I would like to work version update as well as the homepage.

**Comment by davidjharder** [comment]
Apologies A108384, I did not see you working on this
