### ISSUE TITLE
ip command not found

### ISSUE THREAD

**Issue by colomain** [getsolus/packages#3094]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

ip command not found since last update. I've already checked if I have installed `iproute2` package.

### Steps to reproduce

1. Open a terminal
2. Type `ip a`
3. `Command not found: ip`

### Expected result

ip command to output

### Actual result

Command not found: ip

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Other

### System details

System:
  Host: solus-vant Kernel: 6.8.11-292.current arch: x86_64 bits: 64
  Desktop: i3 v: 4.21.1 Distro: Solus 4.5 resilience
Machine:
  Type: Laptop System: Notebook product: N14xWU v: N/A
    serial: <superuser required>
  Mobo: Notebook model: N14xWU serial: <superuser required>
    UEFI: American Megatrends v: 1.07.03 date: 05/17/2018
Battery:
  ID-1: BAT0 charge: 36.1 Wh (100.0%) condition: 36.1/35.3 Wh (102.1%)
CPU:
  Info: quad core Intel Core i7-8550U [MT MCP] speed (MHz): avg: 700
    min/max: 400/4000
Graphics:
  Device-1: Intel UHD Graphics 620 driver: i915 v: kernel
  Device-2: Chicony USB2.0 Camera driver: uvcvideo type: USB
  Display: x11 server: X.Org v: 21.1.13 with: Xwayland v: 23.2.7 driver: X:
    loaded: modesetting unloaded: fbdev,vesa dri: iris gpu: i915
    resolution: 1920x1080~60Hz
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: intel mesa v: 24.1.1
    renderer: Mesa Intel UHD Graphics 620 (KBL GT2)
Network:
  Device-1: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet
    driver: r8169
  Device-2: Intel Wi-Fi 5 Wireless-AC 9x6x [Thunder Peak] driver: iwlwifi
Drives:
  Local Storage: total: 954.81 GiB used: 756.7 GiB (79.3%)
Info:
  Memory: total: 32 GiB available: 31.23 GiB used: 10.86 GiB (34.8%)
  Processes: 316 Uptime: 2h 37m Shell: Zsh inxi: 3.3.35

**Comment by androidnisse** [comment]
I have the same issue. However it works with sudo.

**Comment by colomain** [comment]
> I have the same issue. However it works with sudo.

You're right, with `sudo` works. But I think I need access without sudo... I need to know my ip inside an script runned by Polybar...

**Comment by colomain** [comment]
I've just fixed add `/usr/sbin` to my `$HOME/.profile`, but something is going on by here...
