### ISSUE TITLE
Feature Request: Network Bootable Image (T5474)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#31]
<div dir="rtl"><b>oO.o</b>&nbsp;(<em>&#35;dotdigital-digital</em>),&nbsp;2018-01-05&nbsp;17:19:47&nbsp;UTC</div><br/>

Sorry if this is the wrong place for a feature request. This is my first time using Phabricator, and I did not see a feature request section separate from issues.

I use netboot.xyz to install most of the operating systems that I use. Sadly, it lacks Solus. I brought the issue up with the netboot.xyz dev and he says he needs a publicly hosted network bootable image in order to add it. Not sure this is something you guys have the resources for, but if you do, it would make installing Solus easier and faster for a lot of people.

Here's the issue I opened with netboot.xyz: https://github.com/antonym/netboot.xyz/issues/215#event-1410740104

Thanks!

Started with Solus yesterday and am really liking it so far.

**Comment by ermo** [comment]
@EbonJaeger Does calamares support this? If it doesn't, please close as Not Planned.

Otherwise, it can stay as a wishlist item I'd say.

**Comment by EbonJaeger** [comment]
I'm not even sure what "this" is, let alone where to look for it or even what to ask in the Calamares Matrix room.

**Comment by ermo** [comment]
It's essentially a way to stand up a live ISO environment that's delivered over the network IIUC.

**Comment by TraceyC77** [comment]
We aren't planning to make a net-installable ISO at this time.
