### ISSUE TITLE
Haxe package: "haxelib" tool: Uncaught exception - load.c(181) : Module not found  (T10623)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#310]
<div dir="rtl"><b>James&nbsp;Hofmann</b>&nbsp;(<em>&#35;triplefox</em>),&nbsp;2023-08-16&nbsp;23:21:26&nbsp;UTC</div><br/>

# Summary 

The problem occurs exactly as described in https://github.com/HaxeFoundation/haxe/issues/4735 - the "haxelib" tool fails at startup because a dependency can't be found. The Haxe core developers indicate that it's due to a stripped binary. The author of that issue experienced it on Mint, but the behavior is identical on Solus.

## Steps to reproduce

1. Install haxe package (4.3.0-4)
2. Run "haxelib version" from the terminal

## Expected result

The haxelib tool runs and displays it's version.

## Actual result

Uncaught exception - load.c(181) : Module not found : help

## Environment

Release 4.4, 64-bit, MATE Desktop. Installed from ISO and updated through Software Center.

## System details

Kernel Linux 6.4.9-248.current x86_64
MATE 1.27.1
Memory: 15.5 GiB
Processor: Intel® Core™ i7-7700HQ CPU @ 2.80GHz × 8 
Graphics: Mesa Intel® HD Graphics 630 (KBL GT2)

**Comment by ermo** [comment]
Issue reproduced on my end:

```
Installing 3 / 3
haxe-4.3.0-4-1-x86_64.eopkg [cached]
Installing haxe, version 4.3.0, release 4
Extracting the files of haxe
Installed haxe
 [✓] Syncing filesystems                                                success
 [✓] Updating dynamic library cache                                     success
ermo@solbox:~
$ haxelib version
Uncaught exception - load.c(181) : Module not found : version
ermo@solbox:~
$ 
```
