### ISSUE TITLE
Unreadable icons in LibreOffice in Budgie Edition

### ISSUE THREAD

**Issue by EbonJaeger** [getsolus/packages#311]
### Summary

The Budgie Desktop edition uses a regular (light) theme by default, but LibreOffice is set to use its Sufi (dark) theme, thus rendering the toolbar icons unreadable.

So far, I have been unable to find a way to override this just for the Budgie edition. The patch for setting the icon theme in LibreOffice can be found [here](https://github.com/solus-packages/libreoffice/blob/master/files/0001-Use-the-Sifr-style-by-default.patch). The only other way I can see would be to use Materia-Dark by default on Budgie, but, well, I'd rather have the regular version.

There used to be an issue for this on the old Phabricator instance, but it's too old to have been migrated and searching the read-only instance appears to be impossible.

### Steps to reproduce

1. Install Budgie Desktop
2. Open LibreOffice
3. Observe white-on-white icons in the toolbars

### Expected result

Icons to be visible against the application background.

### Actual result

![image](https://github.com/getsolus/packages/assets/5157277/45159e13-c848-48a8-b13c-7265613e477e)

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

Budgie

### System details

CPU: Intel Core i5-6400
GPU: AMD Radeon RX 560 Series
RAM: 16 GiB
Budgie Version: 10.8-dev

### Other comments

Made this so it won't be forgotten about.

**Comment by malfisya** [comment]
Can't we just use the default as in not patching it at all. If it remains `auto`, will it use appropriate theme? Or just patch it to use elementary icon theme, sure it isn't symbolic icon but it looks legible on both light and dark theme.

**Comment by ermo** [comment]
@EbonJaeger Just a friendly reminder that this is one of those theme bugs we're hoping to be able to fix for 4.6...

**Comment by EbonJaeger** [comment]
Setting the theme to automatic only ever seems to pick the dark theme, so that won't work. Do we want to use the Elementary theme? There really is no other way around this.
