### ISSUE TITLE
vscode: bug: dialog windows open behind main window on Plasma

### ISSUE THREAD

**Issue by TraceyC77** [getsolus/packages#3110]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

When a dialog opens in VS Code, it is behind the main window rather than in front
This is the same as getsolus/packages/issues/1925

### Steps to reproduce

1. Start VS Code
2. Trigger any dialog such as File - Open

### Expected result

The dialog window is on top of all other windows

### Actual result

The dialog window is behind VS Code

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

Plasma

### System details

Operating System: Solus 4.5
KDE Plasma Version: 6.0.5
KDE Frameworks Version: 6.3.0
Qt Version: 6.7.2
Kernel Version: 6.8.12-293.current (64-bit)
Graphics Platform: X11

### Other comments

I had just updated the system this morning
Not sure why this keeps happening?

**Comment by TraceyC77** [comment]
Talked with Reilly, and this is an upstream issue
"Yep. Electron needs to implement a Wayland API"
We have a patch in place to fix the issue on Wayland, but that breaks it in X11. Given that we are moving slowly to Wayland being the priority, supporting Wayland rather than X11 for this makes sense.

**Comment by ReillyBrogan** [comment]
Note that as of vscode 1.95 the version of Electron used has now been updated to one that supports said Wayland API.
