### ISSUE TITLE
chore: Use cargo macros across the repo

### ISSUE THREAD

**Issue by joebonrichie** [getsolus/packages#3111]
`ypkg` now provides standardized cargo macros for rust packages:

`%cargo_fetch`, `%cargo_build`, `%cargo_install`, `%cargo_test`

Note that `%cargo_install` can take an additional argument if the binary name does not match the package name e.g. `%cargo_install mycustombinary`

See d44c520077f1b1b0e9194e014e2b555678e8263e as an example

For an new packagers wishing to learn the Solus packaging system, this would be a good opportunity to do so. See the full list yourself by installing the `ripgrep` package and running the following ripgrep (`rg`) command from the root of this repository:
```
rg --files-with-matches "cargo build" -g '*package.yml' | sort
```

#### The list

**~~37~~  ~~21~~ ~~7~~ 1 package left(!)**
- rav1el

**Comment by androidnisse** [comment]
The macro for install can be improved, see https://github.com/getsolus/packages/issues/3230

**Comment by HarveyDevel** [comment]
We may want to consider new cargo macros as David pointed out:
> rg "cargo c"
packages/r/rav1e/package.yml
23:    cargo cbuild \
34:    cargo cinstall \

packages/l/libdovi/package.yml
20:    cargo cbuild \
26:    cargo cinstall \

packages/l/libimagequant/package.yml
17:    cargo cinstall --prefix=/usr --destdir=$installdir

But the original scope of this task is now complete. Thank you to everyone who contributed.
