### ISSUE TITLE
Update lite-xl to v2.1.5

### ISSUE THREAD

**Issue by uni-dos** [getsolus/packages#3136]
### Please confirm there isn't already an existing package update request

- [X] I have searched through package update requests

### Name

lite-xl

### Version

2.1.5

### Link to the release notes or announcement.

https://github.com/lite-xl/lite-xl/releases/tag/v2.1.5

### Reason for updating

Nothing major for Linux but adds has some syntax highlighting updates for C/C++ and general bug fixes.

**Comment by malfisya** [comment]
You don't have to file package update request if you intend to update it yourself. More over this is the package you maintain, just file a PR.👍 Lets keep this open until your PR got merged.

**Comment by uni-dos** [comment]
Yeah, my bad. I only realized it after I made the pull request. It seemed like I did unnecessary work. I will do better next time.
