### ISSUE TITLE
System UI (Budgie) crashes afer launching `teamviewer` 

### ISSUE THREAD

**Issue by algent-al** [getsolus/packages#315]
### Summary

After installing `teamviewer` system crashed with error "Oh no something has gone wrong" and then log out.

This issues is reported also on the forum by a user using Stable repository:
https://discuss.getsol.us/d/9687-sync-updates-for-week-34-2023/14

### Steps to reproduce

1. Install `teamviewer`
2. Run: `$ teamviewer --daemon start`
3. Launch `teamviewer` from menu.

### Expected result

Launch application and connect to another computer.

### Actual result

Session crashed with message "Oh no something has gone wrong".

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

Budgie

### System details

OS: Solus x86_64
Host: CELSIUS W530
DE: Budgie 10.8
WM: Mutter(Budgie)
Kernel: 6.4.11-251.current
CPU: Intel Xeon E3-1271 v3 (8) @ 4.000GHz
GPU: NVIDIA Quadro M2000
Memory: 2512MiB / 15923MiB

**Comment by EbonJaeger** [comment]
Closing here in favor of https://github.com/BuddiesOfBudgie/budgie-desktop/issues/429
