### ISSUE TITLE
libgnome-menus does not build

### ISSUE THREAD

**Issue by skmd0** [getsolus/packages#3173]
`libgnome-menus` does not build.

```
[Build] setup failed for libgnome-menus
 ✗  Failed to build packages err="Failed to start build of package, reason: exit status 1\n"
task: Failed to run task "build": exit status 1
```

**Comment by Staudey** [comment]
@skmd0 Seems like a lot of the packages you found that don't build as-is just need the `%configure_no_runstatedir` fix (see https://help.getsol.us/docs/packaging/troubleshooting-packaging#an-old-package-using-configure-doesnt-build)

Btw, the error that you posted here is not the one that provides useful information. Make sure to include the part of the build log that shows the error inside the build environment. In this case that would be:

```
+ ./configure --prefix=/usr --build=x86_64-solus-linux --bindir=/usr/bin --sbindir=/usr/sbin --libdir=/usr/lib64 --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var --runstatedir=/run --libexecdir=/usr/lib64/libgnome-menus --disable-static
configure: error: unrecognized option: `--runstatedir=/run'
Try `./configure --help' for more information
Command '['/bin/bash', '--norc', '--noprofile', '/tmp/ypkg-setupdwszcogg']' returned non-zero exit status 1.
[Build] setup failed for libgnome-menus
```

**Comment by skmd0** [comment]
I am completely new to building packages, so reading these logs look like chinese language to me. :laughing:

**Comment by Staudey** [comment]
No worries :grin: 

Marking packages that currently don't build is valuable enough in itself :+1:
