### ISSUE TITLE
KDE Discover

### ISSUE THREAD

**Issue by livingsilver94** [getsolus/packages#318]
### Homepage

https://apps.kde.org/it/discover

### Why should this be included in the repository?

It'll succeed the Software Center.

### Are we allowed to redistribute it?

Usual license used by Plasma. GPL and whatnot

### Who and how many users do you anticipate will use this software?

Since it'll succeed Software Center, at least every user using Solus Plasma.

### Link to source archive file

https://download.kde.org/stable/plasma/5.27.7/discover-5.27.7.tar.xz

**Comment by kostadinsh** [comment]
I think that the icon that is currently manually added to the `flatpak-kcm` package here: https://github.com/getsolus/packages/blob/main/packages/f/flatpak-kcm/files/flatpak-discover.svg (which is responsible for the Flatpak permission thing icon in plasma's settings) should be in discover, so you can remove it from `flatpak-kcm` when this gets packaged.

**Comment by joebonrichie** [comment]
e590eeb4d43ef8cc44b23562ff49913a6c35407d
