### ISSUE TITLE
GNOME Software

### ISSUE THREAD

**Issue by livingsilver94** [getsolus/packages#319]
### Homepage

https://apps.gnome.org/app/org.gnome.Software

### Why should this be included in the repository?

It'll succeed the Software Center.

### Are we allowed to redistribute it?

The usual license used by GNOME

### Who and how many users do you anticipate will use this software?

Since it'll succeed Software Center, at least every user of Solus GNOME, and likely XFCE and Budgie.

### Link to source archive file

https://gitlab.gnome.org/GNOME/gnome-software/-/archive/44.4/gnome-software-44.4.tar.bz2

**Comment by joebonrichie** [comment]
f36b8fdb1e9506cc272b4cd014c6bbb6f632f9f4
