### ISSUE TITLE
deopkg

### ISSUE THREAD

**Issue by livingsilver94** [getsolus/packages#320]
### Homepage

https://github.com/serpent-os/deopkg

### Why should this be included in the repository?

It'll be the glue library between eopkg and PackageKit, so that will be able to install packages using KDE Discover and GNOME Software.

### Are we allowed to redistribute it?

Obviously. It's a Serpent OS project.

### Who and how many users do you anticipate will use this software?

Everyone?

### Link to source archive file

NOT READY YET.

**Comment by davidjharder** [comment]
This is dead.
