### ISSUE TITLE
libgtkmm4

### ISSUE THREAD

**Issue by Xrey274** [getsolus/packages#321]
### Homepage

https://www.gtkmm.org/en/index.html

### Why should this be included in the repository?

It allows the development and use of GTK4 with C++.

### Are we allowed to redistribute it?

LGPL

### Who and how many users do you anticipate will use this software?

I suppose a fair bit of Linux GTK developers would appreciate it.

### Link to source archive file

https://download.gnome.org/sources/gtkmm/4.9/gtkmm-4.9.3.tar.xz

**Comment by Staudey** [comment]
Probably also only a matter of time until some GNOME stuff depends on it.

**Comment by ReillyBrogan** [comment]
878fd223faeb055d3fd023fec9593c8c35a94e1e
