### ISSUE TITLE
new macros for cargo does not accept more then one binary

### ISSUE THREAD

**Issue by androidnisse** [getsolus/packages#3230]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

When using %cargo_install it only accepts one binary. If more is needed a loop or using the macro multiple times is needed. See example in https://github.com/getsolus/packages/pull/3229/files

### Steps to reproduce

1. Build with more then one binary

### Expected result

It installs all.

### Actual result

It fails and falls backs to the package name.

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

Budgie

### System details

x

### Other comments

Posted about this in package room on matrix.

**Comment by EbonJaeger** [comment]
How often does this actually come up? I would consider having to just do a loop in a package file a good tradeoff to the potential complexity of having the macro do it.

**Comment by androidnisse** [comment]
> How often does this actually come up? I would consider having to just do a loop in a package file a good tradeoff to the potential complexity of having the macro do it.

I have found this once for now. This can be looked at further when all packages use the macro.

**Comment by androidnisse** [comment]
> How often does this actually come up? I would consider having to just do a loop in a package file a good tradeoff to the potential complexity of having the macro do it.

Seems to be 4, see above comment. :)

**Comment by Staudey** [comment]
Would also save one line in `ripgrep-all` ^^
https://github.com/getsolus/packages/blob/2a91e453f4b6897b3dbbcb50b90443bac311794e/packages/r/ripgrep-all/package.yml#L25-L26
