### ISSUE TITLE
Switch cadence to maintained fork

### ISSUE THREAD

**Issue by androidnisse** [getsolus/packages#3262]
### Please confirm there isn't already an existing package deprecation request

- [X] I have searched through package deprecation requests

### Name

cadence

### Last Update Date

2022-06-18

### Link to an announcement of archival or deprecation, if applicable.

https://github.com/falkTX/Cadence

### Reason for deprecation

Archived at it's source.

**Comment by Staudey** [comment]
Seems like it has been picked up by the LADI ("Linux Audio Desktop Integration") project https://github.com/LADI/Cadence

> Since August 2023, LADI/Claudia is maintained by Nedko Arnaudov (LADI project), the author of jackdbus and ladish.

Though I'm unsure about the status of it all when I look at the title of their org on GitHub https://github.com/LADI

And their website isn't reachable atm https://ladish.org/

**Comment by androidnisse** [comment]
> Seems like it has been picked up by the LADI ("Linux Audio Desktop Integration") project https://github.com/LADI/Cadence
> 
> > Since August 2023, LADI/Claudia is maintained by Nedko Arnaudov (LADI project), the author of jackdbus and ladish.
> 
> Though I'm unsure about the status of it all when I look at the title of their org on GitHub https://github.com/LADI
> 
> And their website isn't reachable atm https://ladish.org/

Good find, might be worth waiting a little to see if that website goes up.
