### ISSUE TITLE
packaging: Kate is missing the sql plugin

### ISSUE THREAD

**Issue by TraceyC77** [getsolus/packages#3265]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

The SQL plugin is not found in Kate

### Steps to reproduce

1. Open Kate
2. Search the plugins for SQL

### Expected result

The SQL plugin is available

### Actual result

The SQL plugin is not available

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

Plasma

### System details

The plugin needs to be packaged with Kate
See [this upstream bug](https://bugs.kde.org/show_bug.cgi?id=488694)

### Other comments

cc @ReillyBrogan @Justinzobel

**Comment by ReillyBrogan** [comment]
Closing as upstream issue, fix will likely be in Gear 24.08.
