### ISSUE TITLE
Replace exa with eza

### ISSUE THREAD

**Issue by Solarunit** [getsolus/packages#327]
### Homepage

https://github.com/eza-community/eza

### Why should this be included in the repository?

Since  `exa` is no longer maintained we should switch to its active fork called `eza`

>exa is unmaintained, please use the active fork eza instead
https://github.com/ogham/exa/commit/fb05c421ae98e076989eb6e8b1bcf42c07c1d0fe

### Are we allowed to redistribute it?

MIT

### Who and how many users do you anticipate will use this software?

Previous users of `exa` and future users who want a more modern and featured `ls` replacement.

### Link to source archive file

https://github.com/eza-community/eza/archive/refs/tags/v0.11.0.tar.gz

**Comment by EbonJaeger** [comment]
Looks like you used the wrong issue template. :)

That said, I was actually going to get started on this this morning, but didn't have enough time. I'll probably do it after sync or over the weekend.
