### ISSUE TITLE
OneDriveGUI

### ISSUE THREAD

**Issue by maikwoehl** [getsolus/packages#329]
### Homepage

https://github.com/bpozdena/OneDriveGUI

### Why should this be included in the repository?

The [onedrive](https://github.com/solus-packages/onedrive) tool that is already included in repo is CLI only. This is a GUI client for our fellow not-tech users of solus.

### Are we allowed to redistribute it?

GPL-3.0

### Who and how many users do you anticipate will use this software?

Users of OneDrive - probably the ones that are not willing to use CLI.

### Link to source archive file

https://github.com/bpozdena/OneDriveGUI/archive/refs/tags/v1.0.3.tar.gz

**Comment by maikwoehl** [comment]
I would step up and package it myself.

**Comment by silkeh** [comment]
@maikwoehl: PR welcome!

**Comment by maikwoehl** [comment]
@silkeh This package is a python package. Should it be named `onedrive-gui` to be consistent with cli package `onedrive` or should it be named `python-onedrive-gui` and only the execution script in `/usr/bin` can be named `onedrive-gui`?

**Comment by silkeh** [comment]
@maikwoehl: I prefer `onedrive-gui`, as it isn't a python module.
