### ISSUE TITLE
i3-style does not build with new cargo macro

### ISSUE THREAD

**Issue by androidnisse** [getsolus/packages#3298]
i3-style does not build with %cargo_fetch

error: the lock file /home/build/YPKG/root/i3-style/build/i3-style-1.0.2/Cargo.lock needs to be updated but --locked was passed to prevent this
If you want to try to generate the lock file without accessing the network, remove the --locked flag and use --offline instead.

**Comment by joebonrichie** [comment]
they shipped the tarball with and out of date lockfile if i had to guess

**Comment by androidnisse** [comment]
> they shipped the tarball with an out of date lockfile if i had to guess

So what do we do here? Skip the macro, modify it?
