### ISSUE TITLE
Update OTPClient to 3.7.0

### ISSUE THREAD

**Issue by moriel5** [getsolus/packages#3328]
### Please confirm there isn't an existing package update request
- [x] I have searched through package update requests.

### Name

OTPClient

### Version

3.7.0

### Link to the release notes or announcement.

https://github.com/paolostivanin/OTPClient/archive/refs/tags/v3.7.0.tar.gz

### Reason for updating

The version of OTPClient in the Solus repository has been lagging behind quite a bit, with new features that have not made their way to Solus users as a result.

Since I have already packaged it locally yesterday, and it has been working very well, I have no issues upstreaming my package.yml.

**Comment by malfisya** [comment]
Please use the appropriate issue template, We have them for a reason. [This](https://github.com/getsolus/packages/issues/new?assignees=&labels=Package+Update+Request&projects=&template=request-package-update.yml) is the correct one. Cheers!

**Comment by moriel5** [comment]
@malfisya Thank you very much, I need to go over there templates, I see.

I shall edit the issue accordingly once I have gone over them.

**Comment by malfisya** [comment]
Fasthub is [dead](https://github.com/k0shk0sh/FastHub). Please, either use the website or the [official android app](https://play.google.com/store/apps/details?id=com.github.android).

**Comment by moriel5** [comment]
I realize that, however neither simultaneously offer both ease of use and low system utilization, so on mobile I remain on FastHub.

However since the contribution will be sent from my desktop, I'll use the website in any case (for the issue, the commit will be via CLI) to go over the templates and revise the issue accordingly.

**Comment by moriel5** [comment]
And now (very late, admittedly) I have updated it.
Time to send out the comment.
