### ISSUE TITLE
deprecate clipit

### ISSUE THREAD

**Issue by androidnisse** [getsolus/packages#3349]
### Please confirm there isn't already an existing package deprecation request

- [X] I have searched through package deprecation requests

### Name

clipit

### Last Update Date

2020-06-11

### Link to an announcement of archival or deprecation, if applicable.

https://github.com/CristianHenzel/ClipIt/issues/204

### Reason for deprecation

No active development, dropped in Debian and replaced with Diodon

**Comment by TraceyC77** [comment]
This should be done after [the inclusion of diodon](getsolus/packages/issues/3350)
