### ISSUE TITLE
Update Freeplane to 1.11.6

### ISSUE THREAD

**Issue by endumiuz** [getsolus/packages#335]
### Name

Freeplane

### Version

1.11.6

### Link to the release notes or announcement.

https://www.freeplane.org/info/history/history_en.txt

### Other comments

It's a year out of date

https://github.com/freeplane/freeplane/releases/tag/release-1.11.6

**Comment by algent-al** [comment]
Resolved by [ecb59e2](https://github.com/solus-packages/freeplane/commit/ecb59e24dd561e08b7739763afdd43f91c763cff)
