### ISSUE TITLE
diodon

### ISSUE THREAD

**Issue by androidnisse** [getsolus/packages#3350]
### Please confirm there isn't an existing package request

- [X] I have searched through package requests

### Homepage

https://github.com/diodon-dev/diodon

### Maintainer

- [X] Would you like to be the maintainer for this package?

### Why should this be included in the repository?

Aimed to replace clipit.

### Are we allowed to redistribute it?

GPL-2.0-or-later

### What kind of user will use this package, and how many users do you think will use this package?

Current users of clipit.

### Link to source archive file

https://github.com/diodon-dev/diodon/archive/refs/tags/1.13.0.tar.gz

**Comment by TraceyC77** [comment]
Since the last release of a deb for clipit was Oct 23, 2020, a replacement is a good idea.
