### ISSUE TITLE
duf

### ISSUE THREAD

**Issue by HarveyDevel** [getsolus/packages#337]
### Homepage

https://github.com/muesli/duf

### Why should this be included in the repository?

`duf` - Disk Usage/Free Utility is an alternative to `df`

The advantage over `df` is it outputs a colourful, formatted list of devices separated into categories local, network and special with a graphic representation of use % that makes use of colours to indicate different levels of disk space usage; These thresholds are adjustable via a flag.

![duf](https://github.com/muesli/duf/blob/master/duf.png?raw=true)

It can also output this as JSON if you really hate yourself:
```
 {
  "device": "/dev/nvme0n1p3",
  "device_type": "local",
  "mount_point": "/",
  "fs_type": "ext4",
  "type": "ext2/ext3",
  "opts": "rw,relatime",
  "total": 1963403595776,
  "free": 1314173894656,
  "used": 549418733568,
  "inodes": 121823232,
  "inodes_free": 118664287,
  "inodes_used": 3158945,
  "blocks": 479346581,
  "block_size": 4096
 },
```

### Are we allowed to redistribute it?

MIT, BSD-3-Clause

### Who and how many users do you anticipate will use this software?

Anyone that currently uses `df`.

### Link to source archive file

https://github.com/muesli/duf/archive/refs/tags/v0.8.1.tar.gz

**Comment by davidjharder** [comment]
Seems cool
