### ISSUE TITLE
No more Wi-Fi adapter after last upgrade (T6594)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#34]
<div dir="rtl"><b>Kevin&nbsp;Segaud</b>&nbsp;(<em>&#35;Kleak</em>),&nbsp;2018-06-30&nbsp;09:23:47&nbsp;UTC</div><br/>

After the last upgrade my wifi is no more working :/

**Comment by davidjharder** [comment]
Old, no new info, closing
