### ISSUE TITLE
Update networkmanager-openconnect to 1.2.10

### ISSUE THREAD

**Issue by ammunoz** [getsolus/packages#343]
### Name

networkmanager-openconnect

### Version

1.2.10

### Link to the release notes or announcement.

https://gitlab.gnome.org/GNOME/NetworkManager-openconnect/-/tags/1.2.10

### Other comments

An increasing number of us require SSO authentication for work/corporate VPN which is a new feature of 1.2.10 for some protocols.

**Comment by infinitymdm** [comment]
+1 from me. This would be super convenient to have

**Comment by ZachBacon** [comment]
I'll land it in my gnome 45 update that I have in progress.

**Comment by ammunoz** [comment]
> I'll land it in my gnome 45 update that I have in progress.

Appreciate the work!

Anywhere we can keep track of progress on this? Not trying to rush you, just would be nice to know when it lands.

**Comment by infinitymdm** [comment]
@ammunoz If you're wanting to keep an eye on gnome 45 progress, probably the best way to do that is to watch the Solus Packaging Matrix channel: https://matrix.to/#/#solus-packaging:matrix.org

Zach posts info there pretty regularly.

**Comment by malfisya** [comment]
This one already solved by 439453731254c20549648c98dc954bea078084bd as GNOME 45 stack already on shannon/stable.
