### ISSUE TITLE
Upgrade VCMI package

### ISSUE THREAD

**Issue by presianbg** [getsolus/packages#3458]
### Please confirm there isn't already an existing package update request

- [X] I have searched through package update requests

### Name

VCMI 

### Version

1.5.5

### Link to the release notes or announcement.

https://github.com/vcmi/vcmi/releases/tag/1.5.5

### Reason for updating

Hi,

The VCMI is great project and extremely active. Solus repo has v1, which  was released almost 2 years ago.
It would be nice to have the up-to-date version in the repo.

Best Regards,
PY

**Comment by presianbg** [comment]
Hm, actually their site is showing that v1.6 is the latest one:
https://vcmi.eu/ChangeLog/

![image](https://github.com/user-attachments/assets/f38acf7e-19f8-4d5b-8a38-bda2e8851761)

**Comment by presianbg** [comment]
3rd time is a charm :) 
Actually it has up-to-date official flatpak package:
https://flathub.org/apps/eu.vcmi.VCMI

having In mind that Solus is steering towards this approach for some applications, its your decision to have the native package removed from the repo.

**Comment by malfisya** [comment]
Can you help us test this? None of the staff have the game to test it. You can do so with
```
sudo eopkg it https://packages.getsol.us/unstable/v/vcmi/vcmi-1.5.5-29-1-x86_64.eopkg
```
If it is not good you can just do `sudo eopkg it --reinstall vcmi` to rollback it to previous version. Cheers!

**Comment by presianbg** [comment]
Awesome!
![image](https://github.com/user-attachments/assets/7c83e41e-7776-4a96-94bb-735ec493ab60)
