### ISSUE TITLE
Audio stops working after last update (Week 31, 2024)

### ISSUE THREAD

**Issue by deoxys94** [getsolus/packages#3477]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

After applying the Week 31, 2024 updates, audio stops working and the settings only show a dummy output. Audio goes back to normal after rolling back my system to the previous state.

Here's the result of running `lspci | grep -i audio`

`00:1f.3 Multimedia audio controller: Intel Corporation Tiger Lake-LP Smart Sound Technology Audio Controller (rev 20)`

Let me know if you need more information.

### Steps to reproduce

1. Apply the Week 31, 2024 updates.
2. Restart the system

### Expected result

The system should work like usual.

### Actual result

Audio stops working.

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

GNOME

### System details

```
System:
  Host: kuro Kernel: 6.9.10-295.current arch: x86_64 bits: 64
  Desktop: GNOME v: 46.3.1 Distro: Solus 4.5 resilience
Machine:
  Type: Laptop System: LENOVO product: 20TAS01Q00 v: ThinkPad E14 Gen 2
  Mobo: LENOVO model: 20TAS01Q00 v: SDK0J40700 WIN
    serial: <superuser required> UEFI: LENOVO v: R1EET56W(1.56 )
    date: 06/29/2023
Battery:
  ID-1: BAT0 charge: 31.6 Wh (79.4%) condition: 39.8/45.7 Wh (87.0%)
CPU:
  Info: quad core 11th Gen Intel Core i5-1135G7 [MT MCP] speed (MHz): avg: 945
    min/max: 400/4200
Graphics:
  Device-1: Intel TigerLake-LP GT2 [Iris Xe Graphics] driver: i915 v: kernel
  Device-2: NVIDIA TU117M [GeForce MX450] driver: nouveau v: kernel
  Device-3: Bison Integrated Camera driver: uvcvideo type: USB
  Display: wayland server: X.Org v: 24.1.1 with: Xwayland v: 24.1.1
    compositor: gnome-shell driver: gpu: i915 resolution: 1: 2560x1440~120Hz
    2: 1920x1080~120Hz
  API: OpenGL v: 4.6 compat-v: 4.3 vendor: intel mesa v: 24.1.4
    renderer: Mesa Intel Xe Graphics (TGL GT2)
Network:
  Device-1: Intel Wi-Fi 6 AX201 driver: iwlwifi
  Device-2: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet
    driver: r8169
Drives:
  Local Storage: total: 942.7 GiB used: 39.8 GiB (4.2%)
Info:
  Memory: total: 16 GiB note: est. available: 15.33 GiB used: 3.85 GiB (25.1%)
  Processes: 298 Uptime: 11m Shell: Bash inxi: 3.3.35
```

**Comment by malfisya** [comment]
Sorry hijacking your issue a bit. I am making this issue as umbrella for everyone that has the same problem. People are encouraged to post their hardware specs here. Cheers!

**Comment by deoxys94** [comment]
@malfisya Sure! I think that would be more helpful for everyone

**Comment by themouseNZ** [comment]
Issue has affected me. Down-grading the kernel has given me sound back.

System:
  Host: hp-x360-g4 Kernel: 6.9.10-295.current arch: x86_64 bits: 64
  Desktop: KDE Plasma v: 6.1.3 Distro: Solus 4.5 resilience
Machine:
  Type: Convertible System: HP product: HP EliteBook x360 1030 G4 v: N/A
    serial: <superuser required>
  Mobo: HP model: 8637 v: KBC Version 68.36.00 serial: <superuser required>
    UEFI: HP v: R94 Ver. 01.24.00 date: 03/28/2023
Battery:
  ID-1: BAT0 charge: 42.4 Wh (97.9%) condition: 43.3/56.2 Wh (77.1%)
    volts: 8.2 min: 7.7
CPU:
  Info: quad core Intel Core i7-8565U [MT MCP] speed (MHz): avg: 500
    min/max: 400/4600
Graphics:
  Device-1: Intel WhiskeyLake-U GT2 [UHD Graphics 620] driver: i915 v: kernel
  Device-2: Quanta HP Full-HD Camera driver: uvcvideo type: USB
  Display: wayland server: X.org v: 1.21.1.13 with: Xwayland v: 24.1.1
    compositor: kwin_wayland driver: N/A resolution: 3840x2160
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: intel mesa v: 24.1.5
    renderer: Mesa Intel UHD Graphics 620 (WHL GT2)
Network:
  Device-1: Intel Wi-Fi 6 AX200 driver: iwlwifi
  Device-2: Realtek RTL8153 Gigabit Ethernet Adapter driver: r8152 type: USB
Drives:
  Local Storage: total: 504.19 GiB used: 290.58 GiB (57.6%)
Info:
  Memory: total: 16 GiB note: est. available: 15.43 GiB used: 2.94 GiB (19.1%)
  Processes: 311 Uptime: 2m Shell: Bash inxi: 3.3.35

**Comment by hasib-rozi** [comment]
My Linux Kernel: Linux 6.9.10-295.current (rolling back from previous version)

System:
  Host: resilience-solus Kernel: 6.9.10-295.current arch: x86_64 bits: 64
  Desktop: GNOME v: 46.3.1 Distro: Solus 4.5 resilience
Machine:
  Type: Convertible System: LENOVO product: 82R7 v: IdeaPad Flex 5 14IAU7
  serial: <superuser required>
  Mobo: LENOVO model: LNVNB161216 v: SDK0T76493 WIN
  serial: <superuser required> UEFI: LENOVO v: J7CN44WW date: 05/24/2023
Battery:
  ID-1: BAT0 charge: 45.0 Wh (97.0%) condition: 46.4/52.5 Wh (88.3%)
CPU:
  Info: 10-core (2-mt/8-st) 12th Gen Intel Core i5-1235U [MST AMCP]
  speed (MHz): avg: 1412 min/max: 400/4400:3300
Graphics:
  Device-1: Intel Alder Lake-UP3 GT2 [Iris Xe Graphics] driver: i915 v: kernel
  Device-2: Bison Integrated Camera driver: uvcvideo type: USB
  Display: x11 server: X.Org v: 21.1.13 with: Xwayland v: 24.1.1 driver: X:
  loaded: modesetting unloaded: fbdev,vesa dri: iris gpu: i915
  resolution: 1920x1200~60Hz
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: intel mesa v: 24.1.5
  renderer: Mesa Intel Graphics (ADL GT2)
Network:
  Device-1: Intel Alder Lake-P PCH CNVi WiFi driver: iwlwifi
Drives:
  Local Storage: total: 476.94 GiB used: 84.34 GiB (17.7%)
Info:
  Memory: total: 16 GiB note: est. available: 15.19 GiB used: 3.62 GiB (23.9%)
  Processes: 334 Uptime: 5m Shell: Bash inxi: 3.3.35

**Comment by lf-araujo** [comment]
Same here:

System:
  Host: solus Kernel: 6.6.43-251.lts arch: x86_64 bits: 64
  Desktop: GNOME v: 46.3.1 Distro: Solus 4.5 resilience
Machine:
  Type: Laptop System: Dell product: Inspiron 5490 v: N/A
    serial: <superuser required>
  Mobo: Dell model: 0YMVR1 v: A04 serial: <superuser required> UEFI: Dell
    v: 1.11.0 date: 08/13/2020
Battery:
  ID-1: BAT0 charge: 24.0 Wh (60.6%) condition: 39.6/51.0 Wh (77.6%)
    volts: 11.2 min: 11.4
CPU:
  Info: quad core Intel Core i7-10510U [MT MCP] speed (MHz): avg: 2400
    min/max: 400/4900
Graphics:
  Device-1: Intel CometLake-U GT2 [UHD Graphics] driver: i915 v: kernel
  Device-2: NVIDIA GP108M [GeForce MX230] driver: nvidia v: 550.107.02
  Device-3: Realtek Integrated_Webcam_HD driver: uvcvideo type: USB
  Display: wayland server: X.Org v: 24.1.1 with: Xwayland v: 24.1.1
    compositor: gnome-shell driver: X: loaded: modesetting unloaded: fbdev,vesa
    dri: iris gpu: i915 resolution: 1600x900~60Hz
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: intel mesa v: 24.1.5
    renderer: Mesa Intel UHD Graphics (CML GT2)
Network:
  Device-1: Intel Comet Lake PCH-LP CNVi WiFi driver: iwlwifi
Drives:
  Local Storage: total: 238.47 GiB used: 157.58 GiB (66.1%)
Info:
  Memory: total: 16 GiB note: est. available: 15.29 GiB used: 4.44 GiB (29.0%)
  Processes: 319 Uptime: 5m Shell: Zsh inxi: 3.3.35

**Comment by bigrammy** [comment]
I lost my Inbuilt Microphone's again although the sound still works on Digital & Analog Outputs C-Media (R) Audio 

`lspci | grep -i audio
00:1f.3 Multimedia audio controller: Intel Corporation Ice Lake-LP Smart Sound Technology Audio Controller (rev 30)
System:
  Host: bigrammy Kernel: 6.9.12-297.current arch: x86_64 bits: 64
  Desktop: Budgie v: 10.9.2 Distro: Solus 4.5 resilience
Machine:
  Type: Laptop System: ASUSTeK product: VivoBook_ASUSLaptop X515JAB_X515JA
    v: 1.0 serial: <superuser required>
  Mobo: ASUSTeK model: X515JAB v: 1.0 serial: <superuser required>
    UEFI: American Megatrends v: X515JAB.309 date: 08/17/2022
Battery:
  ID-1: BAT0 charge: 34.8 Wh (100.0%) condition: 34.8/37.1 Wh (93.7%)
    volts: 7.8 min: 7.8
CPU:
  Info: dual core Intel Core i3-1005G1 [MT MCP] speed (MHz): avg: 698
    min/max: 400/3400
Graphics:
  Device-1: Intel Iris Plus Graphics G1 driver: i915 v: kernel
  Device-2: IMC Networks USB2.0 HD UVC WebCam driver: uvcvideo type: USB
  Display: x11 server: X.Org v: 21.1.13 with: Xwayland v: 24.1.1 driver: X:
    loaded: modesetting unloaded: fbdev,vesa dri: iris gpu: i915
    resolution: 1440x810~60Hz
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: intel mesa v: 24.1.5
    renderer: Mesa Intel UHD Graphics (ICL GT1)
Network:
  Device-1: Realtek RTL8821CE 802.11ac PCIe Wireless Network Adapter
    driver: rtw_8821ce
Drives:
  Local Storage: total: 1.86 TiB used: 174 GiB (9.1%)
Info:
  Memory: total: 20 GiB note: est. available: 19.28 GiB used: 1.85 GiB (9.6%)
  Processes: 232 Uptime: 1d 15h 59m Shell: Bash inxi: 3.3.35
`

**Comment by PirulicchioInfuocato** [comment]
Same for me:

> System:
  Host: solus Kernel: 6.9.12-297.current arch: x86_64 bits: 64
  Desktop: Budgie v: 10.9.2 Distro: Solus 4.5 resilience
Machine:
  Type: Laptop System: HP product: HP Pavilion Gaming Laptop 16-a0xxx v: N/A
    serial: <superuser required>
  Mobo: HP model: 87AE v: 32.32 serial: <superuser required> UEFI: AMI
    v: F.23 date: 03/29/2022
Battery:
  ID-1: BAT0 charge: 12.3 Wh (30.1%) condition: 40.8/40.8 Wh (100.0%)
CPU:
  Info: quad core Intel Core i5-10300H [MT MCP] speed (MHz): avg: 887
    min/max: 800/4500
Graphics:
  Device-1: Intel CometLake-H GT2 [UHD Graphics] driver: i915 v: kernel
  Device-2: NVIDIA TU117M [GeForce GTX 1650 Ti Mobile] driver: nvidia
    v: 550.107.02
  Device-3: Luxvisions Innotech HP TrueVision HD Camera driver: uvcvideo
    type: USB
  Display: x11 server: X.Org v: 21.1.13 with: Xwayland v: 24.1.1 driver:
    gpu: i915 resolution: 1920x1080~60Hz
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: nvidia mesa v: 550.107.02
    renderer: NVIDIA GeForce GTX 1650 Ti/PCIe/SSE2
Network:
  Device-1: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet
    driver: r8169
  Device-2: Realtek RTL8822CE 802.11ac PCIe Wireless Network Adapter
    driver: rtw_8822ce
Drives:
  Local Storage: total: 1.14 TiB used: 144.66 GiB (12.4%)
Info:
  Memory: total: 16 GiB available: 15.4 GiB used: 2.67 GiB (17.4%)
  Processes: 359 Uptime: 4m Shell: Bash inxi: 3.3.35

**Comment by ReillyBrogan** [comment]
Does it help to delete the wireplumber state directory? `rm -rf ~/.local/state/wireplumber/`?

**Comment by ReillyBrogan** [comment]
Oh, I just noticed someone saying that downgrading the kernel helps. That was going to be my next suggestion.

Unfortunately we're kind of in a pickle with the kernel for this sync. 6.9 got End-of-lifed unexpectedly early so there's not really any fixed version that can go in. We'll be updating to kernel 6.10.4 on Friday/Saturday after the sync, but that doesn't really help anybody with this issue currently. For now I would recommend just using the previous kernel, we can provide downgrade instructions if anybody needs the exact commands to use to downgrade correctly.

It would also be helpful if someone could join the unstable channel after we upgrade the kernel to check if it's fixed there. Please join our Matrix channels and let us know you're able to help with that if so.

**Comment by PirulicchioInfuocato** [comment]
> Does it help to delete the wireplumber state directory? `rm -rf ~/.local/state/wireplumber/`?

I tried, but unfortunetly it didn't change much! The issue still persist.




> Oh, I just noticed someone saying that downgrading the kernel helps. That was going to be my next suggestion.
> 
> Unfortunately we're kind of in a pickle with the kernel for this sync. 6.9 got End-of-lifed unexpectedly early so there's not really any fixed version that can go in. We'll be updating to kernel 6.10.4 on Friday/Saturday after the sync, but that doesn't really help anybody with this issue currently. For now I would recommend just using the previous kernel, we can provide downgrade instructions if anybody needs the exact commands to use to downgrade correctly.
> 
> It would also be helpful if someone could join the unstable channel after we upgrade the kernel to check if it's fixed there. Please join our Matrix channels and let us know you're able to help with that if so.

Got it. We will see. Yeah, I would prefer to have a guide for downgrading kernel. I tried by myself earlier and managed to do it, but had LightDM giving me issues when I installed the Nvidia Driver. So I'm in a very bad spot and I would really like some help...

About the Unstable Channel, sure, I can do it! I'll update my repos to be in the unstable right now

**Comment by bigrammy** [comment]
> Oh, I just noticed someone saying that downgrading the kernel helps. That was going to be my next suggestion.
> 
> Unfortunately we're kind of in a pickle with the kernel for this sync. 6.9 got End-of-lifed unexpectedly early so there's not really any fixed version that can go in. We'll be updating to kernel 6.10.4 on Friday/Saturday after the sync, but that doesn't really help anybody with this issue currently. For now I would recommend just using the previous kernel, we can provide downgrade instructions if anybody needs the exact commands to use to downgrade correctly.
> 

For me the **sof-firmware** does not seem to load/run when using the newer Kernel so the Ice Lake-LP smart Audio Controller does not seem to exist.  
Everything appears to work perfect with the previous Kernel with zero other modifications.
I posted a quick TUT to simply roll back the Kernel on the Forum for those unsure of the cmd's. (Click on the **> Details** to view the commands)
Everything works fine for me but it may not for others so a more detailed TUT would be good.
https://discuss.getsol.us/d/10488-sound-issue-after-week-13-update/13

**Comment by PirulicchioInfuocato** [comment]
Hi Everyone! Updated to the latest Weekly update right now, but I'm still having the audio issue. I joined the unstable channel too, so that we can debug this issue as suggested by @ReillyBrogan

**Comment by Muonch** [comment]
Here's my specs. 

 lspci | grep -i audio

00:1f.3 Multimedia audio controller: Intel Corporation Alder Lake PCH-P High Definition Audio Controller (rev 01)

inxi -b

System:
  Host: movec-pc Kernel: 6.9.12-297.current arch: x86_64 bits: 64
  Desktop: Xfce v: 4.18.1 Distro: Solus 4.5 resilience
Machine:
  Type: Laptop System: HP product: HP Elite Dragonfly 13.5 inch G3 Notebook PC
    v: SBKPF serial: <superuser required>
  Mobo: HP model: 897F v: KBC Version 08.6B.00 serial: <superuser required>
    UEFI: HP v: U90 Ver. 01.11.04 date: 05/09/2024
Battery:
  ID-1: BAT0 charge: 56.5 Wh (99.1%) condition: 57.0/68.4 Wh (83.3%)
CPU:
  Info: 10-core (2-mt/8-st) 12th Gen Intel Core i5-1235U [MST AMCP]
    speed (MHz): avg: 454 min/max: 400/4400:3300
Graphics:
  Device-1: Intel Alder Lake-UP3 GT2 [Iris Xe Graphics] driver: i915 v: kernel
  Display: x11 server: X.Org v: 21.1.13 with: Xwayland v: 24.1.2 driver:
    gpu: i915 resolution: 1920x1280~60Hz
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: intel mesa v: 24.1.5
    renderer: Mesa Intel Graphics (ADL GT2)
Network:
  Device-1: Intel Alder Lake-P PCH CNVi WiFi driver: iwlwifi
Drives:
  Local Storage: total: 476.94 GiB used: 217.17 GiB (45.5%)
Info:
  Memory: total: 16 GiB note: est. available: 15.2 GiB used: 2.62 GiB (17.3%)
  Processes: 300 Uptime: 13m Shell: Bash inxi: 3.3.35

I also just happened to update my BIOS  the same night I found out this was an issue since I'd been using USB audio after my speakers suddenly started distorting badly around the 5.10 kernel update on every distro. Hoping this bug gets the attention it needs soon so I can hear what the native audio on this machine sounds like again.

**Comment by AhmedBH001** [comment]
lspci | grep -i audio
00:1f.3 Multimedia audio controller: Intel Corporation Tiger Lake-LP Smart Sound Technology Audio Controller (rev 20)

Kernel: Linux 6.9.12-297.current

System:
  Host: Lenovo Kernel: 6.9.12-297.current arch: x86_64 bits: 64
  Desktop: Budgie v: 10.9.2 Distro: Solus 4.5 resilience
Machine:
  Type: Laptop System: LENOVO product: 20VE v: ThinkBook 15 G2 ITL
    serial: <superuser required>
  Mobo: LENOVO model: LNVNB161216 v: No DPK serial: <superuser required>
    UEFI: LENOVO v: F8CN58WW(V2.21) date: 03/28/2024
Battery:
  ID-1: BAT1 charge: 20.1 Wh (55.8%) condition: 36.0/45.0 Wh (80.1%)
    volts: 10.7 min: 11.5
CPU:
  Info: quad core 11th Gen Intel Core i5-1135G7 [MT MCP] speed (MHz):
    avg: 1455 min/max: 400/4200
Graphics:
  Device-1: Intel TigerLake-LP GT2 [Iris Xe Graphics] driver: i915 v: kernel
  Device-2: NVIDIA TU117M [GeForce MX450] driver: nvidia v: 550.107.02
  Device-3: Bison Integrated Camera driver: uvcvideo type: USB
  Display: x11 server: X.Org v: 21.1.13 with: Xwayland v: 24.1.2 driver:
    gpu: i915 resolution: 1920x1080~60Hz
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: nvidia mesa v: 550.107.02
    renderer: NVIDIA GeForce MX450/PCIe/SSE2
Network:
  Device-1: Intel Wi-Fi 6 AX201 driver: iwlwifi
  Device-2: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet
    driver: r8169
Drives:
  Local Storage: total: 1.38 TiB used: 62.81 GiB (4.5%)
Info:
  Memory: total: 24 GiB note: est. available: 23.26 GiB
    used: 2.95 GiB (12.7%)
  Processes: 293 Uptime: 13m Shell: Bash inxi: 3.3.35

**Comment by lf-araujo** [comment]
Sound issues were fixed between the update and the reboot. After rebooting no sound: 

```
System:
  Host: solus Kernel: 6.6.43-251.lts arch: x86_64 bits: 64
  Desktop: GNOME v: 46.3.1 Distro: Solus 4.5 resilience
Machine:
  Type: Laptop System: Dell product: Inspiron 5490 v: N/A
    serial: <superuser required>
  Mobo: Dell model: 0YMVR1 v: A04 serial: <superuser required> UEFI: Dell
    v: 1.11.0 date: 08/13/2020
Battery:
  ID-1: BAT0 charge: 31.8 Wh (80.3%) condition: 39.6/51.0 Wh (77.6%)
    volts: 11.8 min: 11.4
CPU:
  Info: quad core Intel Core i7-10510U [MT MCP] speed (MHz): avg: 550
    min/max: 400/4900
Graphics:
  Device-1: Intel CometLake-U GT2 [UHD Graphics] driver: i915 v: kernel
  Device-2: NVIDIA GP108M [GeForce MX230] driver: nvidia v: 550.107.02
  Device-3: Realtek Integrated_Webcam_HD driver: uvcvideo type: USB
  Display: wayland server: X.Org v: 24.1.2 with: Xwayland v: 24.1.2
    compositor: gnome-shell driver: X: loaded: modesetting unloaded: fbdev,vesa
    dri: iris gpu: i915 resolution: 1600x900~60Hz
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: intel mesa v: 24.1.5
    renderer: Mesa Intel UHD Graphics (CML GT2)
Network:
  Device-1: Intel Comet Lake PCH-LP CNVi WiFi driver: iwlwifi
Drives:
  Local Storage: total: 238.47 GiB used: 153.29 GiB (64.3%)
Info:
  Memory: total: 16 GiB note: est. available: 15.29 GiB used: 4.97 GiB (32.5%)
  Processes: 318 Uptime: 7h 8m Shell: Zsh inxi: 3.3.35
```

**Comment by bigrammy** [comment]
@ReillyBrogan 
Did this change have an affect?
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/diff/?h=linux-6.9.y&id=0cd0a7c2c599e57b5dcb1c3a0717a31615b72de3

Maybe this  .**_device = PCI_DEVICE_ID_INTEL_HDA_ICL_LP_**  is not identifying Intel unlike the actual **_.device = 0x34c8,_** 
Just Thinking out loud :laughing:

**Comment by pjolt** [comment]
Also lost sound after sync to w. 32. Previous sync on this hw was w26 and everything works on that. 
Reinstalling sof-firmware / pipewire does not bring sound back. 

```
pjol@pjol-solus ~ $ inxi -b
System:
  Host: pjol-solus Kernel: 6.9.12-297.current arch: x86_64 bits: 64
  Desktop: KDE Plasma v: 6.1.4 Distro: Solus 4.5 resilience
Machine:
  Type: Laptop System: LENOVO product: 82SV v: Yoga Slim 7 Pro 14IAP7
    serial: <superuser required>
  Mobo: LENOVO model: LNVNB161216 v: NO DPK serial: <superuser required>
    UEFI: LENOVO v: JHCN36WW date: 04/04/2024
Battery:
  ID-1: BAT0 charge: 52.5 Wh (98.3%) condition: 53.4/61.0 Wh (87.5%)
CPU:
  Info: 12-core (4-mt/8-st) 12th Gen Intel Core i7-1260P [MST AMCP]
    speed (MHz): avg: 424 min/max: 400/4700:3400
Graphics:
  Device-1: Intel Alder Lake-P GT2 [Iris Xe Graphics] driver: i915 v: kernel
  Device-2: IMC Networks Integrated RGB Camera driver: uvcvideo type: USB
  Display: wayland server: X.org v: 1.21.1.13 with: Xwayland v: 24.1.2
    compositor: kwin_wayland driver: N/A resolution: 1646x1029
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: intel mesa v: 24.1.5
    renderer: Mesa Intel Graphics (ADL GT2)
Network:
  Device-1: Intel Alder Lake-P PCH CNVi WiFi driver: iwlwifi
Drives:
  Local Storage: total: 1.38 TiB used: 749.65 GiB (53.2%)
Info:
  Memory: total: 16 GiB note: est. available: 15.35 GiB used: 3.25 GiB (21.2%)
  Processes: 359 Uptime: 13m Shell: Bash inxi: 3.3.35
```
And fwiw:
```
pjol@pjol-solus ~ $ lspci | grep -i audio
00:1f.3 Multimedia audio controller: Intel Corporation Alder Lake PCH-P High Definition Audio Controller (rev 01)
```

**Comment by pjolt** [comment]
[This weeks sync](https://discuss.getsol.us/d/10865-sync-updates-for-week-34-2024) restored audio for me. I tested both the current and lts kernel.

**Comment by HarveyDevel** [comment]
Two people have reported this is resolved so I will close this issue. Please report back if the issue persists.
