### ISSUE TITLE
quickemu

### ISSUE THREAD

**Issue by ianmjones** [getsolus/packages#3487]
### Please confirm there isn't an existing package request

- [X] I have searched through package requests

### Homepage

https://github.com/quickemu-project/quickemu/

### Maintainer

- [ ] Would you like to be the maintainer for this package?

### Why should this be included in the repository?

Quickemu enables you to quickly create and run optimised Windows, macOS and Linux virtual machines.

### Are we allowed to redistribute it?

MIT

### What kind of user will use this package, and how many users do you think will use this package?

Anyone wanting to quickly and easily create a fast virtual machine, with the included `quickget` tool making it a breeze to download the latest ISO of many OSes, including Solus.

It's especially good for setting up a Solus VM for package development! :wink:

### Link to source archive file

https://github.com/quickemu-project/quickemu/archive/refs/tags/4.9.6.tar.gz

**Comment by ianmjones** [comment]
I'm rescinding this package request for two reasons:

1. I've struggled to get my eopkg to work for EFI boot, it's fine for legacy boot though. :shrug: 
2. I've been using the `gnome-boxes` package instead while investigating (1), and so far, it's been fine. :shrug:

**Comment by silkeh** [comment]
Reopening this as it is still a good addition to the repository.
