### ISSUE TITLE
iscan is missing the network plugin, breaking Epson scanners detection on a network (T6181)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#35]
<div dir="rtl"><b>Anthony&nbsp;Willemot</b>&nbsp;(<em>&#35;Kaeril</em>),&nbsp;2018-04-07&nbsp;20:16:36&nbsp;UTC</div><br/>

iscan (Image Scan! for Linux) doesn't work when trying to connect to an Epson scanner from the network. This is because the package doesn't include the nonfree //network// plugin, which is required for using a scanner from the network.

If you take a look at the official .rpm x64 package, you'll find a //plugins/iscan-network-nt-1.1.1-1.x86_64.rpm// package inside. Extracting that package and moving the library to /usr/lib64/iscan/network actually solve the issue, but I would expect a regular user not to have to deal with that mess.

As it's a nonfree library (according to the README.rst in the official rpm package), I don't know what is the best solution for this. Could it be included with your iscan package, or should it require a new package, something like a script that downloads the network library and installs it properly as an option?

Apologies for any lack of information or if I broke any rule here. This is my first ever attempt at contributing to a Linux distro. Yup, Solus is actually that great.

---

iscan source: http://support.epson.net/linux/src/scanner/iscan/

.deb and .rpm packages: http://support.epson.net/linux/en/iscan_c.php?version=1.0.4

**Comment by davidjharder** [comment]
Old, closing
