### ISSUE TITLE
libgtksourceview2 does not build

### ISSUE THREAD

**Issue by uni-dos** [getsolus/packages#3538]
Adding the %configure_no_runstatedir fixes the initial step, however, there is a `-Wincompatible-pointer-types` error that occurs. There are also warnings about deprecated functions and macros but those are not preventing it from compiling.

**Comment by EbonJaeger** [comment]
GCC 14 turned that from a warning into an error; `libgtksourceview2` will have to be patched for it. Fedora carries [several patches](https://src.fedoraproject.org/rpms/gtksourceview2/tree/rawhide) for this library, as well as using 2.11 instead of 2.10. That might be a bit of a project, though.

**Comment by EbonJaeger** [comment]
As far as I can tell, nothing in the repository uses this package anymore. Fedora still packages it, but I don't know what uses it; Arch appears to not have it packaged at this point. I wonder if we can deprecate it.

**Comment by uni-dos** [comment]
There must have been a gtk2 app that used it at one point. It must have been rewritten to gtk3 and used a newer gtksourceview version. Do we have to make sure that this is indeed needed in order to avoid breaking something?

**Comment by EbonJaeger** [comment]
I ripgrep'ed over the package repository on my system looking for `libgtksourceview`, and no other package appears to want it this version of it.

**Comment by uni-dos** [comment]
So, it seems safe to deprecate.
