### ISSUE TITLE
ecwolf does not build

### ISSUE THREAD

**Issue by androidnisse** [getsolus/packages#3586]
ecwolf does not build with current recipe. I think this is the fix but I don't know how to apply it.
https://bitbucket.org/ecwolf/ecwolf/pull-requests/21

**Comment by Staudey** [comment]
I'm not really used to bitbucket either, but what I did to get a raw patch is to click on the commit, then open the hamburger menu and selected "View raw commit", which could then be downloaded and applied as per usual.
