### ISSUE TITLE
MATE Wayland Session

### ISSUE THREAD

**Issue by hype3** [getsolus/packages#3594]
### Please confirm there isn't an existing package request

- [X] I have searched through package requests

### Homepage

https://github.com/mate-desktop

### Maintainer

- [ ] Would you like to be the maintainer for this package?

### Why should this be included in the repository?

An experimental wayland session for MATE using Wayfire. First release version

### Are we allowed to redistribute it?

GPL-2.0 license 

### What kind of user will use this package, and how many users do you think will use this package?

Anybody that uses Mate Desktop and want to try it on wayland

### Link to source archive file

https://github.com/mate-desktop/mate-wayland-session/archive/refs/tags/v1.28.3.tar.gz

**Comment by malfisya** [comment]
Mate desktop is still on plan to be deprecated, adding wayland session does not make much sense now.
