### ISSUE TITLE
failed to start light.service, boot not possible, laptop stuck when reboot after update

### ISSUE THREAD

**Issue by hunzel** [getsolus/packages#3637]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

After my holiday I did the latest sync yesterday and rebootet afterwards, now it won't come up and I got the following error message on my old laptop:

[FAILED] Failed to start light.service - Light Display Manager.

What would be the best thing to fix this?

Thanks in advance!

### Steps to reproduce

1. Go on holiday for 4 weeks
2. boot up old Laptop
3. update System via terminal: sudo eopkg up
4. reboot after succesfull update
5. Stuck with error message: [FAILED] Failed to start light.service - Light Display Manager.

### Expected result

Laptop should start normally.

### Actual result

Error Message: [FAILED] Failed to start light.service - Light Display Manager.

### Environment

- [ ] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Budgie

### System details

I cannot access the system right now. It gets stuck at bootup at the above mentioned error message.

**Comment by hunzel** [comment]
In the forum was at least one other user (user123), that had the same issue, he/she responded to my message:
https://discuss.getsol.us/d/10848-sync-updates-for-week-33-2024/28

**Comment by Staudey** [comment]
What GPU do you have? NVIDIA?

Can you reach TTY3 (by pressing CTRL+ALT+F3)? If you can, try `sudo eopkg up` again, and `sudo usysconf run -f`, then reboot. Maybe check `uname -a` too and see if it's the current kernel version (should be 6.9.12-297, unless you switched to the LTS kernel)

**Comment by hunzel** [comment]
Hi @Staudey,

AMD GPU.. A9 7th gen, R2/R3/R4/R5 something.

I just tried and was able to get into TTY3. 
`sudo eopkg up` didn't have any packages to update. `sudo usysconf run -f` however did, after reboot the laptop came up completely normal. `uname -a` told me it was using 6.9.12-297.current.

So case closed, thanks a lot @Staudey !
