### ISSUE TITLE
obs-cmd

### ISSUE THREAD

**Issue by ianmjones** [getsolus/packages#3646]
### Please confirm there isn't an existing package request

- [X] I have searched through package requests

### Homepage

https://github.com/grigio/obs-cmd

### Maintainer

- [X] Would you like to be the maintainer for this package?

### Why should this be included in the repository?

obs-cmd is a minimal CLI to control OBS Studio via obs-websocket.

### Are we allowed to redistribute it?

MIT

### What kind of user will use this package, and how many users do you think will use this package?

Anyone that wants to control OBS Studio via the CLI, but most likely by scripts that use obs-cmd, or Stream Deck actions etc.

### Link to source archive file

https://github.com/grigio/obs-cmd/archive/refs/tags/v0.17.6.tar.gz

**Comment by HarveyDevel** [comment]
Seems good.
