### ISSUE TITLE
Update perl-image-exiftool to 12.93

### ISSUE THREAD

**Issue by luzpaz** [getsolus/packages#3647]
### Please confirm there isn't already an existing package update request

- [X] I have searched through package update requests

### Name

perl-image-exiftool

### Version

12.93

### Link to the release notes or announcement.

https://exiftool.org/history.html

### Reason for updating

Many changes since 12.70

**Comment by androidnisse** [comment]
That is not a stable release. From their GitHub.

Note: The most recent production release is Version 12.76. (Other versions are
considered development releases, and are not uploaded to MetaCPAN.)
