### ISSUE TITLE
Firefox Download broken

### ISSUE THREAD

**Issue by roebotron** [getsolus/packages#367]
### Summary

Since update to firefox 117.0.1 (64bit), there's no way to download and save a file anymore. The "save" dialog doesn't open, the download icon is missing (in the configuration view it's there), no file is written to the download folder. Even the "save link as..." context menu has no effect (-> no dialog).
I tried the built-in "repair", I tried uninstalling all plugins, I tried a complete new installation - no effect.
My download configuration is folder "downloads" (default) and "Always ask you where to save files" - I tried different settings with no effect.

### Steps to reproduce

system update to Solus 4.4 Harmony with budgie 10.8
click right on arbitrary link, e.g. to a PDF, select "save link as..."

### Expected result

A dialog opens to select folder and name

### Actual result

nothing

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Budgie

### System details

Budgie Version 10.8
OS Solus 4.4. Harmony
64-bit
Windows manager X11
kernel Linux 6.4.15-254.current

Hardware:
Fujitsu Siemens Esprimo Mobile U9210, 4GB, Intel Core2 Duo P8400, Mesa Mobile Intel GB45 Express Chipset (CTG)

**Comment by ReillyBrogan** [comment]
Is `xdg-desktop-portal-gtk` installed?

**Comment by roebotron** [comment]
No, was missing. I had no chance to install it separately from the today's updates (on pressing "install" nearly all updates came as "drive by").
Now it working as expected. So, I guess, there is some dependency declaration missing in the dependency chain?
Thanks for your immediate help!

**Comment by ReillyBrogan** [comment]
We added `xdg-desktop-portal-gtk` to the Budgie ISO as a default package, but unfortunately there's no good way to install it retroactively on existing Budgie systems due to the way it works. There are different `xdg-desktop-portal` implentations for different DEs and technically a user is allowed to have multiple installed at one time and to be able to remove them as needed.
