### ISSUE TITLE
figlet

### ISSUE THREAD

**Issue by ianmjones** [getsolus/packages#3672]
### Please confirm there isn't an existing package request

- [X] I have searched through package requests

### Homepage

http://www.figlet.org

### Maintainer

- [X] Would you like to be the maintainer for this package?

### Why should this be included in the repository?

A program that creates large characters out of ordinary screen characters.

### Are we allowed to redistribute it?

BSD-3-Clause

### What kind of user will use this package, and how many users do you think will use this package?

Anyone wanting to create large console text, e.g:

```
 ____        _
/ ___|  ___ | |_   _ ___
\___ \ / _ \| | | | / __|
 ___) | (_) | | |_| \__ \
|____/ \___/|_|\__,_|___/
```

### Link to source archive file

https://github.com/cmatsuoka/figlet/archive/refs/tags/2.2.5.tar.gz

**Comment by davidjharder** [comment]
Looks fun!
