### ISSUE TITLE
watchexec

### ISSUE THREAD

**Issue by ianmjones** [getsolus/packages#3681]
### Please confirm there isn't an existing package request

- [X] I have searched through package requests

### Homepage

https://watchexec.github.io

### Maintainer

- [X] Would you like to be the maintainer for this package?

### Why should this be included in the repository?

Execute commands in response to file modifications.

### Are we allowed to redistribute it?

Apache-2.0

### What kind of user will use this package, and how many users do you think will use this package?

Great for running tests or other tasks automatically each time source files etc are modified.

### Link to source archive file

https://github.com/watchexec/watchexec/archive/refs/tags/v2.1.2.tar.gz

**Comment by HarveyDevel** [comment]
Seems good.
