### ISSUE TITLE
Video stutters randomly until there is mouse movement (T7012)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#37]
<div dir="rtl"><b>crunchslick</b>&nbsp;(<em>&#35;crunchslick</em>),&nbsp;2018-10-02&nbsp;01:10:45&nbsp;UTC</div><br/>

1. When playing local video files, the video will stutter or freeze at random intervals for random periods (0.5s-5s) while the audio continues normally. If there any any mouse movements during the freeze, the video will resume normally. This has been verified to occur for different formats (mp4, mkv, flv), different resolutions (480p, 720p, 1080p) and with different media players (mpv, vlc). This situation did not occur until sometime during 2018 Aug, possibly after update of a certain item.

2. A similar(?) issue also occurs that for Google Chrome 67 under default settings (i.e. hardware acceleration ON) video will stutter very badly when playing (e.g. YouTube). Again, mouse movement during video playback will somehow reduce this problem. Such stuttering did not occur previously under identical settings. Supposedly also occurred sometime during 2018 Aug time frame. Initially dismissed as video source issue, until point 1 above occurred and revisited under suggestion of another redditor. Currently hardware acceleration is OFF to temporarily mitigate the issue. Firefox is not affected under default settings. Tried playing a mp4 video that stutters in mpv and it plays normally under Firefox.

Seems there are other people noticing the same behavior in reddit as well.

System is up to date as of time of reporting this issue.

Hardware specs is as below:
Laptop model no: Lenovo T470
CPU: Intel i5-7200U (Intel HD620, no dGPU)
Ram: 16G
SSD: Samsung S1TB

Thank you

**Comment by davidjharder** [comment]
Old, no new info, closing
