### ISSUE TITLE
README file in /var/log has broken symlink

### ISSUE THREAD

**Issue by TraceyC77** [getsolus/packages#371]
### Summary

There is a symlink `README` in /var/log that points to a non-existent file

### Steps to reproduce

This is the symlink. Run `file` on the linked file.

```
/var/log # ll /var/log/README
lrwxrwxrwx 1 root root 39 Jul 30  2022 /var/log/README -> ../../usr/share/doc/systemd/README.logs

/var/log # file ../../usr/share/doc/systemd/README.logs
../../usr/share/doc/systemd/README.logs: cannot open `../../usr/share/doc/systemd/README.logs' (No such file or directory)
```

### Expected result

The symlink points to a file that exists

### Actual result

The file does not exist

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

Plasma

### System details

Operating System: Solus 4.4
KDE Plasma Version: 5.27.7
KDE Frameworks Version: 5.109.0
Qt Version: 5.15.10
Kernel Version: 6.5.3-256.current (64-bit)
Graphics Platform: X11
Processors: 16 × 11th Gen Intel® Core™ i7-11800H @ 2.30GHz
Memory: 62.5 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2
Manufacturer: Dell Inc.
Product Name: XPS 17 9710

### Other comments

The file doesn't exist anywhere on the system. I did a find from / as root for README.logs and there was no result.

**Comment by ReillyBrogan** [comment]
/usr/lib/tmpfiles.d/legacy.conf
```
L /var/log/README - - - - ../../usr/share/doc/systemd/README.logs
```
