### ISSUE TITLE
Heroic Games Launcher

### ISSUE THREAD

**Issue by androidnisse** [getsolus/packages#3731]
### Please confirm there isn't already an existing package update request

- [X] I have searched through package update requests

### Name

Heroic Games Launcher

### Version

2.15.1

### Link to the release notes or announcement.

https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/tag/v2.15.1

### Reason for updating

New major release, added support for EA games from epic store.

**Comment by malfisya** [comment]
@infinitymdm is already on this. I believe he said the latest update is a bit undercooked, so he waited for the bugfix first.
