### ISSUE TITLE
Mesa

### ISSUE THREAD

**Issue by hype3** [getsolus/packages#3733]
### Please confirm there isn't already an existing package update request

- [X] I have searched through package update requests

### Name

Mesa

### Version

24.2.1

### Link to the release notes or announcement.

https://docs.mesa3d.org/relnotes/24.2.1.html

### Reason for updating

**24.2.0**

**New features**

    VK_KHR_dynamic_rendering_local_read on RADV
    VK_EXT_legacy_vertex_attributes on lavapipe, ANV, Turnip and RADV
    VK_MESA_image_alignment_control on RADV
    VK_EXT_shader_replicated_composites on ANV, dozen, hasvk, lavapipe, nvk, RADV, and Turnip
    VK_KHR_maintenance5 on v3dv
    VK_KHR_maintenance7 on RADV
    VK_EXT_depth_clamp_zero_one on v3dv
    GL_ARB_depth_clamp on v3d
    Defaulting to a new shader cache implementation, reducing filesystem overhead.

**Bug fixes**

    u_debug_stack_test.capture_not_overwritten fails on i386
    turnip: vulkaninfo crashed
    turnip-freereno Build error (/usr/local/include/xf86drm.h:40:10: fatal error: drm.h: No such file or directory)
    tu: compilation failing when compiling turnip with only kgsl and X11 enabled
    samplerCube constructor in fragment shader no longer converting uvec2 bindless texture handles ( segmentation fault , core dumped )
    anv: gen9.5 flakiness in dEQP-VK.multiview.dynamic_rendering.depth.*
    vaapi decoding corruption with green blocks
    interpolateAt precision lowering unhandled by glsl_to_nir()
    [anv] CS2 crashes on LNL
    [anv] Dota2 does not start on LNL
    [radeonsi][bisected][regression] glClientWaitSync() quickly times out with INT64_MAX timeout
    d3d10umd: Build regression in 24.2.0-devel
    zink/tu: glcts flake on a750
    nouveau: advertises GL_EXT_memory_object without implementing `*UID` callbacks
    LIBGL_DRIVERS_PATH gone
    [Regression][Vulkan][TGL][Bisected]vkCmdCopyQueryPoolResults failed to write buffer with compute pipeline on Mesa 24.1
    Worms Revolution: not rendering explosion effects
    crash on pushbuf_validate nvc0_blit do_blit_framebuffer
    piglit: cl-api-build-program crashes
    i915g: glGenerateMipmap() fails with 2048×2048 textures
    [radeonsi] Asterix & Obelix XXLRomastered: river misrendered (completely black)
    Build fails without Vulkan
    No dependency check for PyYAML in meson.build
    GPU Hang in Metal Gear Rising Revengeance
    VK_ERROR_DEVICE_LOST A770 DXVK Fallout 3
    [Bisected] Recent compile issue in libnak
    anv: Wrong push constant values for bytes?
    anv: dEQP-VK.protected_memory tests GPU hang on MTL
    RustiCL (or maybe not…): radeonsi freezes after 2 hours of simulation, zink works just fine
    ci_run_n_monitor.py doesn’t monitor manual jobs
    Crash in util_idalloc_resize due to glBindTexture with a way-too-large ID
    mesa-24.1.2 fails to compile: ast_to_hir.cpp:5371:39: error: ‘%s’ directive argument is null
    [regression][bisected] VMware Xv video displays as black rectangle
    Blender 4.2,4.3 crashes when rendering with motion blur on RDNA3 cards (OpenGL/radeonsi)
    nvk: regression with multiple games crashing
    Transparent background in Blender 3D view with nouveau
    turnip: latest git does not build anymore
    ACO Unimplemented intrinsic instr
    RADV/ACO: assert on per-sample interpolation
    radv: large descriptor layout creation is slow
    Gnome shell (wayland) crashes when opening any window
    DRI Intel drivers fix a problem in Redhat 7 (Mesa 18), but are not included for Redhat 8 (Mesa versions v23, v24)
    Vulkan: ../src/nouveau/vulkan/nvk_physical_device.c:1109: VK_ERROR_INCOMPATIBLE_DRIVER
    RADV: Smooth lines affect triangle rendering
    [armhf build error][regression] error: ‘StringMapIterator’ was not declared in this scope; did you mean ‘llvm::StringMapIterator’?
    Build fails with latest llvm 19: error: no matching function for call to unwrap(LLVMOpaqueModule*&)
    tu: support KHR_8bit_storage
    Incorrect colours on desktop and apps
    nir: Incorrect nir_opt_algebraic semantics for signed integer constants causing end-to-end miscompiles
    src/gallium/frontends/clover/meson.build:93:40: ERROR: Unknown variable “idep_mesaclc”.
    panfrost: mpv is broken on T604
    Nightly CI is broken
    [radv] GPU hang in Starfield on RX 5700 XT
    anv, isl, iris: Clarify and improve CCS + FCV on gfx12
    isl: CPCB horizontal and vertical alignment requirements unknown
    Indika: flickering black artifacting on the snow
    intel/isl: Split Xe2 changes into new files of Xe2.
    rusticl: Generated rusticl_mesa_bindings.c fails to find include
    isl: Remove 512B pitch requirement for non-displayable CCS
    MESA 24.1 - broken zink OpenGL under Windows
    Blue flickering rectangles on AMD RX 7600
    GPU hangs on AMD Radeon RX 6400 on a fragment shader
    v3dv: vkcube-wayland crashes
    intel/brw: scoreboarding regression
    regression in !29436 for radv+angle on stoney
    [radv][regression] Starfield invisible terrain on a 7900 XTX
    free_zombie_shaders() leave context in a bad state (access violation occurs)
    r300: X11 fails to start with the modesetting driver (glamor is broken with R300/R400 gpus).
    [NINE]Far Cry 1 trees flicker regression[bisected][traces]
    Vulkan: Most sync2 implementations are missing new access flags
    Incorrect buffer_list advance when writing disjoint image descriptors
    ANV: Block shadows in Cyberpunk on Intel A770
    ACO ERROR: Temporary never defined or are defined after use
    [ANV] Graphics memory allocation in Total War: Warhammer 3
    DG2: God of War trace fails to play
    Borderlands trace fails to play on dg2
    NVK: Vulkan apps simply terminated with segfault under wayland and Xwayland
    NVK: VK_ERROR_OUT_OF_DEVICE_MEMORY on swapchain creation
    anv/zink regression: piglit.spec.arb_fragment_layer_viewport.layer-no-gs
    [anv] failures when upgrading vulkancts 1.3.6 -> 1.3.7 on intel mesa ci
    RustiCL: deadlock when calling clGetProfilingInfo() on callbacks
    [Intel][Vulkan][Gen12] Vulkan compute shader is 3x slower than the same OpenCL kernel
    turnip: Broken AHB support
    zink: nir validation failures in Sparse code
    nir: nir_opt_varyings uses more stack than musl libc has
    dEQP-VK.pipeline.pipeline_library.shader_module_identifier.pipeline_from_id.graphics regression
    freedreno + perfetto missing dependency on adreno_common.xml.h
    anv: unbounded shader cache
    radv: Crash due to nir validation fail in Enshrouded
    vulkan/wsi/wayland: valgrid reports invalid read in `vk_free` call in `wsi_wl_surface_analytics_fini`
    android: sRGB configs no longer exist after !27709
    bisected: turnip: deqp regressions
    aco: Radeonsi unable to use rusticl
    anv: clean up default_pipeline_cache in anv_device
    [24.1-rc4] fatal error: intel/dev/intel_wa.h: No such file or directory
    Turnip driver is crashing since turnip: ANB/AHB support got merged
    vcn: rewinding attached video in Totem cause [mmhub] page fault
    When using amd gpu deinterlace, tv bt709 properties mapping to 2 chroma
    a530: ir3_context_error assertion (unknown vertex shader output name: VARYING_SLOT_EDGE)
    VCN decoding freezes the whole system
    [RDNA2 [AV1] [VAAPI] hw decoding glitches in Thorium 123.0.6312.133 after https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/28960
    radv regression bisected: Flickering textures (vega)
    [Regression][Bisected] EGL/Wayland: QT applications terminated by SIGSEGV (Address boundary error) when using dGPU
    WSI: Support VK_IMAGE_ASPECT_MEMORY_PLANE_i_BIT_EXT for DRM Modifiers in Vulkan
    nvk: Tracker issue for gamescope support
    nvk: Implement VK_EXT_image_drm_format_modifier
    nvk: NVK_DEBUG=zero_memory is hitting an assert
    nvk: Implement VK_EXT_conservative_rasterization
    zink sparse: Improper semaphore handling
    zink sparse: Reference to mip tails should be refcounted
    radv: Enshrouded GPU hang on RX 6800
    NVK Zink: Wrong color in Unigine Valley benchmark
    intel vulkan incremental build takes forever
    intel vulkan incremental build takes forever
    24.0.6: build fails
    shader with multidimensional array in shader storage buffer takes too long to compile
    panforst: T604 issue with using u32 for flat varyings
    lp_screen.c:601:4: error: ‘snprintf’ will always be truncated; specifiedsize is 16, but format string expands to at least 17
    [anv] FINISHME: support YUV colorspace with DRM format modifiers
    gen9/11 test became flaky: piglit.spec.!opengl 1_4.blendminmax
    mesa 24 intel A770 KOTOR black shadow smoke scenes
    nvk: Implement VK_EXT_pipeline_robustness
    [bisected][regression] kitty fails to start due to `glfwWindowHint(GLFW_SRGB_CAPABLE,true)`
    r600: bisected 5eb0136a3c561 breaks a number of piglits
    [bdw][bisected][regression] assertion failure in nir_validate.c
    Graphical glitches in RPCS3 after updating Vulkan Intel drivers
    [R600] OpenGL and VDPAU regression in Mesa 23.3.0 - some bitmaps get distorted.
    VAAPI radeonsi: VBAQ broken with HEVC
    tu: weird fail in packing tests
    radv/video: 10-bit support
    radv: vkCmdWaitEvents2 is broken
    anv: add support for EDS3::extendedDynamicState3AlphaToCoverageEnable
    ci: switch from CI_JOB_JWT to id_tokens
    Zink: enabled extensions and features may not match
    anv: share embedded samplers

**24.2.1**

   **New features**
   None

   **Bug fixes**

    Artifacts on Black Myth Wukong
    DCS world radeon rx 7900 flicker
    radv/aco: Scheduler bug in ACO somewhere in parallel-gs
    Once human black artifacts consume the screen
    [ANV] Breaking Limit benchmark does not run
    Possible race condition when generating enums.h
    [radeonsi] regression with bindless textures (bisected)
    [anv] possible regression found on 982106e6768e6f69d71710e314325c813591452d
    xe2: Non-compiler assertion failure replaying cp2077 fossil
    Mesa doesn’t build with the following config options
    Intel: Enable Compression on depth buffers (Xe2
    Confidential issue #11711
    Spectacle crashes recording h264 video with 24.2-rc3

**Comment by davidjharder** [comment]
Hi there. Do you have a particular feature from the 24.2 series that you need? We are on the 24.1 series at the moment.

**Comment by hype3** [comment]
I thought that Solus waited for first point release before updating to 24.2 series. 
But Mesa 24.1 with its last point release (24.1.7) is also ok.

**Comment by davidjharder** [comment]
Joey just updated us to 24.1.7, so that will probably hit the stable repository on Friday. I'm going to close this issue if you don't mind.

**Comment by joebonrichie** [comment]
i'll get mesa on the 24.2.x series after this weeks sync

**Comment by HarveyDevel** [comment]
Resolved by https://github.com/getsolus/packages/commit/4a580bf0270d5c647b0aaacdb31f839db0071877
