### ISSUE TITLE
 Yin-Yang - Auto Night-mode

### ISSUE THREAD

**Issue by SlowNicoFish** [getsolus/packages#376]
It would be great to include this package in the repos.
Coming from GNOME this is a thing i missed

**Comment by davidjharder** [comment]
Hi there. 
We have a 'Request new package" form so that a few more details are captured for a request. Would you mind creating a new issue using the form found here https://github.com/getsolus/packages/issues/new/choose

**Comment by davidjharder** [comment]
Closing this. Feel free to open another issue for the same package using the "Request New Package" form
