### ISSUE TITLE
Invalid references in zink aarch64 packages

### ISSUE THREAD

**Issue by kripper** [getsolus/packages#3812]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

~ $ pkg install mesa-zink virglrenderer-mesa-zink vulkan-loader-android                                                             Checking availability of current mirror:                          [*] https://packages-cf.termux.dev/apt/termux-main: ok            Reading package lists... Done                                     Building dependency tree                                          Reading state information... Done                                 vulkan-loader-android is already the newest version (27b).        The following packages were automatically installed and are no longer required:                                                       apr apr-util libopenblas libprotobuf libthread-db libusb          openjpeg-tools                                                  Use 'apt autoremove' to remove them.                              Suggested packages:                                                 mesa-zink-dev                                                   The following packages will be REMOVED:                             mesa virglrenderer                                              The following NEW packages will be installed:                       mesa-zink virglrenderer-mesa-zink xorg-xrandr                   0 upgraded, 3 newly installed, 2 to remove and 141 not upgraded.  Need to get 8046 kB/8079 kB of archives.                          After this operation, 16.8 MB of additional disk space will be used.                                                                Do you want to continue? [Y/n] y                                  Err:1 https://tur.kcubeterm.com tur-packages/tur aarch64 mesa-zink aarch64 22.0.5-5                                                   401                                                             Err:2 https://tur.kcubeterm.com tur-packages/tur aarch64 virglrenderer-mesa-zink aarch64 20220627                                     401                                                             E: Failed to fetch https://objects.githubusercontent.com/github-production-release-asset-2e65be/509717777/fbe2a827-a41b-48d9-bafa-ce6f352a679c?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction/20240913/us-east-1/s3/aws4_request&X-Amz-Date=20240913T024131Z&X-Amz-Expires=300&X-Amz-Signature=9b2cb3ef6a00b294051614cc8cf118d12e8d20195b6acd70596afb59a4cb383c&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=509717777&response-content-disposition=attachment; filename=mesa-zink_22.0.5-5_aarch64.deb&response-content-type=application/octet-stream  401                     E: Failed to fetch https://objects.githubusercontent.com/github-production-release-asset-2e65be/509717777/41365b00-c4e4-4bcf-af5f-772821c08142?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction/20240913/us-east-1/s3/aws4_request&X-Amz-Date=20240913T024132Z&X-Amz-Expires=300&X-Amz-Signature=ce7c4f4487d91b0fbfe0c75219b89f4fbf91d53d4902d9f4e5b3e6f3bcaa7cba&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=509717777&response-content-disposition=attachment; filename=virglrenderer-mesa-zink_20220627_aarch64.deb&response-content-type=application/octet-stream  401
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

### Steps to reproduce

pkg install mesa-zink virglrenderer-mesa-zink vulkan-loader-android

### Expected result

Should install

### Actual result

Throws error

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Budgie

### System details

~ $ uname -a
Linux localhost 4.14.186-perf-gf8d872e9279c #1 SMP PREEMPT Tue Sep 19 12:46:50 UTC 2023 aarch64 Android

**Comment by malfisya** [comment]
I think you file this report on the wrong repo. This is Solus (Linux Distribution) package repository.
