### ISSUE TITLE
[Budgie] Need to login twice with laptop connected to docking station.

### ISSUE THREAD

**Issue by androidnisse** [getsolus/packages#3815]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

When I plug in my laptop into my docking station and try to login, I cant enter my password in the prompt. Nothing happens when I type or click in the box. I have to click on Switch User enter my password get back to the first screen enter my password again and then I can login. When I have logged in I can see what I typed. Like for example I have Nheko open. Then I see my password in there or other stuff I typed. I have had Firefox open and then I see my typing in there.

### Steps to reproduce

1. Plug laptop into docking station
2. Try to login.

### Expected result

I get logged in.

### Actual result

Nothing gets typed in the password box.

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Budgie

### System details

System:
  Host: vesslan Kernel: 6.10.8-301.current arch: x86_64 bits: 64
  Desktop: Budgie v: 10.9.2 Distro: Solus 4.5 resilience
Machine:
  Type: Laptop System: Dell product: Latitude 5420 v: N/A
    serial: <superuser required>
  Mobo: Dell model: 047J2X v: A01 serial: <superuser required> UEFI: Dell
    v: 1.37.0 date: 04/22/2024
Battery:
  ID-1: BAT0 charge: 30.7 Wh (85.8%) condition: 35.8/63.0 Wh (56.9%)
CPU:
  Info: quad core 11th Gen Intel Core i5-1135G7 [MT MCP] speed (MHz):
    avg: 3100 min/max: 400/4200
Graphics:
  Device-1: Intel TigerLake-LP GT2 [Iris Xe Graphics] driver: i915 v: kernel
  Device-2: Generalplus Sandberg 133-97 driver: snd-usb-audio,uvcvideo
    type: USB
  Device-3: Sunplus Innovation Integrated_Webcam_HD driver: uvcvideo
    type: USB
  Display: x11 server: X.Org v: 21.1.13 with: Xwayland v: 24.1.2 driver:
    gpu: i915 resolution: 1: 3440x1440~60Hz 2: N/A
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: intel mesa v: 24.2.2
    renderer: Mesa Intel Xe Graphics (TGL GT2)
Network:
  Device-1: Intel Wi-Fi 6 AX201 driver: iwlwifi
  Device-2: Intel Ethernet I219-V driver: e1000e
  Device-3: Realtek RTL8153 Gigabit Ethernet Adapter driver: r8152 type: USB
Drives:
  Local Storage: total: 238.47 GiB used: 156.74 GiB (65.7%)
Info:
  Memory: total: 16 GiB note: est. available: 15.19 GiB
    used: 10.14 GiB (66.8%)
  Processes: 352 Uptime: 2d 21h 32m Shell: Zsh inxi: 3.3.36

**Comment by infinitymdm** [comment]
I have the same issue, though not just when connecting via a dock. It occasionally happens on my desktop, usually when I've walked away and let it sleep. See brief discussion of this on the forum [here](https://discuss.getsol.us/d/10769-major-difficulties-recovering-system-after-week-27-and-28-updates/27)

I'm fairly certain this is a Budgie-specific issue.

**Comment by TraceyC77** [comment]
This is not a problem on Plasma, so I agree it's likely a Budgie issue. Have you tried reaching out to the Budgie folks on Matrix or via their bug tracker? This is likely not in the way we package Budgie.
@EbonJaeger , thoughts?

**Comment by androidnisse** [comment]
> This is not a problem on Plasma, so I agree it's likely a Budgie issue. Have you tried reaching out to the Budgie folks on Matrix or via their bug tracker? This is likely not in the way we package Budgie. @EbonJaeger , thoughts?

Yes, no problems.

**Comment by TraceyC77** [comment]
Thanks for reaching out to Budgie.

Here's the advice Josh has, it may be something we can do differently on our end. (we do have lightdm-gtk-greeter)

> does Solus have lightdm-gtk-greeter? Might be worth seeing if a swap from slick-greeter to lightdm-gtk-greeter would fix it.

**Comment by infinitymdm** [comment]
I can confirm that I'm running slick-greeter, not lightdm-gtk-greeter. That said, I don't think this one is to do with the greeter (what you see on first login after a reboot or logout). My issue (and OP's issue as well, if I understand correctly) is this one on budgie-screensaver: https://github.com/BuddiesOfBudgie/budgie-screensaver/issues/25

@androidnisse can you confirm whether the behavior described in that issue is what you're seeing, or is your issue slightly different?

**Comment by androidnisse** [comment]
> I can confirm that I'm running slick-greeter, not lightdm-gtk-greeter. That said, I don't think this one is to do with the greeter (what you see on first login after a reboot or logout). My issue (and OP's issue as well, if I understand correctly) is this one on budgie-screensaver: [BuddiesOfBudgie/budgie-screensaver#25](https://github.com/BuddiesOfBudgie/budgie-screensaver/issues/25)
> 
> @androidnisse can you confirm whether the behavior described in that issue is what you're seeing, or is your issue slightly different?

That is the exact issue. So for me it happens when I put in my laptop that is suspended in the dock. I use external mouse/keyboard to wake it and then have to login twice.

**Comment by androidnisse** [comment]
Well this is budgie-screensaver. However this will not be fixed as that will be dropped when Budgie goes over to Wayland.  So until then we will have to login twice.

![image](https://github.com/user-attachments/assets/55e3677f-8ff1-4f7e-a31f-86281153c3f2)

**Comment by malfisya** [comment]
@androidnisse Come to the dark side...
