### ISSUE TITLE
light

### ISSUE THREAD

**Issue by androidnisse** [getsolus/packages#3845]
### Please confirm there isn't already an existing package deprecation request

- [X] I have searched through package deprecation requests

### Name

light

### Reason for deprecation

This project has been removed from GitHub so there is no source to build this.

**Comment by davidjharder** [comment]
AUR is using this upstream, which is an archived mirror
https://gitlab.com/dpeukert/light
Also found this (dead 2ys) 
https://github.com/godalming123/light
 And this (deader 4ys )
https://github.com/klaxalk/light

Leaning towards deprecation myself

**Comment by Staudey** [comment]
i3 seems to depend on it
