### ISSUE TITLE
pandoc-include-code does not build

### ISSUE THREAD

**Issue by androidnisse** [getsolus/packages#3854]
Dependency haskell-pandoc-types-devel has been removed from the repo.

**Comment by malfisya** [comment]
This package is not use by any other packages. Either we bring back `haskell-pandoc-types` to make this build or we deprecate this too.

**Comment by androidnisse** [comment]
> This package is not use by any other packages. Either we bring back `haskell-pandoc-types` to make this build or we deprecate this too.

I would say drop it as well then.

**Comment by malfisya** [comment]
It looks useful by itself tho, that's why I am not sure deprecating it. This is not some library that cannot be used by itself. Wondering if someone uses it.
