### ISSUE TITLE
Testing: BORE CPU scheduler

### ISSUE THREAD

**Issue by ReillyBrogan** [getsolus/packages#386]
The BORE CPU scheduler is implemented as a series of patches to the default CFS scheduler that use hueristics to identify threads/processes that are likely interactive so it can prioritize them over those that are likely not. 

This results in improved system latency under load which is generally a good thing for a desktop-oriented distribution like Solus. The con is that there is likely a slight reduction in throughput, though most users would prefer having an interactive system (IE they can still use it during things that take a lot of CPU) over one that finishes builds a few seconds faster but that the system is generally unusable.

The patches for this have been added to the kernel in 9207db45becc4d9f57a7b879a2fd8eea4416a9e2 which means this is currently available for testing by unstable users. I have patched the kernel to keep it opt-in for now but if testing is positive then it will be enabled by default sometime later in the lifecycle of the 6.5 kernel.

To enable this you need to set the following sysctl: `kernel.sched_bore=1`. You can do this with the following command:
```
sudo sysctl -w kernel.sched_bore=1
```
This takes effect immediately and persists until the system is rebooted.

To enable this on new boots automatically you should make use of the sysctl.d functionality.
```
echo "kernel.sched_bore=1" | sudo tee /etc/sysctl.d/80-bore.conf
```
This does not take effect immediately and requires a reboot to activate.

Please post any feedback about this change below. I am especially interested in whether the perceived responsiveness of the system is improved, especially under load. I am also interested in changes to game FPS since that's another area that is purported to benefit from this scheduler.

**Comment by FAb7D** [comment]
No problems at the moment

**Comment by PoorPocketsMcNewHold** [comment]
No issues noticed to be caused by BORE right now. I have not observed any significant enhancements or declines.

**Comment by u2615** [comment]
I have an aging laptop and a custom script that rebuilds certain Cargo binaries as necessary. I can usually discern when it's in operation while browsing due to latency issues. Enabling this scheduler has significantly enhanced my overall user experience.

**Comment by ReillyBrogan** [comment]
BORE is now enabled by default in the linux-current kernel. You may delete the sysctl.d file now if you wish, it is no longer necessary.
