### ISSUE TITLE
change source for picocom

### ISSUE THREAD

**Issue by androidnisse** [getsolus/packages#3875]
### Please confirm there isn't already an existing package update request

- [X] I have searched through package update requests

### Name

picocom

### Version

2024-07

### Link to the release notes or announcement.

https://gitlab.com/wsakernel/picocom/-/releases/2024-07

### Reason for updating

This is a new maintained fork of picocom.

**Comment by silkeh** [comment]
Agreed that the source should be changed (or it should be deprecated). Two questions:

1. Are there modern/well-maintained alternatives?
2. What other distros switched to the suggested fork?

**Comment by joebonrichie** [comment]
1. fedora has switched to this new fork but not yet arch or debian

2 last time i did UART stuff picocom was the best, screen had too many bells and whistles which actively got in the way.

That being said, it's quite a simple piece of software and doesn't require intensive maintenance so i'm not surprised no one really noticed it.

**Comment by silkeh** [comment]
> fedora has switched to this new fork but not yet arch or debian

Good enough for me!

> last time i did UART stuff picocom was the best, screen had too many bells and whistles which actively got in the way.

Yeah, screen is horrible for this imo. The only alternative I know is minicom, but that's not really maintained (Debian ships their own fork).
