### ISSUE TITLE
piksemel

### ISSUE THREAD

**Issue by androidnisse** [getsolus/packages#3877]
### Please confirm there isn't already an existing package deprecation request

- [X] I have searched through package deprecation requests

### Name

piksemel

### Reason for deprecation

Does not build, source is gone. As far as I can see nothing depends on this.

**Comment by davidjharder** [comment]
This is part of Python2 deprecation. We track that here https://github.com/getsolus/packages/issues/270
This package is hanging around because it is tied up in `eopkg` (long story)
