### ISSUE TITLE
menus from applets in top-panel show up blank

### ISSUE THREAD

**Issue by mark-nicholson** [getsolus/packages#389]
In the last two releases, I started running into situations where when I right-click on the "network" applet (to manage a WiFi connection or start the VPN) the menu gets drawn, but is _blank_...  it has the "entries" in the list but no text.

In the newest update (as of September 22nd) other top-panel applets are now also getting _some_ missing entries too.  The menus also seem to be "laggy" ... it eventually draws them, but it takes about 0.5 sec for it to appear after the click.  This now includes the "app menu" applet.  The issue seems to be getting worse.

I do run an external display as my primary with the laptop built-in display as secondary although that does not seem to make any difference to the issue.

I snooped the Issues list but did not see anything like this posted, so it is possible this is a local issue to my machine.

`Linux milliways 6.5.3-256.current #1 SMP PREEMPT_DYNAMIC 0 x86_64 GNU/Linux`
`00:02.0 VGA compatible controller: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] (rev 01)`

Attached a screen shot of the weird network menu.

![empty-network-menu-trim](https://github.com/getsolus/packages/assets/5815500/75420792-3595-4225-9124-603686ecf960)

**Comment by EbonJaeger** [comment]
Will be fixed with the next Budgie release, which should be very soon.

See here for more info: https://github.com/BuddiesOfBudgie/budgie-desktop/issues/451
