### ISSUE TITLE
plasma-welcome

### ISSUE THREAD

**Issue by Justinzobel** [getsolus/packages#3891]
### Please confirm there isn't an existing package request

- [X] I have searched through package requests

### Homepage

https://invent.kde.org/plasma/plasma-welcome

### Maintainer

- [X] Would you like to be the maintainer for this package?

### Why should this be included in the repository?

A great tool for the Plasma desktop to welcome users and show features, how to install apps, ask if they want to turn on telemetry, how to contribute/donate, etc. It is also customizable and you can easily add distro specific pages.

### Are we allowed to redistribute it?

GPL-3.0-or-later

### What kind of user will use this package, and how many users do you think will use this package?

It will be used by all users on the Plasma ISO.

License is GPL3 I think but awaiting confirmation.

### Link to source archive file

https://download.kde.org/stable/plasma/6.1.5/plasma-welcome-6.1.5.tar.xz

**Comment by Justinzobel** [comment]
@ReillyBrogan/@TraceyC77 for KDE/Quality respectively.

**Comment by TraceyC77** [comment]
I think this is a good idea
