### ISSUE TITLE
Virtual Machine Manager - unable to run existing VM or create a new VM due to missing dependency error

### ISSUE THREAD

**Issue by TraceyC77** [getsolus/packages#3893]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

I had attempted to set up a new VM in Virtual Machine Manager using an ISO. After choosing a name and clicking Finish, I saw a message that virtual networking was not active. 
"Virtual Network 'default' is not active. Would you like to start the network now?"
This produced errors and I was unable to create the VM. The errors indicate a missing package.

I'm also unable to run any of my pre-existing VMs.

This may be related to [a recent update to nftables](https://github.com/getsolus/packages/pull/2331)
@ReillyBrogan 

### Steps to reproduce

1. Open Virtual Machine Manager
2. Attempt to create a new VM using an ISO
3. Go through the wizard and click Finish

### Expected result

VM is created and the user can start installation

### Actual result

After clicking Yes, I saw an error
"Unable to complete install: 'Requested operation is not valid: network 'default' is not active'

<details>
<summary>Error details</summary>

```
Unable to complete install: 'Requested operation is not valid: network 'default' is not active'

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 72, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/createvm.py", line 2008, in _do_async_install
    installer.start_install(guest, meter=meter)
  File "/usr/share/virt-manager/virtinst/install/installer.py", line 695, in start_install
    domain = self._create_guest(
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/share/virt-manager/virtinst/install/installer.py", line 637, in _create_guest
    domain = self.conn.createXML(initial_xml or final_xml, 0)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libvirt.py", line 4545, in createXML
    raise libvirtError('virDomainCreateXML() failed')
libvirt.libvirtError: Requested operation is not valid: network 'default' is not active
```

</details>

There is a second error after that
"Could not start virtual network 'default': Unable to create bridge virbr0: Package note installed"

<details>
<summary>Details of second error</summary>

```
Could not start virtual network 'default': Unable to create bridge virbr0: Package not installed

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/device/netlist.py", line 208, in _check_network_is_running
    netobj.start()
  File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 57, in newfn
    ret = fn(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/virt-manager/virtManager/object/network.py", line 69, in start
    self._backend.create()
  File "/usr/lib/python3.11/site-packages/libvirt.py", line 3569, in create
    raise libvirtError('virNetworkCreate() failed')
libvirt.libvirtError: Unable to create bridge virbr0: Package not installed
```

</details>

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

Plasma

### System details

Operating System: Solus 4.5
KDE Plasma Version: 6.1.5
KDE Frameworks Version: 6.6.0
Qt Version: 6.7.2
Kernel Version: 6.10.6-300.current (64-bit)
Graphics Platform: Wayland
Processors: 16 × 11th Gen Intel® Core™ i7-11800H @ 2.30GHz
Memory: 62.5 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics
Manufacturer: Dell Inc.
Product Name: XPS 17 9710

dnsmasq is installed and up to date

```
❯ eopkg.bin info dnsmasq
Installed package:
Name                : dnsmasq, version: 2.90, release: 17
Summary             : DNS cache and forwarder
Description         : dnsmasq in Solus is used to forward and cache DNS queries.
Licenses            : GPL-2.0-or-later
Component           : network.base
Dependencies        : dbus gmp libhogweed glibc libnettle 
Distribution        : Solus, Dist. Release: 1
Architecture        : x86_64, Installed Size: 1.13 MB
Reverse Dependencies: libvirt 

❯ eopkg.bin info nftables
Installed package:
Name                : nftables, version: 1.1.0, release: 9
Summary             : nftables replaces the popular iptables/ebtables
Description         : This software provides a new in-kernel packet classification framework that is based on a network-specific Virtual Machine (VM) and a new nft userspace command
                      line tool
Licenses            : GPL-2.0-only
Component           : security
Dependencies        : gmp libnftnl libmnl readline glibc jansson 
Distribution        : Solus, Dist. Release: 1
Architecture        : x86_64, Installed Size: 1.13 MB
Reverse Dependencies: iptables 

❯ eopkg.bin info iptables
Installed package:
Name                : iptables, version: 1.8.10, release: 17
Summary             : Netfilter firewall
Description         : Netfilter firewall
Licenses            : LGPL-3.0-or-later
Component           : network.base
Dependencies        : glibc libmnl libnfnetlink libnftnl nftables 
Distribution        : Solus, Dist. Release: 1
Architecture        : x86_64, Installed Size: 1.71 MB
Reverse Dependencies: libvirt network-manager iproute2 


```

### Other comments

By default, the network selection is "Virtual network 'default' : NAT (inactive)" on the last screen of the wizard
I have been able to create VMs in the past. Nothing has changed except for the system having been updated since the last VM I created

**Comment by ermo** [comment]
> By default, the network selection is "Virtual network 'default' : NATE (inactive)" on the last screen of the wizard

Did you mean 'NAT' (as opposed to 'NATE')?

**Comment by TraceyC77** [comment]
closing this out, the problem is resolved
I believe it was caused by having installed a new kernel and not being booted into it :( Sorry for the spam
