### ISSUE TITLE
Light doesn't seem to work (T6733)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#39]
<div dir="rtl"><b>Payas&nbsp;Relekar</b>&nbsp;(<em>&#35;whatever</em>),&nbsp;2018-08-03&nbsp;18:12:33&nbsp;UTC</div><br/>

Light, an xbacklight replacement for i3 as the description says, isn't working. Manpage shows all the info, but no command is working.

I have an Acer 5755 with i7-2670QM. X11 works just fine even with keyboard shortcuts and manual xbacklight command, but not on wayland. This is one of the larger problems I'm facing on wayland, and I'm not sure how to combine these into a single issue. Help regarding that, too is appreciated.

**Comment by davidjharder** [comment]
Old, no new info, closing
