### ISSUE TITLE
error name "cli error spawn einval" while bubblewarp build command 

### ISSUE THREAD

**Issue by Jaiveerhanuman** [getsolus/packages#3900]
Dear Admin

Everything works well except this last error, i am not the programmer. this is error which is showing in command prompt and not able to make apk files for my app. "cli error spawn einval" this is error kindly guide how to rectify it, i have run/change the latest node,js files also.
![image](https://github.com/user-attachments/assets/5eff1da8-492c-4b2b-813e-86cda46687a6)
![bubblewrap-build-command-error](https://github.com/user-attachments/assets/8e6af2ff-360f-4836-85f2-c0c282fd9089)

**Comment by malfisya** [comment]
I think you are on the wrong repository. This is package repository for Solus, a linux distribution. Please file your issue on the correct repository. Cheers!
