### ISSUE TITLE
fq

### ISSUE THREAD

**Issue by silkeh** [getsolus/packages#3919]
### Please confirm there isn't an existing package request

- [X] I have searched through package requests

### Homepage

https://github.com/wader/fq

### Maintainer

- [X] Would you like to be the maintainer for this package?

### Why should this be included in the repository?

`fq` is a tool for inspecting binary formats. Solus doesn't ship such a utility yet (outside of Hex editors and network packet inspectors).

### Are we allowed to redistribute it?

MIT

### What kind of user will use this package, and how many users do you think will use this package?

Users that work with binary files/formats and want to inspect the nitty-gritty details.

### Link to source archive file

https://github.com/wader/fq/archive/refs/tags/v0.13.0.tar.gz

**Comment by EbonJaeger** [comment]
Do the thing!
