### ISSUE TITLE
Some related components may missing when install and compile the "pdfinfo" of "pdf-tools" for Emacs on Solus

### ISSUE THREAD

**Issue by vqefvil** [getsolus/packages#3958]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

When installing and compiling the pdf-tools package for Emacs, it prompts whether to rebuild. After answering 'yes',an warning occurs:
(Emacs minibuffer):
 Need to (re)build the epdfinfo program, do it now ? (y or n) 
y
warning:
error: pdf-info-epdfinfo-program is not executable.

(Emcas minibuffer)
So I located .emacs.d/elpa/pdf-tools-1.1.0/build/, and there are no "pdf-tools-autoloads" and "pdf-tools-pkg" .elc file in .emacs.d/elpa/pdf-tools-1.1.0/ .
![Screenshot from 2024-09-30 16-34-03](https://github.com/user-attachments/assets/07168266-a3ea-4851-ad0e-996846285a71)

following the README from https://github.com/vedang/pdf-tools , I ran make -s, which resulted in an error. 
(shell)

qef@qef-solus ~/.emacs.d/elpa/pdf-tools-1.1.0/build $ make -s
Using Emacs 29.4
sed: can't read lisp/pdf-tools.el: No such file or directory
sed: can't read lisp/pdf-tools.el: No such file or directory
sed: can't read lisp/pdf-tools.el: No such file or directory
make: cask: No such file or directory
make: *** [Makefile:49: .cask/29.4] Error 127

(shell)
Afterward, I navigated into the /server directory,try to edited autobuild according to the README file, I add these:
(autobuild)

 # Solus 
os_solus() {
    if [ -f "/etc/os-release" ]; then
        . /etc/os-release
        if [ "$ID" != "solus" ]; then
          return 1
        fi
    else
      return 1
    fi
    PACKAGES="make
              automake
              autoconf
              gcc
              libpng-devel
              zlib-devel
              poppler
              poppler-devel
              libpoppler-glib-devel
              glib2-devel
              pkgconf"
    PKGCMD=eopkg
    PKGARGS="install"
    return 0
}

 solus)   os_solus   "$@";;
 
 os_solus   "$@" || \

 (autobuild)
   but I don't know which package is missing, I guess it's package  libpoppler-glib-devel or m4, right?   It would be better if there is a package like archlinux, debian base-devel that integrates the required library files in one package.
 it is the autobuild file after I edited. And then executed ./autobuild,failed:
(shell)

qef@qef-solus ~/.emacs.d/elpa/pdf-tools-1.1.0/build/server $ ls
autobuild     poppler-versions           synctex_parser_utils.c
autogen.sh    synctex_parser_advanced.h  synctex_parser_utils.h
configure.ac  synctex_parser.c           synctex_parser_version.txt
epdfinfo.c    synctex_parser.h           synctex_version.h

qef@qef-solus ~/.emacs.d/elpa/pdf-tools-1.1.0/build $ ./server/autobuild
bash: ./server/autobuild: Permission denied

qef@qef-solus ~/.emacs.d/elpa/pdf-tools-1.1.0/build $ sudo ./server/autobuild
[sudo] password for qef:
sudo: ./server/autobuild: command not found

(shell)
then I try to run ./autogen.sh,failed:
(shell)

qef@qef-solus ~/.emacs.d/elpa/pdf-tools-1.1.0/build/server $ ./autogen.sh 
Running autoreconf...
autom4te: error: need GNU m4 1.4 or later: /usr/bin/m4
aclocal: error: /usr/bin/autom4te failed with exit status: 1
autoreconf: error: aclocal failed with exit status: 1

(shell)
  The same .emacs file works fine on Debian, Ubuntu, ArchLinux, and OpenSUSE systems, but this problem occurs on Solus. To be honest, Solus has great hardware support. I like Solus very much and have already used it as my main operating system. I hope this problem can be solved as soon as possible because it affects the use process of Emacs. Thank you so much,hope everything goes well. 

=====================
I've uploaded some file you might need, due to format restrictions, I've changed it to .txt extension. They are :
/home/qef/.emacs.d/elpa/pdf-tools-1.1.0/build/makefile
/home/qef/.emacs.d/elpa/pdf-tools-1.1.0/build/server/autobuild and I edited one.
/home/qef/.emacs
/home/qef/.emacs.d/elpa/pdf-tools-1.1.0/pdf-tools-autoloads.el , pdf-tools-pkg.el
[.emacs.txt](https://github.com/user-attachments/files/17189310/default.emacs.txt)
[autobuild.txt](https://github.com/user-attachments/files/17189311/autobuild.txt)
[autobuild (I edited).txt](https://github.com/user-attachments/files/17189312/autobuild.I.edited.txt)
[Makefile.txt](https://github.com/user-attachments/files/17189313/Makefile.txt)
[pdf-tools-autoloads.el.txt](https://github.com/user-attachments/files/17189314/pdf-tools-autoloads.el.txt)
[pdf-tools-pkg.el.txt](https://github.com/user-attachments/files/17189315/pdf-tools-pkg.el.txt)

=====================

### Steps to reproduce

above

### Expected result

compiled success : )

### Actual result

failed : (

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Gnome

### System details

qef@qef-solus ~ $ inxi -b
System:
  Host: qef-solus Kernel: 6.10.11-303.current arch: x86_64 bits: 64
  Desktop: GNOME v: 46.5 Distro: Solus 4.5 resilience
Machine:
  Type: Laptop System: HP product: HP ZHAN A G6 v: Type1ProductConfigId
    serial: <superuser required>
  Mobo: HP model: 8C21 v: 87.34 serial: <superuser required> UEFI: Insyde
    v: F.06 date: 04/09/2024
Battery:
  ID-1: BAT0 charge: 63.3 Wh (100.0%) condition: 63.3/68.0 Wh (93.1%)
CPU:
  Info: 8-core AMD Ryzen 7 7840H w/ Radeon 780M Graphics [MT MCP] speed (MHz):
    avg: 400 min/max: 400/5137
Graphics:
  Device-1: Advanced Micro Devices [AMD/ATI] Phoenix1 driver: amdgpu v: kernel
  Device-2: Cheng Uei Precision Industry (Foxlink) HP Wide Vision 5MP Camera
    driver: uvcvideo type: USB
  Display: wayland server: X.Org v: 24.1.2 with: Xwayland v: 24.1.2
    compositor: gnome-shell driver: gpu: amdgpu resolution: 2560x1600~120Hz
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 24.2.3 renderer: AMD
    Radeon 780M (radeonsi gfx1103_r1 LLVM 18.1.8 DRM 3.57
    6.10.11-303.current)
Network:
  Device-1: MEDIATEK MT7922 802.11ax PCI Express Wireless Network Adapter
    driver: mt7921e
Drives:
  Local Storage: total: 953.87 GiB used: 13.2 GiB (1.4%)
Info:
  Memory: total: 16 GiB note: est. available: 14.93 GiB used: 2.23 GiB (14.9%)
  Processes: 376 Uptime: 2m Shell: Bash inxi: 3.3.36
qef@qef-solus ~ $

**Comment by Staudey** [comment]
> autom4te: error: need GNU m4 1.4 or later: /usr/bin/m4

Do you have the `system.devel` component installed? (https://help.getsol.us/docs/user/software/development/#getting-started)

**Comment by vqefvil** [comment]
> > autom4te: error: need GNU m4 1.4 or later: /usr/bin/m4
> 
> Do you have the `system.devel` component installed? (https://help.getsol.us/docs/user/software/development/#getting-started)

God!! Thank you! After I eopkg install -c system.devel, with libpng-devel and poppler-devel, it worked!! Thank you   
(shell)
qef@qef-solus ~/.emacs.d/elpa/pdf-tools-1.1.0/build/server $ ./autobuild
Failed to recognize this system, trying to continue.
---------------------------
 Configuring and compiling 
---------------------------
./configure -q  && make clean && make -s
configure: error: Package requirements (libpng) were not met:

Package 'libpng' not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables png_CFLAGS
and png_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
===========================
     Build failed.  ;o(    
===========================
Note: maybe try the '-d' option.
qef@qef-solus ~/.emacs.d/elpa/pdf-tools-1.1.0/build/server $ ^C
qef@qef-solus ~/.emacs.d/elpa/pdf-tools-1.1.0/build/server $ ./autobuild
Failed to recognize this system, trying to continue.
---------------------------
 Configuring and compiling 
---------------------------
./configure -q  && make clean && make -s
configure: error: Package requirements (poppler) were not met:

Package 'poppler' not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables poppler_CFLAGS
and poppler_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
===========================
     Build failed.  ;o(    
===========================
Note: maybe try the '-d' option.
qef@qef-solus ~/.emacs.d/elpa/pdf-tools-1.1.0/build/server $ ^C
qef@qef-solus ~/.emacs.d/elpa/pdf-tools-1.1.0/build/server $ ./autobuild
Failed to recognize this system, trying to continue.
---------------------------
 Configuring and compiling 
---------------------------
./configure -q  && make clean && make -s

Is case-sensitive searching enabled ?     yes
Is modifying text annotations enabled ?   yes
Is modifying markup annotations enabled ? yes

test -z "epdfinfo" || rm -f epdfinfo
test -z "libsynctex.a" || rm -f libsynctex.a
rm -f *.o
epdfinfo.c: In function ‘annotation_markup_append_text_region’:
epdfinfo.c:1576:5: warning: ‘poppler_page_get_selection_region’ is deprecated: Use poppler_page_get_selected_region instead [-Wdeprecated-declarations]
 1576 |     poppler_page_get_selection_region (page, 1.0, selection_style, region);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/poppler/glib/poppler.h:251,
                 from epdfinfo.c:28:
/usr/include/poppler/glib/poppler-page.h:75:8: note: declared here
   75 | GList *poppler_page_get_selection_region(PopplerPage *page, gdouble scale, PopplerSelectionStyle style, PopplerRectangle *selection) G_GNUC_DEPRECATED_FOR(poppler_page_get_selected_region);
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ar: `u' modifier ignored since `D' is the default (see `U')
/usr/bin/ld: epdfinfo-epdfinfo.o: in function `mktempfile':
/home/qef/.emacs.d/elpa/pdf-tools-1.1.0/build/server/epdfinfo.c:354:(.text+0x1e6): warning: the use of `tempnam' is dangerous, better use `mkstemp'

===========================
   Build succeeded. :O)    
===========================
 (shell)
