### ISSUE TITLE
PostgreSQL 17

### ISSUE THREAD

**Issue by ur5us** [getsolus/packages#3962]
### Please confirm there isn't already an existing package update request

- [X] I have searched through package update requests

### Name

PostgreSQL

### Version

17

### Link to the release notes or announcement.

https://www.postgresql.org/about/news/postgresql-17-released-2936/

### Reason for updating

I won’t rehash all improvements from the release notes but as an web application developer many of the features will have tangible effects on DX, e.g. performance gains. However, I’m mostly looking at the upgrade from a practical point of view: using the latest version means being able to restore database dumps from most if not all versions of PostgreSQL. Without the latest version I wouldn’t be able to (easily) restore a db dump locally as soon as my DB SaaS upgrades to v17.

**Comment by androidnisse** [comment]
@ur5us I've got it to build now. Could you please test it to see that everything works?
