### ISSUE TITLE
Update font in branding to Noto Sans and Noto Serif - XFCE

### ISSUE THREAD

**Issue by TraceyC77** [getsolus/packages#397]
Update branding packages to use Noto Sans and Noto Serif by default
Subtask of https://github.com/getsolus/packages/issues/208

**Comment by joebonrichie** [comment]
We don't have a xfce desktop branding package yet so we can close

**Comment by ermo** [comment]
Added in https://github.com/getsolus/packages/blob/main/packages/x/xfce4-desktop-branding/package.yml
