### ISSUE TITLE
mouse-actions

### ISSUE THREAD

**Issue by androidnisse** [getsolus/packages#3993]
### Please confirm there isn't an existing package request

- [X] I have searched through package requests

### Homepage

https://github.com/jersou/mouse-actions

### Maintainer

- [X] Would you like to be the maintainer for this package?

### Why should this be included in the repository?

easystroke is deprecated and this is the replacement.

### Are we allowed to redistribute it?

MIT

### What kind of user will use this package, and how many users do you think will use this package?

Current users of easystroke.

### Link to source archive file

https://github.com/jersou/mouse-actions/releases/download/v0.4.5/mouse-actions-gui-v0.4.5.tar.gz

**Comment by malfisya** [comment]
Please add this and deprecate easystroke. Cheers!
