### ISSUE TITLE
gedit-plugins -> Word completion (T4469)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#4]
<div dir="rtl"><b>Pierre-Yves</b>&nbsp;(<em>&#35;kyrios123</em>),&nbsp;2017-09-04&nbsp;09:43:24&nbsp;UTC</div><br/>

It looks like the appstream data for `gedit-plugins` are rotten because in the software center it's called `Word completion`.
I guess it just take the name of the first plugin it found. It would be nice if this could be improved.

**Comment by TraceyC77** [comment]
Confirming this is still an issue. As of now, there are 2 results for gedit-plugins in the SC
Word completion as reported
"Terminal" "A set set of plugins for Pluma, the MATE text editor. The package pluma-plugins started as a fork of gedit-plugins."

Note that I don't find any other gedit plugins in the repo, so if Word Completion was the only result, it seems that would be expected.

**Comment by EbonJaeger** [comment]
All the gedit plugin sources are in one repo, and they all have their own metainfo files. It looks like the intention is that these are split into separate packages, but we have them all in one package. Fedora handles this by splitting all the plugins into separate packages and have the package `gedit-plugins` be a meta-package that just pulls in all the other plugin packages. Wondering if we should do something similar?
