### ISSUE TITLE
Macook Pro 2011 (8,2) unable to boot Kernel 4.9.22-17+ (T3399)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#40]
<div dir="rtl"><b>Keiran&nbsp;Salmon</b>&nbsp;(<em>&#35;KeiranNZ</em>),&nbsp;2017-04-21&nbsp;03:44:47&nbsp;UTC</div><br/>

After downloading latest updates for 2017.04.18 my system will no longer boot. Tried using kernel 4.9.22-17 (+ additional updated versions push through sc), but no go.  Have also installed further subsequent updates - still no go.

Tried to boot from live usb (usb created using dd in Solus) using latest Budgie iso (sha256 correct), same result -> initial loading messages and then solid cursor in top left corner, - cannot TTY, and have to hard power off, then select 4.9.20-12 to boot successfully (Thank goodness for CBM!)

Single boot Solus only
UEFI (Apple's take on it anyway)

System specs: 
OS: Solus x86_64 
Model: MacBookPro8,2 1.0
Kernel: 4.9.20-12.lts 
Uptime: 18 mins 
Packages: 977 
Shell: bash 4.3.42 
Resolution: 1440x900 
DE: Budgie 
Theme: OSX-Arc-White [GTK2/3] 
Icons: La-capitaine-icon-theme [GTK2/ 
Terminal: gnome-terminal 
CPU: Intel i7-2720QM (8) @ 3.3GHz 
GPU: Intel Integrated Graphics 
GPU: AMD Radeon HD 6630M/6650M/6750M/ 
Memory: 1912MiB / 15962MiB

First installed Solus (November 2016 - I think?) using Shannon 1.2.1 straight out of the box, no issues, and happily using all ok with all other updates since.

Can still use my system quite happily on 4.9.20-12, but would like to update when possible.

**Comment by davidjharder** [comment]
This issue is old enough to be in elementary school. Let's close it
