### ISSUE TITLE
Add the trash status indicator plugin for the XFCE panel

### ISSUE THREAD

**Issue by etokarew** [getsolus/packages#4006]
### Please confirm there isn't already an existing package update request

- [X] I have searched through package update requests

### Name

thunar

### Version

4.18.11

### Link to the release notes or announcement.

https://gitlab.xfce.org/xfce/thunar/-/tree/master/plugins/thunar-tpa

### Reason for updating

There is a similar applet in [MATE](https://github.com/getsolus/packages/tree/main/packages/m/mate-applets), very useful for me!

**Comment by EbonJaeger** [comment]
Note to self for later: Adding `xfce4-panel` as a build dependency to `thunar` should cause the plugin to be built automatically.
