### ISSUE TITLE
kcrash is out of date and lacks some application addresses

### ISSUE THREAD

**Issue by TraceyC77** [getsolus/packages#4024]
### Please confirm there isn't already an existing package update request

- [X] I have searched through package update requests

### Name

kcrash

### Version

6.6.0

### Link to the release notes or announcement.

https://download.kde.org/stable/frameworks/6.6/kcrash-6.6.0.tar.xz

### Reason for updating

Current version is 5.116.0
https://download.kde.org/stable/frameworks/5.116/kcrash-5.116.0.tar.xz

This makes me wonder what other framework components we have that might be out of date

Dr Konqui, which relies on kcrash, is unable to report crashes for plasma-browser-integration-host (and perhaps other things)
See [this forum thread](https://discuss.getsol.us/d/11011-plasma-browser-integration-host-closed-unexpectdly)

[Per this comment](https://bugs.kde.org/show_bug.cgi?id=375813#c6)
KCrash picks the bug report address out of KAboutData, if that is not correctly set then kcrash doesn't know the address, doesn't forward it to drkonqi and then drkonqi cannot report the bug because it doesn't know where to report it.

cc @ReillyBrogan @Justinzobel  @joebonrichie

**Comment by HarveyDevel** [comment]
kf6-kcrash exists. kcrash is for compatibility with Qt5 applications that haven't been ported over yet.

**Comment by ReillyBrogan** [comment]
Closing as `kcrash` is the KF5 version of the package, and `kf6-kcrash` is the KF6 one. Both are fully updated (well, technically the newest KF6 is 6.7.0 but I'll update to it when we're not frozen).
