### ISSUE TITLE
heroic-games-launcher

### ISSUE THREAD

**Issue by HarveyDevel** [getsolus/packages#4025]
### Please confirm there isn't already an existing package update request

- [X] I have searched through package update requests

### Name

heroic-games-launcher

### Version

2.15.2

### Link to the release notes or announcement.

https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/tag/v2.15.2

### Reason for updating

Several fixes including:
- Fixed Amazon Games library synchronization failure.
- Fixed GOG cloud saves issues, when files were removed using utility on GOG's website.
- Fixed issues with offline support.

**Comment by HarveyDevel** [comment]
pinging @infinitymdm

**Comment by infinitymdm** [comment]
This update has been on my to-do list for a bit now. I'll try to get around to it this weekend.
