### ISSUE TITLE
Update Audacity to 3.6.4

### ISSUE THREAD

**Issue by uudruid74** [getsolus/packages#4054]
### Please confirm there isn't already an existing package update request

- [X] I have searched through package update requests

### Name

Audacity

### Version

3.6.4

### Reason for updating

Since the update to Audacity 3.6.1 some weird bug has been making the app unusable.  I was hoping 3.6.4 would work, but it appears Solus is incompatible with the AppImage, making that avenue unavailable.

**Comment by Staudey** [comment]
What issue are you seeing exactly? It seems to launch fine for me. Does it not launch at all for you? If so, do you get any output when you run `audacity` from a terminal?

**Comment by malfisya** [comment]
@uudruid74 Just to clarify: 
- v3.6.1 (which is available in repo) is not usable for you. In what way?
- Appimage of v.3.6.4 does not launch in Solus
- You wish audacity in the repo is to be updated to v.3.6.4
Correct?

**Comment by uudruid74** [comment]
> @uudruid74 Just to clarify:
> 
> * v3.6.1 (which is available in repo) is not usable for you. In what way?
> * Appimage of v.3.6.4 does not launch in Solus
> * You wish audacity in the repo is to be updated to v.3.6.4
> 
> Correct?

Correct.

As for question #1, the track display just disappears if you drag the track too far.  It just stops updating it.  You can resize the window and it will fix it, but it keeps happening so often its painful to edit anything.  I don't see it as a bug, but I'd rather not report it as a bug if I'm running a version 3 releases old.

How long does it usually take for the update to hit the stable tree?

**Comment by malfisya** [comment]
It is usually synced on Friday, but most likely we are skipping this week.  We are currently testing Gnome 47, It needs a bit more time. It probably either friday next week or in the middle of next week. Cheers!
