### ISSUE TITLE
GNOME: ship and enable by default firefox search provider

### ISSUE THREAD

**Issue by sebo505** [getsolus/packages#4077]
There is a search provider for the GNOME shell build in firefox.
If enabled, you can search firefox bookmarks and history (and potentially open tabs) via search in overview, if an instance of firefox is running. By clicking on search result, the site gets opened in new tab or window in firefox. (or switched to existing open tab)
This is a really handy feature. And since we ship firefox as default browser, I suggest to enable this feature as default to offer a great GNOME experience.

It's hard to find comprehensive info about this. [This](https://mastransky.wordpress.com/2020/09/25/firefox-gnome-shell-search-provider/) has been a first hint for me.

I then checked how this is set up in Fedora.
You basically need to have 
file `/usr/share/gnome-shell/search-providers/org.mozilla.firefox.search-provider.ini` containing
```
[Shell Search Provider]
DesktopId=firefox.desktop
BusName=org.mozilla.firefox.SearchProvider
ObjectPath=/org/mozilla/firefox/SearchProvider
Version=2
```
and file `/usr/share/dbus-1/services/org.mozilla.firefox.SearchProvider.service` containing
```
[D-BUS Service]
Name=org.mozilla.firefox.SearchProvider
Exec=/usr/lib64/firefox/firefox --dbus-service /usr/bin/firefox 
```

and have `browser.gnome-search-provider.enabled` set to `true` in firefox `about:config`

This config enables search for bookmarks and history. I haven't figured out yet how to enable search for open tabs. This works in Fedora 41 though.

I have found [https://bugzilla.mozilla.org/show_bug.cgi?id=1634961](https://bugzilla.mozilla.org/show_bug.cgi?id=1634961)
This seems to have enabled this feature in firefox recently.

Is this already part of the firefox we are shipping?

https://github.com/user-attachments/assets/2c71e277-9853-485c-a97a-86f4a471fd3f

**Comment by joebonrichie** [comment]
may also need this
https://src.fedoraproject.org/rpms/firefox/c/0bec6f6cb8eef665ee7c9217daddd6a389dd428e?branch=rawhide

**Comment by joebonrichie** [comment]
Alright these files come from the firefox package in fedora. I'm currently unsure whether they should be provided by gnome-desktop-branding or firefox. If provided by firefox should they be split out to their own subpackage?

**Comment by sebo505** [comment]
I have seen the discussions about necessity of changing firefox desktop file on matrix packaging channel. I don't know the exact context of your discussion.
If it is regarding the search provider, I had read in the readme file [here](https://searchfox.org/mozilla-central/source/browser/components/shell/search-provider-files) that the main point is that the `DesktopId=` in `/usr/share/gnome-shell/search-providers/org.mozilla.firefox.search-provider.ini` matches the distributions firefox desktop file name in `/usr/share/applications`.

**Comment by sebo505** [comment]
Just out of curiosity: did you also succeed in getting this switching to open tab working? When this works, open tabs are proceeded with `(*)` in search results, as you can see in the video I have posted above.

**Comment by sebo505** [comment]
Very nice! Also very nice that you were so swift responsive in regard to this issue. Much appreciated!
