### ISSUE TITLE
Time Zone (T3885)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#41]
<div dir="rtl"><b>Don&nbsp;White</b>&nbsp;(<em>&#35;RenHoek</em>),&nbsp;2017-06-15&nbsp;20:20:15&nbsp;UTC</div><br/>

I live in the Chicago time zone (UTC -0500). I just installed Solus on a laptop for someone who lives in the New York time zone (UTC -0400). During the installation process, I configured the machine for the New York time zone (UTC -0400).

I have since opened the Date & Time applet and configured it for:
1) Automatic Date & Time
2) Automatic Time Zone

When I type

Code: Select all

timedatectl status

the results indicate the following:
Local time is UTC -0400
Universal Time: is UTC
RTC Time: is set to UTC
Time Zone: America/New York (EDT, -0400)
NTP enabled: yes
NTP synchronized: yes
RTC in local TZ: no
DST active: yes

So, my concern is that even though I have enabled the Automatic Time Zone option in the Date & Time applet, the time zone which was specified during the installation process seems to be sticky. Therefore, when this laptop travels across time zones, the clock will not automatically adjust. Case in point, the laptop is currently, physically in the Chicago time zone, but it still thinks that it is in the New York time zone.

**Comment by davidjharder** [comment]
Old, no new info. Closing
