### ISSUE TITLE
nheko does not maximize when double clicking titlebar in GNOME or Plasma

### ISSUE THREAD

**Issue by sebo505** [getsolus/packages#4101]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

I have noticed that nheko won't maximize window in GNOME when double clicking titlebar.
As reference I checked in Fedora, where this works.
Also, titlebars look different.

Solus:
![Bildschirmfoto vom 2024-10-19 20-21-22](https://github.com/user-attachments/assets/571f60e9-0150-41fe-aca9-adc4b0e7f3d1)

Fedora:
![Bildschirmfoto vom 2024-10-19 19-48-17](https://github.com/user-attachments/assets/8bd4b001-7b3a-424e-855f-21250cdd937f)

### Steps to reproduce

be in GNOME
start nheko
double click title bar

### Expected result

window should maximize/unmaximize

### Actual result

window does not maximize/unmaximize

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

GNOME

### System details

# Systemdetailsbericht
---

## Berichtdetails
- **Erstellungsdatum:**                            2024-10-19 20:17:42

## Hardware-Informationen:
- **Hardware-Modell:**                             Hewlett-Packard HP EliteBook 6930p
- **Speicher:**                                    4,0 GiB
- **Prozessor:**                                   Intel® Core™2 Duo T9550  × 2
- **Grafik:**                                      AMD RV620
- **Festplattenkapazität:**                        250,1 GB

## Software-Informationen:
- **Firmware-Version:**                            68PCD Ver. F.16
- **Name des Betriebssystems:**                    Solus 4.6 Convergence
- **Betriebssystem-Build:**                        (null)
- **Betriebssystem-Typ:**                          64-bit
- **GNOME-Version:**                               46
- **Fenstermanager:**                              Wayland
- **Kernel-Version:**                              Linux 6.10.13-304.current

**Comment by TraceyC77** [comment]
This bug exists in Plasma as well.

**Comment by TraceyC77** [comment]
This is not something Solus can control. Please report this to [the Nheko bug tracker](https://github.com/Nheko-Reborn/nheko/issues). Thanks.
