### ISSUE TITLE
GNOME 47.1 Wayland session crashes on login with "Mouse Keys" enabled

### ISSUE THREAD

**Issue by Staudey** [getsolus/packages#4127]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

After the update to GNOME 47.1 the Wayland session immediately crashes on login and exits back to `gdm`

This is caused by the "Mouse Keys" accessibility setting being enabled. Disabling it fixes the issue.
Upstream bug report: https://gitlab.gnome.org/GNOME/mutter/-/issues/3708
Upstream MR with tentative fix: https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/4083

According to Daniel van Vugt this is currently one of the most common gnome-shell 47 crashes they see on Ubuntu, so probably worth fixing before this hits Stable:
> Despite only happening when mouse keys is enabled, we're finding this has been close to the top gnome-shell 47 crashes for Ubuntu 24.10 in the last few days.

Serpent OS works around this by just disabling the setting: https://github.com/serpent-os/recipes/commit/a3847b2ce7625b96e0b4803c891be002677b2c0a

Also this note from the upstream bug report:

> Seems this triggers enable_mousekeys and the same crash:

> `org.gnome.desktop.a11y.keyboard enable true`

Not sure if this overrides the mouse keys setting if it's explicitly disabled

### Steps to reproduce

1. Update Unstable GNOME system
2. Set `org.gnome.desktop.a11y.keyboard mousekeys-enable true` using dconf
3. Try to log into a Wayland session

### Expected result

Successful login

### Actual result

Screen turns black for a bit (at least on Nvidia), then `gdm` appears again

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

GNOME

### System details

```
System:
  Host: solus-pc Kernel: 6.11.3-306.current arch: x86_64 bits: 64
  Desktop: GNOME v: 47.1 Distro: Solus 4.5 resilience
Machine:
  Type: Desktop Mobo: MSI model: Z170A PC MATE (MS-7971) v: 2.0
    serial: <superuser required> UEFI-[Legacy]: American Megatrends v: A.60
    date: 12/17/2015
CPU:
  Info: quad core Intel Core i7-6700K [MT MCP] speed (MHz): avg: 800
    min/max: 800/4200
Graphics:
  Device-1: NVIDIA GP106 [GeForce GTX 1060 6GB] driver: nvidia v: 560.35.03
  Display: wayland server: X.Org v: 24.1.3 with: Xwayland v: 24.1.3
    compositor: gnome-shell driver: X: loaded: nvidia
    gpu: nvidia,nvidia-nvswitch resolution: 1920x1080~60Hz
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: nvidia mesa v: 560.35.03
    renderer: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2
Network:
  Device-1: Realtek RTL8192CE PCIe Wireless Network Adapter driver: rtl8192ce
  Device-2: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet
    driver: r8169
Drives:
  Local Storage: total: 1.82 TiB used: 738.59 GiB (39.6%)
Info:
  Memory: total: 32 GiB available: 31.31 GiB used: 4.35 GiB (13.9%)
  Processes: 296 Uptime: 52m Shell: Zsh inxi: 3.3.36

```

**Comment by joebonrichie** [comment]
Should be resolved by 460a45d91cf13830ff35929bf477c56965978467
