### ISSUE TITLE
Add gnome-online-accounts-gtk as dependency to Budgie Control Center

### ISSUE THREAD

**Issue by Staudey** [getsolus/packages#4201]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

Some users seem to be confused about the removal of Gnome Online Accounts from Budgie Control Center and are looking for a way to still use the functionality. gnome-online-accounts-gtk was added as a GTK3-based replacement for the functionality, but is currently not automatically installed on Budgie systems. I suggest including it as a runtime dependency of budgie-control-center.

Side note: The release notes of Budgie Control Center 1.4.0, which removed the Online Accounts feature, say:
>  libgoa is no longer a dependency of the project and gnome-online-accounts is not a recommended package to be installed along-side BCC.

I'm not sure if this is (still) a problem, so I have not created a PR with the change for now.

Side note 2: A rebuild of the package will probably need [this patch](https://github.com/xapp-project/gnome-online-accounts-gtk/commit/a923ff268c33e8254116a1b3dc8dd6ecc33194f2) because of a build issue with GTK4 >= 4.15.0

### Steps to reproduce

N/A

### Expected result

N/A

### Actual result

N/A

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

Budgie

### System details

N/A

**Comment by ermo** [comment]
A PR doing just this was recently merged, closing.
