### ISSUE TITLE
VBox VM taken to full-screen (HOST+F) during a Wayland session locks everything up

### ISSUE THREAD

**Issue by WetGeek** [getsolus/packages#425]
### Summary

When I work with my Solus VMs, I frequently like to do it with the VM at full-screen.  After adopting Wayland for my 
Plasma computers, I found out the doing that during a Wayland session causes (1) the VM to assume a full-screen display, and (2) the system to lock up tight.  I can use the mouse to click the [X] in the system area, which takes the VM out of full-screen mode, but the system remains unresponsive.

The workaround is to switch to an X11 session prior to any workflow that requires the VM to be made full-screen.  This is
definitely a Wayland issue, as VMs work normally during an X11 session.  

If I forget to do that, the only way to recover from the lock-up is to press and hold the power switch - a rude shutdown.

### Steps to reproduce

1.  Create a VBox VM, or use an existing one.  Reproducing this issue does not harm the VM.
2.  Switch to a Wayland session if not already in one.
3.  Save any work in progress.  This part is important, as the session will lock up and need to be restarted.
4.  Launch the VM and use the HOST+F command to cause it to display as full-screen.

### Expected result

Normally, the VM would assume a full-screen display, and function as usual in place of the host machine's UI.  HOST+F is a toggle that will return the VM to its original size when pressed again.  The host machine is unaffected by this process, and will resume its normal operation.

### Actual result

The VM does assume a full-sreen state, but nothing within the client area will respond to the mouse or keyboard.  It is possible return the VM to its original size, but the system still remains unresponsive.  The only way I've found to recover
from this lock-up is to press and hold the power switch until the system shuts down.  

Be sure to return the VM to its original smaller size before shutting the system down, or else log in to an X11 session upon restarting, so that when the VM is started the next time it won't lock up the system as soon as it appears.  

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Plasma

### System details

Info from the System Settings:

![image](https://github.com/getsolus/packages/assets/6805994/b86464b1-be9f-456d-8957-47235fa0ccd1)

**Comment by WetGeek** [comment]
An alternative to taking the VM to full-screen using the HOST+F command is to simply maximize the VM.  That way, it simply occupies the full client area of the host's window.  This works well on Plasma, but other DEs produce scroll bars instead of resizing the VM's window.

Plus, the VM's display + the host window are included, reducing the height of the VM and changing its aspect ratio.

**Comment by HarveyDevel** [comment]
From researching the problem it appears to be a well known issue and has existed for 3+ years.

There is a workaround for wayland that appears to work in testing. Disabling the mini toolbar.

![virtualbox](https://github.com/getsolus/packages/assets/43508890/09733832-3dbd-418c-9a12-fd53664e02a6)

So this appears to be an upstream issue with virtualbox on wayland and as such, there is nothing we can do.

**Comment by WetGeek** [comment]
It's working fine here, too.  The only downside is that the Latte dock is also unavailable at full-screen, but I can live without that.  It's great to be able to use Wayland again.  Maybe they'll figure out a  way to actually fix this one day.

I'm curious to know who actually came up with this work-around.  Was it Oracle or KDE?

**Comment by HarveyDevel** [comment]
I just found users online suggesting the workaround.

Since this is an upstream issue, closing ticket.
