### ISSUE TITLE
Only-Office Desktop Editors

### ISSUE THREAD

**Issue by TheRoarkster** [getsolus/packages#4256]
### Please confirm there isn't an existing package request

- [X] I have searched through package requests

### Homepage

https://github.com/ONLYOFFICE/DesktopEditors

### Maintainer

- [ ] Would you like to be the maintainer for this package?

### Why should this be included in the repository?

LibreOffice is _technically_ compatible with MS Office -- in that it can read Office documents and edit them.  However, it gets the formatting wrong (or messes with the formatting on save) 95% of the time.  As such, LibreOffice is unusable for anyone who has to go back and forth with MS Office users.  OnlyOffice gets formatting right, and users can seamlessly move between it and MS Office.  Also, OnlyOffice is smaller than LibreOffice and, from a UI perspective, way more user-friendly.

Also, for those who would respond "just use `flatpak` or `snap`," many users are drawn to Solus because it runs well on lighter hardware.  Flatpak and Snap base packages are heavy.  And the individual applications on those platforms are often flawed and difficult to resolve (see, e.g., [Signal Desktop issues on Flatpak](https://github.com/flathub/org.signal.Signal/issues/753)), but the same issues are not present on the native app.  

### Are we allowed to redistribute it?

AGPL-3.0-or-later

### What kind of user will use this package, and how many users do you think will use this package?

Mainstream desktop users.  Pretty much everyone though.

### Link to source archive file

https://github.com/ONLYOFFICE/desktop-apps/archive/refs/heads/master.zip

**Comment by malfisya** [comment]
We already discussed it before [here](https://github.com/getsolus/packages/issues/923). Unless the situation has changed, the answer remains the same. Cheers!
