### ISSUE TITLE
hut

### ISSUE THREAD

**Issue by ianmjones** [getsolus/packages#4260]
### Please confirm there isn't an existing package request

- [X] I have searched through package requests

### Homepage

https://sr.ht/~xenrox/hut/

### Maintainer

- [X] Would you like to be the maintainer for this package?

### Why should this be included in the repository?

It's a CLI tool for sr.ht.

### Are we allowed to redistribute it?

AGPL-3.0-only

### What kind of user will use this package, and how many users do you think will use this package?

Developers that use sr.ht services such as git, builds, todo, lists, pages hosting etc.

### Link to source archive file

https://git.sr.ht/~xenrox/hut/archive/v0.6.0.tar.gz

**Comment by davidjharder** [comment]
Approved
