### ISSUE TITLE
IRC clients - remove #solus channel recommendations

### ISSUE THREAD

**Issue by TraceyC77** [getsolus/packages#4297]
Remove IRC clients suggesting the #solus channel when first set up

We have moved support to Matrix
We are no longer actively talking or moderating those channels

- [x] Hexchat https://github.com/getsolus/packages/pull/4300
- [x] Telepathy
- [x] irssi
- [x] quassel
- [x] kvirc
- [x] konversation

**Comment by TraceyC77** [comment]
Verified Konversation doesn't suggest any channels
It auto-joins #konversation only

**Comment by androidnisse** [comment]
Verifeid  irssi, quassel and kvirc. No suggestions for #solus. I have removed a patch for hexchat that suggested #solus

**Comment by ZachBacon** [comment]
I don't see libtelepathy-idle, nor polari been modified to suggest #solus, but that's just on a cursory search of the package in git.
