### ISSUE TITLE
Applications don't open on live Plasma ISO after connecting the WiFi (T5675)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#43]
<div dir="rtl"><b>João&nbsp;Marujo</b>&nbsp;(<em>&#35;jppmarujo</em>),&nbsp;2018-01-30&nbsp;20:58:49&nbsp;UTC</div><br/>

I don't know if this is reproducible, but i burnt with both Etcher and Rufus, more than one time each, and downloaded two instances of the ISO available on Patreon.

When on the live USB of the Plasma ISO with an installer, if i connect to the WiFi, applications don't open. They show up on the taskbar, and something force closes them.

I can't find a proper tag for it, i'm sorry.

**Comment by davidjharder** [comment]
Old, nothing like this has been reported with recent ISOs, closing
