### ISSUE TITLE
Pika Backup scheduling issue

### ISSUE THREAD

**Issue by OlivierM16** [getsolus/packages#4340]
### Please confirm there isn't an open report for this issue

- [X] I have searched through bug reports

### Summary

Pika Backup can not run in background to run schedulings.

### Steps to reproduce

1. Run Pika Backup (flatpak)
2. Try to activate schedule functionnality
3. Pika Backup show an alert about `xdg-desktop-portal`
![image](https://github.com/user-attachments/assets/40ecc4ac-da42-4f42-b491-1cdf57149942)

### Expected result

Pika Backup running in background to activate schedulings

### Actual result

does not work in background, no schedule 

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Budgie

### System details

System:
  Host: workstation Kernel: 6.11.7-308.current arch: x86_64 bits: 64
  Desktop: Budgie v: 10.9.2 Distro: Solus 4.6 convergence
Machine:
  Type: Desktop Mobo: Micro-Star model: MAG B550M MORTAR MAX WIFI (MS-7C94)
    v: 1.0 serial: <superuser required> BIOS: American Megatrends LLC. v: 1.G0
    date: 08/22/2023
CPU:
  Info: 8-core AMD Ryzen 7 5800X [MT MCP] speed (MHz): avg: 1752
    min/max: 550/4851
Graphics:
  Device-1: Advanced Micro Devices [AMD/ATI] Navi 24 [Radeon RX 6400/6500
    XT/6500M] driver: amdgpu v: kernel
  Device-2: Logitech QuickCam Pro for Notebooks
    driver: snd-usb-audio,uvcvideo type: USB
  Display: x11 server: X.Org v: 21.1.14 with: Xwayland v: 24.1.4 driver:
    gpu: amdgpu resolution: 3840x2160~60Hz
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 24.2.6 renderer: AMD
    Radeon RX 6400 (radeonsi navi24 LLVM 18.1.8 DRM 3.59 6.11.7-308.current)
Network:
  Device-1: MEDIATEK MT7921K Wi-Fi 6E 80MHz driver: mt7921e
  Device-2: Realtek RTL8125 2.5GbE driver: r8169
Drives:
  Local Storage: total: 4.08 TiB used: 407.14 GiB (9.7%)
Info:
  Memory: total: 32 GiB available: 31.27 GiB used: 4.93 GiB (15.8%)
  Processes: 421 Uptime: 5h 39m Shell: Bash inxi: 3.3.36

**Comment by OlivierM16** [comment]
There's some information about this issue here :
<https://world.pages.gitlab.gnome.org/pika-backup/help/C/feature-schedule.html>

> **Troubleshooting**
> Pika Backup uses the xdg-desktop-portal Background Portal to configure the Monitor process to run in the background. Some distributions misconfigure xdg-desktop-portal or don't enable the Background Portal. This will then cause an error when enabling scheduled backups. We have tested the following distributions for correct behavior regarding background portals in their stock configuration:
> 
> - Debian
> 
> - Fedora
> 
> If you encounter issues with enabling scheduled backups and you are using a different distribution, please report an issue in your distribution issue tracker.

**Comment by EbonJaeger** [comment]
The Background portal requires tight integration with the desktop environment, so the ones used by Budgie (`xdg-desktop-portal-gtk` and `xdg-desktop-portal-xapp` don't have it. It used to be a part of the GTK portal, but was moved to the GNOME-specific portal.

**Comment by ReillyBrogan** [comment]
`xdg-desktop-portal-xapp` actually does seem to support it at least partially, but that would require wiring up support in Budgie.

Anyway, since this is a Budgie-specific issue with regards to them needing to implement Background portal support _somehow_ and not a packaging issue I'm going to go ahead and close this one. I recommend you make an issue over in the [Budgie repo](https://github.com/BuddiesOfBudgie/budgie-desktop) if one does not already exist.

**Comment by OlivierM16** [comment]
I filed a [bug issue](https://github.com/BuddiesOfBudgie/budgie-desktop/issues/637) on Budgie repo.
