### ISSUE TITLE
Solus Installer fails to detect universal flash storage drive(UFS)

### ISSUE THREAD

**Issue by darkserge0** [getsolus/packages#4341]
### Please confirm there isn't an open report for this issue

- [X] I have searched through bug reports

### Summary

Solus Live usb Doesn't detect ufs drive at all.  I can't install solus or does it show up with gparted on any version of solus live.

### Steps to reproduce

1. Boot up solus live image
2. Can't install solus

### Expected result

Being able to see the ufs drive to install it.

### Actual result

ufs drive didn't show up to install

### Environment

- [ ] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Plasma

### System details

System:
  Host: brett-solus Kernel: 6.11.7-308.current arch: x86_64 bits: 64
  Desktop: KDE Plasma v: 6.2.3 Distro: Solus 4.6 convergence
Machine:
  Type: Laptop System: ASUSTeK product: Vivobook Go E1504GA_E1504GA v: 1.0
    serial: S7N0CV05R611282
  Mobo: ASUSTeK model: E1504GA v: 1.0 serial: S727NBCV001EC1MB UEFI: American
    Megatrends LLC. v: E1504GA.305 date: 03/15/2024
Battery:
  ID-1: BAT0 charge: 43.0 Wh (100.0%) condition: 43.0/41.9 Wh (102.7%)
CPU:
  Info: 8-core Intel Core i3-N305 [MCP] speed (MHz): avg: 800
    min/max: 800/3800
Graphics:
  Device-1: Intel Alder Lake-N [UHD Graphics] driver: i915 v: kernel
  Device-2: ShineTech USB2.0 HD UVC WebCam driver: uvcvideo type: USB
  Display: server: X.Org v: 21.1.14 with: Xwayland v: 24.1.4 driver:
    gpu: i915 resolution: 1920x1080~60Hz
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: intel mesa v: 24.2.6
    renderer: Mesa Intel Graphics (ADL-N)
Network:
  Device-1: Realtek RTL8821CE 802.11ac PCIe Wireless Network Adapter
    driver: rtw_8821ce
Drives:
  Local Storage: total: 119.24 GiB used: 11.09 GiB (9.3%)
Info:
  Memory: total: 8 GiB note: est. available: 7.39 GiB used: 1.37 GiB (18.6%)
    igpu: 64 MiB
  Processes: 228 Uptime: 2m Shell: Bash inxi: 3.3.36

### Other comments

note that I was using a external usb enclosure to run solus on.  Ive tried the ufs drive with fedora and endeavour os and it seen the drive and installed fine.  Mint seen the drive and installed but booted into initramfs.

**Comment by darkserge0** [comment]
I should note its the internal UFS ssd drive that solus isn't detecting

**Comment by ReillyBrogan** [comment]
I'll get this into our next kernel update. Could you join our Matrix in the packaging channel? I think we can link you a test ISO when we next generate those

**Comment by ReillyBrogan** [comment]
Closed by 31ddf5f1ec889866f339ff3eea013d4e10576923
