### ISSUE TITLE
System no longer starts after update "Error preparing initrd: Device Error start_image() returned Device Error'

### ISSUE THREAD

**Issue by Zozosticot** [getsolus/packages#4342]
### Please confirm there isn't an open report for this issue

- [X] I have searched through bug reports

### Summary

After installing Solus on my laptop and performing the update with nvidia drivers from doflicky, the system does not restart and leaves me with the error “error preparing initrd device error”.

### Steps to reproduce

1. Install and update system

2. Install nvdia drivers with Doflicky (step 1 and 2 can be exchanged, the result is the same)

3. Shut down machine.

4. Start

### Expected result

The system should start up without a hitch

### Actual result

The pc returns the error “error preparing initrd device error”, and restarts, forming an infinite loop.

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Budgie

### System details

System:
  Host: laptop Kernel: 6.10.13-304.current arch: x86_64 bits: 64
  Desktop: Budgie v: 10.9.2 Distro: Solus 4.6 convergence
Machine:
  Type: Laptop System: ASUSTeK product: GL553VE v: 1.0
    serial: <superuser required>
  Mobo: ASUSTeK model: GL553VE v: 1.0 serial: <superuser required>
    UEFI: American Megatrends v: GL553VE.308 date: 04/29/2019
Battery:
  ID-1: BAT0 charge: 29.5 Wh (98.7%) condition: 29.9/48.2 Wh (62.1%)
CPU:
  Info: quad core Intel Core i7-7700HQ [MT MCP] speed (MHz): avg: 800
    min/max: 800/3800
Graphics:
  Device-1: Intel HD Graphics 630 driver: i915 v: kernel
  Device-2: NVIDIA GP107M [GeForce GTX 1050 Ti Mobile] driver: nouveau
    v: kernel
  Device-3: Realtek USB2.0 HD UVC WebCam driver: uvcvideo type: USB
  Display: x11 server: X.Org v: 21.1.13 with: Xwayland v: 24.1.4 driver:
    gpu: i915 resolution: 1920x1080~60Hz
  API: OpenGL v: 4.6 compat-v: 4.3 vendor: intel mesa v: 24.2.6
    renderer: Mesa Intel HD Graphics 630 (KBL GT2)
Network:
  Device-1: Intel Wireless 7265 driver: iwlwifi
  Device-2: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet
    driver: r8169
Drives:
  Local Storage: total: 1.36 TiB used: 7.32 GiB (0.5%)
Info:
  Memory: total: 8 GiB available: 7.64 GiB used: 1.27 GiB (16.6%)
  Processes: 241 Uptime: 21m Shell: Bash inxi: 3.3.36

### Other comments

In a previous installation, by pressing the space bar at boot time, I was able to boot the previous kernel entry and remove the nvidia packages that didn't include “modaliases”.
This solved the problem and I was able to reboot the system.

The driver nouveau indicated by inxi is not to blame for the system breakage, as the information comes from a system where the proprietary drivers have not yet been installed.

**Comment by ReillyBrogan** [comment]
Please make sure you are fully updated before installing the driver packages.

**Comment by Zozosticot** [comment]
System updated before driver installation, but nothing happens

**Comment by asianbullet** [comment]
Have same issue installed updates upon reboot, boot error of “Error preparing initrd: Device Error start_image() returned Device Error”. Was able to boot into previous .conf & confirmed all packages were updated. This seems to be same issue from week 28, for reference see matrix Solus support channel chat logs circa 15th July 2024. I ran CBM_DEBUG=1 clr-boot-manager update & found the following;

**Comment by asianbullet** [comment]
[DEBUG] cbm (../src/cli/cli.c:L142): No such file: //etc/kernel/update_efi_vars
[INFO] cbm (../src/bootman/bootman.c:L787): Current running kernel: 6.11.5-307.current
[INFO] cbm (../src/bootman/sysconfig.c:L179): Discovered UEFI ESP: /dev/disk/by-partuuid/13b3da36-b8d1-4ffd-81e6-1e05603c4e93
[INFO] cbm (../src/bootman/sysconfig.c:L256): Fully resolved boot device: /dev/nvme0n1p1
[DEBUG] cbm (../src/bootman/bootman.c:L141): shim-systemd caps: 0x26, wanted: 0x26
[DEBUG] cbm (../src/bootman/bootman.c:L156): UEFI boot now selected (shim-systemd)
[INFO] cbm (../src/bootman/bootman.c:L807): path ///etc/kernel/initrd.d does not exist
[DEBUG] cbm (../src/bootman/bootman.c:L828): Non regular file: ///usr/lib64/kernel/initrd.d/., skipping.
[DEBUG] cbm (../src/bootman/bootman.c:L828): Non regular file: ///usr/lib64/kernel/initrd.d/.., skipping.
[INFO] cbm (../src/bootman/bootman.c:L503): Checking for mounted boot dir
[INFO] cbm (../src/bootman/bootman.c:L555): Mounting boot device /dev/nvme0n1p1 at /boot
[SUCCESS] cbm (../src/bootman/bootman.c:L568): /dev/nvme0n1p1 successfully mounted at /boot
[DEBUG] cbm (../src/bootman/update.c:L164): Now beginning update_native
[DEBUG] cbm (../src/lib/cmdline.c:L361): Removing cmdline using file: ///etc/kernel/cmdline-removal.d/quiet.conf
[DEBUG] cbm (../src/lib/cmdline.c:L361): Removing cmdline using file: ///etc/kernel/cmdline-removal.d/quiet.conf
[DEBUG] cbm (../src/bootman/update.c:L173): update_native: 2 available kernels
[DEBUG] cbm (../src/bootman/update.c:L191): update_native: Running kernel is (current) ///usr/lib/kernel/com.solus-project.current.6.11.5-307
[SUCCESS] cbm (../src/bootman/update.c:L205): update_native: Bootloader updated
[DEBUG] cbm (../src/bootman/kernel.c:L650): installing extra initrd: /usr/lib64/kernel/initrd-com.solus-project.current.6.11.5-307.nvidia
[DEBUG] cbm (../src/bootloaders/systemd-class.c:L219): adding extra initrd to bootloader: initrd-com.solus-project.current.6.11.5-307.nvidia
[SUCCESS] cbm (../src/bootman/update.c:L220): update_native: Repaired running kernel ///usr/lib/kernel/com.solus-project.current.6.11.5-307
[DEBUG] cbm (../src/bootman/update.c:L230): update_native: Checking kernels for type current
[INFO] cbm (../src/bootman/update.c:L243): update_native: Default kernel for type current is ///usr/lib/kernel/com.solus-project.current.6.11.7-309
[DEBUG] cbm (../src/bootman/kernel.c:L650): installing extra initrd: /usr/lib64/kernel/initrd-com.solus-project.current.6.11.7-309.nvidia
[DEBUG] cbm (../src/bootloaders/systemd-class.c:L219): adding extra initrd to bootloader: initrd-com.solus-project.current.6.11.7-309.nvidia
[SUCCESS] cbm (../src/bootman/update.c:L255): update_native: Installed tip for current: ///usr/lib/kernel/com.solus-project.current.6.11.7-309
[DEBUG] cbm (../src/bootman/kernel.c:L650): installing extra initrd: /usr/lib64/kernel/initrd-com.solus-project.current.6.11.5-307.nvidia
[DEBUG] cbm (../src/bootloaders/systemd-class.c:L219): adding extra initrd to bootloader: initrd-com.solus-project.current.6.11.5-307.nvidia
[SUCCESS] cbm (../src/bootman/update.c:L269): update_native: Installed last_good kernel (current) (///usr/lib/kernel/com.solus-project.current.6.11.5-307)
[DEBUG] cbm (../src/bootman/update.c:L280): update_native: Analyzing for type current: ///usr/lib/kernel/com.solus-project.current.6.11.7-309
[INFO] cbm (../src/bootman/update.c:L288): update_native: not-running: ///usr/lib/kernel/com.solus-project.current.6.11.7-309
[DEBUG] cbm (../src/bootman/update.c:L291): update_native: Skipping default-current: ///usr/lib/kernel/com.solus-project.current.6.11.7-309
[DEBUG] cbm (../src/bootman/update.c:L280): update_native: Analyzing for type current: ///usr/lib/kernel/com.solus-project.current.6.11.5-307
[DEBUG] cbm (../src/bootman/update.c:L285): update_native: Skipping running kernel
[DEBUG] cbm (../src/lib/cmdline.c:L361): Removing cmdline using file: ///etc/kernel/cmdline-removal.d/quiet.conf
[DEBUG] cbm (../src/lib/cmdline.c:L361): Removing cmdline using file: ///etc/kernel/cmdline-removal.d/quiet.conf
[INFO] cbm (../src/bootman/bootman.c:L503): Checking for mounted boot dir
[INFO] cbm (../src/bootman/bootman.c:L510): boot_dir is already mounted: /boot
[SUCCESS] cbm (../src/bootman/update.c:L338): update_native: Default kernel for current is ///usr/lib/kernel/com.solus-project.current.6.11.7-309
[DEBUG] cbm (../src/bootman/update.c:L353): No kernel removals found
[INFO] cbm (../src/bootman/bootman.c:L469): Attempting umount of /boot
[SUCCESS] cbm (../src/bootman/bootman.c:L473): Unmounted boot directory

**Comment by TraceyC77** [comment]
When adding code or terminal output please use 3 backticks before and after to make a code block

**Comment by enzoleguennan** [comment]
Another GTX 1050M problem reported on the Nvidia forums, this time from an Ubuntu user.
https://forums.developer.nvidia.com/t/nvidia-gtx-1050-mobile-and-ubuntu-22-04-has-problems/315168

**Comment by Zozosticot** [comment]
Another GTX 1050M problem reported on the Nvidia forums, this time from an Ubuntu user.
https://forums.developer.nvidia.com/t/nvidia-gtx-1050-mobile-and-ubuntu-22-04-has-problems/315168

**Comment by TraceyC77** [comment]
> Another GTX 1050M problem reported on the Nvidia forums, this time from an Ubuntu user. 

The original poster with the was reporting a different error that seems unrelated. The reply from "beunenzo" has the same error with the 560 drivers.

**Comment by Zozosticot** [comment]
Hello, the 560.35.03 driver works on my configuration.

**Comment by TraceyC77** [comment]
@asianbullet , do you still have issues after updating your system and nvidia-glx-driver to the latest version?

**Comment by asianbullet** [comment]
@TraceyC77 Hi there, system is up-to-date w/latest stable nvidia-glx-drivers 560.35.03-551
Issue resolved for my system spec, Thank You

**Comment by TraceyC77** [comment]
Excellent. It sounds like the newer nVidia drivers solved the problem.
