### ISSUE TITLE
ubuntu sans fonts (new ubuntu fonts)

### ISSUE THREAD

**Issue by g1bber1sh** [getsolus/packages#4360]
### Please confirm there isn't an open request for this package

- [X] I have searched through package addition requests

### Homepage

https://github.com/canonical/Ubuntu-Sans-fonts

### Maintainer

- [ ] Would you like to be the maintainer for this package?

### Why should this be included in the repository?

its a very nice font, but please do not remove the old ubuntu fonts, they are also nice
the old one are called ubuntu, the new ones ubuntu sans

### Are we allowed to redistribute it?

https://ubuntu.com/legal/font-licence

### What kind of user will use this package, and how many users do you think will use this package?

anyone who doesent just stick with what comes out of the box might want to give them a try

### Link to source archive file

https://github.com/canonical/Ubuntu-Sans-fonts/releases/download/v1.006/UbuntuSans-fonts-1.006.zip

**Comment by malfisya** [comment]
I want to approve this, but the license is not familiar. At first glance, it looks like we can redistribute it but there are a few limitations. Also this license has not been vetted by either FSF or OSI. Are there any other distributions that ship this in their repo? (AUR doesn't count)

**Comment by g1bber1sh** [comment]
seems to be the exact same license as the original ubuntu font (Ubunto Font License-1.0) 
both the original packages contain the same license file 
old: https://assets.ubuntu.com/v1/0cef8205-ubuntu-font-family-0.83.zip
new: https://github.com/canonical/Ubuntu-Sans-fonts/releases/download/v1.006/UbuntuSans-fonts-1.006.zip
so if one can be redistributed i guess so can the other?

**Comment by malfisya** [comment]
You are right. It will be fine I guess. Just needed someone to maintain for us.
