### ISSUE TITLE
internal mic not detected after updating a new install of solus

### ISSUE THREAD

**Issue by darkserge0** [getsolus/packages#4381]
### Please confirm there isn't an open report for this issue

- [X] I have searched through bug reports

### Summary

The internal mic isn't detected and doesn't show up as input device on solus budgie or plasma.  also the microphone light on the keyboard is on(f9) and won't show up.  It does show up after installing solus,  but stops showing up after updating.

### Steps to reproduce

1.Install solus
2. Update Solus
3. go into budgie settings sound input is greyed out

### Expected result

The Mic should be seen in input options

### Actual result

no options to enable mic

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Budgie

### System details

System:
  Host: brett-budgie Kernel: 6.11.7-309.current arch: x86_64 bits: 64
  Desktop: Budgie v: 10.9.2 Distro: Solus 4.6 convergence
Machine:
  Type: Laptop System: ASUSTeK product: Vivobook Go E1504GA_E1504GA v: 1.0
    serial: S7N0CV05R611282
  Mobo: ASUSTeK model: E1504GA v: 1.0 serial: S727NBCV001EC1MB UEFI: American
    Megatrends LLC. v: E1504GA.305 date: 03/15/2024
Battery:
  ID-1: BAT0 charge: 43.0 Wh (100.0%) condition: 43.0/41.9 Wh (102.7%)
CPU:
  Info: 8-core Intel Core i3-N305 [MCP] speed (MHz): avg: 800
    min/max: 800/3800
Graphics:
  Device-1: Intel Alder Lake-N [UHD Graphics] driver: i915 v: kernel
  Display: x11 server: X.Org v: 21.1.14 with: Xwayland v: 24.1.4 driver:
    gpu: i915 resolution: 1920x1080~60Hz
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: intel mesa v: 24.2.7
    renderer: Mesa Intel Graphics (ADL-N)
Network:
  Device-1: Realtek RTL8821CE 802.11ac PCIe Wireless Network Adapter
    driver: rtw_8821ce
Drives:
  Local Storage: total: 357.88 GiB used: 7.23 GiB (2.0%)
Info:
  Memory: total: 8 GiB note: est. available: 7.39 GiB used: 2.34 GiB (31.7%)
    igpu: 64 MiB
  Processes: 264 Uptime: 15m Shell: Sudo inxi: 3.3.36

arecord -l info

**** List of CAPTURE Hardware Devices ****
card 0: sofhdadsp [sof-hda-dsp], device 0: HDA Analog (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofhdadsp [sof-hda-dsp], device 6: DMIC (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofhdadsp [sof-hda-dsp], device 7: DMIC16kHz (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0

lspci -vv 
00:1f.3 Multimedia audio controller: Intel Corporation Alder Lake-N PCH High Definition Audio Controller
	DeviceName: Onboard - Sound
	Subsystem: ASUSTeK Computer Inc. Device 3650
	Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
	Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
	Latency: 32, Cache Line Size: 64 bytes
	Interrupt: pin D routed to IRQ 132
	Region 0: Memory at 6001150000 (64-bit, non-prefetchable) [size=16K]
	Region 4: Memory at 6001000000 (64-bit, non-prefetchable) [size=1M]
	Capabilities: [50] Power Management version 3
		Flags: PMEClk- DSI- D1- D2- AuxCurrent=55mA PME(D0-,D1-,D2-,D3hot+,D3cold+)
		Status: D0 NoSoftRst+ PME-Enable- DSel=0 DScale=0 PME-
	Capabilities: [80] Vendor Specific Information: Len=14 <?>
	Capabilities: [60] MSI: Enable+ Count=1/1 Maskable- 64bit+
		Address: 00000000fee00438  Data: 0000
	Kernel driver in use: sof-audio-pci-intel-tgl

### Other comments

The audio works fine but the mic isn't detected after updating from a fresh install.  searching around made me think its a kernal problem, not sure.

**Comment by bigrammy** [comment]
I have the same issue with my VivoBook ASUSLaptop X515JAB  Your system seems the same as mine with regard to the the mic's which are identified as device 6 & 7
Try this.
# Make sure this sof firmware is installed and up to date
sudo eopkg it sof-firmware 


# Add this to /user/lib64/modprobe.d/alsa-base.conf (You will probably need to create it)
options snd_sof_intel_hda_common dmic_num=2 

Restart the laptop and see if you can select the mic in your sound settings.
My Mic shows up as **Ice Lake-LP Smart Sound Technology Audio Controller Pro7**

**Comment by darkserge0** [comment]
Tried what you said, sof-firmware was already installed.  created a file named /user/lib64/modprobe.d/alsa-base.conf  with options snd_sof_intel_hda_common dmic_num=2 and saved it,  then I ran clr-boot-manager and rebooted.  The mic still isn't seen.

**Comment by bigrammy** [comment]
I am not totally sure what made my setup work so the next config is:
Add this to /etc/pulse/default.pa.d  (You will probably need to create it and give it permission)
load-module module-alsa-source device=hw:0,6  (Mine is 6 yours maybe 7 so you may need to try both)

Once done power OFF and restart. 
Fingers Crossed it will work.

**Comment by darkserge0** [comment]
> I am not totally sure what made my setup work so the next config is:
> Add this to /etc/pulse/default.pa.d (You will probably need to create it and give it permission)
> load-module module-alsa-source device=hw:0,6 (Mine is 6 yours maybe 7 so you may need to try both)

do you create a folder  or a file with /etc/pulse/default.pa.d and if its a folder what is the name of the file in it.  What permissions do you give to it?

**Comment by bigrammy** [comment]
Sorry the folder already exists if you have pulseaudio installed. It's in the solus software center if not.
The **default.pa.d** you can create and add the line _load-module module-alsa-source device=hw:0,6_

It may well work by simply installing pulseaudio then selecting the correct "input device"

**Comment by darkserge0** [comment]
I use pipewire and wireplumber, is there any fix for that?

**Comment by bigrammy** [comment]
I am not sure about those, I had some trouble with pipewire in the beginning . 
If you check out the Solus forum link I gave earlier and maybe post there. I don't  want to fill this "open issue" with trouble shooting also others on the forum may have some experience of their own.

**Comment by bigrammy** [comment]
As a possible Work around! 
According to https://www.alsa-project.org/main/index.php/Asoundrc
It's possible to create a /home/.asoundrc file that can be modified to set your chosen hw device as the default. 
Could someone familiar with this sort of thing create a .asoundrc template we can easily edit adding our details 
from arecord -L and or arecord -l or aplay -L aplay -l

Arch wiki gives some info about this and I think it would be useful for those with problem devices and SOF issues.
https://wiki.archlinux.org/title/Advanced_Linux_Sound_Architecture/Troubleshooting#Setting_the_default_microphone/capture_device

I would do it myself but I am not confident in my comprehension and coding skills sorry

**Comment by darkserge0** [comment]
I think a update somewhere's broke my mic, because a fresh install of solus from the site recognized the mic.  As soon as I updated with sudo eopkg up it stopped detecting it.

**Comment by darkserge0** [comment]
It seems using pro audio semi fixed my problem with the mic, now if I could turn off that annoying f9 mic keyboard light.

**Comment by mark-nicholson** [comment]
Pulled the new change and verified the fix.  Thanks!
