### ISSUE TITLE
Numlock option not functional on KDE Wayland

### ISSUE THREAD

**Issue by Julien684** [getsolus/packages#4383]
### Please confirm there isn't an open report for this issue

- [X] I have searched through bug reports

### Summary

The numlock option does not work on KDE with Wayland display server.

### Steps to reproduce

1. In the SDDM connection window, select Wayland
2. Once in the session, go to KDE Settings => Keyboard => Num lock on startup => Enable.
3. Restart session or computer.

### Expected result

Numlock must be activated after SDDM connection

### Actual result

It is not activated.

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Plasma

### System details

```bash
System:
  Host: konqi Kernel: 6.11.7-309.current arch: x86_64 bits: 64
  Desktop: KDE Plasma v: 6.2.3 Distro: Solus 4.6 convergence
Machine:
  Type: Desktop System: ASUS product: N/A v: N/A serial: <superuser required>
  Mobo: ASUSTeK model: ProArt X670E-CREATOR WIFI v: Rev 1.xx
    serial: <superuser required> UEFI: American Megatrends v: 2401
    date: 09/12/2024
CPU:
  Info: 16-core AMD Ryzen 9 7950X [MT MCP] speed (MHz): avg: 3010
    min/max: 545/5881
Graphics:
  Device-1: Advanced Micro Devices [AMD/ATI] Navi 31 [Radeon RX 7900 XT/7900
    XTX/7900 GRE/7900M] driver: amdgpu v: kernel
  Device-2: Advanced Micro Devices [AMD/ATI] Raphael driver: amdgpu
    v: kernel
  Display: wayland server: X.org v: 1.21.1.14 with: Xwayland v: 24.1.4
    compositor: kwin_wayland driver: N/A resolution: 1: 2560x1440 2: 2560x1440
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 24.2.7 renderer: AMD
    Radeon RX 7900 XTX (radeonsi navi31 LLVM 18.1.8 DRM 3.59
    6.11.7-309.current)
Network:
  Device-1: Intel Ethernet I225-V driver: igc
  Device-2: Aquantia AQtion AQC113CS NBase-T/IEEE 802.3an Ethernet [Antigua
    10G] driver: atlantic
Drives:
  Local Storage: total: 18.2 TiB used: 5.7 TiB (31.3%)
Info:
  Memory: total: 64 GiB available: 61.93 GiB used: 5.54 GiB (8.9%)
  Processes: 562 Uptime: 11m Shell: Zsh inxi: 3.3.36
```

### Other comments

I've already posted my problem on the forum.
https://discuss.getsol.us/d/11106-numlockw-to-enable-numlock-on-plasma-system-startup
I also did a fresh install and did all the updates on a test PC, same result, yet the post here says it's solved https://discuss.getsol.us/d/11028-small-issues-in-a-clean-install-of-solus-46-plasma
But not on my installations.

**Comment by TraceyC77** [comment]
This is an upstream issue being tracked in the KDE bug tracker [bug 3680630(https://bugs.kde.org/show_bug.cgi?id=368063)

**Comment by TraceyC77** [comment]
Closing this out since there is an upstream issue. This is not something Solus would fix, but KDE will
