### ISSUE TITLE
FreeCAD: Update to v1.0.0

### ISSUE THREAD

**Issue by luzpaz** [getsolus/packages#4396]
### Please confirm there isn't an open request for this package

- [X] I have searched through package update requests

### Name

freecad

### Version

1.0.0

### Link to the release notes or announcement.

https://wiki.freecad.org/Release_notes_1.0

### Reason for updating

Huge milestone update: https://wiki.freecad.org/Release_notes_1.0

Note: it would be beneficial to also bump coin dependency  
* https://github.com/getsolus/packages/issues/4318

**Comment by DeviateFromThePlan** [comment]
#192482

**Comment by ermo** [comment]
Resolved by PR #4418
