### ISSUE TITLE
7 Days To Die crashes Solus and restarts the entire desktop session; impacted by LSI settings (T5011)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#44]
<div dir="rtl"><b>AC</b>&nbsp;(<em>&#35;Beer</em>),&nbsp;2017-11-12&nbsp;19:34:04&nbsp;UTC</div><br/>

* Fresh Solus 3 install
* Linux Steam Integration untouched from default settings
* GTX 970, proprietary drivers 384.98
* Fresh 7 Days to Die installation

On first run, my desktop crashed completely.  The screen blanked a few times and it dropped me back to desktop login with an empty desktop session.  This happened again about 10 times in a row while I was trying to fix it.  It is very reproducible for me.

I managed to get the game running stable by setting these options in LSI:
* DISABLE - Use native runtime
* DISABLE - Force 32 bit
* ENABLE - Use liblsi-intercept

If I ran with all 3 settings enabled, it would crash my desktop 9/10 times.

**EDIT**: I forgot to mention the most important part - enabling "use native runtime" in LSI seems to be the culprit.  Once I disabled that it stopped crashing Solus

I'm not sure where to look for appropriate log files since the desktop crashed, please let me know and I will attach logs.

---

The game also started up at a funky super narrow window size: https://i.imgur.com/rQzQO6K.png

I had to set a generic Unity startup parameter in steam settings in order to fix this: 
```
-screen-fullscreen 1
```

**Comment by davidjharder** [comment]
Old as dirt. Closing.
