### ISSUE TITLE
Clean up some `monitoring.yml`s

### ISSUE THREAD

**Issue by davidjharder** [getsolus/packages#4425]
We have discussed and agreed that `monitoring.yml` files should use the line 

```
  rss: ~

```
when no rss feed is available.

Some existing packages use an incorrect version of this: 

```
 rg 'rss: null'
packages/l/lzip/monitoring.yml
3:  rss: null

packages/l/light/monitoring.yml
3:  rss: null # Upstream is an archived mirror, feed is DOA

packages/w/wireless-regdb/monitoring.yml
3:  rss: null # For example https://github.com/PyO3/maturin/releases.atom

```

Corresponding issue to update the docs here: https://github.com/getsolus/help-center-docs/issues/582

**Comment by Staudey** [comment]
Just remembered that as similar logic applies for the `ignore` keys (there can be one in `releases` and `security`). Should we always include them and set to `~` as well? Would make the minimal monitoring.yml a bit more unwieldy of course.
