### ISSUE TITLE
waydroid Failed to load binder driver

### ISSUE THREAD

**Issue by FAb7D** [getsolus/packages#4440]
### Please confirm there isn't an open report for this issue

- [X] I have searched through bug reports

### Summary

I try to initialize waydroid and I get the following error:
Waiting for waydroid container service...
Failed to load binder driver
modprobe: FATAL: Module binder_linux not found in directory /lib/modules/6.10.13-304.current
Binder node "binder" for waydroid not found

### Steps to reproduce

Open Waydroid
Downolad

### Expected result

Waydroid initialization

### Actual result

Failed to load binder driver

### Environment

- [ ] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Plasma

### System details

System:
  Host: solus Kernel: 6.10.13-304.current arch: x86_64 bits: 64
  Desktop: KDE Plasma v: 6.2.3 Distro: Solus 4.6 convergence
Machine:
  Type: Laptop System: HP product: HP Pavilion Gaming Laptop 15-dk0xxx
    v: Type1ProductConfigId serial: <superuser required>
  Mobo: HP model: 85FC v: 42.34 serial: <superuser required> UEFI: Insyde
    v: F.13 date: 09/04/2019
Battery:
  ID-1: BAT1 charge: 44.2 Wh (100.0%) condition: 44.2/52.5 Wh (84.2%)
CPU:
  Info: 6-core Intel Core i7-9750H [MT MCP] speed (MHz): avg: 800
    min/max: 800/4500
Graphics:
  Device-1: Intel CoffeeLake-H GT2 [UHD Graphics 630] driver: i915 v: kernel
  Device-2: NVIDIA TU117M [GeForce GTX 1650 Mobile / Max-Q] driver: nvidia
    v: 560.35.03
  Device-3: MacroSilicon USB3.0 Capture
    driver: hid-generic,snd-usb-audio,usbhid,uvcvideo type: USB
  Device-4: Lite-On HP Wide Vision HD Camera driver: uvcvideo type: USB
  Display: wayland server: X.org v: 1.21.1.14 with: Xwayland v: 24.1.4
    compositor: kwin_wayland driver: X: loaded: modesetting failed: nvidia
    gpu: i915,nvidia resolution: 1: 2194x1234 2: 1536x864
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: intel mesa v: 24.2.7
    renderer: Mesa Intel UHD Graphics 630 (CFL GT2)
Network:
  Device-1: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet
    driver: r8169
  Device-2: Realtek RTL8822BE 802.11a/b/g/n/ac WiFi adapter
    driver: rtw_8822be
Drives:
  Local Storage: total: 1.84 TiB used: 624.32 GiB (33.1%)
Info:
  Memory: total: 16 GiB available: 15.46 GiB used: 6.6 GiB (42.7%)
  Processes: 336 Uptime: 51m Shell: Bash inxi: 3.3.36

**Comment by ReillyBrogan** [comment]
You need to be using the most recent kernel build, either current or lts

**Comment by FAb7D** [comment]
Thank you!
