### ISSUE TITLE
After swtching from multi monitor, to single monitor (laptop) panel's task manager doesn't show tasks (T6374)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#45]
<div dir="rtl"><b>Tagodroid</b>&nbsp;(<em>&#35;guillefar</em>),&nbsp;2018-05-10&nbsp;16:10:49&nbsp;UTC</div><br/>

I usually work with three screens, and each has its own panel. Now, if  unplugged the other monitors, the laptop screen doesn't panel task manager does not show me the apps. The task manager is there, right clicking on it show me the settings menu, but no programs are show. 
If I reconnect the other monitors their panels will indeed show me the programs, but the laptop screen do not, meaning, the problem does not get fix, I have to restart. 
I discover the problem has to do with the  "Show only the task in this screen" option. For some reason, after the other monitors are unplugged, and even when they are plugged again, the laptop panel task manager doesn't "recognize" the programs running in its own screen, but unchecking that option will indeed  make the task manager show all the programs. 
Hope that's clear.

**Comment by TraceyC77** [comment]
I have not seen this bug in a long time (months). It is not present for me in Plasma6, either newly installed or updated from Plasma5.

Closing the bug as resolved. If this happens for anyone again, please open a new issue. Thanks.
