### ISSUE TITLE
Brightnessctl

### ISSUE THREAD

**Issue by K9T33N-alt** [getsolus/packages#4518]
### Please confirm there isn't an open request for this package

- [X] I have searched through package addition requests

### Homepage

https://github.com/Hummer12007/brightnessctl couldn't find homepage

### Maintainer

- [ ] Would you like to be the maintainer for this package?

### Why should this be included in the repository?

by default you have no way of controlling the brightness via keybinds on solus. one way i have found to get around this in other distros is to use `brightnessctl`. once installed you can set a custom keybind with the command ```brightnessctl set <chosen percentage delta>```.

### Are we allowed to redistribute it?

https://github.com/Hummer12007/brightnessctl/blob/3152968fee82796e5d3bac3b49d81e1dd9787850/LICENSE

### What kind of user will use this package, and how many users do you think will use this package?

anyone who wants to change the brightness of their screen from within a keybind, particularly laptop users.

### Link to source archive file

http://deb.debian.org/debian/pool/main/b/brightnessctl/brightnessctl_0.5.1.orig.tar.gz #im not sure whats meant by this, this is just a stable release of the package from debian.

**Comment by infinitymdm** [comment]
Hi @K9T33N-alt, the "Link to source archive file" section is meant to be a link to a compressed (i.e. tarball, zip, etc) archive of the software source code. In the case of brightnessctl, that appears to be here: https://github.com/Hummer12007/brightnessctl/archive/refs/tags/0.5.1.tar.gz.

You mention that you have no way of controlling screen brightness. On my XPS 15, two of the function keys pull double duty as brightness up and brightness down keys. This works with Solus out of the box. Are you dealing with an issue with your laptop's brightness keys not working on Solus, or are you proposing this package as a way for users to set other keybinds to control brightness?

**Comment by ReillyBrogan** [comment]
Are you on Sway/Hyprland/Labwc? If you're on Plasma there is built-in support for controlling display brightness and you can rebind shortcuts as needed. If not, have you looked into using ddcutil (which is what Plasma uses)?

**Comment by ReillyBrogan** [comment]
I'm slightly reluctant on this one as it seems to require the addition of new kernel modules in order for it to enable support for external monitors.

**Comment by K9T33N-alt** [comment]
> You mention that you have no way of controlling screen brightness. On my XPS 15, two of the function keys pull double duty as brightness up and brightness down keys. This works with Solus out of the box. Are you dealing with an issue with your laptop's brightness keys not working on Solus, or are you proposing this package as a way for users to set other keybinds to control brightness?


On my Asus vivobook the labeled brightness control keys are f4 and F5 which does not work for me on solus out of the box. So on any gnome distro I've ever used (the current one I'm using on solus) I've always had to use brightnessctl to use this feature since their is no official keybind. 
So yes brightnessctl could be used for alternative keys or any scenario where brightness control from the keyboard is not supported by default. 
But I now realise solus could also have a better option, have a available keybind in the keybind section itself so new users wouldn't need to meddle with the cli, either or I'm happy with.

**Comment by K9T33N-alt** [comment]
> Are you on Sway/Hyprland/Labwc? If you're on Plasma there is built-in support for controlling display brightness and you can rebind shortcuts as needed. 
I am using gnome, not sure how the support is on the other systems are 
> If not, have you looked into using ddcutil (which is what Plasma uses)?
No I have not heard of it, I tried Searching for alternatives but this never came up so I'll look into it.

**Comment by ReillyBrogan** [comment]
https://def.lakaban.net/2021-06-25-ddcutil-controlling-the-brightness-of-an-external-monitor/

**Comment by K9T33N-alt** [comment]
> https://def.lakaban.net/2021-06-25-ddcutil-controlling-the-brightness-of-an-external-monitor/

Thank you so much this will probably do. I'll close the ticket now.
