### ISSUE TITLE
yubico-authenticator: broken app indicator

### ISSUE THREAD

**Issue by silkeh** [getsolus/packages#453]
### Summary

The tray icon for Yubico authenticator is broken in the latest versions of Budgie.

### Steps to reproduce

1. Start yubico authenticator.
2. Look at system tray.

### Expected result

Yubi authenticator icon in tray:

![com yubico yubioath-32x32](https://github.com/getsolus/packages/assets/5798032/b4929c67-8bbd-4831-9750-758e3d56150e)

### Actual result

Broken icon:

![image](https://github.com/getsolus/packages/assets/5798032/b5892d49-6099-4b4e-a4fe-1855a304fa2a)

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

Budgie

### System details

Reproduced on multiple Budgie systems (stable and unstable).

**Comment by EbonJaeger** [comment]
It looks like they're providing a path to the icon instead of an icon name. The StatusNotifier spec that Budgie now uses doesn't allow this, but previous AppIndicator did/does. This will likely be implemented in Budgie at some point, hopefully sooner rather than later.

**Comment by Justinzobel** [comment]
Can confirm the icon shows correctly in KDE Plasma. I suggest filing upstream in Budgie so it can be tracked and resolved there.

**Comment by joebonrichie** [comment]
Is this still an issue i see it doesn't provide a path to the icon (anymore?)

`Icon=com.yubico.yubioath.png`

**Comment by TraceyC77** [comment]
I just verified this is still an issue on Budgie stable, fully up to date

**Comment by EbonJaeger** [comment]
> Is this still an issue i see it doesn't provide a path to the icon (anymore?)
> 
> `Icon=com.yubico.yubioath.png`

That's still wrong; it shouldn't have the file extension.

**Comment by silkeh** [comment]
Resolved by #3072.
