### ISSUE TITLE
polychromatic: broken app indicator

### ISSUE THREAD

**Issue by silkeh** [getsolus/packages#455]
### Summary

The tray icon for Polychromatic is broken in the latest versions of Budgie.

### Steps to reproduce

1. Start `polychromatic-tray-applet`
2. Look at system tray.

### Expected result

![chroma](https://github.com/getsolus/packages/assets/5798032/3ddf3c7e-acad-43e5-9847-de92a7832b7d)

### Actual result

![image](https://github.com/getsolus/packages/assets/5798032/dccc3014-5306-4891-b883-f5fabde0a831)

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

Budgie

### System details

Reproduced on multiple Budgie systems (stable and unstable).

**Comment by EbonJaeger** [comment]
It looks like they're providing a path to the icon instead of an icon name. The StatusNotifier spec that Budgie now uses doesn't allow this, but previous AppIndicator did/does. This will likely be implemented in Budgie at some point, hopefully sooner rather than later.

**Comment by silkeh** [comment]
Resolved by #3072!
