### ISSUE TITLE
Cold reset after Suspending-to-Ram (T7170)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#46]
<div dir="rtl"><b>Riad&nbsp;Abdallah</b>&nbsp;(<em>&#35;RustyCore</em>),&nbsp;2018-11-06&nbsp;13:30:46&nbsp;UTC</div><br/>

This is an issue that has happened to me on multiple distros, and it's most likely because of my laptop. Due to the problems I was having (Especially suspend-to-ram and graphics card issues), I ended up reverting back to Windows for almost two years up until last weekend when I switched back to Solus.

Everything works perfectly, but suspending is still a hit-or-miss. I can't find a consistent pattern to explain why it works at times, and why it doesn't. On Windows, it works as expected; I can always resume where I left off even after leaving the laptop asleep for a week.

I know there's not much to work with, and that there might not be a definite solution for this, but maybe there's some sort of way or workaround to solve this problem.

Are there any logfiles that might be needed to debug what's happening?

**Comment by davidjharder** [comment]
Old, closing
