### ISSUE TITLE
prusa-slicer: does not build

### ISSUE THREAD

**Issue by androidnisse** [getsolus/packages#4645]
### Please confirm there isn't an open report for this package

- [X] I have searched through packaging problem reports

### Name

prusa-slicer

### Summary of the problem

It does not build with current recipe. Used newer wxwidgets and it got further but still failed later on.

### More information

```
[773/773] Linking CXX static library lib/libwx_gtk3u_xrc-3.2.a
ninja: build stopped: subcommand failed.
Command '['/bin/bash', '--norc', '--noprofile', '/tmp/ypkg-setupcrvxc4xv']' returned non-zero exit status 1.
[Build] setup failed for prusa-slicer
 ✗  Failed to build packages err="Failed to start build of package, reason: exit status 1\n"

```

**Comment by malfisya** [comment]
@JacekJagosz If you have time, can you take a look at this. Thank you!

**Comment by malfisya** [comment]
To consider: https://github.com/prusa3d/PrusaSlicer/releases/tag/version_2.9.0-alpha1 . TL;DR: They are moving to Flatpak route.
As also noted in the recipe, they have been using vendored dependencies. It makes it more less sense for us to package this, if we cannot use our own libs.

**Comment by davidjharder** [comment]
Yes, let's deprecate in favor of the Flatpak. From the [most recent release notes](https://github.com/prusa3d/PrusaSlicer/releases/tag/version_2.9.0):

> Important note for Linux users: As noted before, we are now using [Flathub](https://flathub.org/) as the only official distribution channel of PrusaSlicer on Linux. The reasons behind this decision and what it means for you are described at the end of [2.9.0-alpha1 release log](https://github.com/prusa3d/PrusaSlicer/releases/tag/version_2.9.0-alpha1).
