### ISSUE TITLE
[Package Change] Remove file-roller Dependency from thunar-archive-plugin

### ISSUE THREAD

**Issue by moriel5** [getsolus/packages#4655]
Please confirm there isn't an open report for this issue
>I have searched through bug reports

Summary
>Currently installing `thunar-archive-plugin` pulls in `file-roller`, and removing vice versa, when in reality, the distro flavor should be the deciding factor, to use the existing archive manager.

Steps to reproduce
1. Install `thunar-archive-plugin`.
2. `file-roller`is downloaded and installed as well.

Or

1. Uninstall `file-roller` when `thunar-archive-plugin` is installed.
2. `thunar-archive-plugin` is removed as well.

Expected result
>The desktop branding package should decide which archive manager is pulled in for integration with `thunar`.

For example:
- GNOME. `file-roller`
- Plasma. `ark`
- XFCE. `xarchiver`
- Budgie. Whatever is decided (currently `file-roller`, perhaps `xarchiver` in the future)

Actual result
>`file-roller` is installed, regardless of environment

Environment
>My systems are up to date.

Repo
>Shannon

Desktop Environment
>All of my systems are currently running Budgie, with `thunar` and `xfdesktop`, however I may switch one over to XFCE.

>A note, I have removed the `budgie-desktop-branding` to make minor changes to the defaults (like removing `budgie-wallpapers` and `moka-icon-theme`), however my changes are mostly minimal, unless otherwise noted due to relevance.

System details
- Operating System: Solus 4.6
- Budgie Version: 10.9.2
- Kernel Version: 6.12.5-311.current
- Graphics Platform: X11

**Comment by EbonJaeger** [comment]
Right now, [`xarchiver` installs the .tap file to `$(libexecdir)/thunar-archive-plugin/xarchive.tap`](https://github.com/ib/xarchiver/blob/master/configure.ac#L178-L183), which expands to `/usr/lib64/xarchiver/thunar-archive-plugin/xarchiver.tap`. I'm not sure if this is the correct directory. `thunar-archive-plugin` [installs its included .tap files also to  `$(libexecdir)/thunar-archive-plugin/`](https://gitlab.xfce.org/thunar-plugins/thunar-archive-plugin/-/blob/master/scripts/Makefile.am?ref_type=heads#L3), which expands to `/usr/lib64/thunar-archive-plugin/thunar-archive-plugin/`.

**Comment by moriel5** [comment]
Interesting, although I do not have the .tap at all, despite installing `xarchiver`.

I manually created the .tap, however I may have improperly configured it (I used `ark`'s .tap as a base, though since then I have found the upstream xarchiver.tap in `thunar-archive-plugin`'s code repository (I forget if it is GitHub or something else), so I should use that instead), so while it "worked", `xarchiver' just crashed when launched that way.
