### ISSUE TITLE
VPN not working in Firefox browser (private window) but working with ssh command line

### ISSUE THREAD

**Issue by FTouzain** [getsolus/packages#469]
> Note: last version of Solus with budgie-desktop 10.8.1-265 (current): Linux 6.5.5-258.current . I believe I use openfortivpn (1.20.2-12, current) and Fortinet SSLVPN client (1.4.0-19, current). I use French interface.

Hi. I found the following issues in the Solus VPN:

* ~~when changing the password of a VPN configuration: "Apply" button seemed deactivated. I believed it was  impossible to change the password.
When doing xkill and coming back to the application, the password is changed. Therefore, probably "Apply" button works but do not close the window.~~ Seems to have been solved by last update: THANKS A LOT

* When connecting to VPN, solus and token appli tells that I am connected in VPN, but __it does not seem to be the case in Firefox browser (use private window to avoid cahe issues)__ (intranet sites unavailable and redirecting to global home page of my organization, this is not the case on a computer running Windows. A restart of the computer does not solve the problem).  A __command line connexion using ssh through the vpn works__.

* ~~In addition, the right bottom hand corner menu for network is not readable (only a black column appearing instead of menus). More exactly, it is available but it does not display any white text, neither submenus.~~ Seems to have been solved by last update: THANKS A LOT
> Note. In many previous versions of Solus/Budgie, I only needed a left click to reach network menu by the bottom right hand corner "icon", now, I need a right click. I supposed it was normal but I am not sure.

Thank you for your answers and Solus

**Comment by ReillyBrogan** [comment]
The next sync will bring systemd-resolved enabled by default for all users (see #426). Systemd-resolved integrates with network-manager and should better handle dns servers distributed by network-manager VPN clients, so please test this after the next sync to see if your issue is resolved.

**Comment by FTouzain** [comment]
After upgrade, then reboot, VPN works both in command line and in Firefox private window. Great. Congratulation and thank you.
