### ISSUE TITLE
gtklock

### ISSUE THREAD

**Issue by EbonJaeger** [getsolus/packages#4690]
### Please confirm there isn't an open request for this package

- [X] I have searched through package addition requests

### Homepage

https://github.com/jovanlanik/gtklock

### Maintainer

- [X] Would you like to be the maintainer for this package?

### Why should this be included in the repository?

The only DE-agnostic Wayland screen locker we have in the repo right now is swaylock, and its default experience is pretty terrible. Adding gtklock provides a nicer, GTK-based alternative for a screen locker in Wayland, particularly for Budgie users.

### Are we allowed to redistribute it?

GPL-3.0-only

### What kind of user will use this package, and how many users do you think will use this package?

Wayland desktop users who require a DE-agnostic screen locking solution. Mainly, me.

### Link to source archive file

https://github.com/jovanlanik/gtklock/archive/refs/tags/v4.0.0.tar.gz

**Comment by malfisya** [comment]
I am guessing you are using wayland on budgie full time now. : )

**Comment by EbonJaeger** [comment]
Actually, I'm on XFCE most of the time, now, because my Budgie session is unusable without a decent lock screen :P
