### ISSUE TITLE
wlr-randr

### ISSUE THREAD

**Issue by EbonJaeger** [getsolus/packages#4694]
### Please confirm there isn't an open request for this package

- [X] I have searched through package addition requests

### Homepage

https://sr.ht/~emersion/wlr-randr/

### Maintainer

- [X] Would you like to be the maintainer for this package?

### Why should this be included in the repository?

It is a `randr` utility for Wayland. It would be very useful for using Wayland.

### Are we allowed to redistribute it?

MIT

### What kind of user will use this package, and how many users do you think will use this package?

Wayland users used to using `randr`.

### Link to source archive file

https://git.sr.ht/~emersion/wlr-randr/refs/download/v0.4.1/wlr-randr-0.4.1.tar.gz

**Comment by HarveyDevel** [comment]
Approved.
