### ISSUE TITLE
kanshi

### ISSUE THREAD

**Issue by EbonJaeger** [getsolus/packages#4695]
### Please confirm there isn't an open request for this package

- [X] I have searched through package addition requests

### Homepage

https://git.sr.ht/~emersion/kanshi

### Maintainer

- [X] Would you like to be the maintainer for this package?

### Why should this be included in the repository?

It is a useful utility for display management under Wayland/wlroots-based compositors.

### Are we allowed to redistribute it?

MIT

### What kind of user will use this package, and how many users do you think will use this package?

Wayland/wlroots users.

### Link to source archive file

https://git.sr.ht/~emersion/kanshi/refs/download/v1.7.0/kanshi-1.7.0.tar.gz

**Comment by HarveyDevel** [comment]
Approved.
