### ISSUE TITLE
Missing dependencies for Gnome apps on Solus Plasma (T7162)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#47]
<div dir="rtl"><b>Claude&nbsp;Durocher</b>&nbsp;(<em>&#35;clauded</em>),&nbsp;2018-11-04&nbsp;23:12:17&nbsp;UTC</div><br/>

Just installed Solus Plasma from the test ISO. When I install a Gnome app (gnote for example) the app won't start and throws an error like "GLib-GIO-ERROR **: Settings schema 'org.gnome.desktop...' is not installed".

To correct this, gsettings-desktop-schemas has to be installed with eopkg. 

As it would be tedious to add this dependency to every gnome app, I suggest to install by default gsettings-desktop-schemas in Solus Plasma.

**Comment by TraceyC77** [comment]
Closing this issue due to age and lack of updates, as well as being unable to reproduce on my system. I have gnote installed on Plasma and it has opened without error since I installed it a while ago. If this is still an issue for anyone, please open a new bug on our tracker.
