### ISSUE TITLE
Device removed from bluetooth not able to ever reconnect again. (T7227)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#48]
<div dir="rtl"><b>Bruno&nbsp;Pereira</b>&nbsp;(<em>&#35;FizzyGoodMakeFeelNice</em>),&nbsp;2018-11-21&nbsp;09:59:20&nbsp;UTC</div><br/>

I accidentally clicked on ''remove'' instead of ''disconnect'' on a bluetooth device's options and realized soon after that I wasn't finding any way to reconnect it. Saw someone on the forums with an identical issue (except he was blaming it on the wife lol)  and 0 awnsers, so I guess it couldn't hurt to ask again about this. This is my first time reporting an issue so apologies in advance for anything I might be doing wrong in this process.

**Comment by davidjharder** [comment]
Old. Can't duplicate. Closing
