### ISSUE TITLE
Blinking mouse cursor and square around around it (T5747)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#49]
<div dir="rtl"><b>fawzi&nbsp;bedidi</b>&nbsp;(<em>&#35;Faz95210</em>),&nbsp;2018-02-06&nbsp;12:37:14&nbsp;UTC</div><br/>

After the update of yesterday I encountered a weird bug. My cursor often bilnk and when it doesn't a square "forms itself" around it preventing me from seeing what happens under this square

**Comment by davidjharder** [comment]
This is ancient. Closing
