### ISSUE TITLE
"ksmserver-logout-greeter" bug (T7498)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#50]
<div dir="rtl"><b>Jason&nbsp;Raleigh</b>&nbsp;(<em>&#35;jraleigh</em>),&nbsp;2019-01-15&nbsp;17:53:33&nbsp;UTC</div><br/>

Type: upstream
Needed: backup / guidance / from Peter or anyone knowledgeable
Reported: yes / my head is spinning / might not have been the right place / might not have done it the right way
https://bugs.kde.org/show_bug.cgi?id=403243

**Comment by davidjharder** [comment]
This appears to be an upstream Plasma bug. See kde.org bug report in description
