### ISSUE TITLE
When Firefox updates, my language gets changed to English (United Kingdom), and I have to change it back to English (United States) (T7445)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#51]
<div dir="rtl"><b>Tristan&nbsp;Partin</b>&nbsp;(<em>&#35;tristan957</em>),&nbsp;2019-01-05&nbsp;03:02:02&nbsp;UTC</div><br/>

I want to report this here, before I go upstream with the issue because I think there might be something wrong with the packaging.

**Comment by davidjharder** [comment]
Old, no new info. Closing
