### ISSUE TITLE
Network settings issue (T7466)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#52]
<div dir="rtl"><b>Stefan&nbsp;Gies</b>&nbsp;(<em>&#35;sg.office</em>),&nbsp;2019-01-07&nbsp;16:12:51&nbsp;UTC</div><br/>

{F4292531} If you try to change the networkspeed of your NIC from "ignored" to "manual" (1Gbit/Full), the connection falis after altering the values and restarting the NIC. Only resetting to "ignored" solves the problem. This problem was prooved on my five PC's running Solus OS Budgie with its latest updates.

**Comment by TraceyC77** [comment]
Closing this issue due to age and lack of updates. If this is still an issue for anyone, please open a new bug on our tracker. 
There have been quite a few updates to network manager since this issue was last upted.
