### ISSUE TITLE
Update glew  to 2.2.0

### ISSUE THREAD

**Issue by FAb7D** [getsolus/packages#523]
### Name

Glew

### Version

2.2.0

### Link to the release notes or announcement.

https://github.com/nigels-com/glew/releases/tag/glew-2.2.0

### Other comments

Hugin's ill functioning probably depends on it,  see also [https://github.com/getsolus/packages/issues/308](https://github.com/getsolus/packages/issues/308)

**Comment by ReillyBrogan** [comment]
I'll probably do this at the same time I update mesalib to 23.2.x.

**Comment by ReillyBrogan** [comment]
Resolved by bd11d315ae3862e0d1b0fbad00af6b99efdea4c7
