### ISSUE TITLE
avahi-daemon: Failed to open /etc/resolv.conf: No such file or directory (T5132)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#55]
<div dir="rtl"><b>Claude&nbsp;Durocher</b>&nbsp;(<em>&#35;clauded</em>),&nbsp;2017-11-26&nbsp;18:55:43&nbsp;UTC</div><br/>

Solus 3 patched as of nov. 26. In my logs I see :

nov 26 16:53:31 dell-laptop avahi-daemon[558]: Failed to open /etc/resolv.conf: No such file or directory

Other distros seem have the same problem : "The avahi-daemon cannot open the /etc/resolv.conf file because it starts before systemd-resolved."

ref. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=800643

**Comment by davidjharder** [comment]
Per a comment at the and of the debian bug in the description,  this should be fixed in systemd v234+ https://github.com/systemd/systemd/commit/3e06055500755053050620a45236ef606507e1bd

**Comment by TraceyC77** [comment]
Closing this issue due to age and lack of updates. If this is still an issue for anyone, please open a new bug on our tracker.

**Comment by ermo** [comment]
```
$ sudo systemctl status NetworkManager-wait-online.service
● NetworkManager-wait-online.service - Network Manager Wait Online
     Loaded: loaded (/usr/lib/systemd/system/NetworkManager-wait-online.service; disabled; preset: enabled)
```

On my system, the NetworkManager-wait-online.service has a preset of enabled and I can see no references to avahi-daemon being unable to find /etc/resolve.conf in my journal.

Closing as resolved.
