### ISSUE TITLE
zoxide

### ISSUE THREAD

**Issue by hertz-hwang** [getsolus/packages#558]
### Homepage

https://github.com/ajeetdsouza/zoxide

### Why should this be included in the repository?

It's a replacement of `cd` write in rust. It's common in other popular linux distros, but missing in Solus official repo.

### Are we allowed to redistribute it?

MIT

### Who and how many users do you anticipate will use this software?

Sorry I don't know how many users will use it, but it is a replacement of "cd" in rust.

### Link to source archive file

https://github.com/ajeetdsouza/zoxide/archive/refs/tags/v0.9.2.tar.gz

**Comment by joebonrichie** [comment]
Approved
