### ISSUE TITLE
Notify user about application crash on startup (T755)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#56]
<div dir="rtl"><b>Andres&nbsp;Clari</b>&nbsp;(<em>&#35;andresclari</em>),&nbsp;2016-09-19&nbsp;15:20:44&nbsp;UTC</div><br/>

Currently if you start an application from the GUI, and it crashes before even starting, as the user you have no idea what just happened, if it's stuck, or there was a lingering process or anything.

We should somehow intercept that case and at least let the user know that the app just crashed. This would remove a lot of head scratching.

I suppose this pretty much would be an error reporting tool... But in any case just a popup that says that it crashed would be key to begin with.

**Comment by davidjharder** [comment]
This is truly ancient. Closing
