### ISSUE TITLE
font-nerd-fonts

### ISSUE THREAD

**Issue by hertz-hwang** [getsolus/packages#560]
### Homepage

https://www.nerdfonts.com/

### Why should this be included in the repository?

Iconic font aggregator, collection, & patcher. It's useful in ricing.

### Are we allowed to redistribute it?

MIT

### Who and how many users do you anticipate will use this software?

maybe a lot.

### Link to source archive file

https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/FiraCode.tar.xz

**Comment by joebonrichie** [comment]
Approved
