### ISSUE TITLE
Offline mounted NFS share causes login failure with message "System is booting up. See pam_nologin(8)", and the password is rejected. (T5931)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#57]
<div dir="rtl"><b>AC</b>&nbsp;(<em>&#35;Beer</em>),&nbsp;2018-02-25&nbsp;07:35:28&nbsp;UTC</div><br/>

I have FreeNAS running on a vmware server.  The server went down tonight and my mounted NFS share in Solus went down with it

During early troubleshooting, I rebooted my primary desktop (Solus).  When I booted back up, I was greeted with an error message on the login screen: "System is booting up. See pam_nologin(8)".  https://imgur.com/a/Bl8kh

Every attempt to enter my password would fail, claiming my password was wrong, which it wasn't.  After about 30 seconds of waiting (presumably when it timed out trying to access my mounted share), the screen turned black like it had just rebooted, and then the login screen would reappear without any errors, and I was able to log in fine. 

This happened every time I rebooted Solus while my NAS was offline.. so I think it should be easily reproducible.  

Not a major issue, but it shouldn't happen

**Comment by davidjharder** [comment]
Old, no new info. Closing
