### ISSUE TITLE
Orange (T7842)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#59]
<div dir="rtl"><b>Kshitij</b>&nbsp;(<em>&#35;kshady</em>),&nbsp;2019-04-11&nbsp;15:13:48&nbsp;UTC</div><br/>

Name of the software - Orange

Project/product Homepage - https://orange.biolab.si/download/linux/

Why we should include this into the repository, i.e. what does it do that the alternatives do not?

Is it open source? - Yes

If it is open source, please provide a link to the most up to date, versioned source tarball/zipfile. master.zip links will not be accepted. - https://orange.biolab.si/download/linux/

If there are no upstream releases but the inclusion policy is otherwise met, please provide a link to the source repository (i.e. GitHub)

**Comment by davidjharder** [comment]
Old, closing
