### ISSUE TITLE
Ralink RT5370 doesn't find networks on first boot (T7613)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#61]
<div dir="rtl"><b>Jake</b>&nbsp;(<em>&#35;watpi</em>),&nbsp;2019-02-17&nbsp;13:27:32&nbsp;UTC</div><br/>

Bus 001 Device 002: ID 148f:5370 Ralink Technology, Corp. RT5370 Wireless Adapter

This behavior has occured for about two months. The adapter doesn't find any networks on first boot, but after a reboot it starts working normally.

**Comment by davidjharder** [comment]
Old, closing
