### ISSUE TITLE
USB Webcams Fail to Initialize (T7663)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#62]
<div dir="rtl"><b>Moriel</b>&nbsp;(<em>&#35;moriel5</em>),&nbsp;2019-03-05&nbsp;13:42:09&nbsp;UTC</div><br/>

Oddly enough, whenever I attempt to connect a USB webcam to any of the Solus computers at home (my desktop and laptop, unstable, and my sister's laptop, Shannon), they are detected by `dmesg` however they all fail to initialize, leading to both Cheese and Kamera failing to access them.
Other USB devices work without any issues, and internal LVDS webcams are also fine.

**Comment by davidjharder** [comment]
Original reporter says it's an upstream issue with old hardware. Closing
