### ISSUE TITLE
Request to package python-mongo-tooling-metrics

### ISSUE THREAD

**Issue by TraceyC77** [getsolus/packages#627]
### Homepage

https://pypi.org/project/mongo-tooling-metrics/

### Why should this be included in the repository?

This is a requirement for mongodb 7.0.2

### Are we allowed to redistribute it?

none

### Who and how many users do you anticipate will use this software?

Anyone who installs mongodb

NOTE: This module has no license specified

```
❯ pip show mongo-tooling-metrics                                                                   ✘ 1
Name: mongo-tooling-metrics
Version: 1.0.8
Summary: A slim library which leverages Pydantic to reliably collect type enforced metrics and store them to MongoDB.
Home-page: 
Author: Tausif Rahman
Author-email: tausif.rahman@mongodb.com
License: 
Location: /home/tracey/.local/lib/python3.10/site-packages
Requires: distro, gitpython, pydantic, pymongo, setuptools
Required-by: 
```

### Link to source archive file

https://files.pythonhosted.org/packages/5a/9a/582069b66a4f8dece95a600bd7bbbc1befb45213def7c5d89a56f1432cc0/mongo_tooling_metrics-1.0.8.tar.gz

**Comment by TraceyC77** [comment]
This module may or may not have issues being redistributed since it has no license specified.
https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#license-txt

> Every package should include a license file detailing the terms of distribution. In many jurisdictions, packages without an explicit license can not be legally used or distributed by anyone other than the copyright holder.

**Comment by joebonrichie** [comment]
yeah without it being licensed i don't think we can package it as is. Is it a hard requirement for the mongodb 7.x series?

**Comment by TraceyC77** [comment]
Thanks for the feedback. After some research, I found mongodb plans to remove this from the build requirements
https://jira.mongodb.org/browse/SERVER-82192
I'm going to add a patch to remove this from the package.
