### ISSUE TITLE
Rendering issues with latest updates (T5867)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#63]
<div dir="rtl"><b>yaomtc</b>&nbsp;(<em>&#35;yaomtc</em>),&nbsp;2018-02-18&nbsp;01:08:38&nbsp;UTC</div><br/>

After I was updated to Linux 4.15.3 (and mesalib 18.0.0_rc4, but it works on Linux 4.14), I now get severe rendering issues making websites nearly impossible to use, and larger images are prevented from fully loading at all. This includes wallpaper before and after login. Disabling Intel IOMMU (intel_iommu=off) or switching to the previous kernel clears up the issue.

Here's a blurry, shaky video I took with my phone: https://www.youtube.com/watch?v=Nxe7oIc-Ie8

Which I took because screen capture currently doesn't capture large areas, as you can see in these screenshots:

https://i.imgur.com/vdbNda4.png

https://i.imgur.com/i7dVxzn.png

I have an AMD Radeon RX 580 that works in Windows. CPU is an Intel Core i5-4690K.

```
$ inxi -G
Graphics:  Card-1: Intel Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller
           Card-2: Advanced Micro Devices [AMD/ATI] Ellesmere [Radeon RX 470/480/570/580]
           Display Server: x11 (X.Org 1.19.6 ) driver: amdgpu
           Resolution: 1920x1080&#35;60.00hz
           OpenGL: renderer: Radeon RX 580 Series (POLARIS10 / DRM 3.23.0 / 4.15.3-53.current, LLVM 5.0.1)
           version: 4.5 Mesa 18.0.0-rc4
```

Here's my dmesg output after opening a larger image: {F2471955}

Here's the image in question, if that helps: {F2471966}

This issue does not occur on Linux 4.14.18-51, which I've just tested. Glad it was still installed.

**Comment by TraceyC77** [comment]
Closing this issue due to age and lack of updates. Additionally, previous commits indicate they would fix this issue. If this is still an issue for anyone, please open a new bug on our tracker.
