### ISSUE TITLE
Vulkan ICD Loader favours Intel iGPU over discrete Nvidia (T6335)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#64]
<div dir="rtl"><b>Burak&nbsp;Yildiz</b>&nbsp;(<em>&#35;arkhenius</em>),&nbsp;2018-05-05&nbsp;19:17:29&nbsp;UTC</div><br/>

**Issue:** On a system with a GTX 970 and an Intel i5-4590, vulkaninfo tries to load the ICD for the integrated Intel GPU over the dedicated Nvidia one by default. Disabling the Intel GPU on BIOS causes a segmentation fault on vulkaninfo.

**Solution:** move all the other ICD loaders out of "/usr/share/vulkan/icd.d/", only keeping the Nvidia one there. 

So for some reason, Solus prioritized the Intel ICD Loader as long as the Intel related .json files were in that directory. Fiddling with the libGL.so locations and filenames in 10_nvidia .json did not solve the problem.

**Extra Notes:** I did not report the issue when I first had it and solved it myself. However, seeing some other people encounter the same issue (https://www.reddit.com/r/linux_gaming/comments/8h5jrp/cant_run_vulkan_on_nvidia_1050_ti_on/), and that the same solution works for them as well, led me to believe that there might be a larger underlying problem that can be solved. So that this does not happen by default.

  - Segmentation fault with all files in the directory (iGPU is disabled in the BIOS. If it's not disabled it just shows the iGPU attributes):
{F3328114}

  - Working with only the Nvidia related loader:
{F3328115}

**Comment by TraceyC77** [comment]
Closing this as stale. There have been improvements in graphics drivers, mesalib and vulkan in recent months that may have resolved this issue.
