### ISSUE TITLE
Out of Paper Error (T4856)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#65]
<div dir="rtl"><b>Danny</b>&nbsp;(<em>&#35;kemra102</em>),&nbsp;2017-10-23&nbsp;20:28:41&nbsp;UTC</div><br/>

Since the update to driverless printing (which works great in general btw) every time my printer takes in a sheet of paper either from the input tray or the collection tray (to do double sided printing) I get a 

> Printer "HP_ENVY_7640_series_03AEE6_" is out of paper.

message.

This is despite the fact that the printer has a tonne of paper in it's tray (and is in fact successfully using it). This message did not occur before the switch to driverless printing.

As you can see above the printer is a HP Envy 7640.

Solus is v3.26.1 amd64.

**Comment by davidjharder** [comment]
Old as dirt. Closing
