### ISSUE TITLE
package request: hardinfo (System Profiler and Benchmark)

### ISSUE THREAD

**Issue by nux2u** [getsolus/packages#651]
A Linux hobbyist since 2001, I maintain 10 distros for my personal use. I have hardinfo on every thumbdrive I dedicate to a Linux OS. I have a thumbdrive dedicated to Solus 4.4, but hardinfo isn't readily available as a package. Please make a package for hardinfo and/or include hardinfo in the Software Center.

**Comment by davidjharder** [comment]
Hi @nux2u 

Please include the following info for a package request: https://help.getsol.us/docs/packaging/procedures/request-a-package/

There is also an issue template for this, please either edit your existing issue (this one), or close this issue and open a new one using the template https://github.com/getsolus/packages/issues/new?assignees=&labels=Package+Request%2CPriority%3A+Wishlist&projects=&template=request-new-package.yml&title=What%27s+the+package+name%3F
