### ISSUE TITLE
xemu

### ISSUE THREAD

**Issue by ermo** [getsolus/packages#658]
### Homepage

https://xemu.app/

### Why should this be included in the repository?

Xemu is a qemu-based OG XBox emulator with good compatibility.

Solus has a strong tradition for offering good emulators and xemu fits with that theme. It is expected that home users will benefit from its inclusion.

### Are we allowed to redistribute it?

GPL-2.0-only, GPL-2.0-or-later, BSD, MIT

### Who and how many users do you anticipate will use this software?

Gamers interested in emulators and OG XBox games.

No idea how many Solus users will be interested, but I'm interested so it's strictly more than zero?

### Link to source archive file

https://github.com/xemu-project/xemu/releases/tag/v0.7.116

**Comment by ZachBacon** [comment]
I shall look into this tonight.
