### ISSUE TITLE
Unturned crashes Budgie on launch (T4048)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#66]
<div dir="rtl"><b>Jack&nbsp;Malcom</b>&nbsp;(<em>&#35;Dizee</em>),&nbsp;2017-07-10&nbsp;13:19:13&nbsp;UTC</div><br/>

Title says it all, when starting Unturned on Steam, the screen goes black and kicks me back to gdm.

**Comment by davidjharder** [comment]
Very old. Closing
