### ISSUE TITLE
Qt application scaling is wrong (T4253)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#67]
<div dir="rtl"><b>Tomas</b>&nbsp;(<em>&#35;tompa</em>),&nbsp;2017-08-11&nbsp;04:34:34&nbsp;UTC</div><br/>

**Known Applications:**

- Calibre
- Seafile client window is gigantic (outside my screen) on a 1920x1080 resolution. This makes it hard (impossible?) to resize the window. Running seafile 6.1.0.
- Zeal
- Ghostwriter

**Comment by ReillyBrogan** [comment]
Closing as qt5 and qt6 both support scaling on Wayland and this issue is unlikely to be fixed for X11.
