### ISSUE TITLE
Menu bar height grows when long music title: make some button interface at the bottom of application unusable (unreachable)

### ISSUE THREAD

**Issue by FTouzain** [getsolus/packages#675]
### Summary

When listeninf to music un budgie with lollypop for instance, when the title is very long, the bottom menu becomes big (because title display does not seem to be limited to 'n' first characters).

It can make some application interface unusable because some button are masked by the bottom menu of budgie (I found this case with darktable).

Example of "big" bottom menu:
![2023-10-26_bug_solus_barre](https://github.com/getsolus/packages/assets/43985838/f1eeb731-0a7c-49bd-be92-20ef9a204237)

### Steps to reproduce

1. Listen to music with a long title
2. Run darktable and try to reach bottom buttons, it won't be possible

### Expected result

Music title in the bottom menu limited to "n" characters (and display entirely when flying over with the mouse if you really want to display it: maybe not usefull because can be displayed in the widgets of the "right masked menu")

### Actual result

Music title displayed entirely, even when very long.

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Budgie

### System details

budgie 10.8.1
Solus 4.4 Harmony
Linux 6.5.7-259.current

**Comment by EbonJaeger** [comment]
What Budgie applet is it that is being enlarged?

**Comment by FTouzain** [comment]
I think this is "Task List" (finally not usefull for me considering the recall of all applications on the left and the reach of each window using right click).

**Comment by EbonJaeger** [comment]
Looks like this should be filed at the [Budgie Desktop issue tracker](https://github.com/BuddiesOfBudgie/budgie-desktop/issues). It's a different organization, so this issue can't be directly transferred. Sorry for the inconvenience.

**Comment by FTouzain** [comment]
Seems to be solved with budgie 10.8.4. Thank you
