### ISSUE TITLE
Huge lag when reconnecting headphones multiple times in a row (T7837)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#68]
<div dir="rtl"><b>Ivan&nbsp;Pavluk</b>&nbsp;(<em>&#35;pavlukivan</em>),&nbsp;2019-04-10&nbsp;13:25:56&nbsp;UTC</div><br/>

After reconnecting the headphones a lot of times (It happened due to the headphones being in the position just between "plugged" and "unplugged", I guess?), the system's cpu usage jumps to 100% rendering it unusable, the issue didn't resolve itself in 10 minutes. I'm using the default audio drivers.

**Comment by davidjharder** [comment]
Old, and we're on pipewire now, so maybe fixed?
