### ISSUE TITLE
gnome-shell-extension-speedinator

### ISSUE THREAD

**Issue by joebonrichie** [getsolus/packages#680]
### Homepage

https://github.com/tehsquidge/speedinator

### Why should this be included in the repository?

This is a GNOME 45+ replacement for the impatience extension. We used to ship the impatience extension OOTB for our GNOME image.

### Are we allowed to redistribute it?

GPL-3.0-or-later

### Who and how many users do you anticipate will use this software?

All GNOME users if we ship it by default to replace impatience

### Link to source archive file

https://github.com/tehsquidge/speedinator/archive/368c7e711b08d5edadfe58c8d9b480417949af33.tar.gz

**Comment by ReillyBrogan** [comment]
DENIED. GNOME users don't deserve anything good.
