### ISSUE TITLE
Can't shutdown on optimus laptop when using Intel card (T7505)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#69]
<div dir="rtl"><b>Juan&nbsp;Carlos</b>&nbsp;(<em>&#35;Juankz</em>),&nbsp;2019-01-16&nbsp;21:14:44&nbsp;UTC</div><br/>

Hi there.

As the title says, I have an MSI laptop with Intel and NVIDIA, when using Intel and proceed to shut it down either by console or budgie UI, the systems hangs and doesn't shutdown. The screens keeps showing the last state it had, the keyboards remains lit and fans spinning. It can go on forever.

With NVIDIA this works as expected. Shuts down almost immediately.

Attached the output of journalctl of a short session: {F4310153}

Edit: Forgot my system specs:

```
System:    Kernel: 4.19.12-106.current x86_64 bits: 64 Desktop: Budgie 10.5 Distro: Solus 3.9999 
Machine:   Type: Laptop System: Micro-Star product: GL63 8RC v: REV:1.0 
           Mobo: Micro-Star model: MS-16P6 v: REV:1.0  UEFI [Legacy]: American Megatrends 
           v: E16P6IMS.106 date: 07/16/2018 
Battery:   ID-1: BAT1 charge: 24.1 Wh condition: 41.9/41.4 Wh (101%) 
CPU:       Topology: Quad Core model: Intel Core i5-8300H bits: 64 type: MT MCP L2 cache: 8192 KiB 
           Speed: 800 MHz min/max: 800/4000 MHz Core speeds (MHz): 1: 800 2: 800 3: 800 4: 800 5: 800 6: 800 7: 801 8: 800 
Graphics:  Device-1: Intel driver: i915 v: kernel 
           Device-2: NVIDIA GP107M [GeForce GTX 1050 Mobile] driver: nouveau v: kernel 
           Display: x11 server: X.Org 1.20.3 driver: intel,nouveau unloaded: fbdev,modesetting,vesa resolution: 1920x1080~60Hz 
           OpenGL: renderer: Mesa DRI Intel UHD Graphics 630 (Coffeelake 3x8 GT2) v: 4.5 Mesa 18.3.1 

```

**Comment by davidjharder** [comment]
Old, appears to be an upstream drivers problem. Closing
