### ISSUE TITLE
Missing resolutions XPS 13 (T4967)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#7]
<div dir="rtl"><b>Jorge&nbsp;Aparicio</b>&nbsp;(<em>&#35;jorge.aparicio</em>),&nbsp;2017-11-06&nbsp;01:04:09&nbsp;UTC</div><br/>

On my XPS 13 with 3200x1800 display I  change to 1920x1080 on distributions for increased application compatibility with non hi-dpi supported applications. However, on Solus all other 16:9 aspect ratio resolutions are missing and I'm only provided with 4:3 aspect ratio resolutions for anything other than the default resolution.

**Comment by davidjharder** [comment]
Old. Closing
