### ISSUE TITLE
Cursor square artifacts using NVIDIA 415.25 (T7368)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#70]
<div dir="rtl"><b>Juan&nbsp;Carlos</b>&nbsp;(<em>&#35;Juankz</em>),&nbsp;2018-12-22&nbsp;15:28:10&nbsp;UTC</div><br/>

Hey guys. I have a GeForce GTX 1050 on a MSI laptop and sometimes when using the nvidia graphics card I get the following artifacts around my cursor. 

{F4251590}

Sometimes rebooting fix the issue,sometimes it doesn't. I don't know to help diagnose this issue. Usually  It's not a big issue for me since I use the nvidia card mainly to play games so the cursor is hidden. But sometimes I work on computer vision projects and it gets really annoying to work with. By the way I'm using solus budgie. Don't know if it happens with other DEs

**Comment by rav101** [comment]
Just to update,

Using Solus 4.4 updated to current and I don't see this issue either with or without Nvidia hardware drivers installed on my Dell G3.

All seems good on my end.

**Comment by TraceyC77** [comment]
Thanks for confirming. I'll go ahead and close this out. If the problem recurs, please open a  new issue.
