### ISSUE TITLE
AMD ROCm 5.5 Testing

### ISSUE THREAD

**Issue by GZGavinZhao** [getsolus/packages#701]
## HIP Tests

Insall `rocm-hip-devel` before testing anything.

### HIP-Examples

1. Clone the `rocm-5.5.x` branch of [HIP-Examples](https://github.com/ROCm-Developer-Tools/HIP-Examples/):
```
git clone https://github.com/ROCm-Developer-Tools/HIP-Examples.git --single-branch --branch rocm-5.5.x --depth 1
```
2. Run all examples! It's recommended that you also install `amdgpu_top` and monitor its output while running the examples.
```bash
cd <wherever you cloned HIP-Examples>
ROCM_PATH=/usr HIP_PATH=/usr DEVICE_LIB_PATH=/usr/lib64/amdgcn/bitcode CC=clang CXX=clang++ ./test_all.sh
```
3. All examples should compile and run successfully.

## OpenCL Tests

Install `rocm-opencl`, `clinfo` and `clpeak` before testing anything.

### clinfo

1. `clinfo` should work out of the box and should list your AMD hardware.
2. `rocm-clinfo` and `clinfo` should have roughly the same output. Say, if one detects an extra device than the other, then something fishy is going on.
3. `clpeak` will run a suite of tests. If this completes successfully, OpenCL has been verified as working on your AMD hardware.
4. For a more advanced test, install and open `blender`, select _Edit -> Preferences_, then select _System -> Cycles Render Devices -> HIP_ and ensure your GPU is selected with a checkmark :heavy_check_mark:. Then, download and unzip the [classroom](https://download.blender.org/demo/test/classroom.zip) benchmark and open it in blender with _File -> Open..._.
5. Ensure that the Render Render properties for \_mainScene has the settings below, then render the scene by pressing _F12_.
<img width="518" alt="blender-render-settings" src="https://github.com/getsolus/packages/assets/118045/9e7a89ba-3cd9-4cb1-bd9f-5b1cabe74828">

**Comment by ermo** [comment]
Tested and confirmed working on AMD RX Vega 64.

**Comment by GZGavinZhao** [comment]
All tests passed on AMD RX6600M (gfx1032, with/without gfx1030 emulation)

**Comment by HarveyDevel** [comment]
AMD RX7600 (gfx1102) fails on final section:

>[100%] Built target test_openmp_helloworld
info: running on device AMD Radeon RX 7600
Hello World... from OMP thread = 0
Hello World... from OMP thread = 10
Hello World... from OMP thread = 15
Hello World... from OMP thread = 11
Hello World... from OMP thread = 12
./test_all.sh: line 83: 41313 Segmentation fault      (core dumped) ./test_openmp_helloworld

journalctl
https://gist.githubusercontent.com/HarveyDevel/0a2efd7000020bbed397e721b6a8d9f8/raw/09d503cf4cecd5b62d3f3d46c89b456ea0dba8e7/journal.log

**Comment by GZGavinZhao** [comment]
> AMD RX7600 (gfx1102) fails on final section:
> 
> > [100%] Built target test_openmp_helloworld
> > info: running on device AMD Radeon RX 7600
> > Hello World... from OMP thread = 0
> > Hello World... from OMP thread = 10
> > Hello World... from OMP thread = 15
> > Hello World... from OMP thread = 11
> > Hello World... from OMP thread = 12
> > ./test_all.sh: line 83: 41313 Segmentation fault      (core dumped) ./test_openmp_helloworld
> 
> journalctl https://gist.githubusercontent.com/HarveyDevel/0a2efd7000020bbed397e721b6a8d9f8/raw/09d503cf4cecd5b62d3f3d46c89b456ea0dba8e7/journal.log

Thanks for the report! Well I guess this is why RDNA3 doesn't get official support until 5.7... Fortunately all of the HIP tests passed. I don't recall I've seen any package that explicitly requires only OpenMP, so I would call this a pass.

**Comment by ermo** [comment]
This works, closing.
