### ISSUE TITLE
llvm: transient build failures on the buildserver

### ISSUE THREAD

**Issue by davidjharder** [getsolus/packages#712]
`llvm` related builds often fail on the first try and succeed on a second attempt when building on the buildserver.

Collect logs and stuff here.

**Comment by ReillyBrogan** [comment]
The build server was running kernel 6.1.58, which was affected by a Zen4 issue that could generate illegal instructions when STIBP is disabled. I've updated it to 6.1.60, so I'm going to close this as _probably_ closed. We can re-open it if it happens again (at which point we need to capture logs).
