### ISSUE TITLE
request app podcast

### ISSUE THREAD

**Issue by giallorosso84** [getsolus/packages#728]
Good evening, we kindly ask you to create the file package for the application in the link provided
https://apps.kde.org/kasts/  (app named **kasts**, **used  for listen and add podcast**)
On your store there are some app podcast (gpodder, vocal), but this si thought for Kde.
Unfortunately I don't know how to package an executable file,otherwise I had done it.

Best regards**

**Comment by sheepman4267** [comment]
Hello!

Thank you for making this request! Unfortunately, this issue does not quite follow our [procedure for requesting a package](https://help.getsol.us/docs/packaging/procedures/request-a-package/). Please edit your issue to follow the linked template, so we can properly consider Kasts for inclusion. 

Thank you again for being involved in Solus. It's appreciated, and I hope you understand why this procedure is important in maintaining our software repository.
