### ISSUE TITLE
New solution to driver management on Plasma

### ISSUE THREAD

**Issue by sheepman4267** [getsolus/packages#732]
# The Problem
This issue exists because of #270.

One of the main blockers to fully eradicating python2 from Solus is the fact that eopkg is still using it. We have a functional port of eopkg in python3, but various other software which interfaces with eopkg is also written in python2. This other software must be either replaced or ported before we deploy the new version of eopkg. 

The two main user-facing blockers here are solus-sc and doflicky. On GNOME (and other GTK-based systems), both of these applications can be replaced with GNOME Software and a PackageKit backend for eopkg. However, on Plasma systems, we don't have a viable replacement for doflicky's hardware driver installation features. KDE Discover handles applications, but it cannot currently detect available hardware drivers.

I propose a two-stage solution to this problem:
# Stage One: Come up with a simple standalone replacement for doflicky
### Advantages:
- Should be fairly straightforward to do, as it's "just" a python2>python3 port

### Disadvantages:
- Won't work once we get to Solus 5
- "just" is a horrible word to use in software development
### Advantages:
- Will work on Solus 5 (once we have a packagekit backend for moss) should phase two take a Long Time
- Relies on the PackageKit API, which is much better understood by people not named Ikey than the eopkg/pisi one
- Uses (probably my) developer time to advance in a new technology rather than extend the use of an obsolete one

### Disadvantages:
- Could take longer
- I'm still not quite clear on what other features of LDM are actually a: functional right now and b: exposed in doflicky (meaning we need to come up with a new solution for those too, if we get rid of doflicky).

# Phase Two: Integrate driver management into Discover and upstream it
I proposed this in the "Brainstorm" section on KDE's forum, and [it got some traction with Nate Graham](https://discuss.kde.org/t/graphical-driver-management/6372). Unfortunately, I don't know C++ (yet). I plan to learn at least enough to implement these features, but I predict that taking too long to be a viable solution to our current python2 problem. It shouldn't be overly complex to implement, however, once I know a bit of C++. If anyone knows C++ and wants to work with me on this (or just do it), let's talk.

# Request
I'd like feedback both generally (do you think this plan sounds good?) and specifically on whether to start with stage one option A or B. I personally prefer B, but I would like to know what others think. Or, should we just give this whole two-stage thing up and work directly on the permanent solution? 

Please discuss!

**Comment by ermo** [comment]
Short term, we need doflicky + ldm working with the eopkg py2 stuff. So that's the major priority as this MUST work for the upcoming 4.5 release.

After that, we can port it to the eopkg py3 stuff with minimal effort and then have it working, which gives us unlimited runway.

And after _that_, we can look towards a future where it's a part of KDE.

That would be my assessment. The good thing about the above is that it will at least help build knowledge about the moving parts and how they fit togethere, when we _do_ reach the point of figuring out a solution that works with KDE.

**Comment by sheepman4267** [comment]
Correct. The Discover driver installation work solves this.
