### ISSUE TITLE
Broken cyrillic text encoding (T7757)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#74]
<div dir="rtl"><b>solusme</b>&nbsp;(<em>&#35;solusme</em>),&nbsp;2019-03-25&nbsp;16:30:26&nbsp;UTC</div><br/>

Hi there, 
I found this problem. 
I am on Souls Budgie, I use English and Cyrillic keyboard layouts.
When I create a simple note with Gedit and write in Cyrillic under the souls partition ext4, save, and after that copy the file on NTFS partition the letters in cyrillic are broken, they look unreadable like this - С‚РѕРІР° Рµ РїСЂРѕР±Р°.

how to recreate the problem:
1. open Gedit
2. copy then paste this text without the brackets: [this is a test - това е проба]  
3. save the file in Home/user/Documents, name it whatever you want 
4. copy the file on NTFS partition
5. open it
6. you should see: [this is a test - С‚РѕРІР° Рµ РїСЂРѕР±Р°]

This problem does not appear when a text file is created with Libra Office. I suppose a better encoding integration in the files. 
At first I thought that it is a problem of the Gedit and its encodng, but I tried this with a couple of more simple text editors and they gave the same bad result. The only program that made it well was Notepadqq, it shows cyrillic characters perfectly well, no matter on which partition the file is. I tested the same exercise in Kubuntu and everything is ok there, no problem with Gedit and other text programs.

I may be wrong, but I think that the problem is somewhere in Solus. Would you be so kind to check this out?

Best regards

Updated info:
---------------

The same issue occurs when: 
a simple note is created  with Gedit and writen in Cyrillic under the Souls partition ext4. 

how to recreate the problem:
1. open Gedit
2. copy then paste this text without the brackets: [this is a test - това е тест]  
3. save the file on the Desktop
4. right click with the mouse - copy
5. right click with the mouse - paste
6. open it
7. you should see: [this is a test - РЎвЂљР С•Р Р†Р В° Р Вµ Р С—РЎР‚Р С•Р В±Р В°]

This problem does not appear when a text file is created with Libra Office and Notepadqq. With Gedit and the other similar text editors the problem occurs. 

The same exercise tested in Kubuntu, Ubuntu and Solus Plasma and everything is ok there, no problem with Gedit and other text programs.

**Comment by davidjharder** [comment]
Old, no new info. Closing
