### ISSUE TITLE
Can't use Ibus input method in KDE/Qt app (T8191)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#75]
<div dir="rtl"><b>Dinh&nbsp;Tien&nbsp;Nam</b>&nbsp;(<em>&#35;dinhnamhihi</em>),&nbsp;2019-07-30&nbsp;09:31:58&nbsp;UTC</div><br/>

Hi Devs, I am recently testing Solus 4 Plasma Testing Edition, because i absolutely fall in love with KDE Plasma DE, super modern and lightweight, it work great on my machine, no problem after upgrade from 3.999 to 4.0. But one problem is known when typing Asian characters with Ibus or Fcitx in KDE/Qt app from using KDE Neon still happen in Solus Plasma, so i can't type Vietnamese in KDE/Qt app like Dolphin, Kwrite, Kate...but Firefox and Libre Office work fine. What can i do to type Vietnamese with Ibus engine (as i can't find a way to install Fcitx in Solus repo) in KDE/Qt app? because i really love the set of KDE default app. I read somewhere that is a package call "ibus-qt" need install to fix this bug, but i can't find a packafe like that in Solus repo. I need your help, please!

**Comment by TraceyC77** [comment]
Closing this as stale. If this is still an issue, it should probably be reported via bugs.kde.org
