### ISSUE TITLE
Tearing on video fullscreen (both youtube and netflix) on FF but not on Chrome (T2267)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#76]
<div dir="rtl"><b>Jose</b>&nbsp;(<em>&#35;usillos</em>),&nbsp;2017-01-21&nbsp;16:14:11&nbsp;UTC</div><br/>

I don't know if this is to be expected. I tried it in two different laptops. Since we ship FF by default, and a bunch of 'normals' will use their machine to watch video full screen... the tearing could send them running for the hills.

Why does it happen?

If unavoidable because reasons, maybe we should use chrome as default?

**Comment by ronnyfredriksen** [comment]
How can I redeem my Netflix Gavekort kr

**Comment by davidjharder** [comment]
Old, no new info. Closing
