### ISSUE TITLE
XFCE4 Papercuts

### ISSUE THREAD

**Issue by ZachBacon** [getsolus/packages#776]
This issue page is to track the current issues regarding the xfce brandings and packages.

- [ ] Currently we are missing network settings in the settings application
- [ ] Add slight customization for whisker menu

This list will expand with each report given as it's being tested.

**Depends on:**
- getsolus/packages/issues/1099
- getsolus/packages/issues/1289
- getsolus/packages/issues/1297 
- getsolus/packages/issues/1299
- getsolus/packages/issues/1302

**Comment by sheepman4267** [comment]
The default keyboard shortcut to open the applications menu is Alt+F1. That shortcut is still bound to `xfce4-popup-applicationsmenu`. Should probably be set to whisker menu out of the box. 

Also, I personally prefer to have the Super key open my applications menu- it seems from a forum thread (though I've never run it) that at least Manjaro's XFCE spin runs whisker menu and has the super key set to open it (as well as the default Alt+F1). I would love to see this as a default on Solus, as it would make the XFCE spin more familiar to existing users of other Solus editions which have this behavior already.

**Comment by ermo** [comment]
The default notification pop-up opens in the top right. It should probably open in the bottom right so it is near the panel?

**Comment by TraceyC77** [comment]
The app menu is missing the "Log Out" item that it has in other distros like Ubuntu.
Ex:See the screenshots in https://bytexd.com/how-to-install-xfce-desktop-or-xubuntu-in-ubuntu/

While the user also has the ability to click on their username to bring up the Log Out / Power menu, it's not very discoverable. Having it also in the menu makes it easier to find for users new to XFCE.

**Comment by ermo** [comment]
> The default notification pop-up opens in the top right. It should probably open in the bottom right so it is near the panel?

This has now been fixed now FWIW.

**Comment by brent111** [comment]
UPDATE:
for the hell of it, I installed gnome-web epiphany from the arch endeavour local (non-aur) repo and installed it in arch endeavour.
It froze the system as soon as it launched.
just like solus xfce repo and flatpak did. (just like solus budgie repo and flatpak versions did).

just from this alone I'd have to say my initial 'bug' may be **independent** of XFCE and may need to be disregarded.

**Comment by ermo** [comment]
@EbonJaeger Might it make sense to use this issue as the high-priority 4.6 issue, and then creating a separate issue for lower-priority 4.7 XFCE items?

**Comment by EbonJaeger** [comment]
I would rather issues all be individual issues; having things grouped together makes problems way harder to keep track of and find later.

**Comment by TraceyC77** [comment]
The remaining open issues are going to be deferred to 4.7 as they are low priority. Closing this issue.
