### ISSUE TITLE
libsignal-protocol-c: Package request

### ISSUE THREAD

**Issue by malfisya** [getsolus/packages#787]
### Homepage

https://github.com/signalapp/libsignal-protocol-c

### Why should this be included in the repository?

To include `dino`  #283 in the repository it requires new dependency which is `libsignal-protocol-c`. We have `python-axolotol` which is a port of `libsignal-protocol-java` but `dino` requires `libsignal-protocol-c`. Both of those project already archived last year.

### Are we allowed to redistribute it?

GPL-3.0 license 

### Who and how many users do you anticipate will use this software?

`dino` user will definitely need it. I already have recipe ready to PR if this is accepted

### Link to source archive file

https://github.com/signalapp/libsignal-protocol-c/archive/refs/tags/v2.3.3.tar.gz

**Comment by EbonJaeger** [comment]
As a quick note, if an accepted package needs another new package as a dependency, the dependency is implicitly accepted and does not require an inclusion request. 🙂

**Comment by malfisya** [comment]
https://github.com/getsolus/packages/pull/788
