### ISSUE TITLE
Wifi connection takes a long time to establish at startup (T6867)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#79]
<div dir="rtl"><b>Radoslaw&nbsp;Jurga</b>&nbsp;(<em>&#35;rjurga</em>),&nbsp;2018-08-31&nbsp;06:08:36&nbsp;UTC</div><br/>

When I start my laptop, after I login to the Plasma session, wifi takes a long time to connect to the saved network. I didn't measure exactly, but it seems to be around 15 seconds. Once it is connected, if I disconnect, and manually reconnect, it is almost instantaneous.

Before I moved to Plasma I had Budgie, and it did not have this issue, wifi was connecting fast at startup. I have another laptop with Budgie currently, configured with the same saved wifi network, and it connects almost instantly at login.

The only reason this is bothering is because I have to wait these 15 seconds before launching Firefox. If I launch it before wifi is connected, it will not find any webpage even once the connection is established.

I installed Solus using the Plasma iso. My wireless card is the Intel 7265. Let me know if I can do anything specific to provide debug information.

**Comment by ReillyBrogan** [comment]
Closing as upstream issue.
