### ISSUE TITLE
Driverless printing adds printers from all over my apartment (T4769)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#8]
<div dir="rtl"><b>Tristan&nbsp;Partin</b>&nbsp;(<em>&#35;tristan957</em>),&nbsp;2017-10-15&nbsp;07:04:09&nbsp;UTC</div><br/>

Pretty sure the driverless printers update has started to add printers from my apartment all willy nilly. Is there a setting to turn this off?

**Comment by davidjharder** [comment]
Who doesn't like extra printing? Also, last updated 2017.
