### ISSUE TITLE
strange journald entry (T8015)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#81]
<div dir="rtl"><b>Adam</b>&nbsp;(<em>&#35;DooshPastesh</em>),&nbsp;2019-06-04&nbsp;14:38:47&nbsp;UTC</div><br/>

I have been running successfully Solus Budgie for some time. From time to time I check journald (which is clean usually). Some time ago strange entry occured:

```
maj 31 21:34:36 plasma [613]: failed to execute '/usr/bin/sh' '/usr/bin/sh -c '/usr/bin/setfacl -m g:lirc:rw /dev/bus/usb/002/001 2>/dev/null || :'': No such file or directory
```
So, I've decided to try Plasma. Fresh Install, update, and the same error occurs.

Firstly I asked about this on [Solus forum](https://discuss.getsol.us/d/1270-strange-journald-entry). There are few details more.

**Comment by ReillyBrogan** [comment]
Closing as this does not appear to be an issue anymore.
