### ISSUE TITLE
pitivi failed to launch 

### ISSUE THREAD

**Issue by malfisya** [getsolus/packages#818]
### Summary

pitivi failed to launch from launcher and terminal. It says `matplotlib` not found in system. I already verified that `matplotlib` is indeed installed. 

### Steps to reproduce

1. Install `pitivi`
2. Run `pitivi` via launcher or via terminal

### Expected result

pitivi launched

### Actual result

via terminal 
```
alfisya@dev-solus ~ $ pitivi 

** (gst-plugin-scanner:40667): CRITICAL **: 10:23:14.252: Couldn't g_module_open libpython. Reason: /usr/lib64/libpython3.10.so: cannot open shared object file: No such file or directory
ERROR - The following hard dependencies are unmet:
==================================================
- matplotlib not found on the system
Missing soft dependency:
- cvtracker GStreamer element not found on the system
    -> enables object tracking
Missing soft dependency:
- librosa not found on the system
    -> enables beat detection functionality
```

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

GNOME

### System details

# System Details Report
---

## Report details
- **Date generated:**                              2023-11-13 10:54:52

## Hardware Information:
- **Hardware Model:**                              (null)
- **Memory:**                                      16,0 GiB
- **Processor:**                                   Intel® Core™ i5-3570K × 4
- **Graphics:**                                    AMD Radeon™ RX 550 / 550 Series
- **Disk Capacity:**                               752,2 GB

## Software Information:
- **Firmware Version:**                            4.6.5
- **OS Name:**                                     Solus 4.4 Harmony
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               45.1
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.5.11-263.current

### Other comments

I have tried to rebuild `pitivi` and `matplotlib` to no effect

**Comment by joebonrichie** [comment]
Do you have `python3` and `matplotlib` installed? They should be installed as part of pitivi automatically?

**Comment by malfisya** [comment]
Yes, i can confirm both `python3` and `matplotlib` are installed. `matplotlib` is pulled automatically when installing `pitivi`. `python3` is already in system before that

**Comment by algent-al** [comment]
It is missing `scipy`.

**Comment by malfisya** [comment]
Unfortunately, this still doesn't fix it. `scipy` is installed but still spits out the same error. I already did `eopkg it --reinstall pitivi`, still same error. Then I did `eopkg rm pitivi` , `eopkg rmo`, then `eopkg it pitivi`, still same error.

**Comment by algent-al** [comment]
Please check `pitivi` again after latest updates.

**Comment by malfisya** [comment]
Just installed again, still same error. Is there anymore i can do to help troubleshoot this?

**Comment by ReillyBrogan** [comment]
e1481aeeb7ba7e64a298344b5fa32444e4ed7524

**Comment by malfisya** [comment]
Nice, confirmed working. Thank you!
