### ISSUE TITLE
Latest `shadow` package update broke Podman rootless

### ISSUE THREAD

**Issue by chax** [getsolus/packages#825]
### Summary

PR #420 broke Podman rootless.
Similar problem is reported on podman repo: https://github.com/containers/podman/issues/2788

### Steps to reproduce

Install podman and setup subuid and subgid for rootless Podman (see [this guide](https://github.com/containers/podman/blob/main/docs/tutorials/rootless_tutorial.md)).

Try to run any container using Podman in rootless mode (use `--userns=keep-id` argument):
`podman run -it --userns=keep-id docker.io/library/busybox:latest /bin/ash`

### Expected result

![Screenshot_20231115_125225](https://github.com/getsolus/packages/assets/632945/54f908d1-8201-451c-9a75-a3f2ced89186)

### Actual result

![Screenshot_20231115_130424](https://github.com/getsolus/packages/assets/632945/ebda72e0-d4b8-400d-bd02-c3c896761763)

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

Plasma

### System details

Operating System: Solus 4.4
KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.110.0
Qt Version: 5.15.11
Kernel Version: 6.5.11-263.current (64-bit)
Graphics Platform: X11
Processors: 12 × Intel® Core™ i7-9750H CPU @ 2.60GHz
Memory: 31.2 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 2060/PCIe/SSE2
Manufacturer: Dell Inc.
Product Name: G5 5590

**Comment by ReillyBrogan** [comment]
@chax FYI I was able to add xattr support to eopkg and so switched shadow back to using file capabilities. Note that eopkg continues to run with the old code when it updates itself, and that old code won't be able to apply the xattr properties if the shadow package with file caps is updated in the same transaction that updates eopkg. Once you do your next update you'll want to do the following to make sure file caps on the shadow package are applied:
```
sudo eopkg it shadow --reinstall
```
