### ISSUE TITLE
Tracker Issue: Add well-integrated support for 16x32 terminus font from bootloader to systemd-controlled virtual consoles

### ISSUE THREAD

**Issue by ermo** [getsolus/packages#826]
This issue describes the path towards giving users a good ootb experience for high-resolution laptops and displays, where the current default 8x16 font is much too small if the user is ever forced to drop to a linux virtual console.

The moving parts that need to be individually configured to support the terminus font:
- Grub  (boot menu configuration, incl. display size considerations)
- Kernel (boot-time messages before DRM KMS kicks in and takes over)
  - set `CONFIG_FONT_TER16x32=y`
- Kernel initramfs (after DRM KMS kicks in and takes over)
- Root fs (installing the package by default in ISOs and/or as a rundep of e.g. systemd via /etc/vconsole.conf or its stateless/hermetic-usr equivalent)

Depends on PR #824

**Comment by ReillyBrogan** [comment]
Self-assigned for kernel bits and bobs

**Comment by ReillyBrogan** [comment]
Seems to be working in draft 6.6 kernel.

**Comment by ermo** [comment]
@EbonJaeger:

Could you perhaps figure out how to instruct calamares to add/modify the installed version of `/etc/vconsole.conf` so it contains the following lines:

```
# 'ls /usr/share/consolefonts/ter-v*' will show available unicode font sizes
FONT=ter-v32b
```

**Comment by ermo** [comment]
@ReillyBrogan 

The only thing left is for you to get the kernel initrds to reflect this change and the issue can be closed as resolved.
