### ISSUE TITLE
ghc 9.2.8 rel 11 FTBFS

### ISSUE THREAD

**Issue by joebonrichie** [getsolus/packages#827]
### Summary

Our current version of `ghc` doesn't build

```
"inplace/bin/mkdirhier" utils/hsc2hs/dist/build/tmp//.
  HC [stage 0] libraries/template-haskell/dist-boot/build/Language/Haskell/TH.o
  HC [stage 0] libraries/template-haskell/dist-boot/build/Language/Haskell/TH/Lib.o
  HC [stage 0] libraries/template-haskell/dist-boot/build/Language/Haskell/TH/Ppr.o
  HC [stage 0] libraries/template-haskell/dist-boot/build/Language/Haskell/TH/PprLib.o
  HC [stage 0] libraries/template-haskell/dist-boot/build/Language/Haskell/TH/Quote.o
<command line>: error: directory portion of "libraries/template-haskell/dist-boot/build/Language/Haskell/TH.o" does not exist (used with "-o" option.)
<command line>: error: directory portion of "libraries/template-haskell/dist-boot/build/Language/Haskell/TH/Ppr.o" does not exist (used with "-o" option.)
<command line>: error: directory portion of "libraries/template-haskell/dist-boot/build/Language/Haskell/TH/Lib.o" does not exist (used with "-o" option.)
<command line>: error: directory portion of "libraries/template-haskell/dist-boot/build/Language/Haskell/TH/PprLib.o" does not exist (used with "-o" option.)
<command line>: error: directory portion of "libraries/template-haskell/dist-boot/build/Language/Haskell/TH/Quote.o" does not exist (used with "-o" option.)
libraries/hpc/ghc.mk:3: libraries/hpc/dist-boot/build/.depend-v.haskell: No such file or directory
```

### Steps to reproduce

Build GHC

### Expected result

Ghc to build

### Actual result

ghc doesn´t build

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

Other

### System details

N/A

**Comment by GZGavinZhao** [comment]
Migrating to the Hadrian build system fixes this, but this also means a rebuild of the Haskell stack plus a small change to the Haskell ypkg macro.

**Comment by ReillyBrogan** [comment]
Appears to be [this](https://gitlab.haskell.org/ghc/ghc/-/issues/21188) issue which indicates that it's not possible to build ghc 9.2.x with 9.2.x using the make build system. It was never fixed upstream because they removed the make build system in 9.4.x. It should be possible to re-bootstrap with 8.10, which could be a temporary solution until we move to a later version.

**Comment by GZGavinZhao** [comment]
I figured out the issue, this requires a change in the YPKG Haskell macros. Currently building the stack to see if anything blows up.
