### ISSUE TITLE
nushell

### ISSUE THREAD

**Issue by olymk2** [getsolus/packages#830]
### Homepage

https://www.nushell.sh/

### Why should this be included in the repository?

Give a move modern shell interface, treats results as data and shows in table format amongst other things

### Are we allowed to redistribute it?

MIT

### What kind of user will use this package, and how many users do you think will use this package?

Power users / developers no idea on number of users

### Link to source archive file

https://github.com/nushell/nushell/archive/refs/tags/0.87.0.tar.gz

**Comment by olymk2** [comment]
I have already got a local version of this packaged so can push it as a PR if accepted

**Comment by EbonJaeger** [comment]
Approved. Have at it! :slightly_smiling_face:

**Comment by ReillyBrogan** [comment]
Note that this will need a bump to the pam package to add it to the list of shells.

**Comment by olymk2** [comment]
https://github.com/getsolus/packages/tree/main/packages/p/pam Looking here I don't see a list of shells what am i missing ?

**Comment by ReillyBrogan** [comment]
It's in the `files/shells` file in that folder.

**Comment by olymk2** [comment]
Sorry @ReillyBrogan I should have done a better checked, I did not have the file locally until i pulled from upstream so guess that's why I did not see it, but I should have spotted it on github, anyway PR has been created now.

**Comment by HarveyDevel** [comment]
Resolved by #974
