### ISSUE TITLE
JMESPath

### ISSUE THREAD

**Issue by Achilleshiel** [getsolus/packages#831]
### Homepage

https://jmespath.org

### Why should this be included in the repository?

This is a dependency for the `json_query` function in Ansible.

### Are we allowed to redistribute it?

MIT

### What kind of user will use this package, and how many users do you think will use this package?

I guess ~10% of the Ansible users. 

### Link to source archive file

https://github.com/jmespath/jmespath.py/archive/refs/tags/1.0.1.tar.gz

**Comment by silkeh** [comment]
Accepted as a dependency of Ansible.

**Comment by silkeh** [comment]
Resolved by #833.
