### ISSUE TITLE
Lightdm/Slick Ignoring Conf Files (T8545)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#84]
<div dir="rtl"><b>Bryan&nbsp;Moore&nbsp;</b>&nbsp;(<em>&#35;moore-bryan</em>),&nbsp;2019-12-14&nbsp;17:32:45&nbsp;UTC</div><br/>

Issues reported on [lightdm](https://github.com/canonical/lightdm/issues/100) and [slick-greeter](https://github.com/linuxmint/slick-greeter/issues/144); devs there seem to think this is a solus issue.

**Comment by ermo** [comment]
@EbonJaeger For some odd reason I have this vague recollection that you might have hit this bug and then fixed it? Do you remember?

**Comment by EbonJaeger** [comment]
It sounds very much like this was a user configuration problem. Slick Greeter apparently thought it was a LightDM problem. Either way, no, I've never run into this, and this likely should have been closed years ago.

**Comment by ermo** [comment]
Closing as a user configuration problem, as both upstream issues have been closed.
