### ISSUE TITLE
Lector Not Loading

### ISSUE THREAD

**Issue by brucetheelephant** [getsolus/packages#848]
### Summary

When I try to run Lector (from the Konsole) this is what I'm getting:

> pymupdf is not installed. Will be unable to load PDFs.
Locale: en_US (No translations found)
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/lector/models.py", line 127, in data
    return pie_chart.pixmapper(
  File "/usr/lib/python3.10/site-packages/lector/resources/pie_chart.py", line 102, in pixmapper
    consider_read_at = consider_read_at / 100
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
Aborted (core dumped)

### Steps to reproduce

1. Install Lector
2. Run Lector

### Expected result

I was expecting that Lector would load.

### Actual result

Lector did not load.

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Plasma

### System details

Operating System: Solus 4.4
KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.110.0
Qt Version: 5.15.11
Kernel Version: 6.5.11-263.current (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i5-10300H CPU @ 2.50GHz
Memory: 7.6 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2
Manufacturer: Micro-Star International Co., Ltd.
Product Name: GF65 Thin 10SDR
System Version: REV:1.0

**Comment by algent-al** [comment]
@brucetheelephant please run `pip3 check` to detect any missing python module.

**Comment by ReillyBrogan** [comment]
I was not able to reproduce this on a Solus Plasma VM running stable in a Plasma Wayland session. I fully updated the system and installed lector and it started right up. If this is still an issue you'll need to provide the backtrace for the segfault, otherwise we can't really debug this.

**Comment by ReillyBrogan** [comment]
So once you see the issue happen run `sudo journalctl -b0 --grep "dumped core"` in a terminal and then paste the output here. You'll probably need to install some more packages to ensure that it's readable but we can tell you what ones to paste once we see the initial stack trace.

**Comment by Justinzobel** [comment]
I just installed lector and it did load. I got an error though in the terminal `pymupdf is not installed. Will be unable to load PDFs.`. Furthermore, I think this can be closed and if necessary a new bug filed to add `pymupdf` into the repository if PDF loading is desired in this app.

**Comment by ermo** [comment]
@brucetheelephant Can you still reproduce this?
