### ISSUE TITLE
torbrowser-launcher based TBB has a persistent GUI elements ghosting issue (T8320)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#85]
<div dir="rtl"><b>Hazem</b>&nbsp;(<em>&#35;hyphens</em>),&nbsp;2019-09-07&nbsp;13:44:21&nbsp;UTC</div><br/>

I'm now on the latest torbrowser-launcher and TBB release (updated the entire system right before writing this), and it's been an issue for a handful of months now that every time I launch the program the GUI does this hard to describe ghosting behaviour:

{F5123301}
{F5123303}

Elements overlay each other and persist as the GUI changing, building on top of each other to the point where they're incomprehensible after a few minutes of use.

Things I tried:
- changing GTK theme back to default
- trying a fresh user profile with no settings modified
- trying to remove the launcher program + any related data as well as TBB then reinstalling

**Comment by davidjharder** [comment]
Old, no new info. Closing
