### ISSUE TITLE
Notifications about old print jobs (T5044)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#86]
<div dir="rtl"><b>michael</b>&nbsp;(<em>&#35;landrykid</em>),&nbsp;2017-11-16&nbsp;08:42:12&nbsp;UTC</div><br/>

I've had multiple challenges printing in other distros, but it "just works" in Solus.  Great job!

However, a few times I've come back to my computer and gotten notified that successful print jobs from a few days ago had failed.  Then I get a notified that my printer was installed.  I think the failure notifications mention cups.  (I have an HP consumer inkjet.)

Please let me know if you need additional information.

Update:  This occurred again today and there was no cups mention.  I think losing and regaining wi-fi connectivity might be a catalyst.

**Comment by davidjharder** [comment]
Old as dirt. Closing
