### ISSUE TITLE
Pioneer Space Sim (pioneer) is out-of-date

### ISSUE THREAD

**Issue by Web-eWorks** [getsolus/packages#868]
### Name

Pioneer Space Sim

### Version

20230203

### Link to the release notes or announcement.

https://github.com/pioneerspacesim/pioneer/releases/tag/20230203

### Other comments

Since the last version packaged in the Solus repositories, the Pioneer Space Sim team has cut two yearly releases. The semi-official annual release date is February 3rd, if that helps with keeping the packaged version up to date.

Additionally, the `package.yml` configuration for Pioneer specifies a build-time dependency on `lua-5.1` - to the best of my knowledge, we don't bundle or require Lua 5.1 for any of our build configurations and the `USE_SYSTEM_LIBLUA` CMake option would be looking for Lua 5.2 if specified.

**Comment by joebonrichie** [comment]
Thanks for the report, we don't have a maintainer for pioneer.

I'll subscribe the to releases and try to keep it up to date in the mean time.
