### ISSUE TITLE
KDE plasma translation for print dialog: half english/half french (T7955)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#87]
<div dir="rtl"><b>Claude&nbsp;Durocher</b>&nbsp;(<em>&#35;clauded</em>),&nbsp;2019-05-13&nbsp;15:19:33&nbsp;UTC</div><br/>

Print dialog in KDE Plasma are not fully translated:

https://i.imgur.com/rtJffrD.png

**Comment by Justinzobel** [comment]
@clauded as this is a translation issue it's not something Solus can influence. Please report this at https://bugs.kde.org if it is still an issue.
