### ISSUE TITLE
Auto login is on but still prompted password

### ISSUE THREAD

**Issue by malfisya** [getsolus/packages#876]
### Summary

A few users on forum report that autologin is turned on but still prompted password on budgie desktop. https://discuss.getsol.us/d/9995-mate-login

### Steps to reproduce

1. Turned on autologin 
2. Reboot 

### Expected result

Successfully login to session without prompted to fill password (except for keyring)

### Actual result

Prompted to fill password

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Budgie

### System details

Budgie

### Other comments

I can't reproduce this on KDE VM and my GNOME machine

**Comment by EbonJaeger** [comment]
If I remember correctly, auto-login is handled by Accounts Service on Budgie; probably MATE, too. The Control Center just calls out to AccountsService to turn it on or off: https://github.com/BuddiesOfBudgie/budgie-control-center/blob/main/panels/user-accounts/cc-user-panel.c#L725-L749

Might be a good first place to look.

**Comment by malfisya** [comment]
Possible solution : https://discuss.getsol.us/d/1979-automatic-login-stopped-working-after-solus-updates

**Comment by ReillyBrogan** [comment]
GDM/LightDM/SDDM are all working now
