### ISSUE TITLE
Wrong keyboard layout in sddm if user is not logged in  (T6583)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#88]
<div dir="rtl"><b>Fabio</b>&nbsp;(<em>&#35;livingsilver94</em>),&nbsp;2018-06-26&nbsp;12:28:33&nbsp;UTC</div><br/>

sddm keyboard layout is set to ANSI (I think. `SHIFT+3` gives `#`) if user is not logged in. Otherwise it's fine, for example when you wake the screen or the whole PC up from sleeping.
Logging out resets the layout to ANSI.
My layout is UK-extended.

**Comment by davidjharder** [comment]
See similar issue #128
