### ISSUE TITLE
Not able to login as a root via tty

### ISSUE THREAD

**Issue by presianbg** [getsolus/packages#882]
### Summary

Hi,

After the[ Week 46 Sync ](https://discuss.getsol.us/d/9984-sync-updates-for-week-46-2023/55), looks like I'm not able to login as `root` from a tty.

### Steps to reproduce

1. Login to Budgie DE;
2. Press `CTRL` + `ALT` +`F5`
3. On the prompt type `root` for a user and you password;
4. It won't let you in despite the correct password.

### Expected result

It should be possible to login as `root` via tty, 

### Actual result

`Login incorrect` 

and this are the relevant records from journalctl:

```
Nov 24 16:11:07 solusbook-py login[69717]: FAILED LOGIN 1 FROM tty5 FOR root, Authentication failure
Nov 24 16:11:10 solusbook-py login[69717]: pam_faillock(login:auth): User unknown
Nov 24 16:11:11 solusbook-py login[69717]: pam_unix(login:auth): check pass; user unknown
Nov 24 16:11:11 solusbook-py login[69717]: pam_unix(login:auth): authentication failure; logname=LOGIN uid=0 euid=0 tty=/dev/tty5 ruser= rhost=
Nov 24 16:11:11 solusbook-py login[69717]: pam_faillock(login:auth): User unknown
```

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Budgie

### System details

```
OS: Solus x86_64 
Host: HP EliteBook 840 G5 
Kernel: 6.5.11-263.current 
Uptime: 1 day, 4 hours, 33 mins 
Packages: 2050 (eopkg) 
Shell: zsh 5.9 
Resolution: 1920x1080, 1920x1080, 1920x1080 
DE: Budgie 10.8.2 
WM: Mutter(Budgie) 
Theme: Sweet-Dark-v40 [GTK2/3] 
Icons: BeautyLine [GTK2/3] 
Terminal: tilda 
CPU: Intel i5-8250U (8) @ 3.400GHz 
GPU: Intel UHD Graphics 620 
Memory: 11166MiB / 31475MiB 
```

### Other comments

Trying to authenticate as `root` from my current user account with `su root` works OK.

**Comment by ReillyBrogan** [comment]
Can't reproduce. On a Solus VM I added a password to the root account with `sudo passwd` and then I was able to login just fine through another TTY. Please check all of the following:
- The root user has a valid shell: `cat /etc/passwd` and then compare with `cat /etc/shells` (if present) or `cat /usr/share/defaults/etc/shells` (if `/etc/shells` doesn't exist).
- The root user has a password set.

Root login will not work if either condition is false.

**Comment by ReillyBrogan** [comment]
> On the prompt type root for a user and you password

I notice you said `you` here, perhaps you are saying `your`? If by "your" you mean the password of the non-root user then that should not work. `root` needs a separate password set.

**Comment by presianbg** [comment]
Yes, it's a typo... sorry, should be `your`.
And yes, I mean the `root` password, which is different from the one for my `user` account.

```
sudo cat /etc/passwd | grep root                                                                                                                                                                
root:x:0:0:root:/root:/bin/bash
```
my `/etc/shells` contained only `zsh`. After adding `bash` and switching to `tty` the root login works again!

Many thanks.

**Comment by ReillyBrogan** [comment]
FWIW if you're fully updated you can actually just delete `/etc/shells`. We have a vendor version of that file at `/usr/share/defaults/etc/shells` which will be used if there is no `/etc/shells` present. That version is kept updated by us and is guaranteed to always work no matter what changes we make to the rest of the system.
