### ISSUE TITLE
Kernel Panic on Asus M2N4-SLI Motherboard (T4862)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#89]
<div dir="rtl"><b>Burt</b>&nbsp;(<em>&#35;evilrobot</em>),&nbsp;2017-10-24&nbsp;20:43:25&nbsp;UTC</div><br/>

As of Kernel 4.13.5-24 a Kernel Panic is now prevents Solus from booting on the Asus M2N4-SLI Motherboard.

Unfortunately when I add apic=debug to the Kernel line in Grub and try booting it just shows the Kernel panic, and when I add noapic it just shows a black screen with a blinking cursor.

The last working Kernel was 4.12.14-21 and currently the LTS Kernels still work. As of this writing I am currently using LTS Kernel 4.9.57-53.

When I boot using Kernel 4.12.14-21 or the LTS Kernel and run //'dmesg'// I get the following output.
```
[    0.026000] ..MP-BIOS bug: 8254 timer not connected to IO-APIC
[    0.026000] ...trying to set up timer (IRQ0) through the 8259A ...
[    0.026000] ..... (found apic 0 pin 0) ...
[    0.028000] ....... failed.
[    0.028000] ...trying to set up timer as Virtual Wire IRQ...
[    0.028000] ..... failed.
[    0.028000] ...trying to set up timer as ExtINT IRQ...
[    0.038092] ..... works.
```
At least this shows what was being done before with the //MP-BIOS bug: 8254 timer not connected to IO-APIC//, in order for the Kernel to boot successfully.

**Comment by davidjharder** [comment]
Old, no new info, closing
