### ISSUE TITLE
Skullgirls (native Linux title) - broken with linux-steam-integration on (T8537)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#90]
<div dir="rtl"><b>Michał&nbsp;Jabłoński</b>&nbsp;(<em>&#35;Junglist</em>),&nbsp;2019-12-11&nbsp;11:23:32&nbsp;UTC</div><br/>

Skullgirls works with lsi-off, but it doesn't launch with linux-steam-integration on. To be precise, the game window doesn't open, it instead spawns as a background zombie process.
{F5417542}
{F5417537}

**Comment by davidjharder** [comment]
We now set native runtime by default. Closing
