### ISSUE TITLE
Broadcom driver isn't finding card (T3988)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#91]
<div dir="rtl"><b>Paul</b>&nbsp;(<em>&#35;old_nerd</em>),&nbsp;2017-06-29&nbsp;10:08:35&nbsp;UTC</div><br/>

Despite the Broadcom Limited BCM4312 802.11b/g LP-PHY being detected in my Old HP 6735s laptop [inxi -Fc 0] It's not picking up my wireless signal.  

Wireless works under Mint XFCE and Ubuntu Mate - so the hardware is ok - installed Broadcom IEE 802 ...... 6.30.223.271 (as per hardware driver DoFlicky recommendation)

Rebooted and still no joy. All other updates installed.

PS: FIRST time reporting a bug - I assigned it to myself - is this in error?  Is there more information I should be giving?

**Comment by davidjharder** [comment]
Old, no new info. Closing
