### ISSUE TITLE
Can't change language (T7359)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#92]
<div dir="rtl"><b>Yurizal&nbsp;Susanto</b>&nbsp;(<em>&#35;yursan9</em>),&nbsp;2018-12-21&nbsp;10:41:35&nbsp;UTC</div><br/>

When I tried to change my language from English to another language, it's always fail.
After restart, everything is still in English, but the Language setting was changed to chosen language.

{F4248385}

**Comment by TraceyC77** [comment]
Closing this issue due to age and lack of updates. If this is still an issue for anyone, please open a new bug on our tracker. 
There have been many updates to Budgie since the last activity in this issue, the problem is likely resolved.
