### ISSUE TITLE
OnlyOffice

### ISSUE THREAD

**Issue by sivajipro** [getsolus/packages#923]
### Homepage

https://www.onlyoffice.com/desktop.aspx

### Why should this be included in the repository?

OnlyOffice is much better than libreoffice when it comes about compatibility with MicrosoftOffice.

### Are we allowed to redistribute it?

ONLYOFFICE Desktop Editors is licensed under the GNU Affero Public License, version 3.0.

### What kind of user will use this package, and how many users do you think will use this package?

Civil

### Link to source archive file
https://github.com/ONLYOFFICE/DesktopEditors

**Comment by ReillyBrogan** [comment]
You can't just say "No response" for "Are we allowed to distribute it?". Don't just punt this over to Solus maintainers, if you want this in the repos you're going to need to do proper legwork to ensure that we can _actually have it in the repos_.

**Comment by infinitymdm** [comment]
From the linked repo, the license appears to be GNU AGPL 3.0 or later. I'd potentially be interested in packaging this if there's a significant file size reduction compared to the flatpak.

**Comment by sivajipro** [comment]
> You can't just say "No response" for "Are we allowed to distribute it?". Don't just punt this over to Solus maintainers, if you want this in the repos you're going to need to do proper legwork to ensure that we can _actually have it in the repos_.

Sorry. Edited.

**Comment by ReillyBrogan** [comment]
So, reading the text of the license very closely I note that it does not grant use of the OnlyOffice trademarks. We'd need to call the compiled package something else, and strip those trademarks out of the build completely to comply with the license. That seems problematic frankly.

**Comment by infinitymdm** [comment]
Yeah, that's consistent with my reading and my limited understanding of trademark fair use. Not only does the license decline to grant use of trademarks, it also requires us to use the OnlyOffice logo - so this looks to be a no-go.

**Comment by malfisya** [comment]
According to [this](https://www.onlyoffice.com/license-faq.aspx), It **requires us** to use OnlyOffice logo. 

> Pursuant to Section 7 § 3(e) we decline to grant you any rights under trademark
> law for use of our trademarks.

But this sentence in the license contradicted it(?). I don't speak legalese. FWIW, only a few distro that distribute this package : Manjaro, LigurOS, Gentoo, NixOS, and PCLinuxOS. When Fedora and Ubuntu are not doing it, I think there is a reason. Then again, Flathub has it.

**Comment by infinitymdm** [comment]
> Then again, Flathub has it.

Flathub has it because OnlyOffice provides that packaging. I think our users are just going to have to get it from there as well.

**Comment by infinitymdm** [comment]
See also this stack exchange thread: https://opensource.stackexchange.com/questions/9481/is-onlyoffice-restricting-our-freedom-with-their-faq-agpl-v3

My understanding is the only way we could distribute this is by forking and removing all the branding, and if we miss something that still leaves us potentially liable for a trademark violation. People should just get it from Flathub.

This seems kinda shady IMO. OnlyOffice should probably make these restrictions a bit clearer, and probably could have made some better choices when licensing their products.

**Comment by ReillyBrogan** [comment]
> Then again, Flathub has it.

If you check the Flatpak build recipe for it it's just downloading the official binaries and extracting them into the flatpak overlay. 

> This seems kinda shady IMO. OnlyOffice should probably make these restrictions a bit clearer, and probably could have made some better choices when licensing their products.

I mean, it is open source, it's just not as open source as we're used to. They keep it open source so that they can receive contributions and fixes from people interested in doing so, but they don't want someone to download unofficial binaries with their branding and come to them for support. This is better than being completely proprietary and source-unavailable at least.

> FWIW, only a few distro that distribute this package : Manjaro, LigurOS, Gentoo, NixOS, and PCLinuxOS

I checked a few of these and they're all just redistributing the binary files.
