### ISSUE TITLE
Keyring pop-up always present after user login

### ISSUE THREAD

**Issue by davfiocchi** [getsolus/packages#925]
### Summary

I am facing an issue related to Keyring after the latest `eopkg upgrade`.

When I log into the system using my default account, a Keyring pop-up always shows up asking for the password to unlock Keyring.
Also this message is present in the pop-up: "_The login keyring did not get unlocked when you logged into your computer_".
The keyboard focus seems to be locked on the text field to input the password and I cannot do much with keyboard only.
I can move the mouse freely, no issues with that.

I've never used actively the Keyring, nor I've changed its password.
The Keyring password matches the one that I use to login with my default account on this computer.

About my environment:
- I do not have autologin enabled.
- I do have a Google account regularly connected but the prompt on the pop-up doesn't seem to be related to my online account.
- I'm using Solus Budgie
- I'm using lightdm as login manager

### Steps to reproduce

1. Power on the computer
2. Log into the system with my default account using graphical interface

### Expected result

The Keyring pop-up should not appear
Keyring should be unlocked as the login procedure succeeds

### Actual result

The Keyring pop-up appears

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Budgie

### System details

Budgie Version: 10.8.2
OS Name: Solus 4.4 Harmony
OS Type: 64-bit
Windowing System: X11
Kernel Version: Linux 6.5.11-263.current

### Other comments

If I recall correctly, I've seen this issue for the first time on Saturday 2023-11-25 after doing `eopkg upgrade`.

The previous eopkg upgrade has been done on Saturday 2023-11-11 and there were no issues with that.

**Comment by ReillyBrogan** [comment]
Can I get the output of the command `sudo journalctl -b0 | grep pam`? And also `eopkg li | grep kwallet`?

**Comment by davfiocchi** [comment]
Here's the output of `sudo journalctl -b0 | grep pam`:
```
nov 28 20:21:05 dave-os lightdm[826]: pam_unix(lightdm-greeter:session): session opened for user lightdm(uid=620) by (uid=0)
nov 28 20:21:05 dave-os (systemd)[831]: pam_warn(systemd-user:setcred): function=[pam_sm_setcred] flags=0x8002 service=[systemd-user] terminal=[] user=[lightdm] ruser=[<unknown>] rhost=[<unknown>]
nov 28 20:21:05 dave-os (systemd)[831]: pam_unix(systemd-user:session): session opened for user lightdm(uid=620) by lightdm(uid=0)
nov 28 20:21:09 dave-os lightdm[826]: pam_unix(lightdm-greeter:session): session closed for user lightdm
nov 28 20:21:09 dave-os lightdm[894]: pam_unix(lightdm:session): session opened for user dave(uid=1000) by dave(uid=0)
nov 28 20:21:09 dave-os (systemd)[925]: pam_warn(systemd-user:setcred): function=[pam_sm_setcred] flags=0x8002 service=[systemd-user] terminal=[] user=[dave] ruser=[<unknown>] rhost=[<unknown>]
nov 28 20:21:09 dave-os (systemd)[925]: pam_unix(systemd-user:session): session opened for user dave(uid=1000) by dave(uid=0)
nov 28 20:21:19 dave-os (sd-pam)[832]: pam_warn(systemd-user:setcred): function=[pam_sm_setcred] flags=0x8004 service=[systemd-user] terminal=[] user=[lightdm] ruser=[<unknown>] rhost=[<unknown>]
nov 28 20:22:21 dave-os sudo[2337]: pam_unix(sudo:session): session opened for user root(uid=0) by dave(uid=1000)
```

I didn't get any output from `eopkg li | grep kwallet`.

**Comment by TraceyC77** [comment]
FYI I have had this popup regularly on a Budgie VM (shannon) for quite some time. I'm happy to also help troubleshoot.

```
$ uname -r
6.5.3-256.current
```

Here's the output of sudo journalctl -b0 | grep pam before an update (last update was a couple of weeks ago, before the recent pam stack update). This is just after entering my password in the keyring popup:

```
Dec 01 14:55:41 budgie-test-vm lightdm[608]: pam_succeed_if(lightdm-autologin:auth): requirement "shell notin /sbin/nologin:/usr/sbin/nologin:/bin/false:/usr/bin/false" was met by user "tracey"
Dec 01 14:55:41 budgie-test-vm lightdm[608]: pam_unix(lightdm-autologin:session): session opened for user tracey by (uid=0)
Dec 01 14:55:41 budgie-test-vm (systemd)[614]: pam_warn(systemd-user:setcred): function=[pam_sm_setcred] flags=0x8002 service=[systemd-user] terminal=[<unknown>] user=[tracey] ruser=[<unknown>] rhost=[<unknown>]
Dec 01 14:55:41 budgie-test-vm (systemd)[614]: pam_unix(systemd-user:session): session opened for user tracey by (uid=0)
Dec 01 14:58:46 budgie-test-vm sudo[1365]: pam_unix(sudo:session): session opened for user root by (uid=1000)
```

After updating the system, and rebooting, I still saw the keyring prompt. Slightly different pam output in logs

```
Dec 01 15:31:26 budgie-test-vm lightdm[599]: pam_succeed_if(lightdm-autologin:auth): requirement "user ingroup users" was met by user "tracey"
Dec 01 15:31:26 budgie-test-vm lightdm[599]: gkr-pam: no password is available for user
Dec 01 15:31:26 budgie-test-vm lightdm[599]: pam_unix(lightdm-autologin:session): session opened for user tracey(uid=1000) by tracey(uid=0)
Dec 01 15:31:26 budgie-test-vm (systemd)[605]: pam_warn(systemd-user:setcred): function=[pam_sm_setcred] flags=0x8002 service=[systemd-user] terminal=[] user=[tracey] ruser=[<unknown>] rhost=[<unknown>]
Dec 01 15:31:26 budgie-test-vm (systemd)[605]: pam_unix(systemd-user:session): session opened for user tracey(uid=1000) by tracey(uid=0)
Dec 01 15:31:26 budgie-test-vm lightdm[599]: gkr-pam: gnome-keyring-daemon started properly
Dec 01 15:32:03 budgie-test-vm sudo[1315]: pam_unix(sudo:session): session opened for user root(uid=0) by tracey(uid=1000)
```

**Comment by ReillyBrogan** [comment]
Does it work if you update the Gnome Keyring password to match your login password? https://help.gnome.org/users/seahorse/stable/keyring-update-password.html.en

**Comment by davfiocchi** [comment]
No, it doesn't work. I already had the same password for both keyring and login. I've tried also to temporarily set a different password and set again the same password as login but it didn't work either

**Comment by ReillyBrogan** [comment]
@davfiocchi OK, I'm not really seeing the correct output there in your pam output so something is definitely not working correctly. Can I please get the output of the following commands? 
`tree /etc/pam.d`
`sudo journalctl -b0 > boot.log` (please upload the boot.log to something like pastebin/hastebin and paste the link here.
`sudo eopkg li > packages.log` (please also upload this one too).

**Comment by davfiocchi** [comment]
Hi! 
Here's the output of `tree /etc/pam.d`:
```
/etc/pam.d
└── lightdm

1 directory, 1 file
```
Here's the [boot.log](https://pastebin.com/ZAZnmq4D) and [packages.log](https://pastebin.com/FhuN8WWe) links.

Thank you for helping me :)

**Comment by ReillyBrogan** [comment]
> ```
> /etc/pam.d
> └── lightdm
> ```

Did you modify this file? If so you should compare it to the new version at `/usr/share/defaults/etc/pam.d/lightdm` and make sure to update `/etc/pam.d/lightdm` with the changes. If you didn't modify that file then it's likely a leftover from us moving the `/etc/pam.d/lightdm` file to the `/usr` location and you can just delete `/etc/pam.d/lightdm` (our PAM is configured so that if a config file doesn't exist in `/etc` then it'll fall back on the one in `/usr`, so deleting `/etc/pam.d/lightdm` should be safe).

**Comment by davfiocchi** [comment]
Uhm, I might have modified the content of `/etc/pam.d/lightdm` as one of the things that I've tried before asking for help here. Its content was a bit different with respect to the one in `/usr/share/defaults/etc/pam.d/lightdm`.
Removing the file `/etc/pam.d/lightdm` solved the issue, thank you very much for your help!
