### ISSUE TITLE
Update beekeper studio to 4.0.3

### ISSUE THREAD

**Issue by malfisya** [getsolus/packages#928]
### Name

beekeeper-studio

### Version

4.0.3

### Link to the release notes or announcement.

https://github.com/beekeeper-studio/beekeeper-studio/releases/tag/v4.0.3

### Other comments

 Evan probably already aware of this, but there is new version. I tried adding homepage to this, but as always `yarn` fail on me. It complains :
 `The engine "node" is incompatible with this module. Expected version "8 || 10 || 12 || 14 || 16 || 17". Got "18.18.0"`
Cheers!

**Comment by EbonJaeger** [comment]
Yeah, our Node is too new for this to build.
