### ISSUE TITLE
Boot entries and "system information" for 4.5 Calamares ISO install reference 4.4 Harmony

### ISSUE THREAD

**Issue by TraceyC77** [getsolus/packages#929]
### Summary

When booting an install from the 4.5 ISO, the boot entry says "Solus 4.4 Harmony" which does not match the name in the ISO

### Steps to reproduce

1. Create a 4.5 test ISO with Calamares (not sure if that matters).
2. Install Solus and reboot
3. Note the boot entry name
4. After logging in, go to About This System

### Expected result

The boot entry matches the name in the installer (currently "4.5 CODENAME"
The title in About This System also matches

### Actual result

The boot entry and title in About This System do not match the name in the installer. They have Solus 4.4

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Plasma

### System details

VM installation

Operating System: Solus 4.4
KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.110.0
Qt Version: 5.15.11
Kernel Version: 6.5.11-263.current (64-bit)
Graphics Platform: X11
Processors: 4 × 11th Gen Intel® Core™ i7-11800H @ 2.30GHz
Memory: 7.8 GiB of RAM
Graphics Processor: llvmpipe
Manufacturer: QEMU
Product Name: Standard PC (Q35 + ICH9, 2009)
System Version: pc-q35-7.2

**Comment by ReillyBrogan** [comment]
This is normal since those boot entries are generated from the `/etc/os-release` which still says 4.4. This will probably be the last thing we do before we create the _official_ ISOs.

**Comment by ermo** [comment]
> This is normal since those boot entries are generated from the `/etc/os-release` which still says 4.4. This will probably be the last thing we do before we create the _official_ ISOs.

Last time I touched baselayout, Joey mentioned a specific thing that breaks on a baselayout update, but neither of us could remember what it was, except that it was annoying and needed fixing.

For that reason, I think we should change the release number to "4.5 Freeze" ASAP and then document what breaks with time to spare before the official ISO release cut?

**Comment by EbonJaeger** [comment]
Both `baselayout` and `calamares` have been updated with the new strings, so this should be closable now.
