### ISSUE TITLE
Falkon doesn't support google meet any longer

### ISSUE THREAD

**Issue by zzrzlk** [getsolus/packages#933]
### Summary

![image](https://github.com/getsolus/packages/assets/17789210/a2a3fc60-ed47-4e17-aff4-6192afd57bee)

### Steps to reproduce

Cannot joint any google meet meeting since 1+ week
Before it was possible but screan sharing was not possible.

### Expected result

cannot join any google meet meetings

### Actual result

![image](https://github.com/getsolus/packages/assets/17789210/9e3ecddf-b2b5-441d-b818-80e0a561b536)

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Xfce

### System details

Archlinux
inux archtst04 6.6.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 20 Nov 2023 23:18:21 +0000 x86_64 GNU/Linux

**Comment by ReillyBrogan** [comment]
> Are you sure you are filing bug to right distro? It says you use ArchLinux.

We also haven't updated to Falkon 23.08.3 yet. I'm going to go ahead and close this since it seems like @zzrzlk is a bit lost.

@zzrzlk, the Arch Linux bug tracker is [here](https://gitlab.archlinux.org/groups/archlinux/packaging/packages/-/issues) as far as I can tell. Hope you have a great day!

**Comment by zzrzlk** [comment]
Hi team
My apologizes.
Yes I definitly use archlinux and I'm not familiar wuth the place to open
this issue.
By the way, the windows I paste is what I get on my machine.
here is the package repo on arch
https://archlinux.org/packages/extra/x86_64/falkon/
Can you help me to place the issue at the right place?
thanks


Le ven. 1 déc. 2023 à 02:49, Reilly Brogan ***@***.***> a
écrit :

**Comment by malfisya** [comment]
Please go here https://gitlab.archlinux.org/groups/archlinux/packaging/packages/-/issues . Cheers!
