### ISSUE TITLE
No Access to X after switch by 'su'

### ISSUE THREAD

**Issue by LarsBeiDrKlein** [getsolus/packages#938]
### Summary

In a normal terminal I can open X11 programs like emacs which opens an own X11 Windows after start. As long as the variable DISPLAY is set to ':0'.
After get root by 'sudo su -' or only 'su -' with a well known password ;-). The DISPLAY variable is empty and emacs will open within the terminal window. A "export DISPLAY=:0" on the terminal as root will not help, the result is an error message:
Invalid MIT-MAGIC-COOKIE-1 key
Display :0 unavailable, simulating -nw

This is my private computer and I do not need "fort knox" security on it. 
This came with the new pam. 
Please help, I need to start cisco vpn as root with X11.

### Steps to reproduce

1. open a terminal
2. get root by "sudo su -"
3. open a X11 program like emacs or glxgears or something else.
You will earn an error message like:

Invalid MIT-MAGIC-COOKIE-1 key
Display :0 unavailable, simulating -nw

### Expected result

The expected result is that emacs start in a X11 Windows with root rights.

### Actual result

after get root on terminal
- start emacs it opens in the terminal window.
- start glxgears results in an error message.
-

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Budgie

### System details

Please provide a "german" name or give the real name so I can start on terminal and copy the information from there.
I really don't know what the "Application Menu" is. I'm run under Budgie desktop.

**Comment by LarsBeiDrKlein** [comment]
System details from `netfetch --off`

root@phoebe ~ # neofetch --off
root@phoebe 
----------- 
OS: Solus x86_64 
Host: 20S00013FR ThinkPad T14 Gen 1 
Kernel: 6.5.11-263.current 
Uptime: 1 hour, 7 mins 
Packages: 1402 (eopkg) 
Shell: bash 5.1.16 
Resolution: 2560x1440 
Terminal: gnome-terminal 
CPU: Intel i7-10510U (8) @ 4.900GHz 
GPU: Intel CometLake-U GT2 [UHD Graphics] 
Memory: 3652MiB / 47847MiB

**Comment by ReillyBrogan** [comment]
Hi Lars! And welcome to the Solus github! I think the issue here stems from you using `-` in your `sudo su -` command. What this does is resets the environmental variables of the session (essentially it's saying "open a clean session as root"). If you remove this then I believe graphical applications should still work. `sudo glxgears` works when I test it, `glxgears` after running `sudo su` works as well.

**Comment by LarsBeiDrKlein** [comment]
Thank you @ReillyBrogan  I'm so stupid, never saw this point. I always thought the '-' was important. So this bug is fixed by adjusting my own action. Thanks.

**Comment by ReillyBrogan** [comment]
Yes, `-` is short for `--login` which resets the environment. You can read more on what it does by running `man su`. The reason this behavior changed with our PAM overhaul was that we switched the implementation of `su` we used. It used to be provided by the shadow package but it now comes from `util-linux` (which is more common in distributions as it's more actively developed). This is probably why this behavior changed, `-` probably behaved slightly different in the previous implementation. Regardless, glad to hear that this is solved for you!
