### ISSUE TITLE
Okular overwrites how .png and text files are opened (T4592)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#94]
<div dir="rtl"><b>Martin</b>&nbsp;(<em>&#35;baimafeima</em>),&nbsp;2017-09-23&nbsp;17:30:58&nbsp;UTC</div><br/>

After installing Okular, .png and text files are opened by Okular by default and not by Image Viewer or Gedit anymore. Is there any way to prevent Okular (or other programmes) from doing so? I know this is a minor issue but it can be quite annoying for new users when each time after installing another programme, file opening defaults are overwritten and need to be configured again.

**Comment by ermo** [comment]
@ReillyBrogan I'm guessing this would have been fixed by the recent mimetype work?

**Comment by TraceyC77** [comment]
I am not able to reproduce this bug anymore on Budgie. Closing.
