### ISSUE TITLE
rtl8852bu (Wi-Fi 6 driver)

### ISSUE THREAD

**Issue by e-wilcox** [getsolus/packages#967]
### Homepage

https://github.com/morrownr/rtl8852bu

### Why should this be included in the repository?

I'm requesting a Wi-Fi 6 driver package that is not currently built into the Linux kernel. I love my Solus installation and your logic for not including the DKMS system makes sense, but I don't want to be required to re-build this driver every time I update the kernel. That means including a pre-built driver (either as a separate package or building it into the kernel) or including DKMS packages in the repository.

### Are we allowed to redistribute it?

GPL-2.0-only

### What kind of user will use this package, and how many users do you think will use this package?

Any user who has a Wi-Fi 6 adapter that uses the Realtek rtl8832bu or rtl8852bu chip set.

### Link to source archive file

https://github.com/morrownr/rtl8852bu

**Comment by ReillyBrogan** [comment]
If I built this would you be to test the new package? I don't have any compatible hardware myself unfortunately.

**Comment by e-wilcox** [comment]
Absolutely! I just need a bit of time to re-install Solus on this laptop. Send me an alert when it's built :)

Ernie

**Comment by e-wilcox** [comment]
FWIW, I have Solus set up, so I'm ready when you are. Please send me a message telling me where to go for the new package.

Ernie

**Comment by ReillyBrogan** [comment]
Give this a try. Make sure you install all updates first:
```
sudo eokpg it https://shared.getsol.us/reilly/2023-12-rtl8852bu/rtl8852bu-current-1.19.3-1-1-x86_64.eopkg https://shared.getsol.us/reilly/2023-12-rtl8852bu/rtl8852bu-common-1.19.3-1-1-x86_64.eopkg https://shared.getsol.us/reilly/2023-12-rtl8852bu/rtl8852bu-modaliases-1.19.3-1-1-x86_64.eopkg
```

**Comment by e-wilcox** [comment]
I ran what you sent me in the email message and received a package not found error, so I ran it again with the '--debug' switch inserted - this is the output:

Traceback:
  File "/usr/bin/eopkg", line 78, in <module>
    cli.run_command()
  File "/usr/lib/python2.7/site-packages/pisi/cli/pisicli.py", line 138, in run_command
    self.command.run()
  File "/usr/lib/python2.7/site-packages/pisi/cli/install.py", line 109, in run
    pisi.api.install(packages, ctx.get_option('reinstall') or reinstall)
  File "/usr/lib/python2.7/site-packages/pisi/api.py", line 65, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python2.7/site-packages/pisi/api.py", line 447, in install
    return pisi.operations.install.install_pkg_files(packages, reinstall)
  File "/usr/lib/python2.7/site-packages/pisi/operations/install.py", line 158, in install_pkg_files
    package = pisi.package.Package(x)
  File "/usr/lib/python2.7/site-packages/pisi/package.py", line 63, in __init__
    self.fetch_remote_file(url)
  File "/usr/lib/python2.7/site-packages/pisi/package.py", line 99, in fetch_remote_file
    self.metadata, self.files, self.repo = pisi.api.info_name(pkg_name, False)
  File "/usr/lib/python2.7/site-packages/pisi/api.py", line 711, in info_name
    package, repo = packagedb.get_package_repo(package_name)
  File "/usr/lib/python2.7/site-packages/pisi/db/packagedb.py", line 197, in get_package_repo
    pkg, repo = self.pdb.get_item_repo(name, repo)
  File "/usr/lib/python2.7/site-packages/pisi/db/itembyrepo.py", line 48, in get_item_repo
    raise Exception(_("Repo item %s not found") % str(item))

I hope it helps,

Ernie

**Comment by ReillyBrogan** [comment]
That's because I accidentally misspelled `eopkg`. I edited that post, please try it now.

**Comment by e-wilcox** [comment]
This time I get the following from the --debug switch:

Traceback:
  File "/usr/bin/eopkg", line 78, in <module>
    cli.run_command()
  File "/usr/lib/python2.7/site-packages/pisi/cli/pisicli.py", line 138, in run_command
    self.command.run()
  File "/usr/lib/python2.7/site-packages/pisi/cli/install.py", line 109, in run
    pisi.api.install(packages, ctx.get_option('reinstall') or reinstall)
  File "/usr/lib/python2.7/site-packages/pisi/api.py", line 65, in wrapper
    ret = func(*__args,**__kw)
  File "/usr/lib/python2.7/site-packages/pisi/api.py", line 447, in install
    return pisi.operations.install.install_pkg_files(packages, reinstall)
  File "/usr/lib/python2.7/site-packages/pisi/operations/install.py", line 158, in install_pkg_files
    package = pisi.package.Package(x)
  File "/usr/lib/python2.7/site-packages/pisi/package.py", line 63, in __init__
    self.fetch_remote_file(url)
  File "/usr/lib/python2.7/site-packages/pisi/package.py", line 99, in fetch_remote_file
    self.metadata, self.files, self.repo = pisi.api.info_name(pkg_name, False)
  File "/usr/lib/python2.7/site-packages/pisi/api.py", line 711, in info_name
    package, repo = packagedb.get_package_repo(package_name)
  File "/usr/lib/python2.7/site-packages/pisi/db/packagedb.py", line 197, in get_package_repo
    pkg, repo = self.pdb.get_item_repo(name, repo)
  File "/usr/lib/python2.7/site-packages/pisi/db/itembyrepo.py", line 48, in get_item_repo
    raise Exception(_("Repo item %s not found") % str(item))

I hope it helps,

Ernie

**Comment by algent-al** [comment]
````
https://shared.getsol.us/reilly/2023-12-rtl8852bu/rtl8852bu-common-1.19.3-1-1-x86_64.eopkg
https://shared.getsol.us/reilly/2023-12-rtl8852bu/rtl8852bu-modaliases-1.19.3-1-1-x86_64.eopkg
https://shared.getsol.us/reilly/2023-12-rtl8852bu/rtl8852bu-current-1.19.3-1-1-x86_64.eopkg
```
@e-wilcox Try to download these packages one by one and then inside the downloaded folder, launch the terminal and install them with this command `sudo eopkg it rtl8852bu-*`

**Comment by e-wilcox** [comment]
@algent-al I did as directed above. The packages installed well enough, and I can see the rtl8852bu configuration entry in /usr/lib/modprobe.d as 8852bu.conf, but I have no evidence that it's being used/connecting. It doesn't show up in the Networks dialog pop-up when I click the network icon in the panel, even after a reboot. Am I missing something? How can I collect diagnostic information?

Ernie

**Comment by ReillyBrogan** [comment]
If the driver installed correctly then it'll be located as `8852bu.ko.zst` in `/lib/modules/6.6.4-265.current/kernel/drivers/net/wireless/rtl8852bu`. If you run `lsmod` you should see `8852bu` somewhere in there if the kernel automatically loaded it due to hardware detection. If it is not present there you can try to force load it with `sudo modprobe 8852bu`.

**Comment by ReillyBrogan** [comment]
If the driver works after running `sudo modprobe 8852bu` then try running `sudo depmod -a` and rebooting.

**Comment by e-wilcox** [comment]
It is - I checked, but sudo modprobe 8852bu returns 'modprobe: FATAL: Module 8852bu not found in directory /lib/modules/6.6.4-265.current'. So what's next?

**Comment by e-wilcox** [comment]
O.K.! That solved the problem! I now have Wi-Fi-6 working very well on my Solus-powered laptop! I can't thank you enough for your help and patience. Do you think this will become a stable package at some point? I hope so. I'd even hope that it will become an in-built driver in the kernel at some point. :)

Ernie

**Comment by ReillyBrogan** [comment]
I haven't decided whether or not this will go in in the upcoming sync, but it'll definitely be in by the next time I update the kernel (since if it isn't your wifi will stop working without a rebuilt driver). I'll let you know if there are any manual steps you need to do when that happens, but most likely you'll just receive a kernel update one day and get the rebuilt driver at the same time.

**Comment by e-wilcox** [comment]
> most likely you'll just receive a kernel update one day and get the rebuilt driver at the same time

Great! That's what I was hoping for! Thank you again for all your effort with my Wi-Fi adapter issue (I hope it helps other users too),

Ernie
