### ISSUE TITLE
rEFInd (T4089)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#97]
<div dir="rtl"><b>Tadeusz&nbsp;Cantwell</b>&nbsp;(<em>&#35;tadcan</em>),&nbsp;2017-07-16&nbsp;19:56:48&nbsp;UTC</div><br/>

Project home page http://www.rodsbooks.com/refind/
I am suggesting its inclusion because with PC's/laptops moving over to UEFI having a Boot Manager for users who like to multi-boot would be helpful. As for the amount of users, I am not sure, but I would see it more as a future proofing move.
The software is under a GPL 3 licence.
This seems to be the latest source file https://sourceforge.net/projects/refind/files/0.10.8/refind-src-0.10.8.tar.gz/download
But here is a higher level link to the packages https://sourceforge.net/projects/refind/files/0.10.8/

**Comment by davidjharder** [comment]
Old, closing
