### ISSUE TITLE
OpenTabletDriver

### ISSUE THREAD

**Issue by triplefox** [getsolus/packages#972]
### Homepage

https://github.com/OpenTabletDriver/OpenTabletDriver

### Why should this be included in the repository?

I purchased a VEIKK S640 digitizer tablet. VEIKK has an official Linux driver for this, but it is a proprietary driver shipped in rpm/deb form, so it won't work on Solus, so I needed an alternative. 

After looking around I found out that OpenTabletDriver supports my device, so I just worked through building it myself from source. Following the README step-by-step and installing the indicated dependencies from Software Center worked, but there is a dependency on .NET SDK which I eventually resolved with Microsoft's dotnet-install script, and the commands: 

`sh dotnet-install.sh -v 7.0.404`
`export DOTNET_ROOT=/home/triplefox/.dotnet`
`export PATH=$PATH:/home/triplefox/.dotnet`

To run it, I start both the daemon and the GUI in separate terminals with a sudo exporting my environment:
`sudo -E ./OpenTabletDriver.Daemon`
`sudo -E ./OpenTabletDriver.UX.Gtk`

And the tablet is detected and functions.

### Are we allowed to redistribute it?

LGPL-3.0-only

### What kind of user will use this package, and how many users do you think will use this package?

- Artists and technical draftspeople
- Users with accessibility considerations
- Gamers playing Osu! or similar stylus-oriented games

Brad Colbow, a popular Youtube reviewer of graphics tablets "for creative professionals", has 822,000 subscribers. If we use this an estimate of tablet market size(assuming his subscriber numbers are honest and reflect potential customers for new devices) and divide it by Steam's 2022 estimate of Linux market share, 1.38%, we get a rough estimate of 11343.6 potential tablet users. Some may use Wacom devices which are already supported separately. Others will not be supported by OpenTabletDriver, or are overcounted because they are specifically looking for a standalone device like an iPad, not a digitizer for desktops.

### Link to source archive file

https://github.com/OpenTabletDriver/OpenTabletDriver/archive/refs/tags/v0.6.3.0.tar.gz

**Comment by nelsontkq** [comment]
I got this building successfully and am willing to maintain it :+1:

**Comment by nelsontkq** [comment]
@triplefox When it's available let me know if it works for your tablet. It worked fine for mine.

**Comment by triplefox** [comment]
@nelsontkq 

I have been able to test the 0.6.4.0-1 package on a fresh machine(without OTD previously used). Unfortunately, it fails with this error when "otd" is run: 

```
Failure processing application bundle; possible file corruption.
Arithmetic overflow while reading bundle.
A fatal error occurred while processing application bundle

```

When I checked, I discovered the binaries were in a conspicuous state:

```
triplefox@silverball2 /usr/bin $ ls /usr/lib/opentabletdriver/ -l
total 216
-rwxr-xr-x 1 root root 72520 Jun 14 18:39 OpenTabletDriver.Console
-rwxr-xr-x 1 root root 72520 Jun 14 18:39 OpenTabletDriver.Daemon
-rwxr-xr-x 1 root root 72520 Jun 14 18:39 OpenTabletDriver.UX.Gtk

```

"diff" reports that they are different binaries. The released package is very small - 286 KiB - while the releases of OTD are few megabytes, so something may have happened at build time.

**Comment by TraceyC77** [comment]
@triplefox  Thanks for the feedback. Would you please put your results in a new bug report so @nelsontkq can take a look? Thanks.
