### ISSUE TITLE
SMPlayer update

### ISSUE THREAD

**Issue by joluveba** [getsolus/packages#982]
### Name

SMPlayer

### Version

23.6

### Link to the release notes or announcement.

https://www.smplayer.info/en/changes

### Other comments

According to the SMPlayer site, version 23.6 brings these improvements:
Version 23.6
    Fix the issue of YouTube playback limited to 720p.
    Update mpv and mplayer.
    New option in preferences to keep the playback speed for all videos.
    Fix the AppImage package.
    Other bug fixes.

**Comment by ReillyBrogan** [comment]
f904ed289877f5fb63b87aaad6f4deb920daa48e
