### ISSUE TITLE
TLP update

### ISSUE THREAD

**Issue by joluveba** [getsolus/packages#983]
### Name

TLP

### Version

1.6.1

### Link to the release notes or announcement.

https://github.com/linrunner/TLP/releases

### Other comments

Bugfixes:

Battery

    LG Gram laptops: ensure lg-legacy is used for kernel <= 5.17 (Issue https://github.com/linrunner/TLP/issues/708)

General:

    tlp-stat -s: report manual mode despite restrictive umask (Issue https://github.com/linrunner/TLP/issues/702)

**Comment by joluveba** [comment]
> I'm curious, which part of the changes do you need here? The LG thing is only relevant for us on -lts kernels currently, and we're upgrading LTS to 6.6 sooner than later.

I admit I don't need any of the changes (I use an Asus laptop), I simply requested this update because I would like Solus to have the last version of TLP. If you consider this low priority, or just a no, I will fully understand. Thank you anyways

**Comment by ReillyBrogan** [comment]
Well, package maintainers don't really have unlimited time so it's important for us to prioritize updates that actually bring value to Solus and it's users. To that end we don't update things just for the sake of having the latest version of a thing if that update doesn't really bring anything useful to Solus. The point of making package update requests is that it's supposed to be users telling us that an update is important to them, not just letting us know that an update is available (we have lots of ways of figuring that out). 

I'll leave this open for now, but could you just keep that in mind for the future?
