### ISSUE TITLE
homebank: Unable to fetch the tarball in solbuild

### ISSUE THREAD

**Issue by algent-al** [getsolus/packages#989]
### Summary

Although there is no problem when running the update command locally to update the source, this error appears when the build command is given in solbuild.

![homebank](https://github.com/getsolus/packages/assets/46356616/7adc7b93-0d3f-45eb-8b0e-7d01a6302df2)

### Steps to reproduce

go to homebank dir and run `task build` or `go-task build`

### Expected result

A successful build.

### Actual result

`Error downloading http://homebank.free.fr/public/sources/homebank-5.7.2.tar.gz: bad content length`

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

Budgie

### System details

OS: Solus x86_64 
Host: CELSIUS W530 
Kernel: 6.6.4-265.current 
Shell: bash 5.1.16 
DE: Budgie 10.8.2 
WM: Mutter(Budgie) 
Terminal: gnome-terminal 
CPU: Intel Xeon E3-1271 v3 (8) @ 4.000GHz 
GPU: NVIDIA Quadro M2000 
Memory: 3122MiB / 15920MiB 

### Other comments

To update this package a workaround for now would be by hosting the tarball in our sources repo.

**Comment by algent-al** [comment]
Looks like it is fixed now: https://github.com/getsolus/packages/commit/54e02851244339b728d958be76e43ae701767f23

Thanks @joebonrichie

**Comment by joebonrichie** [comment]
I think they fixed their tarball upstream, didn't actually patch our system solbuild yet with that patch :D
