### ISSUE TITLE
Update Emacs to 28.X and enable --with-native-compilation (T10045)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#99]
<div dir="rtl"><b>lf_araujo</b>&nbsp;(<em>&#35;lf-araujo</em>),&nbsp;2021-11-28&nbsp;14:13:05&nbsp;UTC</div><br/>

- Project/product Homepages: 

https://akrl.sdf.org/gccemacs.html
https://www.emacswiki.org/emacs/GccEmacs

- Why we should include this into the repository, i.e. what does it do that the alternatives do not?

What it is:

> GccEmacs refers to the --with-native-compilation configuration option when building Emacs, which adds support for compiling EmacsLisp to native code using libgccjit. All of the Elisp packages shipped with Emacs are native-compiled, providing a noticeable performance improvement out-of-the-box. Third-party packages are also compiled to achieve further performance improvements.

Emacs is generally sluggish compared to vim, a new branch was merged to `main` and added as a compilation switch. It does not add regressions to the use of the software AFAIK. This switch improves significantly in terms of speed, but it depends on [libgccjit](https://aur.archlinux.org/packages/libgccjit/), which is not itself in Solus repositories.

This switch appears on Emacs GitHub mirror, but it is not yet at the tar from the ftp you guys pull Solus' Emacs. 

- Is it open source?

Yes. GPL.

- Upstream release:

https://github.com/emacs-mirror/emacs

**Comment by davidjharder** [comment]
emacs has been updated past 28.x
