### ISSUE TITLE
Nemo bug after removing external drive

### ISSUE THREAD

**Issue by SOLUSfiddler** [getsolus/packages#990]
### Summary

I'm running Solus Budgie, fully updated, on a ThinkPad x395 and have this reproduceable problem with Nemo, the file manager:
When I eject an external drive (after updating my backup) and click on the "x" in the top right corner of Nemo to close its window a new window of Nemo opens without the already open one closing.
So, there are now two windows open which I have to close individually.
Several users in the Solus forum (discuss.sol.us) confirmed that behaviour of Nemo, they could reproduce it.

### Steps to reproduce

1. Plug in external drive
2. Mount it in Nemo
3. Run update of backup on external drive
4. Unmount external drive
5. Click on top right x to close Nemo

### Expected result

Nemo closes.

### Actual result

A second window of Nemo opens after step 5 above, the first one still being open as well.

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Budgie

### System details

Lenovo ThinkPad X395
16,0 GB RAM
AMD Ryzen 7 PRO 3700U w/ Radeon Vega Mobile Gfx x 8
AMD Radeon Vega 10 Graphics
Budgie Version 10.8.2
Solus 4.4 Harmony
Linux 6.6.4-265.current

**Comment by EbonJaeger** [comment]
I haven't had much time to look into this, but I did ask other Budgie users on other distros if they could reproduce the issue, and they could not. Not sure how this could be a Solus thing, but it seems to be.

**Comment by TraceyC77** [comment]
I am not able to reproduce this on Plasma, it may be specific to Budgie

**Comment by EbonJaeger** [comment]
This is a bug with Budgie Desktop. Not sure why the others couldn't reproduce it, but I have a working fix.
